### ISSUE TITLE
Promise pending

### ISSUE THREAD

**Issue by andreasonny83** [lukehaas/RunJS#1]
I really love this project, however, I believe it needs to be improved.

I was expecting the following snippet to returns me back the resolved string `test`, but instead all I can see on the right side is a `Promise { <pending> }`.

```
const a = () => new Promise(res => res('test'));

const test = async () => {
  const x = await a();
  
  return x;
};

test();
```

Is there a better way of dealing with promises?

Thanks!

**Comment by lukehaas** [comment]
Aware of this and will investigate further. Thanks.

One work around for now is to put a console log inside the async function:
```
const a = () => new Promise(res => res('test'));

const test = async () => {
  const x = await a();
  console.log(x)
  return x;
};

test();
```

**Comment by lukehaas** [comment]
@andreasonny83 this was the first ever issue raised for RunJS and thanks for raising it! 🚀
I'm very pleased to say that in RunJS version 1.11.0 the handling of promises has greatly improved.

Resolved promises will now display as you described:

![Screenshot 2020-08-30 at 13 35 39](https://user-images.githubusercontent.com/741344/91659141-ff3f0b00-eac5-11ea-934c-64b763c9946c.png)
