### ISSUE TITLE
Endless execution of code when using the CMD + F (Format) shortcut

### ISSUE THREAD

**Issue by yonifra** [lukehaas/RunJS#100]
I've used the CMD + F a few time in succession to format the code, and my code gets executed non stop since then.
I've had to close and reopen the app to make it stop
See the problem here: https://i.imgur.com/q9yLmKu.gif

**Comment by yonifra** [comment]
It's on version 1.7.0

**Comment by lukehaas** [comment]
Thanks, will investigate this.

**Comment by lukehaas** [comment]
Found this issue. This will be fixed in the next release.

**Comment by yonifra** [comment]
> Found this issue. This will be fixed in the next release.

Awesome!

**Comment by lukehaas** [comment]
@yonifra This is now resolved in version 1.8.0
