### ISSUE TITLE
Donwload for Linux link broken on main website page

### ISSUE THREAD

**Issue by gminova** [lukehaas/RunJS#101]
Hi I get a github 404 page when I tried to install the RunJS for linux
![Screenshot from 2019-10-08 18-59-55](https://user-images.githubusercontent.com/42014388/66420500-e0431080-e9fd-11e9-871f-b8d9acc7b3d2.png)
![Screenshot from 2019-10-08 18-59-58](https://user-images.githubusercontent.com/42014388/66420502-e0dba700-e9fd-11e9-93a9-6485db16fab3.png)

**Comment by lukehaas** [comment]
@gminova thanks for raising this. The download link should work now.

**Comment by gminova** [comment]
@lukehaas  Thank you! Closing this issue.
