### ISSUE TITLE
Text gets overwritten when trying to type new characters.

### ISSUE THREAD

**Issue by animanoir** [lukehaas/RunJS#102]

**Comment by lukehaas** [comment]
Thanks @animanoir, could you tell me the OS and version of RunJS you're using? 

Is this issue something you're able to consistently see or is it only occasionally?

**Comment by animanoir** [comment]
W10 and I downloaded it like 2 weeks ago. Useful, but that detail got annoying.

It was consistently. At first I thought it was that keyboard mode that replaces the letter instead of adding it, but I couldn't get it as I wanted.

**Comment by lukehaas** [comment]
Closing this now as I haven't been able to see this issue myself and haven't had any other reports of it recently.

**Comment by animanoir** [comment]
I don´t even remember what is this, ha, but good luck my friend.
