### ISSUE TITLE
[Feature Request] Specify custom babel plugins

### ISSUE THREAD

**Issue by achung89** [lukehaas/RunJS#104]
Could you add an ability for users to specify custom babel plugins? This would allow us to use new and upcoming features like optional chaining.

**Comment by lukehaas** [comment]
Thanks @achung89 this is a good idea.

**Comment by jmlivingston** [comment]
Yes, especially when new features are coming out like optional chaining, we could just add @babel/plugin-proposal-optional-chaining. Great app by the way.

**Comment by coisnepe** [comment]
Hey, any update on this ?

**Comment by lukehaas** [comment]
@coisnepe it's possible this may be introduced later this year.

**Comment by coisnepe** [comment]
@lukehaas That was quick! Thanks for replying. I tried using the "working directory" but I guess it's not the intended use case. Thanks for your work :-) I use RunJS almost daily.

**Comment by lukehaas** [comment]
Options for Babel plugins are now supported in RunJS version 1.10.0

![Screenshot 2020-07-17 at 17 24 46](https://user-images.githubusercontent.com/741344/87808963-7f7d1a00-c852-11ea-9c4d-1f0f879d9efe.png)
