### ISSUE TITLE
Bug: font is missing

### ISSUE THREAD

**Issue by getify** [lukehaas/RunJS#106]
I have a set of fonts installed (windows 10) called "Source Code Pro" (Adobe)... and they show up fine in all the other apps' font selectors on this laptop. But for some reason, they don't show up in the font selector of RunJS:

<img width="399" alt="runjs-font-selection" src="https://user-images.githubusercontent.com/150330/68726307-a037f600-0586-11ea-9a75-481e0baa42d5.png">

In Notepad for example, you can see it listed:

<img width="332" alt="notepad-font-selector" src="https://user-images.githubusercontent.com/150330/68726375-d70e0c00-0586-11ea-8346-b60081137b52.png">

Any ideas on why that would be?

----

I have a theory... is it that RunJS compiles this font list at install time (instead of when the app is opened each time)? I installed this font after I install the RunJS app, so that's the reason for my theory.

**Comment by lukehaas** [comment]
I'll look into this. It could be that it's just picking up system fonts and not installed fonts. 
It does this at runtime, so not related install time

**Comment by lukehaas** [comment]
@getify this should now be fixed in the latest release.

**Comment by getify** [comment]
It does seem to be resolved, thanks!
