### ISSUE TITLE
TypeScript - Could it check type validity?

### ISSUE THREAD

**Issue by LukaszGrela** [lukehaas/RunJS#107]
Typescript code works in terms of compilation, but types are not checked, e.g. following code should report an error:

```
type TColumnIds = 'id' | 'name' | null;

const column:TColumnIds = "boom";
```

this is compiling correctly but it should report an error:
![image](https://user-images.githubusercontent.com/7643591/68772139-33256e80-0621-11ea-9254-e1aba01b12ad.png)

could this be added?

**Comment by youngjuning** [comment]
+1

**Comment by AzrizHaziq** [comment]
Refer: https://github.com/lukehaas/RunJS/issues/122

**Comment by lukehaas** [comment]
@LukaszGrela @youngjuning @AzrizHaziq type checking is now supported in the latest version of RunJS

![Screenshot 2021-06-22 at 21 02 42](https://user-images.githubusercontent.com/741344/122991754-4bcd3d00-d39d-11eb-8922-7373ea74bb2c.png)
