### ISSUE TITLE
Can't install npm package

### ISSUE THREAD

**Issue by kingRayhan** [lukehaas/RunJS#108]
I can't install any npm package.
**My OS**: Mac High Sierra
N.B: I updated npm to the latest version already.

![image](https://user-images.githubusercontent.com/7611746/69005911-9f221280-0952-11ea-8f3d-83a89450290f.png)

**Comment by lukehaas** [comment]
@kingRayhan thanks for raising this. Can you tell me which version of MacOS you're on? Also, have you installed Node through any kind of version manager live nvm?

**Comment by kingRayhan** [comment]
![image](https://user-images.githubusercontent.com/7611746/69033042-3bf2b780-0a08-11ea-895b-8f8f93c04514.png)

**Comment by kingRayhan** [comment]
Any update?

**Comment by lukehaas** [comment]
@kingRayhan I'm not sure what the issue here could be.
I have plans to rework the way that NPM packages are installed so that there is no longer a dependency on the system's NPM. However, it will not be shipped for a while.

**Comment by dYb** [comment]
Same problem here.  
A temporary solution is `Set Working Directory` in the `Action` menu, and then install the package manually.

**Comment by HugoLiconV** [comment]
I'm getting the same error in Ubuntu and setting the working directory didn't work

**Comment by dYb** [comment]
> I'm getting the same error in Ubuntu and setting the working directory didn't work

Did you use a shell？ Open a bash shell and cd the working directory, then run `npm install`

**Comment by HugoLiconV** [comment]
> > I'm getting the same error in Ubuntu and setting the working directory didn't work
> 
> Did you use a shell？ Open a bash shell and cd the working directory, then run `npm install`

It worked, but it would be great if I could do it using the GUI. This error is weird, I have RunJS installed on an Ubuntu and a macOS machine and I don't have this issue in macOS, only on ubuntu

**Comment by elvisduru** [comment]
On Windows, it works by running the app as administrator

**Comment by lukehaas** [comment]
@kingRayhan RunJS version 1.10.0 has a new way of installing NPM packages that should be more robust. This should solve the problem you were seeing.
