### ISSUE TITLE
Can't loading the local files

### ISSUE THREAD

**Issue by basrihsn** [lukehaas/RunJS#109]
When I attempt to open local device file (Ex: JS file) Run.js don't makes anything, nothing seems on the program screen.

**Comment by lukehaas** [comment]
Thanks @basrihsn, can you tell me which OS you're on?
Also, are you loading the file via the file menu?

**Comment by basrihsn** [comment]
Dear @lukehaas Hello,
I'm using Windows 10 pro. Also, I tried to load local files via Run.js environment but program couldn't open the .js files
Sincerely,
Monday, 18 November 2019, 01:56PM +03:00 from Luke Haas  notifications@github.com :

**Comment by basrihsn** [comment]
Thanks Luke, 
Problem was cleared up thank you for your attention.
