### ISSUE TITLE
Feature Request: option to use 'Fira Code' with ligatures.

### ISSUE THREAD

**Issue by thommorais** [lukehaas/RunJS#11]
It will be very nice.

Great tool, thanks!

**Comment by ozum** [comment]
Would be awesome!

**Comment by lukehaas** [comment]
Yes, I'll likely add options for choosing fonts and size. Will aim to include Fira Code and ligature support.

**Comment by lukehaas** [comment]
@thommorais @ozum version 1.4.0 now supports custom fonts, including Fira Code and ligatures.

**Comment by thommorais** [comment]
@lukehaas Nice, thank you!
