### ISSUE TITLE
[Feature Request] Disabling auto-pair?

### ISSUE THREAD

**Issue by andrwj** [lukehaas/RunJS#111]
Could you add an option to toggle auto pairing? It's too hard to modify codes because of the auto-pairing.
Thanks.

**Comment by lukehaas** [comment]
Thanks @andrwj, I'm not clear on what you mean by 'auto-pair', could you describe the behavior?

**Comment by andrwj** [comment]
I mean the function that automatically fills the rest by entering one side of brackets, parens, quotes. 
It's a pretty annoying feature, so I hope we have an option to turn it off.
Thanks.

**Comment by lukehaas** [comment]
I see now. Thanks for the suggestion.

**Comment by lukehaas** [comment]
@andrwj now RunJS 1.10.0 has a preference option for auto-closing brackets.

**Comment by andrwj** [comment]
@lukehaas  Awesome!, Thank you for the implementation!!!, RunJS is vital tool for me to study and work.
