### ISSUE TITLE
iPad Support

### ISSUE THREAD

**Issue by robertherber** [lukehaas/RunJS#113]
Would be supercool to have RunJS on iPad. It's not a laptop replacement for developers yet - but being able to do some rapid prototyping on an iPad would be great!

**Comment by TheBdouilleur2** [comment]
Yes it's a good idea!

**Comment by toropanov** [comment]
+1

**Comment by lukehaas** [comment]
Closing this to tidy up the backlog. While iPad support would be great, it's not something that I'll be pursuing due to limited time and resources.

**Comment by robertherber** [comment]
@lukehaas maybe this would be an enabler? https://nodejs-mobile.github.io/blog/reboot/

**Comment by lukehaas** [comment]
@robertherber @TheBdouilleur2 @toropanov There is now an online version of RunJS that can be used on an iPad:
https://runjs.app/play

It's also a PWA, so it can be installed and used offline.

**Comment by lukehaas** [comment]
@robertherber, there's no plan for that with this version; this is like RunJS lite.
