### ISSUE TITLE
The process object

### ISSUE THREAD

**Issue by metaa** [lukehaas/RunJS#114]
Issue #95 targeted `process.memoryUsage` not being available and it got added, but I see there are more things in `process` that should be available like `process.cwd` or `process.versions`.

Unless there is a reason to strip it down like that (all we have as v1.7.0 of is `env`, `memoryUsage` and `cpuUsage`), why not expose process completely? (you could even sneak the RunJS version into `process.versions`)

**Comment by lukehaas** [comment]
@metaa good point. I think in the next release I implement a less strict approach to handling process.

The only reason for the restriction here is that there are some functions of the process that, if executed, will cause RunJS to break, such as `process.exit()`

**Comment by lukehaas** [comment]
@metaa RunJS 1.8.0 has more relaxed rules around the process object.
