### ISSUE TITLE
Custom code formatting

### ISSUE THREAD

**Issue by marsicdev** [lukehaas/RunJS#116]
It would be great if we could have option to set our code formatting rules. At least option for semi and indentation would be nice. 

Also for the future some snippet support would be awesome  🏆

**Comment by lukehaas** [comment]
Thanks @marsicdev. Configurable code formatting rules are something I have planned for a future release.
Snippet support also, though that will be further down the line.

**Comment by lukehaas** [comment]
@marsicdev RunJS version 1.10.0 now supports Prettier formatting with configurable options.

![Screenshot 2020-07-18 at 11 40 40](https://user-images.githubusercontent.com/741344/87850892-873ccd00-c8eb-11ea-9a2a-c6e38c35bc34.png)
