### ISSUE TITLE
Getting an error installing some random package

### ISSUE THREAD

**Issue by dutzi** [lukehaas/RunJS#118]
Trying to install [ds4](https://github.com/seidtgeist/node-ds4) I get the following error:

![image](https://user-images.githubusercontent.com/927310/72219273-f99faf80-354c-11ea-977b-d541bab22afc.png)

Would be useful if it also showed me the package installation logs.

**Comment by lukehaas** [comment]
@dutzi this should be resolved now in RunJS version 1.11.0
