### ISSUE TITLE
console method is not support.

### ISSUE THREAD

**Issue by LeeHyungGeun** [lukehaas/RunJS#12]
**Description**
I add `console.time()` and `console.timeEnd()` to check performance, but it does not support.

Is it going to support in the future?
``` javascript
console.time();
for (let i = 0; i < 1000; i++) {
  console.timeEnd();
}
```
![console_runjs](https://user-images.githubusercontent.com/2471651/50722396-6cd83f80-1109-11e9-8122-308ae1b26cfb.png)

**Comment by lukehaas** [comment]
Thanks for raising this. Will look into it.

**Comment by CallumDenby** [comment]
Above example should only log once and throw 999 warnings, because it's ending a timer 1000 times, but only starts it once.

```
> (node:21206) Warning: No such label 'undefined' for console.timeEnd()
```

**Comment by hroland** [comment]
+1

**Comment by lukehaas** [comment]
@hroland @LeeHyungGeun @CallumDenby this is now supported in RunJS version 1.11.0
