### ISSUE TITLE
"Check for Updates..." is broken

### ISSUE THREAD

**Issue by getify** [lukehaas/RunJS#121]
I get the following error (on windows) when I try to check for updates, even in the latest updated RunJS.

![Annotation 2020-02-04 095351](https://user-images.githubusercontent.com/150330/73761979-2f434d00-4735-11ea-8691-7a393841d910.png)

The HTTP 404 error is against this URL: https://github.com/lukehaas/RunJS/releases/download/v1.8.0/latest.yml

However, checking the release assets on github here, there is no such file, which is the source of the 404. The assets folder has "latest-mac.yml" and "latest-linux.yml", but no "latest.yml" (or "latest-windows.yml").

**Comment by lukehaas** [comment]
@getify thanks for raising this. I'll aim to get this resolved shortly.

**Comment by lukehaas** [comment]
I've manually added the missing latest.yaml file, though there still seems to be a problem with updating on Windows.
I'll try and get this addressed for the next release.
