### ISSUE TITLE
New Logo - Pixelated

### ISSUE THREAD

**Issue by CassaranoIFTV** [lukehaas/RunJS#123]
Hi! Your new logo is very beautiful and professional. I'm proud to have an app like it and to talk about with my mates. However on mac os, it seem pixelated in the dock on mac book pro 2019 screen and FHD Screen. Is there a solution ?

_Originally posted by @CassaranoIFTV in https://github.com/lukehaas/RunJS/issues/117#issuecomment-581811668_

**Comment by lukehaas** [comment]
@CassaranoIFTV thanks for raising this. I'll see what I can do about this in the next release.

**Comment by Leslie-Wong-H** [comment]
> @CassaranoIFTV thanks for raising this. I'll see what I can do about this in the next release.

The same issue appears on my win10 FHD screen. Please raise the resolution rate of the favicon.ico of runjs. 256*256 should be prefferred. 

![image](https://user-images.githubusercontent.com/27696701/92302437-c8259980-ef9e-11ea-90ba-65e75c1fa39a.png)
![image](https://user-images.githubusercontent.com/27696701/92302440-cd82e400-ef9e-11ea-94a4-3b12bf6bdf23.png)

**Comment by lukehaas** [comment]
@Leslie-Wong-H the resolution of the icon I'm using is 2048x2048 which should be plenty high enough. I think this could be some kind of upstream issue with Electron. Will investigate further.

**Comment by adi518** [comment]
It also looks too much like Windows Sticky Notes.

**Comment by lukehaas** [comment]
@CassaranoIFTV @Leslie-Wong-H @adi518 The latest version of RunJS has an updated icon. This issue should be resolved now.
