### ISSUE TITLE
Bug: "Save"/"save as" Cancellation Error

### ISSUE THREAD

**Issue by finuex** [lukehaas/RunJS#125]
How to reproduce

0. [Preparation] Open *.Js file from RunJS
1. "File" > "Save as"
2. Click "Cancel" button
3. Click "OK" for error notification
4. Click "Save"
5. An error appears

in my opinion, if the "save" menu is clicked [number 4], the file will be saved where the file was previously opened

RunJS 1.8.0

**Comment by lukehaas** [comment]
@finuex thanks for raising this, I will investigate.

**Comment by lukehaas** [comment]
This will be resolved in the next release.

**Comment by Aamir2000** [comment]
Yeah please fix this issue because I honestly save a lot of times and it even pops up when I press ctrl + s after the error occurs first time and then we just can't use that shortcut unless we use "save as" from the file menu and its really annoying

**Comment by lukehaas** [comment]
@finuex @Aamir2000 this is nor resolved in RunJS version 1.10.0
