### ISSUE TITLE
Odd results printed for custom Array function that doesn't appear in Dev Tools or PlayCode

### ISSUE THREAD

**Issue by aquacode** [lukehaas/RunJS#126]
Mac OS Catalina
Version 1.8.0

If I have an array like:
`
const a = [1,2,3,4,5];
`

And then I add a function to Array like so:
`
a.multiply = function() {
  let size = a.length;
  for (var i = 0; i < size; i++) {
    a.push(a[i] * a[i]);
  }
};
`

Then execute the following:
`
a.multiply();
console.log(a);
a.length;
`

The results print the function at the end of the array:
`
[ 1, 2, 3, 4, 5, 1, 4, 9, 16, 25, multiply: [Function] ]
10
`
But length is still in fact 10.

However, in Dev Tools or PlayCode, the console.log(a); output appears like this:

`
[1,2,3,4,5,1,4,9,16,25]
`

Why the different results?

**Comment by lukehaas** [comment]
When you add the function `a.multiply = ...` you're not adding it to the array, you're just adding it as a static property on the array variable. 
This won't be counted in `a.length` even though it's visible when you console log the `a` variable.
That's how I understand it anyway.

**Comment by lukehaas** [comment]
Looking at the Chrome dev tools, I see this result for console.log(a):
`[1, 2, 3, 4, 5, 1, 4, 9, 16, 25, multiply: ƒ]`

Which devs tools did you compare this against?

**Comment by aquacode** [comment]
Forgot to mention, I'm using Firefox dev tools. But also, this doesn't appear in PlayCode.io either.
Just wondering why RunJS and Chrome dev tools show the function at the end of the array ... does RunJS use Chrome's JavaScript engine?

**Comment by lukehaas** [comment]
Yes, RunJS and Chrome use the same JavaScript engine.

**Comment by aquacode** [comment]
OK, thanks for clarifying, I guess some engines and implementations of console are not showing that static property/function.
Germaine to this issue is if one was to implement multiply _for all arrays_ using prototype, any idea why RunJS displays the result of arrays of greater than 3 items on multiple rows and when 3 or less it's a single row? 
![Screen Shot 2020-03-06 at 12 30 40 PM](https://user-images.githubusercontent.com/426933/76111827-a5daa100-5fa6-11ea-8d0a-e5a7c96cc35b.png)

**Comment by lukehaas** [comment]
It's breaking it into rows of 3 as it's too long to show on a single line.
Just a formatting rule.

**Comment by aquacode** [comment]
Ok, that's what I thought, however, fyi, the screenshot cut off the actual size of the "console" and my screen size -- it could actually handle a _much_ larger single row, but somehow defaults to 3.

**Comment by lukehaas** [comment]
Array wrapping has been updated in the latest version of RunJS. It will now wrap according to the width of the panel.
