### ISSUE TITLE
Install packages on the fly

### ISSUE THREAD

**Issue by robertherber** [lukehaas/runjs#13]
Love this idea and simplicity of it, thanks @lukehaas for building it!

I have a suggestion to build on top of this simplicity, and that is to automatically install packages that are required/imported. When a package isn't found ask the user "Install now?". At least for me I see the biggest use-case is to play around (I won't usually run it in the context of a specific project, so I don't want to care about what's installed locally) - this would greatly enhance this experience! :)

Cheers!

**Comment by lukehaas** [comment]
Thanks. I'm currently developing a feature that will allow user to install packages. 
It will be in the next release.

**Comment by robertherber** [comment]
Great news, thanks @lukehaas!

**Comment by dnalborczyk** [comment]
@lukehaas before inventing the wheel from scratch, you could check out **tink** https://github.com/npm/tink as well as https://blog.npmjs.org/post/178027064160/next-generation-package-management

**Comment by lukehaas** [comment]
@robertherber You can now install Node packages.
![install-npm-packages](https://user-images.githubusercontent.com/741344/52523400-f048fb80-2c88-11e9-98be-e2ee1584f660.png)

You can access this window via the Action menu.

@dnalborczyk no wheel reinvention needed here.

**Comment by robertherber** [comment]
Super, thanks @lukehaas! Tried it out and it works well :)

**Comment by robertherber** [comment]
Would be great if there's also a hotkey or something to make it easier to reach the installation @lukehaas :)

**Comment by lukehaas** [comment]
Already got this in the next release. It will be Cmd-I

**Comment by robertherber** [comment]
Awesome @lukehaas, thanks!
