### ISSUE TITLE
there should be more light theme

### ISSUE THREAD

**Issue by alikadir** [lukehaas/RunJS#131]
for example [IntellijLightTheme](https://plugins.jetbrains.com/plugin/12697-intellij-light-theme) and [hypest](https://github.com/dizzyup/hyper-hypest)

**Comment by Kachulio1** [comment]
@lukehaas  I also want my favorite theme [**Andromeda**](https://github.com/EliverLara/Andromeda) or ability to add a theme

**Comment by lukehaas** [comment]
@alikadir RunJS now has a new light theme called Visual Studio
