### ISSUE TITLE
Strings spanning more than one line have inconsistent syntax highlighting

### ISSUE THREAD

**Issue by dnicolson** [lukehaas/RunJS#132]
The "More text" part of the string is green while the rest of the strings are yellow.

<img width="1042" alt="Screen Shot 2020-04-19 at 18 10 00" src="https://user-images.githubusercontent.com/2276355/79693130-358f9280-8269-11ea-960e-e4ae4cbf4e01.png">

RunJS 1.8.0

**Comment by lukehaas** [comment]
@dnicolson thanks for raising this.

**Comment by lukehaas** [comment]
@dnicolson this is now resolved in RunJS version 1.10.0
