### ISSUE TITLE
Line no in the Editor

### ISSUE THREAD

**Issue by prashantpiyer** [lukehaas/RunJS#136]
Line no in the editor will  help us to differentiate programming codes

**Comment by lukehaas** [comment]
Line numbers are an option in the preferences.

![Screenshot 2020-04-26 at 12 55 35](https://user-images.githubusercontent.com/741344/80306788-4dad6780-87bd-11ea-834c-cabd4d0d6089.png)

**Comment by prashantpiyer** [comment]
Thanks alot :)
