### ISSUE TITLE
Any way to contribute?

### ISSUE THREAD

**Issue by monojack** [lukehaas/RunJS#137]
Hi. I really enjoy using RunJS and I constantly find myself reaching for it for rapid prototyping. It does lack some nice-to-have features and I would love to help with that. So, is there any way one can contribute?

Thanks!

**Comment by guillaumekpomda** [comment]
Same here!

**Comment by LaksCastro** [comment]
Same here v2.0!

**Comment by gkucmierz** [comment]
@monojack what are features that is missing here?
What contributions can you make?

**Comment by monojack** [comment]
> @monojack what are features that is missing here?
> What contributions can you make?

Well, personally I'd like to see code formatting, custom themes, enabling new js features either through custom babel configs or automatic feature detection. And I see there are many more features people are asking about.

**Comment by gkucmierz** [comment]
> > @monojack what are features that is missing here?
> > What contributions can you make?
> 
> @gkucmierz, personally I'd like to see code formatting, custom themes, enabling new js features either through custom babel configs or automatic feature detection. And I see there are many more features people are asking about.

I started similar project but with a little bit different approach.
If you are interested check instacode repo in my profile.
You can add issues there or create PRs.

**Comment by lukehaas** [comment]
Many nice-to-have features have been added since this ticket was opened, including code formatting, Babel configuration, multiple tabs etc. For this reason, will close this ticket now.
