### ISSUE TITLE
Add an option to disable auto print of lines that return a value

### ISSUE THREAD

**Issue by gkpo** [lukehaas/RunJS#139]
For instance:
```
let str = "Bonjour";
let arr = str.split('');

arr.reverse(); // <= This will output in console 
console.log(arr); // <= This will output in console too
```
When I have large chunks of code, my output is becomes messy and I don't have a good view of what is printed or not. (e.g can't just search all "console.log()" statements).

Would be great to have an option to disable this behaviour.

**Comment by lukehaas** [comment]
@gkpo, There is an option for this. Go to the preferences and under advanced, there is an option called 'Holistic evaluation'

![Screenshot 2020-05-01 at 11 24 33](https://user-images.githubusercontent.com/741344/80799326-7c9d5200-8b9e-11ea-938e-56662bc2e215.png)

Enabling this will give you the result you're looking for.

**Comment by gkpo** [comment]
Awesome, thank you :)
