### ISSUE TITLE
What is the extra line of evaluated output?

### ISSUE THREAD

**Issue by getify** [lukehaas/RunJS#14]
This may sound silly, but that extra line of output as shown here was actually causing me to think I had a bug in a loop where it was printing an extra iteration. Is there a reason for it? Is there a way to remove it?

<img width="448" alt="screen shot 2019-01-06 at 9 13 19 am" src="https://user-images.githubusercontent.com/150330/50737957-33004b00-1194-11e9-8883-5932ea76081b.png">

**Comment by lukehaas** [comment]
Thanks for raising this.
You're right, i can see how this could be confusing. Currently there's a line break added to every line of output. I'll update it so that this doesn't happen to the final line.

**Comment by lukehaas** [comment]
This is now resolved in version 1.3.1
