### ISSUE TITLE
Check for updates error

### ISSUE THREAD

**Issue by pauloimon** [lukehaas/RunJS#141]
Hi!

I'm getting this error since the version 1.8.0:

![image](https://user-images.githubusercontent.com/3463932/81507244-61cf8980-92d2-11ea-9dc7-b39dca9f184f.png)

I checked this directory and the file `app-update.yml` doesn't really exists.

Steps to reproduce:

Go to *Help > Check for Updates*

Information about my system:

OS: Ubuntu 20.04 LTS
RunJS: Version 1.9.0

--

Thanks! I'm really enjoying this app!

**Comment by lukehaas** [comment]
@pauloimon thanks for raising this. Were you able to update to 1.9.0 even with the error message?

**Comment by pauloimon** [comment]
@lukehaas No. I needed to download the .deb package from the releases page and install it manually.

**Comment by lukehaas** [comment]
@pauloimon automatic updates are no-longer supported on Linux.
