### ISSUE TITLE
Failed to update to version 1.9.0 on Mac

### ISSUE THREAD

**Issue by yonifra** [lukehaas/RunJS#143]
Getting this error:
![image](https://user-images.githubusercontent.com/726718/81683151-62952680-945e-11ea-8f05-cc6876f77028.png)

**Comment by yonifra** [comment]
It actually updated to 1.9.0 after closing this error message, weird...

**Comment by lukehaas** [comment]
@yonifra not sure what could have caused this issue, do you see the same error when upgrading to 1.10.0?

**Comment by lukehaas** [comment]
Closing as I've not been able to replicate this issue.
