### ISSUE TITLE
Cannot find module 'moment.js'

### ISSUE THREAD

**Issue by webmasterThomas** [lukehaas/RunJS#144]
Hi Luke, could not find any info of how to import correctly, so have issue like this:

Error: Cannot find module 'moment.js' 

my code like :

import {moment} from "moment.js"

Can you direct?

**Comment by lukehaas** [comment]
If you got to the `Action` menu then choose `Install NPM Packages` a window will open where you can search for packages and install them.

**Comment by webmasterThomas** [comment]
Many thanks for quick answer.

> 
> 
> If you got to the `Action` menu then choose `Install NPM Packages` a window will open where you can search for packages and install them.

**Comment by lukehaas** [comment]
👍
