### ISSUE TITLE
Change Timezone

### ISSUE THREAD

**Issue by yurakruhlyk** [lukehaas/RunJS#145]
Hi, how I can change the timezone? because I notice that RunJs doesn't use the device time.
For example I generated array of date and result in RunJs and in vscode debugger not the same.
By the way thanks, nice tool.
<img width="283" alt="Знімок екрана 2020-05-22 о 14 28 27" src="https://user-images.githubusercontent.com/16261471/82663529-81eb3b00-9c38-11ea-8f0f-5c3a61f46793.png">

![Знімок екрана 2020-05-22 о 14 27 09](https://user-images.githubusercontent.com/16261471/82663426-52d4c980-9c38-11ea-8a9b-f52454267667.png)

**Comment by lukehaas** [comment]
@yurakruhlyk thanks for raising this.
It looks like you're comparing a raw date object to a date string. This behaviour is expected in this case as the date object shows the date/time without any timezone and when it's converted to a string your timezone is accounted for.

Here is an example where I set my system time ahead by 8 hours:
![Screenshot 2020-05-22 at 20 53 18](https://user-images.githubusercontent.com/741344/82669734-df30bd80-9c33-11ea-971f-5c2f27699290.png)

**Comment by yurakruhlyk** [comment]
@lukehaas hmm, really when I add .toString() I get the right timezone. But in chrome everything works without toString, can we do the same behavior?
<img width="679" alt="image" src="https://user-images.githubusercontent.com/16261471/82671878-3a6cab00-9c48-11ea-8e98-5ad1146acb97.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/16261471/82671892-40fb2280-9c48-11ea-82de-43717591363a.png">

**Comment by lukehaas** [comment]
This is a case where RunJS is being true to the language while the Chrome console is showing you a modified result.
The Chrome console if showing you a stringified result for `new Date()` which is wrong.

**Comment by yurakruhlyk** [comment]
@lukehaas ok, thanks👍🏻

**Comment by lukehaas** [comment]
👍
