### ISSUE TITLE
No type error for typescript codes

### ISSUE THREAD

**Issue by sujeet-agrahari** [lukehaas/RunJS#146]
I am not getting any type error for typescript code. 
![image](https://user-images.githubusercontent.com/22151975/82720237-10aa9700-9ccf-11ea-9309-13c1a1e93657.png)

**Comment by lukehaas** [comment]
RunJS currently only supports TypeScript syntax and won't show any warnings/errors.

**Comment by sujeet-agrahari** [comment]
Instead of wrapping around node.js, now you can  use Deno to get TypeScript support out of the box.
That way you also don't need babel and other stuffs.
I haven't use electron before. I don't know that's possible to use Deno inside an electron app.
However, if that's possible, it would be awesome.

**Comment by lukehaas** [comment]
Let's see how things go with Deno. Regarding Babel, I don't think Deno supports modern JavaScript beyond what Node currently supports so there would still be a need to use Babel.

**Comment by ivosabev** [comment]
+1 for full TypeScript support with errors. Maybe add eslint support and the ability to set your TypeScript version?

**Comment by sujeet-agrahari** [comment]
> +1 for full TypeScript support with errors. Maybe add eslint support and the ability to set your TypeScript version?

Indeed full Typescript support but with errors? I don't get any typescript error.

**Comment by lukehaas** [comment]
Improved TypeScript support is a high priority. Aiming to have this in RunJS before the end of the year.

**Comment by tairt** [comment]
@lukehaas RunJS is a great tool for JavaScript prototyping and I like it a lot. Great work!

Regarding TypeScript support, it may be misleading that RunJS is called a TypeScript playground/scratchboard. Without the feature of transparently showing the result of type checking the main requirement for a TypeScript scratchboard is not met. Until this feature is not implemented it may help new users if you change the description on the main webpage and the project description or as another option add a note that the feature is not implemented yet but upcoming. Otherwise, users will look through the settings or search for documentation on how to enable this feature.

Thanks a lot : )

**Comment by lukehaas** [comment]
Thanks @tairt, I can see your point. TypeScript support needs to improve and it will. However, RunJS does currently support TypeScript syntax which I think is the most important part. I don't think it would be right to not mention such a significant feature.

**Comment by tairt** [comment]
@lukehaas Thanks for the quick feedback. Sure, makes sense. Then it may be good to just add a note, that error checking is not supported yet. This will reduce the time for users to get accustomed to the features of the pad : )

**Comment by lukehaas** [comment]
Yeah, I'm currently working on expanding the documentation, will make sure to make this clear there.

**Comment by tairt** [comment]
Great, Thanks @lukehaas!

**Comment by HenriqueOmena** [comment]
I'm anxiously waiting for this feature, Will be very nice to teach technology like typescript and all array methods and stuff like that's, with this feature, thanks a lot!

**Comment by lukehaas** [comment]
@sujeet-agrahari @ivosabev @andreastai @HenriqueOmena type checking is now supported in the latest version of RunJS:

![Screenshot 2021-06-26 at 17 51 07](https://user-images.githubusercontent.com/741344/123520156-4460a900-d6a7-11eb-9cc4-501179b635ff.png)
