### ISSUE TITLE
The application “RunJS.app” can’t be opened.

### ISSUE THREAD

**Issue by chrise86** [lukehaas/RunJS#147]
This has just started happening for me, it's been working fine.

I've tried the following:

- Allowed apps to run from anywhere (`sudo spctl --master-disable`)
- `chmod +x /Applications/RunJS.app/Contents/MacOS/RunJS`
- `sudo xattr -rd com.apple.quarantine /Applications/RunJS.app`
- Remove, reinstall
- Restart the machine
- Checked system preferences incase

Any ideas?

I also get this (I think possibly after running one of the commands above):
```
Check with the developer to make sure RunJS works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.
```
When running the binary directly, by opening the package contents, I get the following in the terminal window:
```
dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/RunJS.app/Contents/MacOS/RunJS
  Reason: no suitable image found.  Did find:
	/Applications/RunJS.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/RunJS.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1
[1]    3548 abort      /Applications/RunJS.app/Contents/MacOS/RunJS
```

**Comment by chrise86** [comment]
Update: just downloaded 1.8.0 (issue was with 1.9.0) and it works fine.

**Comment by lukehaas** [comment]
@chrise86 thanks for raising this, this is very odd.
What version of macOS are you on?

**Comment by chrise86** [comment]
Hey @lukehaas I'm on `10.15.4 (19E287)`.

**Comment by molvqingtai** [comment]
Same issuse

The process has started, but the run.js window is not displayed.

Run.js:1.9.0
MacOS:10.15.5 (19F101)

**Comment by lukehaas** [comment]
Thanks @molvqingtai, I think this must be a Catalina related issue. Will investigate soon.

**Comment by lukehaas** [comment]
I've now installed RunJS 1.9.0 on macOS 10.15.5 - both as a fresh install and via auto-update and I haven't encountered any issues, it's all working fine.
Not sure what to suggest only to make sure you can install apps from identified developers and make sure the download isn't corrupted somehow.
![Screenshot 2020-06-18 at 11 16 29](https://user-images.githubusercontent.com/741344/85008953-95b19080-b155-11ea-8469-5eb7214ef5a7.png)
