### ISSUE TITLE
Enhancement: New File 

### ISSUE THREAD

**Issue by finuex** [lukehaas/RunJS#148]
Please add "New File" sub menu on "File" Menu.

the algorithm I think of is like this:

1.  click menu "FILE"
2.  click submenu "NEW FILE"
3.  if you are currently opening a file, RunJS will ensure the file is saved first.
4.  then, runJS will clean up the workspace in runJS.

RunJS 1.9.0

**Comment by lukehaas** [comment]
@finuex thanks for raising this. The behaviour you're describing is very similar to what is provided by the `Clear` option that can be found in the `Edit` menu.
I'm reluctant to add a new file option that clears code from the workspace.
