### ISSUE TITLE
Windows protected your PC

### ISSUE THREAD

**Issue by rrcamc** [lukehaas/RunJS#149]
Is this a known issue? i.e. this app does not have a certificate or is there really a problem?
![chrome_2020-05-30_11-06-01](https://user-images.githubusercontent.com/50029456/83333462-17ed1a00-a266-11ea-980a-e12381125b3b.png)

Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.
App: | RunJS-Setup-1.9.0.exe
Publisher: | Unknown publisher

Thanks for any feedback!

**Comment by lukehaas** [comment]
Thanks @rrcamc, this is known. RunJS does not have a Windows certificate yet.

**Comment by rrcamc** [comment]
thank you @lukehaas. Great work on the app!
