### ISSUE TITLE
Zoom keyboard shortcut, zoom vs font-size

### ISSUE THREAD

**Issue by getify** [lukehaas/runjs#15]
The keyboard shortcut for zooming is `⌘ +`, which makes sense. However, that actually requires (on most US keyboards anyway) a `⌘ ⇧ +` keypress, because `+` is on the upper portion of the `=` key. Most editors I've worked with actually allow just `⌘ =` as well. This would be *very helpful*.

----

Also, the "zoom" behavior of this operation feels a bit weird:

![runjs-zooming](https://user-images.githubusercontent.com/150330/50738105-106f3180-1196-11e9-8cfc-302a5d069e5d.gif)

It's strange and a bit frustrating that the zooming is also changing the spacing around the text. I would expect zooming to only affect the text... in other words, like in Sublime, when you do `CMD +`, it just ups the font size by a point, and `CMD -` drops the font size by a point. The zoom/unzoom don't change any of the UI layout/positioning, only the content text.

Also, it might be helpful if we could independently "zoom" the scratch area from the console output area, similar to how in Chrome the devtools has a zoom that's independent of the page's zoom.

**Comment by lukehaas** [comment]
Thanks for raising this.
Firstly, I will add the `CMD =` shortcut for zooming.

Regarding your second point, only increasing the font-size on zoom seems to make sense, especially as the UI is very minimal.
My only concern would be if some users, possibly ones with sight issues, would expect a full UI zoom.

**Comment by getify** [comment]
> My only concern would be if some users, possibly ones with sight issues, would expect a full UI zoom.

That concern is understandable, but I think there are generally other OSX A11Y tools they can use in those cases.

**Comment by lukehaas** [comment]
In version 1.2.2 zooming will now increase the font size.
I've also implemented the ⌘ = shortcut.
