### ISSUE TITLE
Enable experimental decorator feature

### ISSUE THREAD

**Issue by sujeet-agrahari** [lukehaas/RunJS#150]
> SyntaxError: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (8:1):

```
function Logger(constructor: Function) {
  console.log('Logging...')
}

@Logger
class Person {
  name = 'Max';

  constructor() {
    console.log('Creating person object...');
  }
}
```
```
SyntaxError: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (8:1):

   6 | }
   7 | 
>  8 | @Logger
     | ^
   9 | class Person {
  10 |   name = 'Max';
  11 | 
```

**Comment by lukehaas** [comment]
Decorators are not currently supported. I intend to include support when the spec matures.

**Comment by sujeet-agrahari** [comment]
If it is using bable. Why don't just give an option to enable it?

**Comment by sujeet-agrahari** [comment]
> Decorators are not currently supported. I intend to include support when the spec matures.
Many frameworks are using those features a lot, whether it is angular or nestjs.

**Comment by lukehaas** [comment]
@sujeet-agrahari I've taken another look and will be including decorators as an option in the next release. Thanks for the suggestion 👍

**Comment by lukehaas** [comment]
Decorators are now an option in RunJS version 1.10.0

![Screenshot 2020-07-17 at 17 35 07](https://user-images.githubusercontent.com/741344/87809818-ea7b2080-c853-11ea-8c5f-c91e8c1efc82.png)
