### ISSUE TITLE
Issue with handling semi colon in runjs

### ISSUE THREAD

**Issue by sameerinfodb** [lukehaas/RunJS#153]
semicolon should have been optional, refer the screenshot below,  check why first code block is returning error whereas same code in the second code block works fine if we use a semicolon in the first line. Please explain why this behavior.

![Runjs-issue](https://user-images.githubusercontent.com/1568953/84531221-e2363f80-ad01-11ea-88a0-56a59ff40945.png)

**Comment by lukehaas** [comment]
There will always be edge cases where semi-colons are essential. In a case where you have parentheses at the beginning of a new JS will interpret this as a function call with the previous line as the function name.
