### ISSUE TITLE
No indication about current 'working file'

### ISSUE THREAD

**Issue by gabiaker** [lukehaas/RunJS#154]
Hello,
i've noticed that there is no way to know on which file I'm currently working on,  I like using RunJS a lot, and in many cases i'm saving my work, but before that it would be nice if in the App Window it would say "untitled" as after the save it would indicate the name of the currently open file.

Thank you !

**Comment by orest22** [comment]
Would love to see something like that as well!

**Comment by LukaszGrela** [comment]
I'd like to see this feature too.

**Comment by lukehaas** [comment]
@gabiaker @orest22 @LukaszGrela RunJS now has tabs and filenames are displayed after saving. 👍
