### ISSUE TITLE
"no suitable image found" when importing an NPM package

### ISSUE THREAD

**Issue by sk8Guerra** [lukehaas/RunJS#155]
I've just installed `bcrypt` package to try it out. But as soon as I import it: it throws this error: 

`Error: dlopen(/Users/**/Library/Application Support/runjs/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node, 1): no suitable image found.  Did find:`

And I'm not sure what it is. what could it be? any suggestion?

Thanks.

**Comment by lukehaas** [comment]
@sk8Guerra sorry to see you're having this issue. I'm not sure what the issue here could be, I'd just suggest removing the package and re-installing.

**Comment by sk8Guerra** [comment]
I've uninstalled and reinstalled the package and didn' work.

I've tried to install and use other packages and worked fine.

Do you think is the package itself?

**Comment by sk8Guerra** [comment]
Thanks @lukehaas,  actually that is the problem. Tried **bcryptjs** and everything worked fine.
