### ISSUE TITLE
Select next word + List of Shortcuts

### ISSUE THREAD

**Issue by leocaseiro** [lukehaas/RunJS#156]
Hi, I was hoping it would have the feature of Cmd+D to select the same word, similar the SublimeText one.

Also, could you please share the list of shortcuts? I can't find it. Thanks

![select_words](https://user-images.githubusercontent.com/940070/85843847-27b83980-b7e5-11ea-88ed-2aea97aa416f.gif)

**Comment by lukehaas** [comment]
@leocaseiro this is now supported in RunJS version 1.10.0

**Comment by leocaseiro** [comment]
Thank you for that implementation. It's working very nice.

However, it would be nice be able to see a list of the shortcuts (I'll open a new issue about that)

Thanks again!
