### ISSUE TITLE
If you write bad code you can never fix RunJS

### ISSUE THREAD

**Issue by pbitkowski** [lukehaas/RunJS#158]
The problem is that when you write some endless loop or some bad recursive function then you can't fix this. The UI freezes and you can't remove bad code.

**Comment by pbitkowski** [comment]
This code broke RunJS on my mac: 
```
function longestMotif (seq) {
  const seqsCount = {};
  
  function safeIncrement(key) { 
    if (typeof seqsCount[key] === 'number') {
      seqsCount[key]++;  
    } else { 
      seqsCount[key]=1; 
    }
  }

  function aux(previous, rest) {
    if(previous.length > 0) {
      safeIncrement(previous);
    }

    if(rest.length > 0) {
      aux(previous+rest[0], '')
      aux(rest[0], '')
    }
  }
  
  seq.split().forEach(letter => { });
}


```

**Comment by lukehaas** [comment]
![Screenshot 2020-06-29 at 17 56 15](https://user-images.githubusercontent.com/741344/86034071-dcdf3180-ba31-11ea-9747-43dacc5a7494.png)

The next version of RunJS has some big improvements in this area. For now, just make sure you have loop protection enabled.

**Comment by pbitkowski** [comment]
Thanks @lukehaas, is there a way to remove code from app before running it? I can't do it on app because it's crashing immediately .

**Comment by ethancane** [comment]
The only remedy I found it to navigate to your home Library folder and delete all references to Runjs under your Application Support directory and also the Preferences folder.

Then relaunch and all should be well again. I was caught in this situation and it was my only way out of an endless loop sequence.

**Comment by pbitkowski** [comment]
Awesome, it worked. Thanks @ethancane ❤️

**Comment by ethancane** [comment]
Please be advised however, that this is not the ideal or recommended solution to your problem (but it worked for me).

To follow up, you only need to remove the "runjs" directory under the "Application Support" directory in your home "Library". You can leave the preferences *.plist file alone that sits under the "Library/Preferences" directory.

After a relaunch all should be working again. The only major caveat to this however is that you will also wipe out any and all node packages you have installed via the app?
