### ISSUE TITLE
Settings window does not fit all content

### ISSUE THREAD

**Issue by Konc** [lukehaas/RunJS#160]
On my Windows 10 Pro machine when I go to the RunJS settings, the Babel settings get cropped at the bottom because the window isn't high enough, and there's no way to resize it manually.

![image](https://user-images.githubusercontent.com/2979149/86530697-28269380-bebb-11ea-9cc0-d49bc0da8464.png)

My RunJS is up-to-date.

**Comment by lukehaas** [comment]
@Konc there will be a fix for this in the next release.

**Comment by lukehaas** [comment]
This is fixed now in version 1.11.0
