### ISSUE TITLE
Enable key repeat in vim mode

### ISSUE THREAD

**Issue by nabn** [lukehaas/RunJS#161]

**Comment by lukehaas** [comment]
@nabn thanks for raising this. Could you describe in a bit more detail what it is you're doing and what you're expecting to see?

**Comment by nabn** [comment]
With the vim mode on, pressing and holding a key only registers it once. I can't press and hold j to keep moving the cursor down, for example. It would be nice for this behaviour to be the same as other editors (including vim).

**Comment by lukehaas** [comment]
Thanks @nabn, I've just tried this and for me holding j does keep moving the cursor. I'm on a Mac using RunJS version 1.10.1, what OS and RunJS version are you using?

**Comment by nabn** [comment]
I'm on 1.10.1 too, macos 10.15.6 (Catalina). Checked all preferences to see if I'm not missing anything, "Always use vim keys" is the only relevant option I found, which is checked.

**Comment by nabn** [comment]
@lukehaas did you try that in vim mode or the normal one?

**Comment by lukehaas** [comment]
@nabn key-repeat is working fine for me in both modes. 
Are you sure you have key-repeat enabled in your system keyboard settings?

**Comment by nabn** [comment]
Yes. It's working fine in other apps. Not sure what's wrong. I'll do some more investigation and report back.
