### ISSUE TITLE
File > Open Bug

### ISSUE THREAD

**Issue by ethancane** [lukehaas/RunJS#162]
Having just launched the app an empty window will appear.

Enter some code and proceed as normal. Save the file, etc.

Close the active window and then attempt to Use the File > Open command and nothing happens. This means I am unable to open previously saved scratchpads for further development.

Thanks
<img width="499" alt="Screenshot 2020-07-08 at 16 47 06" src="https://user-images.githubusercontent.com/2612792/86940409-b2305f80-c13a-11ea-81c8-9d4bbcd54d6a.png">

**Comment by ethancane** [comment]
Just tested again. If you have an active editor open and attempt to File > Open a file then it does indeed present an open dialog, but the original issue logged still holds true. Close your active editor, it seems you can only have one open at a time and you'll be unable to re-open another file.

**Comment by lukehaas** [comment]
@ethancane thanks for raising this. Will aim to have a fix in the next release.

**Comment by lukehaas** [comment]
@ethancane this is now resolved in version 1.13.0
