### ISSUE TITLE
Can't use bcrypt package

### ISSUE THREAD

**Issue by shafkathullah** [lukehaas/RunJS#164]
Throws this error while importing `bcrypt` library.

`Error: dlopen(/Users/mac-machine/Library/Application Support/runjs/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node, 1): no suitable image found.  Did find:`

**Comment by lukehaas** [comment]
@shafkathullah this is likely an issue with bcrypt being a native module. I will look into this but for now, I would suggest using `bcryptjs`
