### ISSUE TITLE
List of shortcuts available (Documentation or inside the IDE)

### ISSUE THREAD

**Issue by leocaseiro** [lukehaas/RunJS#165]
It would be nice to be able to see all shortcuts available in the IDE. 

Could you please display in the DOCS /readme or somewhere?

Thanks

**Comment by lukehaas** [comment]
@leocaseiro good suggestion will do.

**Comment by lukehaas** [comment]
@leocaseiro shortcuts are now documented here: https://runjs.app/docs#shortcuts
