### ISSUE TITLE
Can't install npm packages

### ISSUE THREAD

**Issue by sujeet-agrahari** [lukehaas/RunJS#166]
I have latest version of the app. Whenever I try to install  a package getting below error.
I have also tried setting a working directory, but that doesn't solve the issue.
I am running on Windows 10 Home.
![image](https://user-images.githubusercontent.com/22151975/88149920-57106980-cc1e-11ea-8c29-596517c89e36.png)

**Comment by lukehaas** [comment]
@sujeet-agrahari could there be anything on your system that might be preventing RunJS from creating files?

**Comment by sujeet-agrahari** [comment]
Tried also running as administrator, still the same error. As a workaround, I have set the working directory to a node-app directory and using npm to install packages.

**Comment by nicolab28** [comment]
Same issue,
Windows 10
RunJS 1.13.1.0

installed/run with administrator privileges or not, Install NPM Packages tells me This feature is unavailable

**Comment by lukehaas** [comment]
@nicolab28 If you go to %APPDATA%\runjs in your terminal are you able to manually install NPM packages there?

**Comment by lukehaas** [comment]
@sujeet-agrahari @nicolab28 are you still facing this issue with the latest version of RunJS, version 1.15.1?

**Comment by sujeet-agrahari** [comment]
@lukehaas It's working now, thanks for the fix.

**Comment by lukehaas** [comment]
🎉
