### ISSUE TITLE
Indenting selection with tab deletes the text.

### ISSUE THREAD

**Issue by alexdevero** [lukehaas/RunJS#168]
It would be nice feature or option to allow Tab key to indent selected text. Now, selecting text and pressing Tab deletes the text. Tab key now works in a similar way only combined with Shift key, to decrease the indentation of the text for one level. Tab alone could could do the opposite, indent the text for one level.

**Comment by lukehaas** [comment]
@alexdevero good suggestion, thanks for rasing it.

**Comment by lukehaas** [comment]
@alexdevero this is now supported in RunJS version 1.11.0

**Comment by alexdevero** [comment]
@lukehaas  Thank you.
