### ISSUE TITLE
Error - something went wrong

### ISSUE THREAD

**Issue by sk8Guerra** [lukehaas/RunJS#169]
I'm installing a [package](https://www.npmjs.com/package/statistiken), and this is the message that appears... what exactly happens?

<img width="547" alt="Screen Shot 2020-08-05 at 18 21 55" src="https://user-images.githubusercontent.com/18681676/89476694-9d9ab380-d748-11ea-8b35-b23aebde869b.png">

Thanks for your help.

**Comment by lukehaas** [comment]
@sk8Guerra the link you provided to the package is going to a 404 page, this could be related to the error you're seeing in RunJS.

**Comment by sk8Guerra** [comment]
@lukehaas really? it's weird because when I click the link it redirects me here: https://www.npmjs.com/package/statistiken

**Comment by lukehaas** [comment]
Odd, link is working fine now.
I've taken a look into this and the install is failing on the postinstall script within statistiken. I'll investigate further for a solution.

**Comment by sk8Guerra** [comment]
@lukehaas ohhh I get it thanks! Ok, let me know what you find out.

**Comment by lukehaas** [comment]
@sk8Guerra this is working now in RunJS version 1.11.0

**Comment by sk8Guerra** [comment]
Thank you so much @lukehaas!
