### ISSUE TITLE
Feature request: explore object properties

### ISSUE THREAD

**Issue by hontas** [lukehaas/RunJS#17]
First of all - thanks for a great tool, something I've wanted a long time.

I use the dev console in Chrome to do small explorations in JS-land and the best feature in my mind is the "explore object methods and properties"-functionality that for example shows me what methods a date object has when I type "." after. So `myDate.` would yield
```
constructor
getDate
getDay
[...]
```

And then autocompletes when I start typing something like `myDate.to` would yield
```
toDateString
toGTMString
toISOString
[...]
```

If RunJS had this I would never need to open another Crome tab again ;)

**Comment by lukehaas** [comment]
Agree, this would be good.

**Comment by TylerEikenberg** [comment]
+1 to this idea! This would get a ton of use from me if this feature were added.

**Comment by lukehaas** [comment]
@hontas autocomplete is now supported in the latest version of RunJS
