### ISSUE TITLE
Pasting over 2Mb of code to run completely freezes the actions from the RunJs editor 

### ISSUE THREAD

**Issue by MatiasHiltunen** [lukehaas/RunJS#170]
Impossible to clear the editor, apparently the data persists even during the complete reinstalling of the program.

**Comment by lukehaas** [comment]
@MatiasHiltunen deleting RunJS's config file should fix the problem. This is located here:
`~/Library/Application\ Support/runjs/config.json` - on a Mac

**Comment by lukehaas** [comment]
RunJS version 2.2.2 includes improvements for handling large files.
