### ISSUE TITLE
TypeError: Cannot set property 'consoleCount' of undefined

### ISSUE THREAD

**Issue by dnicolson** [lukehaas/RunJS#172]
Version 1.10.1

```
const a = 'test'
```

<img width="1177" alt="Screen Shot 2020-08-24 at 22 37 14" src="https://user-images.githubusercontent.com/2276355/91093945-6a1dbb80-e65a-11ea-9411-f591faea2ede.png">

**Comment by lukehaas** [comment]
@dnicolson are you able to consistently see this message when you run this code?

**Comment by lukehaas** [comment]
Closing as no detail is provided.
