### ISSUE TITLE
[Feature Request] - Add vs-code style keyboard shortcuts

### ISSUE THREAD

**Issue by yonifra** [lukehaas/RunJS#173]
I miss my `Option+Up/Down` to move lines around and other key bindings that I use a lot in VS code and are missing from RunJS

**Comment by lukehaas** [comment]
Thanks @yonifra, improved support for keyboard shortcuts is something I'm working on. `Option+Up/Down` for line swapping is something I can add in the next release.
Please list any other keyboard shortcuts you think are missing.

**Comment by lukehaas** [comment]
Option+Up/Down shortcut is now implemented.
