### ISSUE TITLE
Frozen after pasting long object, no way to reset since it autoloads (even uninstalling didn't fix)

### ISSUE THREAD

**Issue by JeremyBernier** [lukehaas/RunJS#178]
I pasted a long JSON object into RunJS, which froze RunJS. If I close and reopen RunJS, it still tries to load this JSON object and is frozen, and there's no way for me to clear it because it's frozen (eg. Edit -> Clear does nothing). I even reinstalled RunJS and it's still trying to load this JSON object. The application is basically permanently broken on my computer.

In the meantime, where is the client-side data stored so I can delete it and get this application working again? 

https://www.loom.com/share/93812bb763ca49e68d0bc585aca4c39d

OS: Windows 10

**Comment by lukehaas** [comment]
If you go to `%APPDATA%` in you4r explorer, theres should be a folder called runjs, delete the `config.json` file in there.

**Comment by JeremyBernier** [comment]
Thanks!

**Comment by jelitter** [comment]
Seems odd to me that this issue is closed. The application should handle this kind of issue, without the user needing to google his way to the solution.
I've had this problem a couple of times since I purchased the license. Everytime I need to google for the way to resolve it.
Thanks!

**Comment by lukehaas** [comment]
@jelitter this is closed because RunJS now guards against pasting large objects. The paste limit is 5MB.
Please ensure you are using a recent version of RunJS.

**Comment by jelitter** [comment]
Hello. I am indeed using the latest version. The application still freezes
when having a large enough object in the file (way under 5MB).

It would be nice to have the ability to kill dead tabs from within the
application.

**Comment by lukehaas** [comment]
@jelitter what's the size of the object you're pasting in?

You should try turning off transpilation and runtime values. With these turned off, you will see a performance improvement.

**Comment by duck9see** [comment]
If you want to keep your settings, just delete `tabs` from your config.json file.
and I agree with @jelitter.
