### ISSUE TITLE
Feature Request: show api doc along side

### ISSUE THREAD

**Issue by multics** [lukehaas/runjs#18]
That would be nice.

**Comment by CallumDenby** [comment]
Good option for this is using OSX splitscreen and using [Dash](https://kapeli.com/dash) or [Zeal](https://zealdocs.org/)

**Comment by multics** [comment]
good idea!

**Comment by lukehaas** [comment]
Agree with @CallumDenby here. Dash and Zeal are both great solutions for viewing documentation.

**Comment by multics** [comment]
alright
