### ISSUE TITLE
Automatic indentation is not working

### ISSUE THREAD

**Issue by yumemi-yshoji** [lukehaas/RunJS#180]
When I updated the RunJS version from 1.10.1 to 1.11.0, automatic indentation stopped working. 
Is there any errors?

## Environment

* Mac: macOS Catalina v10.15.6

### v1.10.1

![v1 10 1](https://user-images.githubusercontent.com/68892899/92551634-70867700-f299-11ea-898f-a6fa6940f979.gif)

### v1.11.0

![v1 11 0](https://user-images.githubusercontent.com/68892899/92551640-74b29480-f299-11ea-9cc0-c2c6bf301559.gif)

**Comment by lukehaas** [comment]
@yumemi-yshoji thanks for raising this. This will be resolved in the next release.

**Comment by yumemi-yshoji** [comment]
@lukehaas Thanks for your response!

**Comment by lukehaas** [comment]
@yumemi-yshoji this is now resolved in the latest version of RunJS.
