### ISSUE TITLE
Shortcut for commenting code not working

### ISSUE THREAD

**Issue by hellosophiee** [lukehaas/RunJS#182]
Hello there!
First thank you for this tool, I am a big fan of it ♥️.
Please be informed that a shortcut for commenting code `Cmd+/` does not work starting from `v1.10.0`, so I have to use `v1.0
9.0 `instead.
I'd be obliged if you could fix that.
Thank you!

**Comment by lukehaas** [comment]
Commenting with `Cmd+/` is working for me in RunJS version `1.11.0`. I recommend you upgrade to the latest version.

**Comment by hellosophiee** [comment]
Thank you, @lukehaas. I've already tried the latest version, but it didn't work for me. I am on `macOS Catalina 10.15.6`. Thanks.

**Comment by hellosophiee** [comment]
By unchecking the `Vim Keys` in the preferences helped to sort out the issue. 
<img width="712" alt="Screen Shot 2020-09-24 at 3 24 10 PM" src="https://user-images.githubusercontent.com/50250729/94134357-4fb64800-fe7b-11ea-99b0-bf193da9b619.png">
