### ISSUE TITLE
Escape double quotes when stringify

### ISSUE THREAD

**Issue by slumbering** [lukehaas/RunJS#185]
Hello :),

When I stringify a JSON, double quotes are not escape (like it would be with a browser console for instance)

**RunJS** :
<img width="1316" alt="Capture d’écran 2020-10-16 à 11 32 36" src="https://user-images.githubusercontent.com/1186424/96242334-a6f39800-0fa3-11eb-8ac3-7ee54afdc7ed.png">

**Firefox**:
<img width="838" alt="Capture d’écran 2020-10-16 à 11 34 11" src="https://user-images.githubusercontent.com/1186424/96242340-a955f200-0fa3-11eb-9c14-23b937d1f262.png">

Many thanks for the great job !

**Comment by lukehaas** [comment]
Thanks @slumbering, this is expected behaviour as RunJS outputs strings with single quotes so double quotes within those strings don't need to be escaped.

**Comment by slumbering** [comment]
Ok. Thanks for the quick response 👍
