### ISSUE TITLE
Auto hide menu bar

### ISSUE THREAD

**Issue by arnoson** [lukehaas/RunJS#190]
On Linux (and Windows) the menu bar is always visible (and not included in the top bar like on Mac OS). Therefore Runjs doesn't feel as elegant as in the Mac version. Would it be possible to activate the `autoHideMenuBar` property in electron? With this option the menu bar is only visible when `alt` key is pressed.

**Comment by e200** [comment]
+1

**Comment by lukehaas** [comment]
Will be adding the ability to toggle the menu bar in the next release 👍

**Comment by arnoson** [comment]
Great, thank you!

**Comment by lukehaas** [comment]
@arnoson @e200 It's now possible to toggle the menu bar from the view menu 👍

**Comment by smeijer** [comment]
Yet now we have tabs :grimacing: . An option to hide those would be nice to have as well.

**Comment by ricky11** [comment]
Cant seem to remove the title bar in windows, it still shows the application name on the bar, would like a cleaner look? is it possible even for the paid verison?

**Comment by lukehaas** [comment]
@ricky11 this was updated to be available on Linux only as it generated too many support requests from Windows users unaware of how to re-enable the menu bar.

**Comment by ricky11** [comment]
would purchase it if i could toggle the bar.
