### ISSUE TITLE
Top padding on linux

### ISSUE THREAD

**Issue by arnoson** [lukehaas/RunJS#191]
On linux there is a padding on top of the screen (below the menu bar). I guess the padding is used to make space for the window decorations on mac OS. Since this padding is mac OS specific it would be great to remove it on linux.

![Screenshot from 2020-10-26 16-39-02](https://user-images.githubusercontent.com/15122993/97194703-c14f2200-17aa-11eb-9899-43d8aca0cd5f.png)

**Comment by smeijer** [comment]
This will be awesome in combination with #190

**Comment by lukehaas** [comment]
👍  in the next release the space will be reduced. Some space will remain for optional toolbar buttons.

**Comment by lukehaas** [comment]
Top padding is now reduced in the latest release.
