### ISSUE TITLE
Support for ARM on linux

### ISSUE THREAD

**Issue by chefguevara** [lukehaas/RunJS#192]
hi! We use these simple dev machines in Raspberry PIs running Ubuntu MATE for ARM64 processors, any chance we can get a build for this architecture? 

Awesome job by the way!

M

**Comment by lukehaas** [comment]
Thanks @chefguevara, I'll look into it.

**Comment by lukehaas** [comment]
@chefguevara RunJS is now available for ARM and ARM 64. Download links can be found here: https://runjs.app/#platforms
