### ISSUE TITLE
File too big clean history to prevent app crash

### ISSUE THREAD

**Issue by LucasVilela** [lukehaas/RunJS#194]
I load a really big object and the app and it crashed, now every time I re-open the app it loads the history and crashes again, is there a way to clean the history outside the app?

**Comment by lukehaas** [comment]
@LucasVilela yes, you'll need to delete the config.json file, it's location depends on your OS: 

Linux: ~/.config/runjs/config.json
Mac: ~/Library/Application\ Support/runjs/config.json
Windows: %APPDATA%

**Comment by LucasVilela** [comment]
Perfect that worked great! Thank you very much
