### ISSUE TITLE
screenshot homepage is wrong ?

### ISSUE THREAD

**Issue by GuillotJessica** [lukehaas/RunJS#195]
i wrote the screenshot code on the homepage to test your app and find issues:
first of all there is a bug in the code :
<img width="1023" alt="Screen Shot 2020-11-10 at 08 14 26" src="https://user-images.githubusercontent.com/21151517/98673083-3420d700-232d-11eb-9501-f5d8551bb524.png">
then if i fix that bug, it is still not the same 
<img width="1022" alt="Screen Shot 2020-11-10 at 08 14 16" src="https://user-images.githubusercontent.com/21151517/98673113-4569e380-232d-11eb-92a5-7c753c3211ea.png">
as your exemple 
<img width="900" alt="Screen Shot 2020-11-10 at 08 14 35" src="https://user-images.githubusercontent.com/21151517/98673148-50bd0f00-232d-11eb-9f3a-33cdd898be58.png">

**Comment by lukehaas** [comment]
Thanks @GuillotJessica, I've now updated it to show the correct code. To get the right output, `z += 1;` on line 4 needs to be changed to `z += 2;`

**Comment by lukehaas** [comment]
@GuillotJessica closing this now, hope that's all good.
