### ISSUE TITLE
Loops infinite loading 

### ISSUE THREAD

**Issue by z0xyz** [lukehaas/RunJS#198]
sometimes particularly with loops , the program doesn't output anything , and keep giving a loading icon on the top , 
and in order to solve this problem , i have to restart the program

**Comment by lukehaas** [comment]
Thanks @z0xyz, would you be able to provide some examples of code you're having issues with?

**Comment by z0xyz** [comment]
i can't tell exactly , but it happened multiple times ,  usually as i stated with  loops .

**Comment by lukehaas** [comment]
Sorry @z0xyz, without some specific examples I will need to close this issue.

If you do ever see the issue again please make a note of the problem code and I will be happy to investigate further.
