### ISSUE TITLE
[Feature Request] Add a "New" option to "File" menu

### ISSUE THREAD

**Issue by yonifra** [lukehaas/RunJS#199]
There's no intuitive way to start a new playground in RunJS (There's only **Open** or **Save**, I ask for **New**)
![image](https://user-images.githubusercontent.com/726718/99790192-7071e580-2b2c-11eb-822c-888973a3d075.png)

**Comment by lukehaas** [comment]
Thanks @yonifra, could you clarify what you would expect to happen when clicking New?

**Comment by yonifra** [comment]
Sure @lukehaas , I expect a blank document ready for my code and if I save it, then it will ask me for a filename (just like a regular text editor)

**Comment by lukehaas** [comment]
Ok, just to clarify, the blank document would be your current document cleared, not a new additional window?

**Comment by yonifra** [comment]
Yep, exactly.
Although it would be nice to have tabs, but at first I guess current window being cleared is great

**Comment by lukehaas** [comment]
Clicking New and having the editor clear your document is a little odd to me. Are you aware of any other editors that do this?
RunJS currently has a Clear option in the Edit menu that performs this function.

**Comment by yonifra** [comment]
It will clear but also will be a different file.
What happens today is that i will have an `empty.js` file that i open to start a new playground, and then if i wanna save it, i will do a **Save as..** and save it with a different name.
I want the **New** menu not only to clear the current code, but to also be a new file

**Comment by lukehaas** [comment]
Ok, I'll consider this further, thanks for raising it 👍

**Comment by lukehaas** [comment]
It's now possible to open a new tab from the file menu 🎉
