### ISSUE TITLE
Feature Request: increase text size

### ISSUE THREAD

**Issue by tonydewan** [lukehaas/runjs#20]
`⌘ -` works to decrease the text size, but I'd like to make it bigger. :)

**Comment by getify** [comment]
`⌘ SHIFT +` works, just not `⌘ +` (since that's actually `⌘ =`). See #15. Also, the text size is not really being increased or decreased as much as the view is being zoomed. My request is that the text size be changed and not actually zoom the view.

**Comment by tonydewan** [comment]
Duplicate of #15.
