### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by jeffthorne** [lukehaas/RunJS#200]
Quick question. Relatively new to JS. Getting this error on trying to import an ES6 module. .mjs
Tried setting --experimental-modules as an ENV variable within RunJS. Any thoughts I what I am doing wrong?

Appreciate the help. 

Cheers, 
Jeff

**Comment by lukehaas** [comment]
Sorry @jeffthorne, importing ES modules is not yet supported in RunJS. This may be possible in the future when RunJS ships with Node 15. Currently shipping with Node 12.16.3.

**Comment by jeffthorne** [comment]
Thanks @lukehaas. Appreciate the reply and great work on RunJS.
