### ISSUE TITLE
Don't prettify code automatically, allow a hotkey to do so

### ISSUE THREAD

**Issue by jcyl29** [lukehaas/RunJS#202]
This is a great tool to use.  If this feature can be added, it will be closer and closer to a real IDE imo.

**Comment by lukehaas** [comment]
Hi @jcyl29,
automatic formatting is a preference option, it's toggled off by default:

![Screenshot 2020-12-03 at 10 00 52](https://user-images.githubusercontent.com/741344/100994551-9cd72a00-354e-11eb-8176-4083fd5a2adb.png)


The hotkey for formatting is `Alt+Shift+F`

You can also trigger formatting from the action menu:
![Screenshot 2020-12-03 at 10 03 43](https://user-images.githubusercontent.com/741344/100994783-da3bb780-354e-11eb-9734-ccc01b23ce4c.png)

**Comment by jcyl29** [comment]
Ooof, textbook case of RTFM...thank you!
