### ISSUE TITLE
[Feature Request] - Internal OS fonts

### ISSUE THREAD

**Issue by ricosandyca** [lukehaas/RunJS#203]
I have some fonts installed on my Linux OS and i want to use it in RunJS. Is it possible to load installed fonts from OS?

Thanks,

**Comment by lukehaas** [comment]
@ricosandyca unfortunately not. This is something I'd very much like to be able to do but accessing user fonts it not trivial.

**Comment by ricosandyca** [comment]
I mean not accessing it all. it's just like vscode where i can manually type my preferred font and load it from my OS

![Screen Capture_select-area_20201206211059](https://user-images.githubusercontent.com/43330562/101282402-92938500-3807-11eb-8439-54e6c1a77558.png)

**Comment by lukehaas** [comment]
I see. That would certainly be easier technically, but would require a redesign of the way user preferences are handled.

**Comment by lukehaas** [comment]
@ricosandyca you should now be able to see installed fonts in the latest version - 2.3.1

**Comment by ricosandyca** [comment]
Woww, that's awesome. Thank you so much ❤️ 👍
