### ISSUE TITLE
Atom One Dark theme

### ISSUE THREAD

**Issue by joonseokhu** [lukehaas/RunJS#204]
Can you add [Atom One Dark Theme](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme) in theme list?

**Comment by lukehaas** [comment]
Thanks @joonseokhu, will consider this for future updates.

**Comment by KhushrajRathod** [comment]
I came here looking for this 👀

**Comment by davidfabianok** [comment]
please add this topic

**Comment by joonseokhu** [comment]
Any update yet?

**Comment by lukehaas** [comment]
@joonseokhu @khrj @davidfabianok One Dark is now included in the latest version of RunJS
