### ISSUE TITLE
[Bug] Clicking/dragging titlebar to move window takes focus from text editor

### ISSUE THREAD

**Issue by alexrussell** [lukehaas/RunJS#205]
I only have macOS so have only seen this behaviour there, so I'm not sure if it happens on other platforms, but it can be quite frustrating.

I don't know of any other app (electron or otherwise) that takes focus away from the active input/control when you click to drag a titlebar.

![RunJS](https://user-images.githubusercontent.com/412784/103046625-d2d16200-4580-11eb-82db-68877526b755.gif)

**Comment by lukehaas** [comment]
@alexrussell thanks for raising this. You're right, I'll look into getting this resolved.

**Comment by alexrussell** [comment]
Woohoo, nice one thanks ☺️

**Comment by lukehaas** [comment]
@alexrussell this is now resolved in the latest release.
