### ISSUE TITLE
Feature Request: update check for npm packages

### ISSUE THREAD

**Issue by alexdevero** [lukehaas/RunJS#207]
RunJS has the option to add npm. There is no way to check for package updates, and to update them. So far, the only way to do this is to check for updates elsewhere and then reinstall the package.

Option to check for updates, and for updating them, would make this much easier.

**Comment by lukehaas** [comment]
Thanks @alexdevero, good suggestion. I'll consider how this could be implemented.

**Comment by lukehaas** [comment]
The latest release adds the ability to update outdated packages:
![npm-packages](https://user-images.githubusercontent.com/741344/233046844-ad9bb359-5fb7-4635-8c50-c6fc6e0c1de2.png)
