### ISSUE TITLE
Math.ceil spelled wrong in lodash _.countBy method

### ISSUE THREAD

**Issue by virginiableu** [lukehaas/RunJS#208]
![image](https://user-images.githubusercontent.com/57457033/103823934-9d288080-5038-11eb-925b-da01c1207dcf.png)
<img width="805" alt="Screen Shot 2021-01-06 at 4 00 59 PM" src="https://user-images.githubusercontent.com/57457033/103823944-a1549e00-5038-11eb-93ca-45d65fe73361.png">

In my function:
`import _ from 'lodash';

let array = ["apples", "apples", "apples", "bananas","bananas"];

function countUniqChars() {
  let value = _.countBy(array, Math.ciel);
  console.log(value)
}

countUniqChars(array)`

"ciel" spelled incorrectly returns my desired output: { apples: 3, bananas: 2 }
but spelled correctly as "ceil" returns: { NaN: 5 }

**Comment by lukehaas** [comment]
@virginiableu 
`_.countBy(array, Math.ceil);` - should be used with an array of numbers, not strings as `Math.ceil` does not expect a string.

The reason you're seeing the expected output with the misspelled `Math.ciel` is due to the way lodash is safely handling the error.

**Comment by virginiableu** [comment]
ahhhh, I thought it might be user error but it was return what a wanted tho. Thank you
