### ISSUE TITLE
[Feature Request] Add support for ES Modules

### ISSUE THREAD

**Issue by SimplySayHi** [lukehaas/RunJS#209]
Hi, great work! I really like it :D
It would be great to also have the possibility to import native ES Modules.
I tried with my `javascript-helpers` and I got an error.
Thanks

**Comment by lukehaas** [comment]
Yep, this will come eventually, it's just dependent on upstream dependencies getting updated to support this.

**Comment by backspaces** [comment]
Would it be reasonable to base RunJS on Deno? Imports, TypeScript etc built in. It would certainly be non-trivial but as wonderful as node is, it has some pretty poor aspects.

Btw, one package that may be of interest for bash users is https://github.com/shelljs/shelljs. It does help to "tame" node!

**Comment by lukehaas** [comment]
@backspaces RunJS is Electron based which is where it gets its Node integration from. To move to Deno would require Electron to integrate Deno. There's a discussion here about that: https://github.com/electron/electron/issues/23613

**Comment by backspaces** [comment]
Fascinating, Thanks!

**Comment by josh-hemphill** [comment]
Another option would be to use Tauri instead of electron, though you wouldn't get TS support, and since all JS code technically just makes calls from a webview into the native layer, there might be some performance limitations.
Though if you wanted to go really deep into it, it does let you bundle binaries (e.g. Node.js and Deno) and invoke them from the webview.

**Comment by 5tormTrooper** [comment]
Any update on this?

**Comment by lukehaas** [comment]
@5tormTrooper some updates on this can be found here: https://github.com/electron/electron/issues/21457

**Comment by vladyn** [comment]
```ReferenceError: exports is not defined```
Is this relevant to the current issue?

**Comment by vladyn** [comment]
Oh, OK I see. Bu is it possible to have import and export across my scratch files?

**Comment by lukehaas** [comment]
@vladyn no, each tab is a sandboxed playground. 
You could use the 'Set Working Directory' feature to point RunJS to a directory and import files from there.

**Comment by vladyn** [comment]
I've set the directory and save the file. But why I'm getting this error the moment I write "export"?

**Comment by lukehaas** [comment]
@vladyn RunJS treats your code as a script, not a module so export is not supported.

**Comment by lukehaas** [comment]
ES modules are now supported. Just enable bundling via the preferences.
