### ISSUE TITLE
[Bug ] Npm list is empty. Search does not work

### ISSUE THREAD

**Issue by victoriaunizhona** [lukehaas/RunJS#210]
The list is empty

![image](https://user-images.githubusercontent.com/32535863/106312667-b3a8ad00-626f-11eb-813d-80561c8a5aab.png)

If I search for anything it is just constantly loading

![image](https://user-images.githubusercontent.com/32535863/106312736-cf13b800-626f-11eb-9bcf-49cc1803e0d4.png)

How to fix that?

**System**: Windows 10

**Comment by lukehaas** [comment]
Thanks @victoriaunizhona, I've not seen this issue before. If you go to %APPDATA%\runjs in your terminal are you able to manually install NPM packages there?

**Comment by victoriaunizhona** [comment]
> Thanks @victoriaunizhona, I've not seen this issue before. If you go to %APPDATA%\runjs in your terminal are you able to manually install NPM packages there?

Yes, if I go there and manually install than it appears in the list as installed.

Still, if I try searching in the Install Npm packages - loading spinner goes endlessly - nothing found and empty list.

If I try to remove manually installed package via that window - loading spinner is also just rolling. I need to restart that to see that package was removed.

**Comment by lukehaas** [comment]
Are you able to use the Windows Event Viewer to see if any errors are logged while searching/removing packages?

It can be found here: Control Panel > System & Security > Administrative tools > Event Viewer

**Comment by lukehaas** [comment]
@victoriaunizhona is it possible that a firewall is blocking RunJS from making requests to the NPM servers?

**Comment by marcfs31** [comment]
I have a similar issue, in my case it shows an error message when I try to search for a npm module.
![image](https://user-images.githubusercontent.com/33263750/112322628-5cdcb400-8cb1-11eb-828d-b5afa5e59a11.png)

**Comment by lukehaas** [comment]
@marcfs31 any possibility of an internet connection problem or being blocked by a firewall?

**Comment by lukehaas** [comment]
@victoriaunizhona @marcfs31 the latest version of RunJS - version 1.15.1 has some NPM improvements that may fix the issues you were seeing.

**Comment by lukehaas** [comment]
Closing, assuming it's fixed now.
