### ISSUE TITLE
Infinite loop will not stop executing even after updating code

### ISSUE THREAD

**Issue by peter-olom** [lukehaas/RunJS#211]
OS: Windows 10

Example

`let guard = 0;
while(guard < 100) {
    
    
}`

Will not stop running even after updating it as follows
`let guard = 0;
while(guard < 100) {
    
 guard++   
}`

Only way to regain normal operation is to relaunch the app.

A stop execution button will be nice.

**Comment by lukehaas** [comment]
👍  in the next version of RunJS it will be possible to stop execution.

**Comment by lukehaas** [comment]
@peter-olom stopping execution is now possible in the latest version of RunJS.
