### ISSUE TITLE
Shortcut for commenting code not working on AZERTY keyboard

### ISSUE THREAD

**Issue by topheman** [lukehaas/RunJS#212]
I saw this issue closed : https://github.com/lukehaas/RunJS/issues/182 about shortcut to commenting with `Cmd+/`.

I'm trying using `Cmd+/`, it doesn't work. Maybe it's because of azerty keyboards (since the problem seemed solved on the other issue).

Here is my config : 

- Mac OS Catalina 10.15.7
- RunJS 1.12.2

**Comment by lukehaas** [comment]
@topheman thanks for raising this, I will investigate.

**Comment by lukehaas** [comment]
@topheman are you still facing this issue in version 2.3.0?
