### ISSUE TITLE
There is no error if I don't declare the variable "name" and use it in the code.

### ISSUE THREAD

**Issue by b-dabrowski** [lukehaas/RunJS#213]
Hi, thank you for the tool I use RunJS daily :) 

Today I have found a little bug:

I don't have declared variable "name", but RunJs doesn't throw an error like (ReferenceError: name is not defined). When I change the variable to "name1" I see the error

```
console.log(name);
console.log(name1)
```

I only receive one error:
`ReferenceError: name1 is not defined`

**Comment by lukehaas** [comment]
Hi @b-dabrowski, this is because `name` is defined, it's a global object: 
https://developer.mozilla.org/en-US/docs/Web/API/Window/name

**Comment by b-dabrowski** [comment]
Sorry for bothering you

**Comment by lukehaas** [comment]
@b-dabrowski no worries 😀
