### ISSUE TITLE
Installed modules don't seem to respect "exports" field

### ISSUE THREAD

**Issue by getify** [lukehaas/RunJS#214]
I installed some of my own npm packages: [Monio](https://github.com/getify/monio) and [Domio](https://github.com/getify/domio).

But I'm not able to use them quite normally in RunJS sessions the way I can in a normal Node program. These packages have a `exports` package.json field , such as [this one in Monio](https://github.com/getify/monio/blob/018d4dcc14e7792d53424a157cbbe54c07676d37/package.json#L34-L85).

These exports allow something like:

```js
var IO = require("monio/io");
```

These exports use [Node's "conditional exports"](https://nodejs.org/api/packages.html#packages_conditional_exports) style. Thus, the `"./io"` (aka `"monio/io"`) export path is mapped in that field to either the  `./dist/esm/io.mjs` location if being `import`ed from an ES module, or the `./src/io.js` location if being `require(..)`d.

It seems I'm only able to use `require("monio")` -- the top-level package export -- in RunJS, not any of its export sub-paths.

I'm guessing it's because RunJS is doing its own parsing/loading of packages instead of just deferring to Node's built-in system. Can this be upgraded to support the conditional exports paths?

**Comment by lukehaas** [comment]
Hi @getify, I think this is due to RunJS currently being on Node version 12.16.3. This should work when RunJS moves to Node version 14 later in the year.

**Comment by getify** [comment]
Oh, OK... I didn't realize it wasn't already 14. Thanks!

----

Out of curiosity, what blockers remain for that upgrade? Anything contributors might be able to help with?

**Comment by lukehaas** [comment]
The Node version is inherited from Electron, Node 14 will come when Electron version 12 is released.

**Comment by lukehaas** [comment]
Closing as RunJS is now shipped with Node 14.
