### ISSUE TITLE
Feature Request: config option for HOME ~/ path

### ISSUE THREAD

**Issue by getify** [lukehaas/RunJS#216]
I use RunJS on windows 10. I launch it as a windows app. However, I have pretty much all my code inside a wsl2 instance (debian) on this box. I run a Windows Terminal in that environment, so that's where my Node runs from, and access to any files inside wsl2 is great just like a real linux.

My text editor is Sublime and I run that as a windows app as well. To open files, I navigate to the wsl file mount, which is: `\\wsl$\Debian\`. From there, it's just like opening files in my normal directories, so I never have to contend with that that wsl2 file boundary in paths (since every path reference is relative).

However, using RunJS in this sort of system setup is a bit more awkward because of needing to specify a long/complicated path every time. If I want to `require(..)` a file inside a RunJS snippet that happens to reside in this wsl2 environment:

<img width="695" alt="runjs+wsl" src="https://user-images.githubusercontent.com/150330/107151253-2e845e80-6927-11eb-85ec-718009b39dea.png">

I'm thankful that it works, but it would be great if I could have some way to set up a sort of "HOME" directory option on RunJS... to configure where a path like `~/` resolved to. It's sorta like changing the CWD but not really, because I know RunJS needs to keep running its normal CWD location to be able to resolve `require(..)` calls for packages that I've directly installed via RunJS.

So, what I'd like is:

```js
var { IO } = require("monio");  // works because "monio" is an installed package that RunJS knows about/manages

var whatever = require("~/whatever");  // works because I set a HOME or ~/ config option to point to "//wsl$/Debian/home/getify" -- it's cool that Node handles the "/" to "\" translation for me!!
```

Does that make sense? I don't know how possible/practical it is to do this... it might mean RunJS had to insert a [require hook](https://www.npmjs.com/package/require-hook) to override its normal path resolution.

Or maybe it's easier than that, where just setting some sort of *environment variable* like "HOME" for me would cause Node to resolve ~/ to where I want. I tried this in code but it doesn't work:

```js
process.env.HOME = "//wsl$/Debian/home/getify";
var x = require("~/whatever");
console.log(x);
```

**Comment by lukehaas** [comment]
Have you tried using the 'Set Working Directory' feature? It enables you to point RunJS to a particular directory and then import files relative to that location.
If I'm understanding this right then I think that might be what you need.

**Comment by getify** [comment]
I didn't know about that feature, because I was looking for it in the options pane, not in the "Action" menu.

Just tried setting that to a directory location in my wsl2 mount. I verified it's correctly set by doing `console.log(process.cwd())`, and that shows the full location as expected.

Maybe this is a Node weirdness with its `require(..)` path resolution, but when I tried `"./whatever.js"`, it didn't work, but when I tried just `"whatever.js"`, it did work. That's pretty confusing. Any idea why that might be?

**Comment by lukehaas** [comment]
Possibly Node weirdness. I'll have an investigate and try and improve it in the next release.

**Comment by getify** [comment]
From what I can tell, "./" in a require call is always relative to the current file, not the "current working directory". So I guess it's working "as designed", though in this case it's fairly counter-intuitive. Anyway, I think this feature is working correctly as far as it can be. Thanks!

**Comment by getify** [comment]
There's an interesting gotcha:

if the directory you set your "cwd" to has a folder/file in it that's also the same name as a RunJS-installed npm package, then doing `require("something")` will always resolve to the package and not to the version in your working directory.

Normally, you would be able to do `./something` to tell Node to skip to the "local working dir" version. But that doesn't work here because "./" is limited by Node to the same directory as the file being run, not the current working directory.

So I think the only fix here, which kinda sucks, is that I have to do:

```js
var something = require(path.join(process.cwd(),"something"));
```

That way, I'm able to force it to use the "working directory" version instead of the installed one.

The worst part here is that it's a sorta a silent footgun, because it only happens if you've used RunJS to "install" a package of the colliding name. Otherwise, `require("something")` will eventually resolve into your working directory.

That gotcha sorta argues for never installing packages via RunJS if you're planning to set your current working directory to anything other than the typical RunJS default. Probably a good thing to warn users about in some way, not sure how best though.

**Comment by lukehaas** [comment]
👍 This is useful, thanks. I'll see what I can do.
