### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by dkoudstaal** [lukehaas/RunJS#217]
This is not an issue. Just letting you know that RunJS is exactly what I was looking for. Tried coding large programs using the consoles in Chrome or Firefox and was frustrated that I could not reassign variable bindings.
Fantastic off-line JS console!!
Thank you.

**Comment by lukehaas** [comment]
Thanks @dkoudstaal, really glad you're finding RunJS useful.
Would you mind if I quoted on in the testimonials section of https://runjs.app/ ?

**Comment by dkoudstaal** [comment]
Hi,

Here is a bit more information:
> I am a procedural (FORTRAN) programmer new to JavaScript. I decided to learn a more modern language and using the excellent book Eloquent JavaScript by Marijn Haverbeke <https://eloquentjavascript.net/>. Living in a remote area with unreliable internet access, I could not use the web based console for the book. I found the off-line browser consoles impossible to use as those console do not allow reassignments of variable bindings and re-running the code (which a learner has to do often) became impossible. RunJS is the ideal tool for me to do all the examples and exercises in an hassle free online console.

You are free to edit the above and combine this with my statement on github in which ever way you want. 
I am not so sure about the use of my full name. Use of first name is OK.
 
In my view open source developers do not get enough credit and at times the reverse is happening where people are very abusive towards developer(s) and their software.

Again, thank you very much for freely sharing your programming and software design skills.

Kind regards,
-- 
  Dirk Koudstaal
  dkgithub@fastmail.com

**Comment by dkoudstaal** [comment]
More than happy. I sent more information you might want to use to mail@runjs.app

**Comment by lukehaas** [comment]
Thanks
