### ISSUE TITLE
name is printed as '' and typeof name is printed as 'string

### ISSUE THREAD

**Issue by shashidwivedi** [lukehaas/RunJS#218]
name is not created. But it has a value '' and a type of 'string'
![Screenshot (30)](https://user-images.githubusercontent.com/16834982/107499623-2f352300-6bbb-11eb-841c-c491a46410ee.png)

**Comment by lukehaas** [comment]
@shashidwivedi this is because name is defined, it's a global object:
https://developer.mozilla.org/en-US/docs/Web/API/Window/name

**Comment by shashidwivedi** [comment]
Thank you. I am learning. I should have read more. :)

**Comment by shashidwivedi** [comment]
Not a valid issue

**Comment by lukehaas** [comment]
No problem 🙂
