### ISSUE TITLE
[windows] Taskbar pin disapears on update

### ISSUE THREAD

**Issue by oguimbal** [lukehaas/RunJS#219]
Hi !

I have pinned RunJS to my Windows taskbar, and I noticed that the pin disapears on each RunJS update.

I'm not sure if something can be done about it on your side, so please close this issue if not.

And thanks for this nice tool 😁

FYI i've developped something in the same spirit [for postgres](https://oguimbal.github.io/pg-mem-playground/)  (not embbeded in an app though, and the main purpose is to have the parser, not the UI, so it's kind of simpler !).

**Comment by lukehaas** [comment]
@oguimbal thanks for raising this, I'll look into it. Your postgres playground looks great!

**Comment by DerGoogler** [comment]
This is also the case with the Electron app I created myself. I using Electon Builder :smile:

**Comment by lukehaas** [comment]
@oguimbal are you still seeing this issue?
