### ISSUE TITLE
Feature request: auto-format using Prettier

### ISSUE THREAD

**Issue by will-stone** [lukehaas/RunJS#22]
Hi! Thanks for making this. It looks like a fun project. Loving that you can now install npm packages. I usually go to jsbin to run small JS tests but I can foresee RunJS being my go-to tool from now on.

Would it be possible to add Prettier formatting? I'm crap at formatting code now and rely on it heavily. I'm thinking: `alt-shift-f` to format and have format on run (optional?). Also, is there any particular reason why the source code isn't in a branch?

**Comment by lukehaas** [comment]
Good idea.
I'll likely also to expose the Prettier config in the preferences.

**Comment by JaKXz** [comment]
I am a huge fan of this app, and would love to contribute this, but then I noticed the source code isn't here :(

**Comment by lukehaas** [comment]
Prettier formatting is now supported in RunJS version 1.10.0 @will-stone 

![Screenshot 2020-07-17 at 17 26 31](https://user-images.githubusercontent.com/741344/87809115-bc491100-c852-11ea-8577-5c628b034023.png)

**Comment by will-stone** [comment]
Awesome! Works great. Thank you very much.
