### ISSUE TITLE
[Windows] New Tab option in File menu is not shown

### ISSUE THREAD

**Issue by shashidwivedi** [lukehaas/RunJS#220]
The New Tab is not shown in the File menu after opening the app second time.

![image](https://user-images.githubusercontent.com/16834982/107759918-fe85f280-6d4e-11eb-9b2c-713f820f386d.png)

**Comment by lukehaas** [comment]
I can't see how the new tab option would ever have been visible. This feature in development.

**Comment by shashidwivedi** [comment]
It's only visible for the first time after installation:

![image](https://user-images.githubusercontent.com/16834982/107764666-99ce9600-6d56-11eb-8fda-7ea985ca76e2.png)

Not a problem if in development.

**Comment by lukehaas** [comment]
Thanks, this is good to know.
