### ISSUE TITLE
var name = ....; typeof name = 'string'

### ISSUE THREAD

**Issue by gruber123** [lukehaas/RunJS#221]
Hi,
This code shows wrong expectation:
var name = some_value; 
typeof name
// typeof name simply return 'string' and not the type of name variable

if change name to 'namex' all is fine.
so what's wrong with variable 'name', it's not reserved word so actually the value that it consist is printed correctly in console

**Comment by lukehaas** [comment]
@gruber123 this is because `name` is a global object:
https://developer.mozilla.org/en-US/docs/Web/API/Window/name
