### ISSUE TITLE
Universal macOS Binary or Apple Silicon version

### ISSUE THREAD

**Issue by m-ivanov** [lukehaas/RunJS#222]
It would be great if you could release a native M1 version of RunJs

**Comment by lukehaas** [comment]
👍 this will be coming in the next release.

**Comment by keverw** [comment]
Noticed in your release notes you added Apple M1 support. However get info still says "Application (Intel)". So wonder if something went wrong?

I know last I heard the Electron people so far was only supporting a separate binary since would be bloated to do a universal one I guess. So I figured maybe since it's running under Rosetta or a cache issue, redownloading from your website and that reports as Intel too. 

Either way, it works for me either way. Was just kinda curious if any of the Electron apps I have are even using ARM yet, wonder if they use less memory maybe.

**Comment by m-ivanov** [comment]
Electron encourage to recompile saying  there is a big speed advantage because on rosetta is translated twice. One keypoint of making it all native m1 can be node version as that as far i know only the v15 version run natively.

**Comment by lukehaas** [comment]
@keverw @m-ivanov apologies, yes, I've realised I made a mistake on this. I assumed it would be a universal binary. I don't have an M1 mac myself so didn't look too closely.

**Comment by hroland** [comment]
@lukehaas Can a recompile be expected any time soon? :)

**Comment by midudev** [comment]
Bumping this... :)

**Comment by lukehaas** [comment]
@hroland I'm aiming to include an arm build in the next release but can't make any promises.

**Comment by midudev** [comment]
@lukehaas what can I do to help you? I see you don't have GitHub Sponsors but I would be more than happy to pay you 50$ in order to sponsor this feature. :)

**Comment by lukehaas** [comment]
Thanks @midudev, that's generous but not necessary. No effort is needed on my side for this as it's just dependant on electron-builder. I'm just uncertain if it can produce a working build as I won't be able to verify it.

**Comment by m-ivanov** [comment]
i think all of us will be happy to help you test out if it worked, you can share with us a build and i think any of us will be glade to test

**Comment by lukehaas** [comment]
I've now tried out RunJS on an M1 mac and it's all working nicely. 🎉

![Screenshot 2021-05-17 at 21 53 27](https://user-images.githubusercontent.com/741344/118555448-9e8e5600-b75a-11eb-97a7-e38aa48461ef.png)

**Comment by aosabrooktec** [comment]
That's great! Any ETA? 🥰😇

**Comment by lukehaas** [comment]
@aosabrooktec aiming for the middle of June.

**Comment by aosabrooktec** [comment]
Tried the latest version you uploaded and it is working great on M1, now runs natively.

Thanks! 🚀

**Comment by m-ivanov** [comment]
i confirm that https://github.com/lukehaas/RunJS/releases/download/v2.0.0/RunJS-2.0.0-arm64.dmg is running as Apple silicon
