### ISSUE TITLE
Settings won't open

### ISSUE THREAD

**Issue by chefnoname** [lukehaas/RunJS#223]
I've uninstalled and reinstalled a couple of times

everything in the drop-down menu works except when I try to open Settings. I've checked for updates but I am using the latest version for windows 1.13.1.0

thanks

**Comment by lukehaas** [comment]
Thanks @chefnoname, I'm not able to see this issue on Windows myself. is there anything about your Windows setup that might be non-standard?
Also, if you downgrade to a previous version of RunJS, such as: https://github.com/lukehaas/RunJS/releases/download/v1.12.2/RunJS-Setup-1.12.2.exe
Do you still see the issue there?

**Comment by chefnoname** [comment]
Hi, I've downloaded the older version and re-upgraded back to the latest and it seems everything is working fine!

thanks for a great app!
