### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by pusharr** [lukehaas/RunJS#226]
cannot import axios

**Comment by lukehaas** [comment]
To use import statements you will need to have Babel transpilation enabled. You can do this from the preferences window.

If you want to keep Babel disabled then you will need to use a require statement instead of import.

**Comment by lukehaas** [comment]
![2021-03-01 10 56 54](https://user-images.githubusercontent.com/741344/109488098-034fe380-7a7d-11eb-9319-df8c4515e043.gif)
