### ISSUE TITLE
Set output console to bottom of screen

### ISSUE THREAD

**Issue by VektorTech** [lukehaas/RunJS#230]
The ability to switch the layout between column and row view would be very useful.

**Row:**
```
--------------------
                   
     CODE EDITOR               
                            
--------------------
                            
     OUTPUT      
                            
-------------------- 
```

Can this feature be implemented?

**Comment by lukehaas** [comment]
@VektorTech yes, aiming to have this as an option in the near future.

**Comment by VektorTech** [comment]
Any progress on this yet @lukehaas ?

**Comment by lukehaas** [comment]
Still on track. Hoping to have this released within the next couple of months.

**Comment by lukehaas** [comment]
@VektorTech this is now supported in the latest version of RunJS
