### ISSUE TITLE
Hoisting doesn't work properly

### ISSUE THREAD

**Issue by yuri-semenenko** [lukehaas/RunJS#231]
Try to execute code in any modern browser and in RunJS...
`func(); //?

var func;

function func() {
  console.log(1);
}

func = function() {
  console.log(2);
} `

**Comment by lukehaas** [comment]
@yuri-semenenko thanks for raising this. This issue seems to be related to the 'Runtime values' option in the advanced settings/preferences. I'd suggest turning this option off till a fix is released.

**Comment by lukehaas** [comment]
@yuri-semenenko this is now resolved in the latest version of RunJS - 1.15.1
