### ISSUE TITLE
App freezes with too big of an object

### ISSUE THREAD

**Issue by Whymess** [lukehaas/RunJS#232]
How do force a hard reset?  tried reinstalling the app. Old data still shows up. Copy and paste is either too big or there is syntax errors. In either case, Infinite loop remains. I

![image](https://user-images.githubusercontent.com/9116787/111079831-2f825000-84d2-11eb-8d15-3378856181e7.png)

**Comment by lukehaas** [comment]
There are tow options here, if you go to the `Action` menu, there should be an option labeled `Stop` - try clicking that.

Other option is if you go to the `Edit` menu there should be an option labeled `Clear` - clicking this will remove the code.

**Comment by Whymess** [comment]
Both don't work. The spinner keeps spinning....
