### ISSUE TITLE
Accessing promise return value should return Promise object

### ISSUE THREAD

**Issue by selrond** [lukehaas/RunJS#233]
consider this code:

```js
'use strict';

const prom = new Promise((resolve, reject) => resolve(1));

prom; // 1 - should be Promise
```

`prom` value should be a promise object, like everywhere else:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/6603389/111609636-cb65d180-87da-11eb-8436-1838b9cd9db3.png">

Is that intentional? It's really confusing when using RunJS as a teaching REPL

**Comment by lukehaas** [comment]
It was originally the case that a promise object would be returned in this scenario but by popular demand it was changed so that resolved promises return the resolved value.

**Comment by lukehaas** [comment]
It could be possible to make this behaviour option based - controlled from the preferences, if that's something you think would be useful?

**Comment by selrond** [comment]
@lukehaas 
this is similar to https://github.com/lukehaas/RunJS/issues/225#issuecomment-785944089 in a way that it deviates from standard way JS runtimes work. 

I don't know what's the goal for this project, but it would appear to me it should not abstract away standard behavior - I don't see where it would be useful.
RunJS is not a compiler for a custom language (one that would return promise value right away for instance), but a "JavaScript playground" as written in README.

And "JavaScript" returns a Promise object.

**Comment by lukehaas** [comment]
👍  yeah, I'll look into this.
The problem previously was also linked to RunJS not showing the prototype (which it now does) - so all people saw before was `Promise { <pending> }`

**Comment by selrond** [comment]
Hey @lukehaas, I've just noticed the Promise display behavior has been improved in `1.15.1`, thanks for that!

Have you considered adding something like Promise `<state>` and `<value>`? 

So instead of the current output of my code example in the original comment

```
Promise { 1 }
```

it would be

```
Promise { <state>: "fulfilled", <value>: 1 }
```
?

**Comment by lukehaas** [comment]
@selrond yes, and thanks again for raising this.

The way promises are displayed now matches how the Node REPL outputs them. A state is provided for all apart from the fulfilled state, for example, if a promise is rejected:
```
Promise { <rejected> 1 }
```

This way the fulfilled is more like a default or implied state.

**Comment by selrond** [comment]
@lukehaas thanks for the clarification, wasn't aware of the way Node REPL prints it!

**Comment by selrond** [comment]
@lukehaas I consider this issue solved now. 
Thanks for being receptive!
