### ISSUE TITLE
Dupplicate selection with keyboard shortcuts

### ISSUE THREAD

**Issue by cssrno** [lukehaas/RunJS#234]
Dupplicate the current selection with <kbd>⌥</kbd>+<kbd>⇧</kbd>+<kbd>↑</kbd> and <kbd>⌥</kbd>+<kbd>⇧</kbd>+<kbd>↓</kbd> like on VS Code.

thanks :)

**Comment by lukehaas** [comment]
@cssrno RunJS uses Sublime text key bindings, so duplicating a line is done via ⌘+⇧+D.

**Comment by lukehaas** [comment]
@cssrno I've now improved the documentation for shortcuts and a complete list can be found here: https://runjs.app/docs#shortcuts

**Comment by cssrno** [comment]
Oh great!! btw I wanted to say the esthetic of the app is awesome + One Dark, i'm using it every day at work and at home!

**Comment by lukehaas** [comment]
@cssrno Thanks! That's really great to hear.
