### ISSUE TITLE
macOS: "RunJS" is damaged and can't be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by chriscalo** [lukehaas/RunJS#238]
# Steps:
1. Go to https://runjs.app/
2. Click **Download RunJS**
3. Open `.dmg`
4. Drag to `/Applications`

# Expected

The installation works without an error message.

# Actual

I get the following message every time:

![image](https://user-images.githubusercontent.com/867717/114307217-b19f6d80-9aac-11eb-9772-5fb022f7eb82.png)

**Comment by lukehaas** [comment]
Thanks @chriscalo, unfortunately I'm not able to see this issue. What version of macOS are you on?

**Comment by lukehaas** [comment]
From what I've just found, there are a few solutions to try:

 - Re-downloading the app
 - Rebooting the Mac
 - Installing system software updates, 
 - Install via the command line

**Comment by chriscalo** [comment]
It appears the restart solved the issue for me 👍

I had previous re-downloaded several times, and I had no software updates to install.

Thanks!
