### ISSUE TITLE
Feature Request: option for only-last-statement evaluation

### ISSUE THREAD

**Issue by getify** [lukehaas/runjs#24]
I would like an option to switch on a mode like how browser devtools consoles only evaluate the last statement in a snippet, because sometimes you have a bunch of statements in a snippet of code that you don't want to evaluate, but only want to evaluate the last statement.

Consider the differences between these two:

<img width="497" alt="screen shot 2019-01-08 at 10 38 15 am" src="https://user-images.githubusercontent.com/150330/50845073-adb29d00-1331-11e9-88f2-77938e4543fd.png">

<img width="209" alt="screen shot 2019-01-08 at 10 38 44 am" src="https://user-images.githubusercontent.com/150330/50845077-b0ad8d80-1331-11e9-964e-f8ad5eb922ca.png">

In RunJS, it outputs the result of the `x = foo()` statement (which is just another function), and then also evaluates both `x()` calls. In the Chrome console, it only evaluates the last `x()` call.

Sometimes, I want the behavior of the former, sometimes I want the behavior of the latter. It would be really nice to have an option to toggle between both modes.

**Comment by lukehaas** [comment]
Makes sense.
I'll create an option for line-by-line evaluation, defaulting to true.

**Comment by lukehaas** [comment]
This is now available in version 1.3.0, under a preference option called 'Holistic Evaluation'

![screenshot 2019-02-17 at 16 14 01](https://user-images.githubusercontent.com/741344/52915700-1f85eb00-32cf-11e9-8a18-97a5399ae432.png)
