### ISSUE TITLE
Cursor gets stuck for a while after resizing the output panel

### ISSUE THREAD

**Issue by ssmkhrj** [lukehaas/RunJS#241]
The image below shows my initial window structure.

![RunJs-1](https://user-images.githubusercontent.com/49264891/115671459-29e91700-a368-11eb-9cec-0b5d326362b1.png)

Suppose I expand the output panel (which shrinks the code panel), the cursor does not change its position and it gets stuck as shown in the image below. Now, for few minutes it will not move to the desired location as I click, it will weirdly reposition itself.

![RunJs-2](https://user-images.githubusercontent.com/49264891/115671484-2e153480-a368-11eb-8794-4f50e7f77157.png)

> I am on a Windows 10 machine

**Comment by lukehaas** [comment]
Thanks for raising this. Will investigate 👍

**Comment by lukehaas** [comment]
@ssmkhrj are you still seeing this issue?

**Comment by ssmkhrj** [comment]
@lukehaas Hmm, I haven't noticed that in a while, so probably it's fixed now! 

But there's another issue that I constantly face and i.e. when there's an update the app gets broken (windows can't locate the app) and I've to download it again from the website to get it working. Is this a known issue?

**Comment by ssmkhrj** [comment]
I quit but then when I try to open it back I don't find the app anymore.

**Comment by lukehaas** [comment]
It needs some time to install after quitting, if it's re-opened while this is happening then that can cause problems. It's an upstream issue with electron-builder.

**Comment by ssmkhrj** [comment]
I think this happens even if I open the app after significant amount of time. I usually don't quit and open again just for the update to take effect. My usual workflow is: If I'm working on the app and I see an update, I don't quit and open again, I continue with whatever I'm doing and then close the app for the day and when I open it the next time (usually the next day) I don't find it.

**Comment by lukehaas** [comment]
Ok, that is unusual then. I've not encountered that issue myself or had any report of that before.

**Comment by ssmkhrj** [comment]
The next time there's a update, I'll observe this more carefully and open an issue.
