### ISSUE TITLE
SyntaxError: Unexpected end of input - String literal interpolation on certain strings 

### ISSUE THREAD

**Issue by Uzwername** [lukehaas/RunJS#242]
Somewhy this code (which seems to be valid), produces an error:

<img width="1368" alt="run" src="https://user-images.githubusercontent.com/21230845/115991988-8ac45980-a5cb-11eb-8bf0-59b8ef69be9e.png">

The same code works in the latest version of Chrome & Firefox.

Version: 1.15.1

**Comment by lukehaas** [comment]
Thanks for raising this, I will investigate.

It looks like this is related to the runtime values option, so I'd recommend disabling it for now.

**Comment by Uzwername** [comment]
I've just tried & disabling this option fixes the issue, so thanks for a tip 👍

**Comment by lukehaas** [comment]
This is now resolved in the latest version of RunJS

![Screenshot 2021-06-29 at 14 32 00](https://user-images.githubusercontent.com/741344/123806390-cdb1ee80-d8e6-11eb-8a6e-805d541e45d1.png)
