### ISSUE TITLE
[Feature Request] allow using the shortcut Ctrl/Cmd+Enter to invoke the "Run" command

### ISSUE THREAD

**Issue by scoobers** [lukehaas/RunJS#245]
Currently, RunJS uses Ctrl/Cmd+R as the shortcut for "Run." It would be good to allow an alternate shortcut to invoke Run: **Ctrl/Cmd+Enter**.

Reasons:
- This alternate key combo is slightly easier to hit.
- It's the standard key combo for running code in lots of other apps, including browser-based ones.
- In browser-based apps, Ctrl+R refreshes the browser. It's annoying committing Ctrl+R to muscle memory in RunJS, and then accidentally using it in a browser app to run code, which instead reloads the page. Oops.

**Comment by lukehaas** [comment]
Thanks, @scoobers. Happy to give this some consideration.
Out of curiosity, could you name some of the code running apps where Ctrl/Cmd+Enter is the shortcut for running code?

**Comment by scoobers** [comment]
My mistake, looks like it's mostly the web-based code editors that do it (Replit, JSFiddle, the editors at CodeCademy and FreeCodeCamp, etc). I could've sworn I'd seen other desktop code editors do it, but from Googling around, it's not as common, or it's used to run only chunks / single lines of code, in desktop editors like RStudio, Spyder, Matlab.

Still, it'd be really nice to have the option, thanks for considering it. I love RunJS.

**Comment by lukehaas** [comment]
Happy to add it as an additional shortcut. Will be in the next release.

**Comment by lukehaas** [comment]
The Ctrl/Cmd+Enter shortcut is now supported in the latest release. @scoobers
