### ISSUE TITLE
Create new logo for macOS 11

### ISSUE THREAD

**Issue by JB1905** [lukehaas/RunJS#248]
Add a new logo that matches the style of macOS Big Sur

![Zrzut ekranu 2021-05-1 o 22 02 33](https://user-images.githubusercontent.com/28870390/116793769-1016a500-aac9-11eb-8d46-64ba5dbda2e7.png)

**Comment by dnicolson** [comment]
There is one available here:
https://macosicons.com/runjs

**Comment by chrisjaber** [comment]
Version 2.0 has the updated icon.
