### ISSUE TITLE
Inconsistent output of Regex

### ISSUE THREAD

**Issue by oculus42** [lukehaas/RunJS#249]
Very minor, but output of regex assignments alternate in appearance.

```javascript
foo = /foo/;
foo = /foo/;
foo = /foo/;
foo = /foo/;
```

<img width="401" alt="regex-alternate" src="https://user-images.githubusercontent.com/1731657/117022131-faba9a00-acc5-11eb-96d2-ca221436ba23.png">

A regex following another non-regex value always has the second appearance:
<img width="405" alt="regex-alternate-interrupted" src="https://user-images.githubusercontent.com/1731657/117023215-e4610e00-acc6-11eb-847d-497d31c11d51.png">

And following a regex with flags always has the second appearance:
<img width="505" alt="regex-with-flags" src="https://user-images.githubusercontent.com/1731657/117024053-a6181e80-acc7-11eb-94f5-d07bb0c657b2.png">

**Comment by lukehaas** [comment]
@oculus42 thanks for raising this, I'll look into it 👍

**Comment by lukehaas** [comment]
This is now resolved in the latest version of RunJS

![Screenshot 2021-06-29 at 14 30 16](https://user-images.githubusercontent.com/741344/123806145-92172480-d8e6-11eb-88a9-bf9704c52144.png)

**Comment by oculus42** [comment]
Checked with 2.0.1 because I saw it in the release notes.
Looks like the majority of the formatting issues are resolved, but the formatting issues return when following a number output:

<img width="461" alt="runjs-201-regex-working" src="https://user-images.githubusercontent.com/1731657/123669970-b0a7ed80-d80a-11eb-9f1b-6a40dd12845e.png">
<img width="462" alt="runjs-201-regex-issue" src="https://user-images.githubusercontent.com/1731657/123669973-b1408400-d80a-11eb-8b65-f97d2c31b92a.png">

**Comment by lukehaas** [comment]
Thanks. Will take another look.

**Comment by lukehaas** [comment]
@oculus42 This should now be fixed in the latest version of RunJS:![Screenshot 2021-07-29 at 10 51 54](https://user-images.githubusercontent.com/741344/127471487-2ae0892c-fe66-4c41-994c-5acd2bd8041a.png)
