### ISSUE TITLE
Allow shift-return when auto-evaluate is disabled

### ISSUE THREAD

**Issue by ohepworthbell** [lukehaas/runjs#25]
Hi,

Love the app - simple and beautiful!

One little feature request I think could be useful is allowing keyboard shortcuts for 'run' (especially when auto-evaluate is disabled). Perhaps have `shift`+`return` as a shortcut, so you don't manually have to click the button repeatedly, breaking up the flow of typing?

**Comment by lukehaas** [comment]
There's already a keyboard shortcut for this, it's ⌘R

**Comment by ohepworthbell** [comment]
Excellent, thanks for the info!
