### ISSUE TITLE
wrong log order

### ISSUE THREAD

**Issue by kmbenjel** [lukehaas/RunJS#251]
Hi everyone!
This code is supposed to log the results in this order 'c123a123t123', while the log order with RunJS is different!

Photo: https://ibb.co/T4CFH0s

**Comment by lukehaas** [comment]
This is because you have the 'Match Lines' option turned on.

![Screenshot 2021-06-14 at 09 11 53](https://user-images.githubusercontent.com/741344/121860461-c7215580-ccf0-11eb-8596-c58b8bf14c57.png)

**Comment by kmbenjel** [comment]
What does it mean please?

في الاثنين، 14 يونيو، 2021 09:13 Luke Haas ***@***.***> كتب:

**Comment by lukehaas** [comment]
When 'Match Lines' is enabled, the output will be placed on the same line as the input regardless of execution order.

![2021-06-14 10 24 35](https://user-images.githubusercontent.com/741344/121870358-df966d80-ccfa-11eb-8f26-4beb77526a21.gif)

**Comment by kmbenjel** [comment]
Ah, thank you very much Luke!

في الاثنين، 14 يونيو، 2021 10:26 Luke Haas ***@***.***> كتب:
