### ISSUE TITLE
App running a large script can't be stopped or cleared

### ISSUE THREAD

**Issue by MajorTom327** [lukehaas/RunJS#252]
Hi,
I'ved paste a very large file in the app, and I can't stop the app or clean up to start something else.
The app is not a loop so the protection agains long loop not working. It's a sort of a large dataset.

Maybe the app should be able to be launch from terminal with an argument for loading a file could ba good solution to recover in my case.

Or having a way to start a clean new app.

In my case,
OS: MacOs 11.4 (MacBook Pro 2019)

**Comment by MajorTom327** [comment]
I found a solution, but it's not optimal.
```bash
rm -rf ~/Library/Application Support/runjs
```

**Comment by lukehaas** [comment]
Apologies, @MajorTom327, this is certainly something that needs improvement.
Currently, the best way to deal with this is to use the 'Clear' option in the edit menu and then restart the app. This works because the menus are in a different thread to the UI. But I realise this is not intuitive.

**Comment by MajorTom327** [comment]
Nice !
I didn't realize there is a clear option.
I only tried to stop the running from the action menu (which do nothing in my case)
Sure i will try your option if any case happen again to me !
Thanks !
