### ISSUE TITLE
this js script cannot get return

### ISSUE THREAD

**Issue by bukuxiaoheshang** [lukehaas/RunJS#253]
`var b64map = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";  
var b64pad = '=';
function hex2b64(a) {
        var b, c, d = "";
        for (b = 0; b + 3 <= a.length; b += 3)
            c = parseInt(a.substring(b, b + 3), 16),
            d += b64map.charAt(c >> 6) + b64map.charAt(63 & c);
        for (b + 1 == a.length ? (c = parseInt(a.substring(b, b + 1), 16),
        d += b64map.charAt(c << 2)) : b + 2 == a.length && (c = parseInt(a.substring(b, b + 2), 16),
        d += b64map.charAt(c >> 2) + b64map.charAt((3 & c) << 4)); (3 & d.length) > 0; )
            d += b64pad;
        return d
    }

hex2b64("bb6cd43a75483b7ce01a4dc542cba535b856650ba9b69ec27623e843497c60e02d1c8aec0663c8e980659419d7165a23a990ee5617519d72ec4ccc5f880cc8242bbb59cb35001cbe8e547b93717118b031240e71316251e944187caebb74127787bc708c66a6c8597a2d7c6bf13ac2843ec6662afbb1730ffdcc757a8a641313")`

**Comment by lukehaas** [comment]
@bukuxiaoheshang it returns for me without issues. What version of RunJS are you on?

**Comment by lukehaas** [comment]
Closing due to lack of response.
