### ISSUE TITLE
plus plus counter doesn't work

### ISSUE THREAD

**Issue by donnydarko** [lukehaas/RunJS#254]
var a = 1;

a++;
console.warn(a)

returns 1

**Comment by lukehaas** [comment]
RunJS doesn't currently support `console.warn`. The 1 you're seeing returned is from the `a++` line.

**Comment by donnydarko** [comment]
ok thanks, it's not such a big deal

**Comment by lukehaas** [comment]
Just to clarify further, when you use the ++  increment operator after the variable like that, the value increments and returns the value before incrementing. 
If you wanted the value to increment and return the new value then you would need to place the increment operator before the variable like this: `++a;`
