### ISSUE TITLE
RunJS execution doesn't show application's window

### ISSUE THREAD

**Issue by donnydarko** [lukehaas/RunJS#255]
I'm really about to buy a license because it is very useful, but I have a serious issue.

After I run the application a few times then I close it and run it back again it stopped appearing on the screen. It only appears in task manager with 4 RunJS processes. 

2 of them are taking 12% and 15% cpu consistently. I always kill all processes and trying to run again but it happens the same over and over.

Is this behaviour familiar to anyone else?

**Comment by donnydarko** [comment]
Windows 10 Pro 64 bit
version 20H2
Windows Feature Experience Pack 120.2212.2020.0

**Comment by donnydarko** [comment]
The problem persists after reboot, uninstall, reinstall and also after uninstall, deleting %appdata%\Roaming\runjs folder and reinstall

**Comment by lukehaas** [comment]
Thanks for raising this. I've not seen this issue but will investigate.

**Comment by lukehaas** [comment]
Closing this as I'm not able to recreate the issue.
