### ISSUE TITLE
Collapsed code regions always expand on format

### ISSUE THREAD

**Issue by rBortnikas** [lukehaas/RunJS#256]
Collapsed code regions always expand on code format. This is especially annoying when auto format is enabled.

**Comment by lukehaas** [comment]
Thanks for raising this, I'll try and get this resolved for the next release.

**Comment by lukehaas** [comment]
@rBortnikas this should now be resolved with the latest version of RunJS

**Comment by rBortnikas** [comment]
Thanks!
