### ISSUE TITLE
UI issues on Mac & Windows

### ISSUE THREAD

**Issue by tschanz-pcv** [lukehaas/RunJS#258]
On mac some of the windows (e.g. the npm manager or ENV variable window) seem to have titlebars that are too narrow.

On windows there are windows like the Settings > Transpilation that does not expand with the content so you content gets cut off.

**Comment by lukehaas** [comment]
Regarding the narrow title bars, I'm not seeing what you mean, could you provide a screenshot?

The height issue with the settings on Windows will be resolved in the next release 👍

**Comment by tschanz-pcv** [comment]
@lukehaas Yes, sorry for the delay, here you can see a selection of windows & their titlebars on my macOS 11.4:
<img width="2142" alt="Screenshot 2021-06-29 at 13 59 08" src="https://user-images.githubusercontent.com/67736248/123793789-698d2b80-d8e2-11eb-989f-bee9003ac58b.png">

As you can see the "About" window has a normal sized titlebar, while the "Manage Packages" & "Env Variables" Windows have titlebars that are cut off. The "Settings" look fine but while I'm at it, it looks like the tabs are a bit close to the titlebar.

**Comment by lukehaas** [comment]
I see now. Looks like it's macOS 11 related. I'll aim to get it fixed in the next release. Thanks.

**Comment by lukehaas** [comment]
@tschanz-pcv this should now be fixed in the latest version of RunJS

**Comment by tschanz-pcv** [comment]
@lukehaas Thanks, looks better on my mac. 

I'm not sure how detail oriented you are but the buttons are not centered in the titlebar though (and the About window has a different titlebar height than all other windows).

<img width="184" alt="Screenshot 2021-07-30 at 09 06 36" src="https://user-images.githubusercontent.com/67736248/127614948-562cf99e-f426-44c2-a725-53c5232ef45c.png">

**Comment by lukehaas** [comment]
@tschanz-pcv I'll be able to adjust this more easily when I update my development machine to Big Sur. For now, that's the best it's going to get on that OS.
