### ISSUE TITLE
Import syntax always highlights package name in red

### ISSUE THREAD

**Issue by tschanz-pcv** [lukehaas/RunJS#259]
Installing e.g. `lodash` from the npm manager view and then importing `import _ from 'lodash';` will always put a red squiggly line below the `'lodash'` part of the import but it runs just fine.

**Comment by lukehaas** [comment]
To resolve this you just need to install the types package for lodash: `@types/lodash`

**Comment by tschanz-pcv** [comment]
Great, thanks, works! Would be nice to get some clearer warning/error outputs for situations like these, in the future.
