### ISSUE TITLE
JS Only Mode and/or Linter Settings

### ISSUE THREAD

**Issue by tschanz-pcv** [lukehaas/RunJS#260]
The type checking from the last version also brought many linting errors with it. e.g. "X is declared but it's value is never read" and similar errors. They don't prevent the script from running but as I use the tool mainly to play around and figure things out, it's a bit distracting to have these issues highlighted.

It would be great if there was a way to tweak these warnings/errors so one could relax them if desired. I'm not 100% sure which of the errors are directly from tsc and which ones from eslint/tslint (if you even include such a tool) so I'm not sure what can be done here.

A related request would be to allow for a `JS Only` mode that does not allow any TS and would not touch the TS pipeline, so the linting could be even more relaxed there.

**Comment by lukehaas** [comment]
Thanks for the feedback, I'll think about what could be done to improve this 👍

**Comment by lukehaas** [comment]
It's now possible to receive JS only diagnostics by turning off the TypeScript option in the transpilation preferences.

![Screenshot 2021-12-31 at 11 22 37](https://user-images.githubusercontent.com/741344/147820801-d44a4bef-7fbc-452d-b08e-c9185afcecab.png)
