### ISSUE TITLE
Feature Request: make setting to use ONE scroll view for both (code, result) panels

### ISSUE THREAD

**Issue by atmadev** [lukehaas/RunJS#261]
It is very annoying when results lines don't match to the code lines.

It happens when scrolling is enabled. You can scroll one panel, but the second stays in place. Why actually we need this? I don't know the case when you need to scroll only code, but you also need to keep result in place. Result strings always should much the code strings. So, results panel should be a part of code panel, and these two panels should be wrapped in one scroll view.

Here are screenshots for example

I just opened RunJS, everything is ok
<img width="685" alt="Screenshot 2021-06-23 at 10 04 09" src="https://user-images.githubusercontent.com/7728638/123051344-5bcf3600-d40a-11eb-9a30-d391fe703b15.png">
I scrolled down my code, and now results don't match the code:
<img width="685" alt="Screenshot 2021-06-23 at 10 04 35" src="https://user-images.githubusercontent.com/7728638/123051391-6ab5e880-d40a-11eb-8914-b25fe8f3aaf2.png">
It is annoying! 🥶

What do you think? Does it make sense?

I believe this fix make a lot of developers happy 😃

**Comment by luisee** [comment]
I bought the **license** thinking that this option, to scroll the code along with the result, was there but it wasn't. There is an option in "Preferences" of "Auto-scroll" but it doesn't work as I expected, hope you can add and / or fix this.

**Comment by lukehaas** [comment]
@atmadev thanks for raising this. I'll consider how this can be offered as an option 👍

**Comment by shahul01** [comment]
@lukehaas maybe you can use ctrl + scoll to ctrl both panels

**Comment by KennanChan** [comment]
any progress?

**Comment by lukehaas** [comment]
The next release will include a synchronous scroll option

![Screenshot 2022-05-17 at 10 53 29](https://user-images.githubusercontent.com/741344/168784207-3d65cac5-1f59-416d-ba71-1bea222643bf.png)

**Comment by KennanChan** [comment]
Will this be a feature available in free version?

**Comment by lukehaas** [comment]
@KennanChan yes it will.

**Comment by lukehaas** [comment]
This is now available in the latest release - version 2.4.1
