### ISSUE TITLE
Clickable links in output pane

### ISSUE THREAD

**Issue by alDuncanson** [lukehaas/RunJS#263]
## Enhancement
I think a nice feature would be the ability to click (ctrl+click / cmd+click) links in the output pane

## Context
![Kapture 2021-06-24 at 10 53 42](https://user-images.githubusercontent.com/25286675/123285375-fbf49000-d4da-11eb-8be9-ef9abf23b5fb.gif)

**Comment by lukehaas** [comment]
Thanks, it's a nice idea 👍

**Comment by lukehaas** [comment]
@alDuncanson this is now supported in the latest version of RunJS - 2.3.0

**Comment by alDuncanson** [comment]
Awesome! I'll close this issue then 👍🏻
