### ISSUE TITLE
Suggestion: remove single quotes from output of console.log

### ISSUE THREAD

**Issue by horaceho** [lukehaas/RunJS#266]
It'll be nice to remove the single quotes such that every line starts from the same column zero:

<img width="909" alt="Screenshot 2021-06-28 at 08 53 16 " src="https://user-images.githubusercontent.com/6657/123565205-b1cb2180-d7ee-11eb-9f93-506b126dd7b6.png">

like node:

<img width="862" alt="Screenshot 2021-06-28 at 08 52 34 " src="https://user-images.githubusercontent.com/6657/123565222-be4f7a00-d7ee-11eb-8687-d538829f5dce.png">

**Comment by lukehaas** [comment]
The reason Node does this is because it has no syntax highlighting, all its output is a single colour.
If RunJS were to remove quotes on strings it would also need to remove syntax highlighting and display all output in a single colour.

**Comment by horaceho** [comment]
Understand.
