### ISSUE TITLE
Feature Request: Open multiple files in tabs, on macOS:

### ISSUE THREAD

**Issue by lunelson** [lukehaas/RunJS#267]
Two things which would be nice, but don't currently work:

- allow multiple selection of files in the `Open...` dialog, where each file should open in a new tab
- allow double-clicking of one or more files in the Finder (assuming RunJS has been assigned as default application for `.js` files), to open them (in tabs, if multiple), in the app

**Comment by lukehaas** [comment]
Good suggestion, this all makes sense. I'll aim to get these implemented. 👍

**Comment by lukehaas** [comment]
@lunelson this is now implemented in the latest version of RunJS - version 2.2.2
