### ISSUE TITLE
Unknown publisher when installing on windows

### ISSUE THREAD

**Issue by jaibeales** [lukehaas/RunJS#268]
I assume the installer executable needs signing with a trusted cert:
![image](https://user-images.githubusercontent.com/21100238/123628518-172d0b80-d80b-11eb-8315-2459fcf07426.png)

**Comment by lukehaas** [comment]
That's right. Some details are provided in the docs about this: https://runjs.app/docs#installation

**Comment by jaibeales** [comment]
I see. Any plans to get a cert? This sort of thing is very frowned upon when installing on a Work laptop :(

**Comment by lukehaas** [comment]
Yes, aiming to get a cert soon. Hopefully before the next release.

**Comment by lukehaas** [comment]
@jaibeales Windows builds of RunJS are now signed - as of version 2.2.2
