### ISSUE TITLE
adds extra backslash when replacing " with \"

### ISSUE THREAD

**Issue by StartMeUp** [lukehaas/RunJS#269]
Hi

Here's the code 

```
const myJSON = { name: "Kris", surname: "Bob" };

var myJSONString = JSON.stringify(myJSON);

console.log(myJSONString.replace(/"/g, '\\"'));
```

output in runJS

```
{\\"name\\":\\"Kris\\",\\"surname\\":\\"Bob\\"}
```

Output in my console

```
{\"name\":\"Kris\",\"surname\":\"Bob\"}
```

**Comment by lukehaas** [comment]
Thanks, will look into it 👍

**Comment by lukehaas** [comment]
This will be fixed in the next release.

**Comment by lukehaas** [comment]
@StartMeUp this is now resolved in the latest version of RunJS

![Screenshot 2021-09-09 at 11 45 05](https://user-images.githubusercontent.com/741344/132672389-d29a89a4-504d-41e2-86ff-9cb065c83d48.png)
