### ISSUE TITLE
Feature Request: display the evaluation results at the same line of the source code

### ISSUE THREAD

**Issue by multics** [lukehaas/RunJS#27]
The evaluation result is a bit confusing sometimes.
<img width="697" alt="image" src="https://user-images.githubusercontent.com/1222707/50911037-fbcabc00-1469-11e9-9531-ca85f703ad3d.png">

I think the following one makes the results more clear (I copied it from swift playground of Xcode):
<img width="566" alt="image" src="https://user-images.githubusercontent.com/1222707/50910785-77783900-1469-11e9-80d2-71ccb3c87cc7.png">

I like the app very much! Thank you very much for making it.

**Comment by lukehaas** [comment]
Thanks, yes, I'm aiming to implement this in a future version

**Comment by lukehaas** [comment]
@multics this is now supported as an option in RunJS version 1.11.0
