### ISSUE TITLE
Error: cannot find module

### ISSUE THREAD

**Issue by zeliwipin** [lukehaas/RunJS#271]
![image](https://user-images.githubusercontent.com/33418718/124123281-6aa39180-da77-11eb-80c5-0d2f9dc42680.png)

Hello, thank you for your software.

I have bought it.
When trying to import the module bcrypt i have the error :
"Error: Cannot find module '/Users/DrDream/Library/Application Support/runjs/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'"

I have also tried with a require still not working.

Can you help? thank you so much

**Comment by lukehaas** [comment]
@zeliwipin try using the bcryptjs package instead: https://www.npmjs.com/package/bcryptjs

**Comment by zeliwipin** [comment]
Interesting thank you for your quickness to reply,
 and your amazing contribution to the community
