### ISSUE TITLE
Create a new snippet in current tab

### ISSUE THREAD

**Issue by MajorTom327** [lukehaas/RunJS#272]
An option to create a new snippet easily would be create.

I got a file open which i don't want to override. I want to create a new snippet.
The clear action is not a good option, if I clear and write my new script. The save option will override my file.

The current method is:
- Create a new file in finder
- Open it in the app.

There is an "New Tab" option, but that do not respond to my request to replace my current tab.

**Comment by lukehaas** [comment]
Thanks for raising this @MajorTom327. The issue you're describing isn't very clear to me. It sounds like simply selecting Save as, instead of Save would solve your problem. Please correct me if I'm mistaken.

**Comment by MajorTom327** [comment]
Yes, that a way to handle the problem.
But start a new empty snippet could be better to handler the clumsiness of the user. Or if they forgot to `save as` in first place.

That not a real problem but a improvement for better user experience I guess.

**Comment by lukehaas** [comment]
Ok, there is a snippet management feature that will be coming to RunJS in the future but it will function quite differently from this. For that reason, I'll close the ticket, but please do feel free to share any other ideas you have.
