### ISSUE TITLE
Vim mode: repeat the action while holding down the key

### ISSUE THREAD

**Issue by diegoulloao** [lukehaas/RunJS#274]
I'm using the vim mode available, so when I hold on the `J` key to go down, it only go down 1 line and doesn't repeats the action until I leave the key.

Any fix for this?

version: `2.0.1`
pro license

**Comment by lukehaas** [comment]
Thanks for raising. Will look into it.

**Comment by lukehaas** [comment]
@diegoulloao this is fixed in the latest version of RunJS

**Comment by diegoulloao** [comment]
Not working yet for `v2.1.1`

**Comment by lukehaas** [comment]
Ok, holding down J is working fine for me so I have no idea what the issue could be.

![2021-07-30 17 34 28](https://user-images.githubusercontent.com/741344/127684201-a48b0a4d-be44-4ef7-bf12-dae04346d209.gif)

**Comment by diegoulloao** [comment]
How can I help providing more information about my issue? (btw, what keyboard app are you using?)

**Comment by lukehaas** [comment]
The keyboard app is just the on-screen keyboard in macOS: https://support.apple.com/en-gb/guide/mac-help/mchlc74c1c9f/mac#:~:text=Turn%20it%20on%3A%20On%20your,then%20select%20Enable%20Accessibility%20Keyboard.&text=You%20can%20also%20turn%20on%20the%20Accessibility%20Keyboard%20by%20clicking,then%20choosing%20Show%20Keyboard%20Viewer.

**Comment by diegoulloao** [comment]
![Grabación de pantalla](https://user-images.githubusercontent.com/45423661/127707590-a2aef66a-d0ba-4676-aec6-dd11653a0745.gif)

**Comment by lukehaas** [comment]
What are your key repeat settings on?

![Screenshot 2021-07-31 at 11 37 03](https://user-images.githubusercontent.com/741344/127737232-c3cd2191-4d41-4c1d-91f1-260f29b4ea71.png)

**Comment by diegoulloao** [comment]
I’ll check when arrive to home, but I remember to have set it to fast

**Comment by lukehaas** [comment]
@diegoulloao have you been able to verify that your key repeat settings are on?

**Comment by diegoulloao** [comment]
> @diegoulloao have you been able to verify that your key repeat settings are on?

yes, are on

![Captura de Pantalla 1](https://user-images.githubusercontent.com/45423661/130717956-f1c9c7a4-ba25-473d-b5f2-43dff0cad65b.png)

**Comment by lukehaas** [comment]
Closing as I'm not able to replicate the issue.

**Comment by ekathuria** [comment]
@diegoulloao not sure what was causing your issue or if you were able to get it resolved, but for some reason i had changed this command to `true` in the past. Setting it back to `false` resolved the issue for me:

`defaults write -g ApplePressAndHoldEnabled -bool false`

more info [here](https://superuser.com/questions/363252/how-to-enable-keyboard-repeat-on-a-mac):

**Comment by jamesofficer** [comment]
For anyone else with this issue, run this command in your terminal:

`defaults write me.lukehaas.runjs ApplePressAndHoldEnabled -bool false`

This will apply it just to RunJS instead of globally like twrkco's post above.

**Comment by diegoulloao** [comment]
> For anyone else with this issue, run this command in your terminal:
> 
> `defaults write me.lukehaas.runjs ApplePressAndHoldEnabled -bool false`
> 
> This will apply it just to RunJS instead of globally like twrkco's post above.

This works!!! Thank youuuu
