### ISSUE TITLE
Preferences window empty on MacOS

### ISSUE THREAD

**Issue by Case09** [lukehaas/RunJS#275]
Just installed RunJS and tried to open preferences but window opens up empty and stays like that (see screenshot below).
<img width="500" alt="Screenshot 2021-07-05 at 08 26 14" src="https://user-images.githubusercontent.com/2895851/124427417-a71f0800-dd6b-11eb-949d-3177d435e759.png">
Tried reinstalling but didn't help. Any suggestions? I'm on MacOS Catalina.

**Comment by lukehaas** [comment]
Very odd. Could you try deleting the config file located here: ~/Library/Application\ Support/runjs/config.json

**Comment by Case09** [comment]
@lukehaas Unfortunately it didn't help, same empty window. I've also noticed that i cannot move that window. Also, other windows work fine, for example "Manage NPM packages" opens normally and i can move it. So looks like it's just about preferences window.

**Comment by lukehaas** [comment]
Ok, could you message me at mail@runjs.app and we'll go through some debug steps.
