### ISSUE TITLE
Error in the order of printing in loops

### ISSUE THREAD

**Issue by Elteoremadebeethoven** [lukehaas/RunJS#276]
Code: 
```javascript
const is_even = (i) => {
  if(i%2===0) console.log(`${i} is even`)
  if(i%2!==0) console.log(`${i} is odd`)
}

for(let i=0; i<10; i++){
  is_even(i)
}
```
Expected result:
![even2](https://user-images.githubusercontent.com/43224662/125368150-42514800-e33f-11eb-995e-612e38187a53.png)

RunJS Result: 
![even](https://user-images.githubusercontent.com/43224662/125368050-061de780-e33f-11eb-88d5-ef7ade631163.png)

Machine: Linux Mint 20.04

**Comment by lukehaas** [comment]
This is because you have the 'Match Lines' option turned on.

![Screenshot 2021-07-13 at 09 05 01](https://user-images.githubusercontent.com/741344/125415292-16eef181-387c-4503-b051-d885e70c7c63.png)

**Comment by sfonua10** [comment]
@lukehaas yeah, I would go ahead and default that to off (uncheck)

> This is because you have the 'Match Lines' option turned on.
> 
> ![Screenshot 2021-07-13 at 09 05 01](https://user-images.githubusercontent.com/741344/125415292-16eef181-387c-4503-b051-d885e70c7c63.png)

**Comment by lukehaas** [comment]
@sfonua10 yeah, I thought about it, but it's also a core behaviour that I think a lot of people find useful.
