### ISSUE TITLE
Printing log statements inside condition when false

### ISSUE THREAD

**Issue by sfonua10** [lukehaas/RunJS#277]
<img width="1253" alt="Screen Shot 2021-07-13 at 4 41 09 PM" src="https://user-images.githubusercontent.com/18669021/125534416-863cf211-5286-4009-96d0-a17b0eceb34e.png">

It shouldn't be printing out 'fizz' for every loop. Only when the condition is true

**Comment by JackPhilippi-Mo** [comment]
Should be `if (i % 3 === 0) {`. Easy mistake!
