### ISSUE TITLE
Incorrect console.log output of escaped string

### ISSUE THREAD

**Issue by antonklimov** [lukehaas/RunJS#278]
`var x = "c:\\new\\temp";
console.log(x)`

Supposed to output:
c:\new\temp

Instead the output is split into 2 lines. Apparently `\\n` is treated as a slash and a newline, but that's incorrect, it's a slash and `n`. The second escape sequence is not processed at all.

**Comment by lukehaas** [comment]
@antonklimov thanks, will look into it.

**Comment by iliakan** [comment]
Confirmed, here's the screenshot:

![image](https://user-images.githubusercontent.com/349336/129259170-98cb7901-892a-4e28-bae4-37989e059cae.png)

**Comment by lukehaas** [comment]
This will be fixed in the next release. 👍

**Comment by lukehaas** [comment]
@antonklimov this is now resolved in the latest version of RunJS

![Screenshot 2021-09-09 at 11 46 22](https://user-images.githubusercontent.com/741344/132672537-e800e37f-4b03-4909-81b1-8d93e25f2b26.png)
