### ISSUE TITLE
Feature Request: Tab usability

### ISSUE THREAD

**Issue by Liamballin** [lukehaas/RunJS#279]
It would be great if tabs could be named, and switched with alt+tab and shift+alt+tab

**Comment by lukehaas** [comment]
You can switch tabs using the shortcut `cmd+Alt+left/right arrow`

**Comment by lukehaas** [comment]
Naming tabs could be useful. Will have a think about it.

**Comment by lordlycastle** [comment]
Good to know the shortcut for switching tab. 

It would be better to use OS standards where possible. On macOS it should be `Cmd + Shift + [` or `Cmd + Shift + ]` which works in all apps. If it uses the default then most people won't have to ask or look up the shortcut.

Also you could add the tab number/index in the title (w/ and w/o saving the file), so people know they can also `Cmd + <tab number>` to switch.

**Comment by lukehaas** [comment]
@lordlycastle standard shortcuts are always the aim. I was under the impression that `cmd+Alt+left/right arrow` was the standard (it's what I use for tabbed apps), but having just looked into this it seems you're right `Cmd + Shift + [/]` is more of a standard way. I'll get this implemented in the next release 👍

**Comment by bendman** [comment]
I'm on macOS and use `Ctrl+Tab` and `Ctrl+Shift+Tab` in most programs to switch tabs. This works in VSCode, Chrome, Vivaldi, and just about anything else I try it in.

**Comment by lukehaas** [comment]
@bendman `Ctrl+Tab` and `Ctrl+Shift+Tab` are supported for Windows on the latest version of RunJS

**Comment by lordlycastle** [comment]
Nice one @bendman. Who knew you'd find it on Wikipedia, through I must say they're only as good as they're updated. Like the tab switching for Safari (`Cmd+Shift+➡️`) is not a native shortcut and is perhaps a legacy shortcut as it does not work in other native tabbed applications e.g. Finder, which got the tabs features relatively recently. But `Ctrl+Tab` works in Finder 🤯

Still very good to know, especially for left handed people!

**Comment by lukehaas** [comment]
@bendman @Liamballin the latest version of RunJS includes support for `Ctrl+Tab`, `Ctrl+Shift+Tab` on Mac.
