### ISSUE TITLE
Feature Request: code completion/prompts

### ISSUE THREAD

**Issue by multics** [lukehaas/RunJS#28]
I captured the screen from my Xcode playground.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/1222707/50911274-7a275e00-146a-11e9-8be3-e702e336fa81.png">

Again, I like the app very much! Thank you very much for making it.

**Comment by lukehaas** [comment]
Yes, would be a good feature.

**Comment by AceroM** [comment]
Bump, would love this feature

**Comment by lukehaas** [comment]
The latest version of RunJS now supports autocomplete:

![autocomplete](https://user-images.githubusercontent.com/741344/122990315-b7aea600-d39b-11eb-83ca-1756e1a287f8.gif)
