### ISSUE TITLE
Syntax Highlighting Not Consistent

### ISSUE THREAD

**Issue by lordlycastle** [lukehaas/RunJS#281]
I have tried out almost all default themes and all have syntax highlighting issues (in some you cannot see them because themes are using same color for many different components).

See screenshot below with the syntax highlighting mistakes:
 - object's or function's first property has different highlight than others.
 - string template's first template is different color

Would love consistent highlighting as it playing a large part in helping your eyes peruse code.

![SS 2021-07-21T19 01 02](https://user-images.githubusercontent.com/11729541/126530061-e3229f49-3689-4ba2-8680-670e8a12738a.png)
![SS 2021-07-21T19 04 40](https://user-images.githubusercontent.com/11729541/126530076-a2d18ab9-20dc-492c-acd2-f84b454811f1.png)

**Comment by lukehaas** [comment]
Thanks for this. Will look into it.

**Comment by lukehaas** [comment]
This is now resolved in version 2.2.2 @lordlycastle
