### ISSUE TITLE
Latest update via check software update not compatible with OS-X 10.15.7

### ISSUE THREAD

**Issue by alankleindev** [lukehaas/RunJS#282]
I upgraded yesterday and noticed the message below.

The previous version ran without any issues.

![runJSerror](https://user-images.githubusercontent.com/57042275/126898665-d123054d-afec-41d8-b216-866080204a12.jpg)

**Comment by alankleindev** [comment]
I downloaded it directly from, https://runjs.app/, instead of choosing "Check for Updates..." from within RunJS and now it works. Strange.

**Comment by lukehaas** [comment]
This is odd, the minimum supported version of macOS is 10.11.
I'm using macOS 10.15.7 myself and have not encountered this message.

**Comment by indifferentghost** [comment]
I just got this after attempting to update to the latest version of runjs: 
<img width="264" alt="image" src="https://user-images.githubusercontent.com/12449668/126914318-68786357-0e25-4333-b623-943f6f65390c.png">

**Comment by rodrigo398** [comment]
> I just got this after attempting to update to the latest version of runjs:
> <img alt="image" width="264" src="https://user-images.githubusercontent.com/12449668/126914318-68786357-0e25-4333-b623-943f6f65390c.png">
> 
> trying to open the executable directly shows:
> 
> > bad CPU type in executable: /Applications/RunJS.app/Contents/MacOS/RunJS
> 
> Redownloading from the site fixed the problem.

Doing this actually worked for me. Redownloading and replacing it from the site fixed it. Thanks

**Comment by lukehaas** [comment]
@indifferentghost @rodrigo398 are you on M1 or Intel macs?

**Comment by pchiorean** [comment]
Got that today, too, on macOS Catalina 10.15.7. Updated manually from runjs.app.

**Comment by lukehaas** [comment]
I've now set the 2.1.0 release to a pre-release so no more people will be auto-updated onto it.

**Comment by lukehaas** [comment]
There was an issue with the release that caused Intel macs to update onto the M1 build.
I've pushed a new release that resolves this with a universal build.

Thanks, everyone for alerting me to this issue, really appreciate it 👍 🙏

**Comment by alankleindev** [comment]
That was a fast fix! Thanks @lukehaas for resolving it so quickly!

**Comment by indifferentghost** [comment]
> @indifferentghost @rodrigo398 are you on M1 or Intel macs?

I'm sure it's no longer needed, but intel.
