### ISSUE TITLE
Error report for runjs 2.1.1

### ISSUE THREAD

**Issue by dwhenson** [lukehaas/RunJS#283]
Error:
```Error: net::ERR_INVALID_HANDLE
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```
OS: macOS 10.16

Since updating I haven't been able to run the app successfully. (But when it works I love it!)

**Comment by lukehaas** [comment]
Thanks @dwhenson, could you try re-installing it from here: 

https://github.com/lukehaas/RunJS/releases/download/v2.1.1/RunJS-2.1.1-universal.dmg

**Comment by lukehaas** [comment]
@dwhenson are you seeing this error every time you open RunJS or was it just once?

**Comment by lukehaas** [comment]
Closing as this seems to be a one-time error.
