### ISSUE TITLE
Feature Request: shift+alt+up/down to duplicate line

### ISSUE THREAD

**Issue by Froskk** [lukehaas/RunJS#284]
Following common keybindings, especially from VS Code, it would be great to have these keybinds

shift+alt (or option)+up: duplicate line above cursor
shift+alt (or option)+down: duplicate line below cursor

Hopefully you agree!

**Comment by lukehaas** [comment]
Thanks, @Froskk. A shortcut for line duplication is already implemented `Cmd+Shift+D`. 
RunJS uses Sublime Text shortcuts for editing, a complete list can be found here: https://runjs.app/docs#shortcuts

**Comment by Froskk** [comment]
Ah, apologies. I think this maybe be broken on windows though

**Comment by lukehaas** [comment]
I'm not seeing an issue on Windows, could you please double-check?

![2021-07-30 11 25 39](https://user-images.githubusercontent.com/741344/127640292-de9a8019-73e0-4f86-b89c-05febbcd289a.gif)

**Comment by Froskk** [comment]
My mistake. I glanced over the key information of what the actual shortcut was. I was expecting it to be ctrl+shift+down arrow. ctrl+shift+d does indeed work

**Comment by lukehaas** [comment]
Ah nice, thanks for confirming 👍
