### ISSUE TITLE
Error: Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by lordlycastle** [lukehaas/RunJS#287]
I cannot seem to debug or understand what this error is referring to. The code snippet to recreate it is taken from `ascii-art` package:
```ts
import * as art from 'ascii-art';

art.font('Some Text', 'doom', (err, rendered) => {
  //if err, err is the error that occured
  //if !err rendered is the ascii
  if (err) {
    console.log(err);
  } else {
    console.log(rendered);
  }
});
```

I also manually installed `node-canvas` and `canvas` packages and the error persists.

<img width="1180" alt="SS 2021-07-27T22 49 33@2x" src="https://user-images.githubusercontent.com/11729541/127225706-027b781a-ba0a-4105-ab2a-00f1418afee4.png">

**Comment by lukehaas** [comment]
Looks like this is a native node module. It will need to be re-built for electron. The easiest way to do this is with electron-rebuild: https://github.com/electron/electron-rebuild.

Improving support for native modules is on my to-do list.
