### ISSUE TITLE
[FEATURE REQUEST] - Split View / editor for tabs

### ISSUE THREAD

**Issue by ondrovic** [lukehaas/RunJS#288]
Would love to see a split view / editor for the tabs where you could have tabs side by side or the same tab split.
![split view](https://user-images.githubusercontent.com/3682042/127520642-dc2276a2-19eb-4a62-928e-ec3a6d36050e.png)

**Comment by lukehaas** [comment]
Thanks @ondrovic. Given that each tab has an editor pane and also an output pane, having two tabs next to each other would mean 4 panes would be visible. This seems to me like it might not be very usable or useful. Closing for that reason.
