### ISSUE TITLE
setTimeOut output difference in function

### ISSUE THREAD

**Issue by sathishk2030** [lukehaas/RunJS#289]
Code sample:

// Function Timeout

function func1() {
    console.log(1); 
    setTimeout(function(){console.log(2)}, 1000); 
    setTimeout(function(){console.log(3)}, 0); 
    console.log(4);
};

func1();

Expected Output: 
1
4
3
2

1. RunJS Output: 
![image](https://user-images.githubusercontent.com/28302736/127734266-c6b4e273-f4ff-4871-b01c-fd62d4b7e653.png)

2. Chrome Output:
![image](https://user-images.githubusercontent.com/28302736/127734283-9a83c91c-7975-4286-94d1-f62e2aaafc5c.png)

3. Ijavascript Jupyter Notebook Output:
![image](https://user-images.githubusercontent.com/28302736/127734298-0d4379c5-b7bf-4240-93c5-36be91fd5607.png)

**Comment by lukehaas** [comment]
@sathishk2030 this is because you have Match Lines turned on.

![Screenshot 2021-07-31 at 11 07 50](https://user-images.githubusercontent.com/741344/127736563-88b6f611-4415-463e-9f38-2d392668043d.png)

**Comment by sathishk2030** [comment]
@lukehaas thank you. got it!!!
