### ISSUE TITLE
Feature Request: Linux support

### ISSUE THREAD

**Issue by joppe** [lukehaas/RunJS#29]
I hope that you will support Linux soon, I hear great things about this tool. Would be awesome if it was also available for Linux.

**Comment by lukehaas** [comment]
Thanks, it's coming 👍

**Comment by lukehaas** [comment]
A Linux version is now available: https://runjs.dev/

**Comment by joppe** [comment]
Thank you for creating a Linux version!
I installed it, everything seems to work, except for the settings dialog. It doesn't appear. Once it appeared for me, after closing it never came back.

**Comment by lukehaas** [comment]
@joppe thanks, this is a bug, I've opened a separate ticket for this: https://github.com/lukehaas/RunJS/issues/61
It will be fixed in the next release.
