### ISSUE TITLE
Tabs: modules?

### ISSUE THREAD

**Issue by iliakan** [lukehaas/RunJS#290]
Can I import content from one tab into another, as a module?

Is there any way for scripts in different tabs to interact?

Thank you!

**Comment by lukehaas** [comment]
No, the tabs are sandboxed. There's no import/export between them.

**Comment by iliakan** [comment]
It could be nice if one could export/import =) 

Would be beneficial for tutorial examples.  Just a minor feature request =)

**Comment by lukehaas** [comment]
I'm not sure if there would be an intuitive way of handling this. For example, what would the import path be for importing from a sibling tab?

**Comment by iliakan** [comment]
Easy if tabs have names :-)

Best regards,
Ilya Kantor

**Comment by lukehaas** [comment]
You can give a tab a name by saving it as a file, once you've done that it may be easier to just use the 'Set Working Directory' option to then import those files.

**Comment by iliakan** [comment]
And then I can use import?

Best regards,
Ilya Kantor

**Comment by lukehaas** [comment]
Yes, when a working directory is set, you can import files from that directory.
