### ISSUE TITLE
Error report for runjs 2.1.1

### ISSUE THREAD

**Issue by ihaveint** [lukehaas/RunJS#293]
I get this error often

Error:
```UnhandledRejection Error: Invalid argument provided for port
    at e.exports (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:223:270876)
    at App.<anonymous> (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:223:269158)
    at App.emit (events.js:327:22)
```
OS: macOS 11.2.3

and here is debug log:

debug log:

[
  {
    "path": "/Users/ihaveint/Library/Logs/runjs/main.log",
    "lines": [
      "[2021-07-31 10:24:17.912] [info]  Checking for update",
      "[2021-07-31 10:24:17.920] [info]  Generated new staging user ID: 62addf54-0144-5465-92a9-b8bc2271c018",
      "[2021-07-31 10:24:20.452] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
      "[2021-07-31 14:46:58.180] [info]  Checking for update",
      "[2021-07-31 14:47:00.711] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
      "[2021-07-31 15:04:55.457] [info]  Checking for update",
      "[2021-07-31 19:17:09.899] [info]  Checking for update",
      "[2021-07-31 19:17:13.673] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
      "[2021-08-01 03:06:36.538] [info]  Checking for update",
      "[2021-08-01 03:06:41.310] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
      "[2021-08-01 11:42:45.715] [info]  Checking for update",
      "[2021-08-01 11:42:48.582] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
      "[2021-08-01 22:51:14.170] [info]  Checking for update",
      "[2021-08-01 22:51:16.799] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
      "[2021-08-02 11:53:00.342] [error] UnhandledRejection Error: Invalid argument provided for port",
      "    at e.exports (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:223:270876)",
      "    at App.<anonymous> (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:223:269158)",
      "    at App.emit (events.js:327:22)",
      "[2021-08-02 13:16:31.393] [info]  Checking for update",
      "[2021-08-02 13:16:33.897] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
      "[2021-08-04 15:43:53.241] [error] UnhandledRejection Error: Invalid argument provided for port",
      "    at e.exports (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:223:270876)",
      "    at App.<anonymous> (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:223:269158)",
      "    at App.emit (events.js:327:22)",
      "[2021-08-04 15:44:07.255] [info]  Checking for update",
      "[2021-08-04 15:44:10.542] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
      ""
    ]
  }
]

**Comment by lukehaas** [comment]
What kind of scenarios are you seeing this in, is it when opening the app, running particular code etc?

**Comment by ihaveint** [comment]
> What kind of scenarios are you seeing this in, is it when opening the app, running particular code etc?

When opening the app.

**Comment by lukehaas** [comment]
Ok, I think I have some idea of what's going on here. The error `Error: Invalid argument provided for port` originates from a dependency that is used to clear up a port that's used for language services. This happens when the app is quitting, I have no idea why it would happen for you on start.
Are the features such as type checking and autocomplete working ok for you?

**Comment by ihaveint** [comment]
I was almost sure that it happened at the start, but if you think otherwise, I'll try being more careful to see what actually happens and I'll let you know :)

And about the functionalities, yes, they do seem to work.

**Comment by ihaveint** [comment]
> Ok, I think I have some idea of what's going on here. The error `Error: Invalid argument provided for port` originates from a dependency that is used to clear up a port that's used for language services. This happens when the app is quitting, I have no idea why it would happen for you on start.
> Are the features such as type checking and autocomplete working ok for you?

It's weird that after posting this the error didn't happen until now. Today it happened again, I think you were right and it happened when closing the app.
<img width="260" alt="Screen Shot 2021-08-15 at 4 35 08 AM" src="https://user-images.githubusercontent.com/19837363/129463061-d6b4ce74-382d-434c-bce6-40d7e74fd97e.png">

**Comment by lukehaas** [comment]
Thanks, @ihaveint. I have a pre-release here of the next version of RunJS: https://github.com/lukehaas/RunJS/releases/download/v2.1.2/RunJS-2.1.2-universal.dmg

It has a fix for this issue.

**Comment by ihaveint** [comment]
> Thanks, @ihaveint. I have a pre-release here of the next version of RunJS: https://github.com/lukehaas/RunJS/releases/download/v2.1.2/RunJS-2.1.2-universal.dmg
> 
> It has a fix for this issue.

Thank you 😃
