### ISSUE TITLE
Stuck in loop, needs restart

### ISSUE THREAD

**Issue by shahul01** [lukehaas/RunJS#296]
The loop keeps running even after commenting the code.

I write a for loop and as I try to write  code inside curly brackets, it becomes stuck.
And I have to reload it to work.

**Comment by lukehaas** [comment]
To stop execution, select the `Stop` option from the `Action` menu.

![Screenshot 2021-08-08 at 11 13 44](https://user-images.githubusercontent.com/741344/128628582-98c6189b-2627-4afc-9c39-4fbec46210f3.png)

**Comment by shahul01** [comment]
Nice, btw if you can, can you make a hotkey eg: escape etc.
