### ISSUE TITLE
Do not copy on deleting a line

### ISSUE THREAD

**Issue by shahul01** [lukehaas/RunJS#297]
Do not copy on deleting a line.

Or at least make an option to disable the fn.

Thanks

**Comment by lukehaas** [comment]
@shahul01 I'm not quite sure what you mean. The shortcut for deleting a line is `Ctrl+Shift+K` it does not also copy.

A full list of shortcuts can be found here: https://runjs.app/docs#shortcuts

**Comment by shahul01** [comment]
When I delete a line, it automatically copies. Maybe it has to do with vim/emac kind of stuff?

**Comment by lukehaas** [comment]
what method are you using to delete the line?

**Comment by shahul01** [comment]
shift+delete

**Comment by lukehaas** [comment]
`shift+delete` is not a supported shortcut. Please use `Ctrl+Shift+K` for deleting lines.

**Comment by shahul01** [comment]
k, thanks
