### ISSUE TITLE
Don't show the result for assignment

### ISSUE THREAD

**Issue by iliakan** [lukehaas/RunJS#298]
Is it possible to skip outputting the result for assignments? 

E.g don't show `'Arnold'` here:

![image](https://user-images.githubusercontent.com/349336/128643708-644b9ccb-9a41-472b-b04f-a5f5e316a6d9.png)

I'm using RunJS for a video tutorial, and it's a bit confusing for newbies, the 1st assignment doesn't show anything, while the 2nd one does.

**Comment by lukehaas** [comment]
Hi @iliakan, the output here is just showing what your code evaluates to.  The two lines are very different as the first is a variable declaration, which in JavaScriot, evaluates to `undefined`, the second is an assignment which evaluates to the assigned value.
I don't quite see this as being something that is confusing because this is just standard JavaScript behavior.

**Comment by lukehaas** [comment]
Just for further clarification, here is an example from the Chrome dev tools where the same behavior can be seen. It's also the same in the Node Repl.

![Screenshot 2021-08-09 at 09 06 36](https://user-images.githubusercontent.com/741344/128676312-a3122fc1-1a32-45b8-828e-204f1f2de464.png)

**Comment by iliakan** [comment]
@lukehaas of course that doesn't confuse you, because you know this stuff.

Not so obvious for a newcomer who sees no output `let a = 5`, and then `a = 6` yields the output for some reason.

**Comment by lukehaas** [comment]
One thing you could do is turn off auto-run, that way you can trigger execution manually when you want to see the output.

**Comment by iliakan** [comment]
That's interesting.

There's a hotkey for the execution, right? And the execution just runs whole code and outputs everything?

**Comment by lukehaas** [comment]
The shortcut is `Cmd+R`.

If you want it to just execute the whole code and show a single output, you'll also need to turn off the runtime values option in the advanced preferences.
