### ISSUE TITLE
Simple for loop key undefined

### ISSUE THREAD

**Issue by Brydom** [lukehaas/runjs#3]
Running this code:

```
const foo = [1, 2, 3];

for (bar in foo) {
  console.log(bar);
}
```

Returns `ReferenceError: bar is not defined` - this should return:

```
0
1
2
```

Let me know if I'm losing it or if this is an issue :)
Version 1.0.2 (1.0.2)

**Comment by piousdeer** [comment]
You should use `const` to define `bar`. `let` and `var` are acceptable too, but not recommended.

```
const foo = [1, 2, 3];

for (const bar in foo) {
  console.log(bar);
}
```

**Comment by lukehaas** [comment]
This is because the code is run in "strict mode" by default - which will require you to define all variables , as in `var bar in foo`.

The "strict mode" is a result of Babel transpilation, which you can turn off in the preferences. When disabled, you see that your example code runs fine.

**Comment by Brydom** [comment]
Thank you both - I would apologize for the confusion but it seems that I am the only one confused.
