### ISSUE TITLE
Why not open the source code?

### ISSUE THREAD

**Issue by WeslleyNasRocha** [lukehaas/runjs#30]
I'm just curious, with the open source someone would might help you with some features

**Comment by demircancelebi** [comment]
I'd also like to offer help if you open source the code

**Comment by schester44** [comment]
+1

**Comment by ltfschoen** [comment]
I'd retweet this product again if it was open source

**Comment by WeslleyNasRocha** [comment]
@lukehaas do you have any plan to sell this app?

**Comment by lukehaas** [comment]
RunJS is a young app with a long road ahead of it. I chosen not to open source it at this point so as not to place any limitations on what it can become.

**Comment by zcei** [comment]
Just ran into this topic as well, was there any progress in how you imagine the outcome of this app?
In my opinion sharing these roadmaps with the outside helps a lot. And as others have expressed interest it might even speed up development.

In case it's a fear of missing out on monetarization, there are some ways to do it in OOS (which tbh can be quite frustrating).
And as you offer a free version as well, just having the proper licence selected should help getting "ripped off" by larger businesses, and you can sell it to them.

Just my 2c, obviously it's your call to make 🙂

**Comment by mknmohit** [comment]
> 
> 
> RunJS is a young app with a long road ahead of it. I've chosen not to open source it at this point so as not to place any limitations on what it can become.

Not Free anymore 😞. I was very excited about the new update but after hearing that there is an option to purchase a licence it broke mine heart. The most loved feature (install any npm packages) also require purchasing a licence to use it. Earlier it was free before v2.0.0 but now you have to purchase the licence to access it 😞
The thing is that, not everyone can afford to purchase a licence. It would be really helpful if you could make it free of us, or provide a dummy licence to access all the features. 🙂 
Thanks!

**Comment by lukehaas** [comment]
@mknmohit sorry you feel this way 😞  It was my hope that the cost would be reasonable and affordable to all.
