### ISSUE TITLE
[Feature Request] Live code sharing feature

### ISSUE THREAD

**Issue by nraskoti** [lukehaas/RunJS#301]
It would be good if we get the feature like [LiveShare VSCode](https://visualstudio.microsoft.com/services/live-share/).

**Comment by lukehaas** [comment]
Thanks, @nraskoti. Live sharing would be a great feature, however, this would be far too large a feature to implement due to the limited time and resources of this project. 
For that reason, I'm gonna close this ticket but if things change, I'd be happy to reconsider it.
