### ISSUE TITLE
Wrong order of console.log

### ISSUE THREAD

**Issue by iliakan** [lukehaas/RunJS#302]
Here's the code:
```js
function sayHi() {
  console.log(`Hello!`);
  console.log(`Glad to see everyone!`);
}

sayHi();
sayHi();
sayHi();
```

And here's the odd output of RunJS:

![image](https://user-images.githubusercontent.com/349336/129256126-2cc98c2d-e292-44dc-a982-8fdc15b5184b.png)

**Comment by iliakan** [comment]
P.S. You see the problem, more comments not necessary?

**Comment by iliakan** [comment]
P.P.S. Quite important for me, actually ;( Really broken stuff ;((

**Comment by lukehaas** [comment]
This is because you have Match Lines turned on.

![Screenshot 2021-08-12 at 21 15 10](https://user-images.githubusercontent.com/741344/129263493-03ba9d97-dc06-4534-8ab4-0e9e2afd2305.png)

**Comment by iliakan** [comment]
Exactly, most of time this option works correctly.

The current behavior looks odd and buggy.

One would either outputting at `sayHi()` line. But never a broken order.

Is it possible to fix it?

**Comment by iliakan** [comment]
...Or maybe the current behavior is good and valid in some other case?

**Comment by iliakan** [comment]
Line matching is a good option for teaching. Turning it off will make RunJS much worse.

Right now the output isn't quite aligned, because it's multiline.

As it's impossible to align it, the output could be at least in order, unless I'm missing something.

**Comment by lukehaas** [comment]
It's three results each for lines two and three, so subsequent results are pushed down a line due to the original being occupied. 
I have been considering changing this so that results are concatenated onto single lines.

**Comment by iliakan** [comment]
It feels like the alignment algorithm that works fine with plain code - isn't that good-looking for function calls.

**Comment by lukehaas** [comment]
Yeah, there are some scenarios like this where the line matching isn't really adding much. I've been contemplating ways to improve this.
Could you describe the output you expected to see here?

**Comment by iliakan** [comment]
The current output order looks really weird. I had thought it's a bug, before you drew my attention to the option.

Maybe like this, but the output should start at line 6.

That would feel somewhat more natural.

![image](https://user-images.githubusercontent.com/349336/129267985-9f7b96bc-fccb-47a1-86e3-932efc3a7619.png)

**Comment by iliakan** [comment]
P.S. One could imagine nested ("collapsible") output blocks for function calls, but it would probably harm readability.

**Comment by lukehaas** [comment]
I'll have a think about this. Thanks for your input.

**Comment by iliakan** [comment]
...Although without them, there's no way to really align output for multiple function calls. 

And if there's no alignment, then there should be at least correct output order.

**Comment by lukehaas** [comment]
@iliakan I've pushed a pre-release that includes a tweak to the line-matching logic.
https://github.com/lukehaas/RunJS/releases/tag/v2.1.3

Now, if a line is already occupied by the result of another line, the result will display on a subsequent line instead of pushing the previous result down a line.

It would be great if you could take a look and check it with your code examples. I've checked it against many hundreds of scenarios in automated tests but there is always the potential for unexpected issues when changing something fundamental like this.

**Comment by iliakan** [comment]
Thank you! I'll be able to download and review it on Monday. Will write back.

**Comment by iliakan** [comment]
Thank you, I tried the same example.
The main problem - the wrong line order - is fixed now.
