### ISSUE TITLE
Error report for runjs 2.1.1

### ISSUE THREAD

**Issue by vladyn** [lukehaas/RunJS#303]
Error:
```Error: net::ERR_NAME_NOT_RESOLVED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```
OS: macOS 10.16

**Comment by lukehaas** [comment]
@vladyn This error seems to occur when internet connection is lost during a check for updates. Is that consistent with your experience?

**Comment by vladyn** [comment]
> @vladyn This error seems to occur when internet connection is lost during a check for updates. Is that consistent with your experience?

Yep, I had a bad connectivity this mornign. Thanks Luke!

**Comment by lukehaas** [comment]
Cool, there is a pre-release here where that error won't occur: https://github.com/lukehaas/RunJS/releases/tag/v2.1.2
