### ISSUE TITLE
RunJS process does not die when terminating the program

### ISSUE THREAD

**Issue by luizgamabh** [lukehaas/RunJS#307]
Please check the demo video below:

[![RunJS Process demo](https://img.youtube.com/vi/t_0F51-5hd0/0.jpg)](https://www.youtube.com/watch?v=t_0F51-5hd0)

**Comment by lukehaas** [comment]
Thanks for raising this @luizgamabh. Which version of RunJS are you using?

**Comment by luizgamabh** [comment]
> Thanks for raising this @luizgamabh. Which version of RunJS are you using?

2.1.3.0

**Comment by luizgamabh** [comment]
Sorry for the delay. No, I had this problem with versions before 2.1.3 also. You can try to replicate it using [ProcessHacker](https://github.com/processhacker/processhacker/releases/tag/v2.39) instead of default Windows Task Manager. https://github.com/processhacker/processhacker/releases/tag/v2.39

Using Windows Task Manager the process disappear from the `Processes` tab, but you can find the process still running in the Details tab

![](https://myscreen.s3.amazonaws.com/2021/08/20210831213608003yRmnMDBvS2ClG3aV993w.png)

**Comment by luizgamabh** [comment]
I got it. The problem occurs only when you are using a licensed version. When I deactivated my license, it stopped to keep a remaining process. After reactivating, the problem came back.

**Comment by lukehaas** [comment]
@luizgamabh yes, the problem with the process persisting in version 2.0.0 related to the language services that are only activated when using a licensed version.

**Comment by lukehaas** [comment]
Closing as I'm not able to replicate the issue.
