### ISSUE TITLE
Error report for runjs 2.1.1

### ISSUE THREAD

**Issue by naveen-repos** [lukehaas/RunJS#309]
Error:
```Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```
OS: macOS 10.16

**Comment by lukehaas** [comment]
Thanks @naveen-repos, please could you copy your error log and paste it here:

![Screenshot 2021-08-23 at 19 24 46](https://user-images.githubusercontent.com/741344/130765828-91fc3c21-8069-4acd-9cd7-8751b3bf78a2.png)
