### ISSUE TITLE
Document the engine used

### ISSUE THREAD

**Issue by dotproto** [lukehaas/runjs#31]
I can't seem to find any information about what JavaScript engine is used, what version, or how the engine is updated. This is important when attempting to target new language features like class fields. At the time this issue was created public fields were available in Chrome Canary, but not Chrome, Firefox, or Safari.

**Comment by lukehaas** [comment]
Good point. I'll get this documented.

**Comment by lukehaas** [comment]
This is now documented in the readme: https://github.com/lukehaas/runjs/blob/master/README.md

**Comment by dotproto** [comment]
Thanks!
