### ISSUE TITLE
How to remove "in progress" indicator?

### ISSUE THREAD

**Issue by iliakan** [lukehaas/RunJS#311]
In most cases, the code execution is very fast.

So the progress indication looks like a nasty glitch. 
Especially if the output doesn't change: the blurry visual effect isn't good.

Can I disable it? 

P.S. In general, one might consider showing progress indication ONLY if the operation takes more than 300ms.
P.P.S. I'm making a screencast with RunJs, so kind of sensitive to how people see it.

**Comment by lukehaas** [comment]
The progress spinner now has a slight delay before appearing - in version 2.2.2
