### ISSUE TITLE
Incorrect package downloaded when clicks the button in Homepage

### ISSUE THREAD

**Issue by calamarico** [lukehaas/RunJS#315]
I'm on Ubuntu 20.04, and from RunJS website, if I click the button "Download RunJS (.deb)" (it's saying a correct debbian extension, that is valid for me) but, after clicking, it downloads the ' .dmg' extension package (MacOS). It also occurs in both download buttons there are in the home page. I show a screenshot to see it clear:
![screenshot](https://user-images.githubusercontent.com/2332886/131359304-3ce18b5f-3d33-4bfa-ada1-7c6184770b84.png)

Download links work fine in the "platforms table" in the Home, so, the problem only occurs in the buttons I said. I hope you find helpful this report.

**Comment by lukehaas** [comment]
@calamarico thanks for raising this. The issue was a server-side rendering bug. It should be fixed now. 👍

**Comment by calamarico** [comment]
@lukehaas FYI I just tried again, and now it's working fine  :+1:
