### ISSUE TITLE
Run JS go to black in use on windows 10

### ISSUE THREAD

**Issue by mvpsdvlpr** [lukehaas/RunJS#316]
Hello, good morning, I am trying to use Run JS for my day to day and lately when I use it this is going black, I still do not understand what may be producing it and it is a bit annoying actually, I do not know if something is happening in me team at the time of running the software, or is it for reasons that I have the unpaid version and it has airtime, hopefully you can help me with this problem, greetings and thanks for your time

ps: I am attaching a picture to demonstrate the problem.

![image](https://user-images.githubusercontent.com/65572029/131375702-4f309cc7-22e8-405e-9c7f-0807bf6775a5.png)

**Comment by lukehaas** [comment]
@mvpsdvlpr sorry you're having this issue. It's not something I've seen before.

Could you please provide the debug logs for the app. They can be found by going to this location in your explorer: `%AppData%/runjs/logs`

**Comment by lukehaas** [comment]
@mvpsdvlpr please provide your debug logs. They can be found here in your explorer: `%AppData%/runjs/logs`

**Comment by lukehaas** [comment]
Closing as there's been no response.
