### ISSUE TITLE
when typeScript error occur, why doesn't it work ?

### ISSUE THREAD

**Issue by dongwu-kim** [lukehaas/RunJS#317]
![image](https://user-images.githubusercontent.com/74899114/131440398-3e1ce331-bd3d-4811-8867-60f5e27bfd76.png)

when I using RunJS for typescript study, sth wrong in toggle output console.

how to check type error with underline display or error log?

settings : [ACTIVATED mod] preferences all checked & module manager was empty.

plz, comment any solution in here...😭

**Comment by dongwu-kim** [comment]
+ AutoComplete, Type Checking not working too

but RunJS's status ACTIVATED now...

**Comment by lukehaas** [comment]
Which version of RunJS are you using?
Which operating system are you using?

**Comment by dongwu-kim** [comment]
Using 2.3.0 version & m1 silicon mac 10.9 ver> bigsur

**Comment by lukehaas** [comment]
Please copy your debug log and paste it here.

![Screenshot 2021-08-31 at 10 15 49](https://user-images.githubusercontent.com/741344/131476534-8ed300d1-06fa-4e96-97eb-2152ca382805.png)

**Comment by dongwu-kim** [comment]
[
  {
    "path": "/Users/kimdong-u/Library/Logs/runjs/main.log",
    "lines": [
      "[2021-08-31 13:51:25.626] [error]",
      "[2021-08-31 14:03:52.184] [error]",
      "[2021-08-31 14:26:30.955] [error]",
      "[2021-08-31 14:50:29.716] [error]",
      ""
    ]
  }
]

Sry. here is my log!

**Comment by lukehaas** [comment]
Your debug log is not showing full errors. I'm not sure why that would be but it makes diagnosing the issue impossible.

Please contact mail@runjs.app for a refund.
