### ISSUE TITLE
Output to show the line number the evaluation is related to

### ISSUE THREAD

**Issue by gstark** [lukehaas/RunJS#32]
Since the output values do not align with the line that created them, annotating with the line number would be great.

If you *could* align the output with the line number that generated it, that would be amazing. If a second evaluation generated another value it could be placed in columns to the right. 

Similar to the editor in [Bret Victor's Inventing on Principle talk](https://vimeo.com/36579366#t=1045s)

<img width="368" alt="bret victor - inventing on principle on vimeo 2019-01-11 14-53-00" src="https://user-images.githubusercontent.com/2607/51056366-9e8d5280-15b0-11e9-80aa-c05a86433feb.png">

**Comment by lukehaas** [comment]
Aligning the output to the code is definitely something I'm aiming to do at some point.

**Comment by lukehaas** [comment]
@gstark line matching is now supported as an option in RunJS version 1.11.0
