### ISSUE TITLE
How to stop a long-running app?

### ISSUE THREAD

**Issue by joseph4tw** [lukehaas/RunJS#321]
I love the app and I use it to test out several websocket applications I have. For these tests, I like to have autorun turned off as I adjust the code. So I will often use the Run button (or `ctrl+r`) whenever I'm ready to test something.

Since it uses Socket.io, it ends up being a long-running app. What's the best way to stop the app from running?

Currently, what I do is just `ctrl+a, ctrl+/, ctrl+r` which is (select all text, comment out everything, run the code - which is just comments). Is there a better way to stop the app from running without closing the tab/app?

**Comment by lukehaas** [comment]
@joseph4tw thanks for raising this, this is an interesting problem.
In a scenario where you're running some synchronous code then stopping it is just a case of selecting the `Stop` option from the Action menu. However, in your case where your code is async, RunJS doesn't provide a stopping mechanism for that. I'll have a think about how something like this could be provided and how it could be presented in an intuitive way.

**Comment by joseph4tw** [comment]
@lukehaas thank you for the quick response. Sounds good, I look forward to that enhancement 👍 

Again, I love the app - great job!

**Comment by iKlsR** [comment]
I accidentally pasted a 200k line json and I can't stop it, it's trying to log it out, the program also boots up back with the same state each time, is there some directory I can delete this cache?

**Comment by lukehaas** [comment]
@iKlsR use the Clear option in the Edit menu.

**Comment by iKlsR** [comment]
@lukehaas No luck.

**Comment by joseph4tw** [comment]
@iKlsR are you able to get into the File->Preferences modal and turn off Auto-Run?

**Comment by iKlsR** [comment]
No, the preferences window doesn't open, only thing that the app reacts to are the window controls.

**Comment by joseph4tw** [comment]
@iKlsR what OS are you using?

**Comment by iKlsR** [comment]
@joseph4tw On windows, here is the text I pasted https://gist.githubusercontent.com/iKlsR/779f686e5377aabd35c6dadd3ec78302/raw/d62f44473a9e0d9dd6f56f1e944a3c9ad4629983/data.json

**Comment by iKlsR** [comment]
Along with disabling autorun, maybe we could have a timeout option or so, 120s default prob.

**Comment by joseph4tw** [comment]
@iKlsR first, close RunJS if you haven't already.

Then, if you go to `%appdata%\runjs` there is a `config.json` file in there. Under the section called `tabs`, there is an array called `order` that shows all of your tabs. Each of those UUIDs references a `*.js` file of that same name in that `%appdata%\runjs` directory. If you have multiple tabs open, you can change the `activeTabID` to a different UUID and then restart RunJS and it will show a different tab than the one you opened. This should give you the ability to open the preferences and turn off Auto-Run. I was able to try this myself and didn't notice any issues with it.

However, if you only have a single file (tab) and it's the active tab, I'm not sure what you can do besides this (and I haven't tested this, so I don't know if there are any other side effects this would come with - please use with caution):

1. Remove the UUID from the `order` array and the `activeTabID` in the `config.json` file.
2. Delete that `[UUID].js` file from the `%appdata%\runjs` directory.
3. Open RunJS

I don't know if that would cause other issues, though, and I'm not a maintainer of this repo or anything - I'm just making a guess at what you can try.

**Comment by markosmk** [comment]
Hi, I had a similar problem with a function, which after restarting the app was loading and also the window frozen, it did not allow me to enter preferences, I was looking for a function to **RESET** the app but I could not find, I look for the `%appdata%\runjs` in mac in `/Users/*****/Library/Application Support/runjs` to find the js of the tabs

what solved my problem was the `Edit->Clear` mentioned here, even after executing it, it didn't do anything in the app, but after restarting it, the window was empty ready for new tests !! 👍

I just comment on it in case someone on mac has the problem of infinite loop and screen freezing, by the way, incredible app!👏

**Comment by whenmoon** [comment]
I have been using runJS for a good few years now and always end up running into this problem. Love the app but it's a real pain to have to delete all of the associated app files to make it work again.

**Comment by lukehaas** [comment]
Thanks @whenmoon, I'm working on improvements to help solve this problem.
For now, if this happens again go to the Edit menu, click Clear `Edit->Clear` and restart the app. There is no need to delete files.

**Comment by getify** [comment]
I also came here looking for an "asynchronous Stop button" basically. I love having the Stop button for synchronous code, but it'd be great if the "Stop" button was also present (as well as in the action menu) while the asynchronous code is still running, such as timers, etc. Basically, any time the underlying Node process hasn't finished yet (still has open timers/etc), the Stop action/button should be present and basically all it needs to do is just invoke Node again with node code, essentially pretending as if the whole code had been commented out and run that way.

**Comment by lukehaas** [comment]
In the latest version of RunJS (2.4.1) `Stop` has been renamed `Kill` and a new `Stop` has been introduced which can be used to stop async tasks. Both of these are now always available from the `Action` menu.

**Comment by joseph4tw** [comment]
@lukehaas this is a great addition, thank you for getting this feature done!
