### ISSUE TITLE
Menu bar disappeared and there's no documentation

### ISSUE THREAD

**Issue by hank-lenzi** [lukehaas/RunJS#324]
Hello --
I've just toggled the menu bar, somehow, and now I can't get it back.
This is on Linux.
The documentation page has no shortcut for untoggling:

https://runjs.app/docs#shortcuts

Please fix this, I actually paid to the license, and this is annoying.

**Comment by lukehaas** [comment]
@hank-lenzi sorry you're having this issue. 
To toggle the menu bar, press `Alt`. This is not documented because it is an OS-level shortcut.

**Comment by hank-lenzi** [comment]
Hi --
This should be documented. It's absolutely stupid that I have to keep
clicking random key combinations. You can't write documentation for
multiple OSs? A single line? Really?

**Comment by lukehaas** [comment]
@hank-lenzi what I mean is it's not a RunJS shortcut, it's a standard shortcut across multiple apps on your OS. It's similar to copy/paste `ctrl+c`/`ctrl+v` these kinds of shortcuts are not typically documented by each app.
