### ISSUE TITLE
Scripts not compiling

### ISSUE THREAD

**Issue by nicholastillman** [lukehaas/RunJS#326]
Editor is not displaying the output but rather just the code that is typed. I am running Version 2.1.3 (2.1.3) activated.

![Screen Shot 2021-09-09 at 9 39 50 AM](https://user-images.githubusercontent.com/11887250/132706814-2eb94cc1-dfc1-4051-8b5f-0eece2affed5.png)

**Comment by lukehaas** [comment]
It looks like you might have the output set to show transpiled code.

![Screenshot 2021-09-09 at 16 03 18](https://user-images.githubusercontent.com/741344/132711484-5e205bf9-653c-43c1-b260-74eb48979df6.png)

**Comment by nicholastillman** [comment]
@lukehaas Thanks! That fixed it. I appreciate you. Keep up the good work on the app, its been great having an environment for testing without firing up VSCode or a browser.

**Comment by lukehaas** [comment]
Thanks @nicholastillman
