### ISSUE TITLE
Tab name is blank

### ISSUE THREAD

**Issue by aestheticsdata** [lukehaas/RunJS#327]
It would be great to be able to name the tabs. When there's a lot of tab, it's difficult to find the correct one.

**Comment by lukehaas** [comment]
Yep, this feature is currently in development and will be included in the next release.

**Comment by aestheticsdata** [comment]
great ! thanx.

**Comment by lukehaas** [comment]
Tab names can now be set in version 2.2.2 @aestheticsdata
