### ISSUE TITLE
Top-level exceptions not reported, infinite spinner shown instead

### ISSUE THREAD

**Issue by idevelop** [lukehaas/RunJS#329]
Unless I'm misunderstanding how RunJS is expected to work, I'm not seeing exceptions getting reported in the output.

For example, this code `atob("!")` just leads to an infinite loading spinner and no output, which is confusing because the code has finished executing.

If I wrap it that code in a `try/catch` block and log the error, I indeed see "The string to be decoded is not correctly encoded", but I would have expected that to not be a hard requirement of RunJS, and instead the code itself to be wrapped automatically with an exception handler that logs the caught exception.

**Comment by lukehaas** [comment]
@idevelop thanks for raising this. I'll investigate this further.

**Comment by lukehaas** [comment]
@idevelop this is now fixed in version 2.2.2
