### ISSUE TITLE
Doesn't honor TypeScript protected class properties and methods

### ISSUE THREAD

**Issue by EricEisaman** [lukehaas/RunJS#33]
TypeScript protected class properties and methods are not honored.  Here is an example taken directly from the [TypeScript handbook](https://www.typescriptlang.org/docs/handbook/classes.html).  The example should throw an error on the attempted protected constructor call of Person, but does not.
![typescript_protected](https://user-images.githubusercontent.com/6116865/51075069-8cfd8680-1654-11e9-9647-0fb59535f722.png)

**Comment by lukehaas** [comment]
Thanks for raising this. I will look into it.

**Comment by lukehaas** [comment]
@EricEisaman The latest version of RunJS has type checking:

![Screenshot 2021-06-26 at 17 37 39](https://user-images.githubusercontent.com/741344/123519799-53def280-d6a5-11eb-848d-353ffe79d86e.png)
