### ISSUE TITLE
Environment variables not working

### ISSUE THREAD

**Issue by spotcaredev** [lukehaas/RunJS#330]
The "EXAMPLE" variable is showing as undefined. I've attached a screenshow below to show the issue.

![image](https://user-images.githubusercontent.com/89613656/133196081-702bcd21-7b34-4dd7-a863-9a27cc241080.png)

**Comment by spotcaredev** [comment]
The debug log is below:

`[
  {
    "path": "/Users/navtoj/Library/Logs/runjs/main.log",
    "lines": [
      "[2021-09-13 19:40:39.770] [error]",
      "[2021-09-13 20:05:52.558] [error]",
      "[2021-09-13 20:12:52.024] [error] TypeError: Cannot read property 'webContents' of null",
      "    at EventEmitter.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2407:307393)",
      "    at EventEmitter.emit (events.js:327:22)",
      "    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)",
      "[2021-09-13 20:13:18.299] [error] TypeError: Cannot read property 'webContents' of null",
      "    at EventEmitter.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2407:307393)",
      "    at EventEmitter.emit (events.js:327:22)",
      "    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)",
      "[2021-09-13 20:15:00.705] [error] TypeError: Cannot read property 'webContents' of null",
      "    at EventEmitter.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2407:307393)",
      "    at EventEmitter.emit (events.js:327:22)",
      "    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)",
      "[2021-09-13 20:16:32.090] [error] TypeError: Cannot read property 'webContents' of null",
      "    at EventEmitter.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2407:307393)",
      "    at EventEmitter.emit (events.js:327:22)",
      "    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)",
      "[2021-09-13 20:17:08.516] [error] TypeError: Cannot read property 'webContents' of null",
      "    at EventEmitter.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2407:307393)",
      "    at EventEmitter.emit (events.js:327:22)",
      "    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)",
      "[2021-09-13 20:18:03.053] [error] TypeError: Cannot read property 'webContents' of null",
      "    at EventEmitter.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2407:307393)",
      "    at EventEmitter.emit (events.js:327:22)",
      "    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)",
      "[2021-09-13 20:19:28.838] [error] TypeError: Cannot read property 'webContents' of null",
      "    at EventEmitter.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2407:307393)",
      "    at EventEmitter.emit (events.js:327:22)",
      "    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)",
      "[2021-09-13 20:19:37.727] [error] TypeError: Cannot read property 'webContents' of null",
      "    at EventEmitter.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2407:307393)",
      "    at EventEmitter.emit (events.js:327:22)",
      "    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)",
      "[2021-09-13 21:39:39.409] [error] TypeError: Cannot read property 'webContents' of null",
      "    at EventEmitter.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2407:307393)",
      "    at EventEmitter.emit (events.js:327:22)",
      "    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)",
      ""
    ]
  }
]`

**Comment by lukehaas** [comment]
@spotcaredev thanks for providing your error log. I think the issue you're seeing with the missing env vars may be related to an error in your log: `TypeError: Cannot read property 'webContents' of null"` - this error means the app is in a very strange state. Please try re-installing.

**Comment by lukehaas** [comment]
Closing as there's been no further update. 
Issue is not reproducible so I'm guessing it's an isolated incident.
