### ISSUE TITLE
An error occured: request to https://haaslabs-license.herokuapp.com/activate failed, reason: connect ETIMEDOUT 23.22.144.165:443

### ISSUE THREAD

**Issue by tomatobybike** [lukehaas/RunJS#331]
Can I apply for a refund

When I pay, I can't activate
when I input the License Key from email.
--

An error occured: request to https://haaslabs-license.herokuapp.com/activate failed, reason: connect ETIMEDOUT 23.22.144.165:443

**Comment by lukehaas** [comment]
@tomatobybike yes, you likely have a proxy or firewall on your network that is blocking connections to the server.

Please contact mail@runjs.app for a refund.
