### ISSUE TITLE
Problem with Re-Activation

### ISSUE THREAD

**Issue by MrCoding-cl** [lukehaas/RunJS#332]
I deactivated the license on my computer because I was going to format it and install runjs again, but when I apply the license it says that it is already being used but I had already deactivated it.

**Comment by MrCoding-cl** [comment]
![image](https://user-images.githubusercontent.com/49502340/133340958-e77d74f3-f76c-4227-93d1-1f7de84d9e1e.png)

**Comment by MrCoding-cl** [comment]
![image](https://user-images.githubusercontent.com/49502340/133364455-a20f0371-f61b-4f6d-a7a1-994878ef765c.png)

**Comment by lukehaas** [comment]
Handled via 1:1 support.

**Comment by byverdu** [comment]
Hi,

How do we sort the `Two machines have already ...`? I got a new job / laptop and I deleted the app from the old one and I can't activate.

Could you help with this issue? thanks

**Comment by lukehaas** [comment]
@byverdu please contact mail@runjs.app and provide the email address you used to purchase your license. I can deactivate your previous machine then.

**Comment by byverdu** [comment]
Sure, will do. Thanks @lukehaas
