### ISSUE TITLE
Custom run without the button

### ISSUE THREAD

**Issue by iliakan** [lukehaas/RunJS#333]
Hello,

Could you add an option to hide the "Run" button in the "no autorun" mode?

The shortcut is enough.

I mostly record my screencasts with autorun, but then need to disable it, and I'd like to avoid questions like "why does the button show up in this recording, but not in the others?".

**Comment by iliakan** [comment]
Is there any way I could customize this thing? Edit code?

**Comment by lukehaas** [comment]
@iliakan yes, it's an Electron based app so that is possible to do.

**Comment by iliakan** [comment]
I'm very familiar with node.js (since version 0.1), but not with Electron.

Should I unpack asar and then pack it back?

**Comment by iliakan** [comment]
I tried this:
```
root@winner-2 /Applications/RunJS.app/Contents/Resources
npx asar extract app.asar destfolder
(make edits to CSS)
npx asar pack destfolder app.asar
```

But then an attempt to run the app shows:
![image](https://user-images.githubusercontent.com/349336/133456318-c751f3f1-38f2-4774-a7dd-9e68e2416dc5.png)

Maybe there's a checksum mismatch or something.

I tried to run directly:

root@winner-2 /Applications/RunJS.app/Contents/Resources
```
❯ electron app.asar
(node:32020) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:32020) electron: Failed to load URL: http://localhost:3001/index.html with error: ERR_CONNECTION_REFUSED
```

Please give me a hint, how to run the "fixed" app?

**Comment by iliakan** [comment]
Could you maybe email me at iliakan@gmail.com? I bought this app. 

I'm even intend to make it known to others via my free screencast at https://javascript.info. 

Makes me almost a contributor ;)
