### ISSUE TITLE
Cannot minimize with CMD+M

### ISSUE THREAD

**Issue by christopher-caldwell** [lukehaas/RunJS#335]
This is a super small gripe, but is there a reason why the standard keyboard macro doesn't minimize the app? Other Electron apps have this functionality, so I'm not sure if it's a design choice? 

It's mildly frustrating to have to click the minimize button.

**Comment by lukehaas** [comment]
Definitely not a design choice. Looks like this shortcut is conflicting with an editor shortcut. I'll get this resolved in the next release, thanks for raising it.

**Comment by christopher-caldwell** [comment]
Wow, awesome. Thank you!

**Comment by lolbat** [comment]
Related to this, Cmd-H also doesn't work. It opens a replace panel in the current tab instead of hiding the app.

**Comment by lukehaas** [comment]
@lolbat thanks, that will also be resolved in the next release.

**Comment by lukehaas** [comment]
@christopher-caldwell @lolbat - Cmd-M and Cmd-H are now working in the latest version of RunJS - 2.2.2

**Comment by lolbat** [comment]
Awesome. Thanks. What is the issue in Electron that you had to fix? I've seen this same issue in other apps as well.

**Comment by lukehaas** [comment]
The issue here was that the shortcut was being overridden by an editor shortcut so it's unrelated to Electron, Electron supports these shortcuts by default.
