### ISSUE TITLE
React Support

### ISSUE THREAD

**Issue by rmcarias** [lukehaas/RunJS#337]
@lukehaas 

Before buying a full license, I want to know what is the support for React and TS? I need something for quick REACT prototypes. I could not find anything in your docs on how to use it with React.

**Comment by lukehaas** [comment]
@rmcarias this probably isn't an ideal tool for React prototyping as there's no web view.

**Comment by rmcarias** [comment]
Ok thank you. We can close this issue then.

**Comment by lukehaas** [comment]
@rmcarias RunJS now has a web view, so it's now a great solution for React prototyping.
