### ISSUE TITLE
Color plugin

### ISSUE THREAD

**Issue by nkint** [lukehaas/RunJS#339]
Hi!
thanks for the great tool.
I'm working a lot with colors, and I would like to have something like [VSCode color plugin](https://github.com/enyancc/vscode-ext-color-highlight) for runjs.
Are there any way to write plugins? I'm also opened to collaborate to write this.
Thanks in advance. Hope not to bother you too much.

**Comment by lukehaas** [comment]
Thanks @nkint. There are currently no plans to support plugins but it's not ruled out as a far-future possibility.
