### ISSUE TITLE
Outputs different result than other compilators (such as Chrome, NodeJS) in the loop iteration

### ISSUE THREAD

**Issue by firsturdiev** [lukehaas/RunJS#340]
### RunJS
![image](https://user-images.githubusercontent.com/83493139/134538870-2b0be9f5-0ce5-442f-91dc-338487e6f1ab.png)
### NodeJS 
![image](https://user-images.githubusercontent.com/83493139/134538847-5465980b-abe9-4e6b-ad80-d1a20a358973.png)
### Chrome
![image](https://user-images.githubusercontent.com/83493139/134538897-b978c04d-7db6-4ad2-a212-9d9e35e7e0e6.png)

As above images you can see RunJS outputs different (wrong) result than others. RunJS have get wrong in the loop iteration. This is why?

**Comment by lukehaas** [comment]
This is because you have 'Match Lines' turned on.

![Screenshot 2021-09-23 at 17 04 42](https://user-images.githubusercontent.com/741344/134543362-e87e5f3c-dfc6-4b92-be04-3ef726f81ffb.png)

**Comment by firsturdiev** [comment]
Thanks much
