### ISSUE TITLE
Feature Request: Use Vim key-bindings AND ⌘/ shortcut to comment/uncomment

### ISSUE THREAD

**Issue by ekathuria** [lukehaas/RunJS#341]
Maybe [VSCodeVim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) has spoiled me, but I'm used to using vim key-bindings and also using ⌘/ to comment/uncomment, so it seems like a bad user experience in RunJS to have to choose between one or the other (#182).

Any way to get this working?

**Comment by lukehaas** [comment]
Thanks @ekathuria. Unfortunately, this is an upstream issue. It would require the Codemirror Vim keymap to have a comment function added to it: https://github.com/codemirror/CodeMirror

**Comment by bozoputer** [comment]
@lukehaas: i see that the above-referenced functionality works now (in version 2.3.0).

just curious as to whether the upstream issue was resolved (in Codemirror) or was it able to happen via some other means?

either way, very excited it's now part of RunJS 🥳

**Comment by lukehaas** [comment]
Hi @bozoputer, this was resolved as a side-effect of adding a new menu shortcut for commenting. Not related to anything upstream.
