### ISSUE TITLE
Output inconsistent with other environments

### ISSUE THREAD

**Issue by ekathuria** [lukehaas/RunJS#342]
Running code in RunJS gives different results than the same code run in other environments.

![Screen Shot 2021-10-03 at 2 48 33 PM](https://user-images.githubusercontent.com/2061889/135767827-9cb7b8b5-7d4c-496d-ac03-70bc6d5923f6.png)

![Screen Shot 2021-10-03 at 3 06 15 PM](https://user-images.githubusercontent.com/2061889/135767926-d62b3d44-9110-410b-adc2-e02d48a6354c.png)

![Screen Shot 2021-10-03 at 3 07 25 PM](https://user-images.githubusercontent.com/2061889/135767948-7f7d622b-ba9a-423a-8763-269f766d7073.png)

**Comment by lukehaas** [comment]
@ekathuria this is because you have the Match Lines option turned on. 
See here: https://github.com/lukehaas/RunJS/issues/340

**Comment by ekathuria** [comment]
@lukehaas ahhhhh 🤦🏽‍♂️👍🏽
