### ISSUE TITLE
Commenting Shortcut German Keyboard (QWERTZ)

### ISSUE THREAD

**Issue by Jonsibua** [lukehaas/RunJS#343]
Hi,
when I try to use the commenting shortcut CMD + / on my german keyboard is does not work. 
/ is on the same button as 7, and can be used when pressing SHIFT + 7. When I press CMD + SHIFT + 7 the help menu opens.
Is there any way to change the shortcuts? Would be great for example to have the same as in VSC.
Thanks a lot!

**Comment by lukehaas** [comment]
@Jonsibua this is now fixed in the latest version of RunJS - 2.3.0
