### ISSUE TITLE
Objects are not double quoted in the results frame

### ISSUE THREAD

**Issue by lolbat** [lukehaas/RunJS#346]
I have a piece of code that I am using to format some data. It is converting an array of arrays (with string values) into an object.

```
tables.forEach (table => {
  results[table[1]] = {"filepath": table[0], "rendered": false, "html":"", json:"", "template":"#modTable", tableOptions:""};
});
```

The code is coming out with no double quotes on the attributes

```
  'Visual Effects': {
    filepath: 'VisualEffects.json',
    rendered: false,
    html: '',
    json: '',
    template: '#modTable',
    tableOptions: ''
  }
```

It might be related to the formatting code since when I activated the "Prettify" preference it reformatted my source and also stripped out the double quotes in the source.

**Comment by lukehaas** [comment]
What you're creating is a JavaScript object, not a JSON object. JSON is a string format, data is only JSON when it is in a string format

**Comment by lukehaas** [comment]
@lolbat there really isn't an issue here, it's not down to nomenclature. The object you're creating is a JavaScript object so in the output it isn't going to be displayed as JSON unless you parse it into JSON.

**Comment by lukehaas** [comment]
@lolbat here is an article that might help clear up the confusion here: https://medium.com/@alifabdullah/never-confuse-json-and-javascript-object-ever-again-7c32f4c071ad
