### ISSUE TITLE
Electron / SSL Certificate issue

### ISSUE THREAD

**Issue by cmrlp** [lukehaas/RunJS#348]
Https REST requests & promises to certain (very popular) APIs are failing for me due to a `certificate has expired` error. 

Thinking this might be related to [this issue concerning electron's certs](https://github.com/electron/electron/issues/31212) 

Might require an electron update.

**Comment by lukehaas** [comment]
@cmrlp a new version of RunJS has just been released. I'm not able to verify if this fixes the issue as I'm not aware of any of the affected APIs.
