### ISSUE TITLE
[Feature Request | Question] Setting option to display output on first line

### ISSUE THREAD

**Issue by handhikadj** [lukehaas/RunJS#349]
<img width="414" alt="Screen Shot 2021-10-30 at 2 06 48 PM" src="https://user-images.githubusercontent.com/22522638/139523910-754a3d70-095d-40ec-b936-05d08e4e2a94.png">

I want it to display on the first line regardless I log it on a given line.
How do I do it?

**Comment by lukehaas** [comment]
There's already an option for this:

![Screenshot 2021-10-30 at 10 19 24](https://user-images.githubusercontent.com/741344/139527419-d6326f2a-b1cb-425d-870b-c9aee31bc381.png)

**Comment by handhikadj** [comment]
ah thanks
