### ISSUE TITLE
Asking to save before quit.

### ISSUE THREAD

**Issue by RickardRanniger** [lukehaas/RunJS#350]
Add an option that asks to save before closing a tab. It's very easy to close by accident.

**Comment by lukehaas** [comment]
Makes sense. I'll have a think about adding this as an option.

**Comment by flacial** [comment]
Yes please. Just wrote a file and closed it by accident. Tried to hit `Command + Shift + T` to restore it and it seems to not be working...

**Comment by joonseokhu** [comment]
Any updates yet?

**Comment by lukehaas** [comment]
This will be in the next release.

**Comment by lukehaas** [comment]
The latest version of RunJS - 2.4.1 includes an option to ask before closing a tab:
![Screenshot 2022-06-04 at 15 21 28](https://user-images.githubusercontent.com/741344/172006279-a253f520-818d-4dc2-935b-5dd24894f2c2.png)
