### ISSUE TITLE
UI unfriendliness during output

### ISSUE THREAD

**Issue by abdullah4a** [lukehaas/RunJS#354]
Hey there,
By UI unfriendliness , I mean about the output the output is showing where it shouldn't be. 
like No one wants his output down below there, that's not an issue but not it UI friendliness means 'look alike / look and feel'
link for [ Folder link ](https://drive.google.com/drive/folders/10ncn4a4BbCd3i_AHauGzBiJhslp7mBNP?usp=sharing) 
It shouldn't be like I'm printing something at line no 17 and it's at front of it... I think it should be like [this image](https://drive.google.com/file/d/1ucgCTPeC4LUCUbDVbqSEyHoj9qTa8Uc7/view?usp=sharing).

**Comment by lukehaas** [comment]
@abdullah4a turn off the match lines option.

![Screenshot 2021-11-11 at 08 38 04](https://user-images.githubusercontent.com/741344/141265588-851f126d-4511-4b0a-8f20-1ce50d44a7ba.png)

**Comment by lukehaas** [comment]
Another option is to switch to horizontal layout:

![Screenshot 2021-11-11 at 08 39 05](https://user-images.githubusercontent.com/741344/141265749-cbeba487-4ed5-4d83-948c-07fea34db3c4.png)

**Comment by lukehaas** [comment]
@abdullah4a hope that's all clear. Closing this now as what you're asking for is already supported via the above options.
