### ISSUE TITLE
find and replace not working in - Tested in .js file (BUG)

### ISSUE THREAD

**Issue by rehanhanar7** [lukehaas/RunJS#355]

**Comment by lukehaas** [comment]
Thanks for raising this. I'll have it fixed in the next release 👍

**Comment by lukehaas** [comment]
@rehanhanar7 this is resolved in the latest release - version 2.2.2

**Comment by rehanhanar7** [comment]
> @rehanhanar7 this is resolved in the latest release - version 2.2.2

Thank you will check
