### ISSUE TITLE
Ayu theme support

### ISSUE THREAD

**Issue by michaeljaggers** [lukehaas/RunJS#356]
Would be fantastic to have my favorite theme, ayu, available for RunJS!

https://github.com/dempfi/ayu

**Comment by lukehaas** [comment]
Thanks @michaeljaggers. 

If anyone else is also interested in this theme being added, please give it a thumbs up or add a comment.

**Comment by michaeljaggers** [comment]
Is there any way I could help move my own request along?  Via a PR or something similar?  Only a theme, no behavior changes.

**Comment by lukehaas** [comment]
Sorry, this doesn't seem to be garnering much support. To include this theme I would want to see a response similar to the one for the One Dark theme: https://github.com/lukehaas/RunJS/issues/204

RunJS already has quite a lot of themes so I'm reluctant to add more unless there is significant interest.

**Comment by lukehaas** [comment]
@michaeljaggers the Ayu theme is now included in RunJS version 2.6.0.
Thanks again for raising this.

**Comment by michaeljaggers** [comment]
Hey thanks!  I see the light theme is included.  I personally use ayu-dark and there is also ayu-mirage.  Just and fyi.  Appreciate the work!
