### ISSUE TITLE
Arrow function output discrepancy

### ISSUE THREAD

**Issue by swapniljn8** [lukehaas/RunJS#357]
```
color = 'white';

const getColor = () => {
  return this.color;
}

console.log(getColor());
```

The above code when I ran in RunJS is giving me the output of console.log as : 
`white`

whereas when I ran the code in Chrome console I am getting the output of console.log as :
`undefined`

Please explain this discrepancy or let me know if something functional I am missing in here.

**Comment by lukehaas** [comment]
The Chrome console outputs `white` from the console.log and also `undefined` which is the result of the statement.
![Screenshot 2021-11-14 at 11 42 35](https://user-images.githubusercontent.com/741344/141679385-2609a9cd-7f50-4f2a-9b00-62a04c85ed92.png)

RunJS, by default, ignore undefined outputs, if you want to show the undefined output in RunJS, you will need to enable the 'show undefined' options.
![Screenshot 2021-11-14 at 11 43 11](https://user-images.githubusercontent.com/741344/141679400-081baca7-ca45-4543-98b7-4ba8943e9ee1.png)

**Comment by swapniljn8** [comment]
Thanks, @lukehaas for the help, I didn't know about the `undefined` this in the RunJS.
