### ISSUE TITLE
console.log prints in the called line, and not where it should.

### ISSUE THREAD

**Issue by joajimenez** [lukehaas/RunJS#360]
I'm making a simple for loop count down. 

I'm calling three console.logs. In lines 3, 5 and 7. And RunJS is printing this commands out of order, or rather using the line where they are called. Attaching screenshot.

![Screenshot from 2021-11-20 11-00-05](https://user-images.githubusercontent.com/428554/142731161-5af8e2e5-72ce-48db-bca8-06761bf12e4b.png)

**Comment by lukehaas** [comment]
This is because you have Match Lines turned on.

![Screenshot 2021-11-20 at 17 18 37](https://user-images.githubusercontent.com/741344/142735391-2654e733-d0e2-445f-aeca-487edb628d5a.png)

**Comment by joajimenez** [comment]
oh. ty.
