### ISSUE TITLE
Large object or array freezes app

### ISSUE THREAD

**Issue by bell-steven** [lukehaas/RunJS#362]
## Overview

If I paste a large object or array into RunJS, the app freezes completely, and won't work unless I quit the app and restart.

## Steps to reproduce

1. Generate an array of objects
```
Array(500).fill({ name: 'bob', avatar: '' });
```
2. Paste the generated array into RunJS and click 'run'

The app completely freezes.

## Expected behavior
Data should be pasted into RunJS, and I should be able to continue to use RunJS.

**Comment by lukehaas** [comment]
@bell-steven thanks for raising this. This runs without issue for me, can I ask what the specs are on the machine you're using?

**Comment by bell-steven** [comment]
MacBook Pro (15-inch, 2017)
macOS Monterey (been happening before upgrade)
2.8 GHz Quad-Core Intel Core i7
16 GB 2133 MHz LPDDR3
Radeon Pro 555 2 GB

---

My issue is basically the same as in #170 and #232, except that I don't want to have to quit the app.

**Comment by lukehaas** [comment]
@bell-steven I've now run this on a 2019 i5, 13" MacBook and I'm seeing instant results:

<img width="1069" alt="Screenshot 2021-12-04 at 16 43 45" src="https://user-images.githubusercontent.com/741344/144717498-de15ea46-be02-4f23-b747-2a61907655cd.png">

It's really not clear to me why your machine would struggle here, is it possible you have a lot of background processes running?

**Comment by bell-steven** [comment]
@lukehaas Thanks for taking a look. I don't think it is a machine power issue. I am using other applications that can format the same data instantly.

Here is a screen recording reproducing the issue.

https://user-images.githubusercontent.com/13405567/144865853-a739e9ae-de31-42fc-b6ba-4514fb549404.mov

Note:
The issue starts as soon as I remove the quotes from around the array. 
Just noticing (after running this test) that if I disable 'format on run with Prettier', then it works as expected (even if I re-enable 'auto-run code on change').

Hope this helps, let me know if there is anything else I can do to help debug this.

**Comment by lukehaas** [comment]
@bell-steven apologies! I misread the original issue, I missed that you're pasting the generated output into the input.

This all makes a lot more sense now. I already have improvements in the release candidate for dealing with large input so this should be fixed in the next release.

**Comment by bell-steven** [comment]
No worries. 
Thanks for your work on RunJS!

I'll close this after the next release if fixed.

**Comment by lukehaas** [comment]
Yes, it seems it is related to Prettier.

**Comment by lukehaas** [comment]
@bell-steven I've found that the issue relates to a particular Prettier function called `formatWithCursor` it turns out it has known performance issues: https://github.com/prettier/prettier/issues/4801

I've switched to using the standard Prettier format function for now, this performs very well but there may be some scenarios where the cursor ends up in the wrong position.
This update will be in the next release.

**Comment by lukehaas** [comment]
This should now be resolved in the latest version of RunJS - 2.2.2

**Comment by bell-steven** [comment]
Yes! I just tested this to confirm. Thank you @lukehaas.
