### ISSUE TITLE
JavaScript ".toString" doesn't work on Arrays

### ISSUE THREAD

**Issue by AmJustSam** [lukehaas/RunJS#364]
I think there's some issue with the interpreter, it gives an error saying "SyntaxError: Unexpected token" when executing this code.

```
[].toString()
```

**Comment by lukehaas** [comment]
I'm not seeing the issue.

![Screenshot 2021-11-28 at 16 46 50](https://user-images.githubusercontent.com/741344/143777720-022513c1-3379-44b4-a5da-9b01e0fd08d2.png)

Is it possible the error is related to some other code you have in the editor?

**Comment by AmJustSam** [comment]
I'm sorry you're right, as I forgot to put semicolon after "string".

![image](https://user-images.githubusercontent.com/11780229/143794112-dc155d6f-8b91-429f-a971-5b66cfd48ad4.png)
