### ISSUE TITLE
Better output representation

### ISSUE THREAD

**Issue by BunnyFiscuit** [lukehaas/RunJS#365]
This is mainly inspired by [PlayCode - Javascript Playground](https://playcode.io/new/). They have a nice output system that properly represents the `console.log()` output.

RunJS result:
![bild](https://user-images.githubusercontent.com/8507158/143869071-346465eb-afca-4f78-ac7b-e8f900d6d8d6.png)

Expected result:
![bild](https://user-images.githubusercontent.com/8507158/143869005-9110e25d-af40-4187-9784-4a61b1a0304d.png)

**Comment by lukehaas** [comment]
Thanks, I'll look into it.

**Comment by lukehaas** [comment]
@BunnyFiscuit this is now resolved in the latest version of RunJS - 2.2.2
