### ISSUE TITLE
An error occured while installing package:lodash

### ISSUE THREAD

**Issue by tomatobybike** [lukehaas/RunJS#366]
![veAIl6yzgoOW4CR](https://i.loli.net/2021/11/29/veAIl6yzgoOW4CR.jpg)
![uITGO3AyWkX6ZHM](https://i.loli.net/2021/11/29/uITGO3AyWkX6ZHM.jpg)
node v16.13.0

RunJS
版本2.1.3 (2.1.3)

**Comment by tomatobybike** [comment]
[
  {
    "path": "/Users/tomatoboy/Library/Logs/runjs/main.log",
    "lines": [
      "[2021-11-29 22:35:15.721] [error]",
      ""
    ]
  }
]

**Comment by tomatobybike** [comment]
> Please provide your debug log: ![Screenshot 2021-11-29 at 14 48 06](https://user-images.githubusercontent.com/741344/143889099-d8c452ab-7e56-4ad2-83ff-cd2c83d422d7.png)

`1 [2021-11-29 22:35:15.721] [error]`

log just above

**Comment by lukehaas** [comment]
Does this error occur when installing other packages or was it just this one?

**Comment by tomatobybike** [comment]
> Does this error occur when installing other packages or was it just this one?

yes， any packages

i guess maybe because  the GFW

**Comment by lukehaas** [comment]
Maybe it's the GFW. One was to test is to try and install the package manually, to do this, open your terminal app and navigate to this directory:

`~/Library/Application\ Support/runjs`

then run the command `npm i lodash -S`

**Comment by tomatobybike** [comment]
> 
> 
> Maybe it's the GFW. One was to test is to try and install the package manually, to do this, open your terminal app and navigate to this directory:
> 
> 
> 
> `~/Library/Application\ Support/runjs`
> 
> 
> 
> then run the command `npm i lodash -S`

Ok, thanks . Let me try it

**Comment by tomatobybike** [comment]
> ~/Library/Application\ Support/runjs

![ql73zyKG8hpSQ4j](https://i.loli.net/2021/11/29/ql73zyKG8hpSQ4j.jpg)

Bingo! thanks 
I installed success

**Comment by tomatobybike** [comment]
> > Maybe it's the GFW. One was to test is to try and install the package manually, to do this, open your terminal app and navigate to this directory:
> > `~/Library/Application\ Support/runjs`
> > then run the command `npm i lodash -S`
> 
> Ok, thanks . Let me try it

thanks , good night ,
