### ISSUE TITLE
un ordered logs

### ISSUE THREAD

**Issue by mohamed-abdelrhman** [lukehaas/RunJS#368]
I was trying to write an insertion sort example and I noticed the logs within the inner loop get prints incorrectly 

```
const array=[3, 2, 5, 4, 1]
function insertionSort(arr){
  for(let i =1; i<arr.length; i++){
      let numberToInsert= arr[i]
      let j
    for(j=i-1; j>=0&&arr[j]>numberToInsert; j--){
      console.log("before",arr)
      arr[j+1]=arr[j]//keep moving the step forward
      console.log("after",arr)
    }
    arr[j+1]=numberToInsert
  }
  return arr
}
insertionSort(array)
```

the expected log is 
```
before [ 3, 2, 5, 4, 1 ]
after [ 3, 3, 5, 4, 1 ]
before [ 2, 3, 5, 4, 1 ]
after [ 2, 3, 5, 5, 1 ]
before [ 2, 3, 4, 5, 1 ]
after [ 2, 3, 4, 5, 5 ]
before [ 2, 3, 4, 5, 5 ]
after [ 2, 3, 4, 4, 5 ]
before [ 2, 3, 4, 4, 5 ]
after [ 2, 3, 3, 4, 5 ]
before [ 2, 3, 3, 4, 5 ]
after [ 2, 2, 3, 4, 5 ]
```

runjs print
<img width="927" alt="Screen Shot 2021-12-02 at 9 50 52 PM" src="https://user-images.githubusercontent.com/26941732/144493750-e5f8f65f-3f3c-4134-9d10-8786fcf51a56.png">

**Comment by lukehaas** [comment]
@mohamed-abdelrhman turn off the Match Lines option

![Screenshot 2021-12-03 at 11 46 43](https://user-images.githubusercontent.com/741344/144597603-2daeca3e-41b8-4577-bbe9-1b86b06e6b0e.png)

**Comment by mohamed-abdelrhman** [comment]
now it works fine , thanks
