### ISSUE TITLE
TypeScript Error:   Duplicate identifier 'Notification'.

### ISSUE THREAD

**Issue by didaquis** [lukehaas/RunJS#369]
Hi! 

I just noticed that if you type this code, a type error appears with this message.

Code: 
`type Notification = {}`

Error message: 
`Duplicate identifier 'Notification'.`

<img width="617" alt="Captura de pantalla 2021-12-03 a las 21 56 31" src="https://user-images.githubusercontent.com/6883041/144672251-5c3cf7c1-8749-421e-88c5-dd8589127a60.png">

**Comment by lukehaas** [comment]
This is because the `Notification` type already exists as part of the `dom` lib, see here:
https://github.com/microsoft/TypeScript/blob/97a7901f26290a13ea6c3b057c8720c1614cb221/lib/lib.dom.d.ts#L10727

**Comment by didaquis** [comment]
WOW, you are right. This situation also occur on TypeScript Playground. 

Thanks for the information!
