### ISSUE TITLE
Bug in handling async..await

### ISSUE THREAD

**Issue by getify** [lukehaas/runjs#37]
I'm not sure what's going on here... dunno if this is a babel transpilation issue or something about how your code instruments and captures each line of output.

This code is fine:

<img width="709" alt="screen shot 2019-01-14 at 7 27 20 am" src="https://user-images.githubusercontent.com/150330/51115482-0c629580-17ce-11e9-8a0e-5ce762e10b3a.png">

But when I add a single `console.log(..)` statement:

<img width="711" alt="screen shot 2019-01-14 at 7 26 47 am" src="https://user-images.githubusercontent.com/150330/51115517-1f756580-17ce-11e9-8b96-4f3cd88d9e4d.png">

Notice the extra `3` (on line 3 of the output) before it then prints `2` and `3` (in the correct order).

Here's an even more severe illustration of whatever the bug is:

<img width="794" alt="screen shot 2019-01-14 at 7 24 18 am" src="https://user-images.githubusercontent.com/150330/51115585-521f5e00-17ce-11e9-904b-3a1506b87d80.png">

See the extra `2` and `1` being printed, before the `3`, `2`, `1` output in expected order?

**Comment by getify** [comment]
Here's another expression of (possibly) the same bug:

<img width="689" alt="screen shot 2019-01-14 at 8 32 06 am" src="https://user-images.githubusercontent.com/150330/51118849-f1e0ea00-17d6-11e9-8321-fc78afd4b059.png">

`await;` is not allowed, and should throw an exception, but RunJS just silently does nothing.

**Comment by getify** [comment]
Just FYI... I have babel transpilation turned off and this bug is still happening.

**Comment by lukehaas** [comment]
I'm able to replicate the extra console output. Looks like a bug, I will investigate further.

Regarding the `await;` It does complain if I have transpilation turned on but not if it is off. The only difference in the code is that the transpiled version has `"use strict";` prepended to it.

**Comment by getify** [comment]
It's a syntax error regardless of strict mode or not. try it in a chrome console.

**Comment by lukehaas** [comment]
Indeed. I need to investigate further.

**Comment by getify** [comment]
Looks great, thanks!
