### ISSUE TITLE
Compatibility issue with OS running high-contrast color settings

### ISSUE THREAD

**Issue by Lovelaces** [lukehaas/RunJS#372]
Hi! Could there be an option that would override the high contrast color system setting to simply have the original colors be applied on RunJS? The thing is, high contrast colors are very helpful for me in terms of clearly showing particular elements and apps on the Windows operating system, but when it's applied to RunJS, the setting simply makes RunJS have a black background with white lines of codes that have no coloration for differing syntax/highlights, nor any red error markings (seen below):
![Example Screenshot](https://user-images.githubusercontent.com/94806370/146883897-4fd8944e-e518-4a6d-83b9-5fa5f3c83b00.png)

Since Firefox has the option for users to decide whether their high contrast system settings are also applied to its browser,
![image](https://user-images.githubusercontent.com/94806370/146886740-e401161a-381b-48bc-8731-a214eef5a971.png)
I figured that a system's high contrast setting does not apply a high contrast deadlock upon _all_ applications running that OS. With that in mind, I was wondering if you could make RunJS more accessible for people with disabilities by allowing us the option to decide whether or not an operating system's high contrast setting should also be applied to RunJS? I believe having this option on RunJS would make the app more user-friendly because it creates better accessibility for users who have OS(s) with high contrast settings. Anyways, thanks for reading my request and keep up the awesome work!!

**Comment by Lovelaces** [comment]
I didn't mention my specific OS in this first post because I think this issue could be applied to other operating systems. However, I'll mention it in this following comment just in case such information would be useful:
![image](https://user-images.githubusercontent.com/94806370/146887612-b9e47f6b-1d1e-4678-82fd-6f772fc9b33c.png)

**Comment by lukehaas** [comment]
@Lovelaces thanks for raising this. RunJS is built on Electron which doesn't provide a way to override the high contrast mode but it does provide a way to detect when high contrast mode is enabled. This means I may be able to implement some improvements to the way RunJS looks under the high contrast mode.
I'll look into improving this for the next release.

**Comment by lukehaas** [comment]
@Lovelaces I've now looked into this a bit further and unfortunately there doesn't seem to be anything I can do about this. Electron apps have no way, that I can see, of disabling or manipulating the high contrast mode.

**Comment by Lovelaces** [comment]
@lukehaas Instead of disabling/manipulating the high contrast mode, could you simply make the app interpret a system's high contrast colors as [dark/light mode](https://www.electronjs.org/docs/latest/api/native-theme#nativethemeshouldusedarkcolors-readonly) when it detect that high contrast mode is enabled? It would look a lot better compared to only having black and white colors. Or, could you allow us the option to choose between a light or dark theme instead of depending on what the OS's theme setting?

**Comment by lukehaas** [comment]
Sorry, I'm not sure what you mean by this: "make the app interpret a system's high contrast colors as dark/light mode" The high contrast mode is not something that I have control over, it's occurring at the system level.

**Comment by Lovelaces** [comment]
@lukehaas  Thanks for your quick response and apologies for not being more clear. What I meant to ask is can it be possible for you to add the [`forced-color-adjust: none;`](https://github.com/electron/electron/issues/28000#issuecomment-850550710) flag to the body's CSS in order to turn off the forced contrast colors, and instead, use a light or dark theme in its place. Despite being a band-aid solution for this issue, having a dark-theme in-place of a high contrast theme is often requested for Electron apps [[1](https://github.com/mrstallion/fchat-rising/issues/60#issuecomment-1002227457)] [[2](https://github.com/microsoft/vscode/issues/105715#issuecomment-689480749)] [[3](https://github.com/microsoft/AzureStorageExplorer/issues/4636#issuecomment-942639870)] [[4](https://github.com/Eugeny/tabby/issues/4165#issuecomment-877150196)]. It seems that using the flag [should](https://drafts.csswg.org/css-color-adjust-1/#forced-color-adjust-prop) allow you to control how the colors look on RunJS regardless of OS's color settings. Overall, I think the best solution currently is to have a toggle that lets us decide whether to use a light or dark theme when using RunJS. Could you implement this option?

**Comment by lukehaas** [comment]
That's very interesting. I wasn't aware of this `forced-color-adjust` CSS property. I will look into it.

**Comment by lukehaas** [comment]
@Lovelaces the latest version of RunJS - 2.4.1 uses `forced-color-adjust` to preserve syntax highlighting within the editor.
