### ISSUE TITLE
Can't use NPM Packages

### ISSUE THREAD

**Issue by mmazurowski** [lukehaas/RunJS#373]
Hey, 

I've just bought a license for RunJs, yet I am facing issue with Manage NPM Packages functionality. It's a fresh installation on MacOS with latest version and I receive following error:
`An error occurred that prevented NPM from initializing` 

These are logs:
```
[2021-12-21 10:18:54.667] [error]
[2021-12-21 10:21:30.333] [error]
```

Manual initialization allowed me to enter install package window but packages are not being installed. As soon as I click "add" list of packages is being cleared. Removal of package also does not work.

Kind regards,
Marcin

**Comment by lukehaas** [comment]
@mmazurowski thanks for providing the details and logs of the issue.
Unfortunately, I don't know what can cause this issue. The only thing I can offer you is a refund - please contact mail@runjs.app to proceed.

**Comment by mmazurowski** [comment]
Sure, just sent an email
