### ISSUE TITLE
There is no "Check for updates" item in the menu 

### ISSUE THREAD

**Issue by bogdan-13** [lukehaas/RunJS#374]
There is no "Check for updates" item in the menu. Version 2.2.2 from Linux (.deb installer)
<a href="https://ibb.co/JKDhzyW" target="_blank"><img src="https://i.ibb.co/JKDhzyW/2021-12-27-03-35-45.png" alt="2021-12-27-03-35-45" border="0"></a>

**Comment by lukehaas** [comment]
This is now the expected behaviour on Linux due to the lack of support for auto-updates on Linux.
Checking for updates will need to be done through your package manager.

**Comment by bogdan-13** [comment]
This item used to be on the menu and it worked great. Updates through the package manager are possible if there is an application repository. And in this case, you need to manually check on the site or in the repository here on Gitgub

**Comment by lukehaas** [comment]
Thanks for your feedback @bogdan-13. I wasn't sure if this was a useful feature for Linux users but it sounds like it might be.
I'll consider reinstating it in the next release 👍

**Comment by bogdan-13** [comment]
Thank you very much!  :)

**Comment by lukehaas** [comment]
@bogdan-13 this feature is now back for Linux in the latest version of RunJS - 2.3.0
