### ISSUE TITLE
Error when choosing the Check for Updates... Option (when update found)

### ISSUE THREAD

**Issue by alankleindev** [lukehaas/RunJS#376]
I noticed this error on two separate machines, both running the latest version of OS-X.

This dialog pops up when updating. It still seems to update fine.

Monterey 12.1 (Intel and M1)

![image](https://user-images.githubusercontent.com/57042275/148308208-f076fad8-0387-4c26-97ff-1f048b570490.png)

**Comment by lukehaas** [comment]
Thanks @alankleindev in RunJS version 2.2.2 I've made a number of improvements around catching and handling update errors such as this. 
Hopefully you shouldn't see this next time you update but if you do, please let me know.
