### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by OlivierAlbertini** [lukehaas/RunJS#377]
macOS Monterey v12.0.1
Just bought RunJS v2.2.2

I dont have autocompletion at all. 
<img width="822" alt="Capture d’écran, le 2022-01-04 à 20 10 07" src="https://user-images.githubusercontent.com/3801683/148145091-7b602357-45b5-4d07-9a97-609b0a51ca3b.png">

Nothing in application support for logs

here the copy to clipboard : 

```
[
  {
    "path": "/Users/ualbe94/Library/Logs/runjs/main.log",
    "lines": [
      "[2022-01-04 17:28:08.550] [error] [renderer] Error: Request textDocument/completion failed with message: Unrecognized JSON command: completionInfo",
      "    at file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659112",
      "    at file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659412",
      "    at Immediate.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659781)",
      "    at processImmediate (node:internal/timers:464:21)",
      "[2022-01-04 17:46:51.871] [error] [renderer] Error: Request textDocument/completion failed with message: Unrecognized JSON command: completionInfo",
      "    at file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659112",
      "    at file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659412",
      "    at Immediate.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659781)",
      "    at processImmediate (node:internal/timers:464:21)",
      "[2022-01-04 17:46:52.513] [error] [renderer] Error: Request textDocument/completion failed with message: Unrecognized JSON command: completionInfo",
      "    at file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659112",
      "    at file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659412",
      "    at Immediate.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659781)",
      "    at processImmediate (node:internal/timers:464:21)",
      "[2022-01-04 17:46:53.842] [error] [renderer] Error: Request textDocument/completion failed with message: Unrecognized JSON command: completionInfo",
      "    at file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659112",
      "    at file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659412",
      "    at Immediate.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659781)",
      "    at processImmediate (node:internal/timers:464:21)",
      "[2022-01-04 17:46:54.615] [error] [renderer] Error: Request textDocument/completion failed with message: Unrecognized JSON command: completionInfo",
      "    at file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659112",
      "    at file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659412",
      "    at Immediate.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1659781)",
      "    at processImmediate (node:internal/timers:464:21)",
      "[2022-01-04 17:46:54.954] [error] [renderer] Error: Request textDocument/completion failed with message: Unrecognized 
]
```

Following : @OlivierAlbertini please try deleting the directory ~/Library/Application\ Support/runjs and re-installing RunJS. If you're still seeing the issue, please raise a new ticket.

Nothing changed. Also note that I have no runjs folder in `/Library/Application Support` but it was in `/Users/ualbe94/Library/Application Support/runjs`

**Comment by lukehaas** [comment]
Thanks @OlivierAlbertini. Got a few questions for you below that might provide some insight:

Are tooltips/hints failing to display for your code also?
Is autocomplete failing to display every time you open RunJS or just sometimes?
Could you provide an example of the code you're expecting to see autocomplete suggestions for?
Did you install RunJS directly or through Homebrew etc?

**Comment by OlivierAlbertini** [comment]
Are tooltips/hints failing to display for your code also? No hints seems to work when something is red. 
![Capture d’écran, le 2022-01-06 à 13 06 34](https://user-images.githubusercontent.com/3801683/148429771-6013c857-d3ac-446b-be66-af4f7c5a94e8.png) (but it's not true, so it doesn't really work)
Is autocomplete failing to display every time you open RunJS or just sometimes? autocomplete failing every time


https://user-images.githubusercontent.com/3801683/148430008-d3737e0f-8601-4f38-bffc-c25d65b51387.mp4



Could you provide an example of the code you're expecting to see autocomplete suggestions for? `console.` (should see log, error, etc...) or if I create an object like const `obj = { hello: 'world' };` and I enter `obj.` (it should suggest `hello`)
Did you install RunJS directly or through Homebrew etc? I installed RunJS directly

**Comment by OlivierAlbertini** [comment]
![Capture d’écran, le 2022-01-06 à 13 10 37](https://user-images.githubusercontent.com/3801683/148430207-6d02c778-571f-4511-9d96-fb88476487b2.png)

**Comment by lukehaas** [comment]
@OlivierAlbertini thanks for providing those details.
The hint message you're seeing is very odd and could be a clue.
It says it's looking for the module in the path beginning: `/Users/ualbe94/node_modules` but that's wrong, it should be the pointing to the application support folder, this likely means there's been an issues resolving the correct path.

Please try running this code in RunJS and pasting the output here:
`process.argv;`

**Comment by OlivierAlbertini** [comment]
```
[ '/Applications/RunJS.app/Contents/Frameworks/RunJS Helper (Renderer).app/Contents/MacOS/RunJS Helper (Renderer)', '--type=renderer', '--user-data-dir=/Users/ualbe94/Library/Application Support/runjs', '--app-path=/Applications/RunJS.app/Contents/Resources/app.asar', '--no-sandbox', '--no-zygote', '--field-trial-handle=1718379636,9615437587050456079,2902189311337499294,131072', '--disable-features=PlzServiceWorker,SpareRendererForSitePerProcess', '--lang=fr', '--num-raster-threads=4', '--enable-zero-copy', '--enable-gpu-memory-buffer-compositor-resources', '--enable-main-frame-before-activation', '--renderer-client-id=5', '--shared-files', '--userDataPath=/Users/ualbe94/Library/Application Support/runjs', '--tabID=b5d96c68-8a4b-44ba-9031-17c1fbe4e782' ]
```

**Comment by OlivierAlbertini** [comment]
Hey, If someone got into this problem, for me, it was the typescript installed globally, after deleting the package, it worked. Not sure way this app has this behaviour... but doing this solved this issue.

**Comment by lukehaas** [comment]
@OlivierAlbertini thanks for providing that info, any idea what version of TypeScript you had installed globally?
