### ISSUE TITLE
Feature request - Snippets

### ISSUE THREAD

**Issue by shahul01** [lukehaas/RunJS#378]
Example If I type `clg` and press tab, it should type in console.log('').

We should be able to configure the ipt text and output code of the snippet.

[Vscode docs](https://code.visualstudio.com/docs/editor/userdefinedsnippets)

[Snippet-example](https://snippet-generator.app/?description=&tabtrigger=&snippet=console.log%28%27%24%7B1%3Aval%7D%27%24%7B1%3Aval%7D%29%3B&mode=vscode)

**Comment by lukehaas** [comment]
@shahul01 thanks, snippets will be coming to RunSJ in the near future.

**Comment by shahul01** [comment]
that's cool and thanks for making such a cool JS playground with package installation and what not

**Comment by lukehaas** [comment]
@shahul01 snippets are now supported in the latest release.

**Comment by shahul01** [comment]
This is a cool feature, will give it a try, thank you for making it 😁

**Comment by egerardoqd** [comment]
@lukehaas I love this update. Would be possible to specify the cursor position when the snippet is called? something like Gedit have.
