### ISSUE TITLE
Feature: see transpilation code, turn off transpilation

### ISSUE THREAD

**Issue by getify** [lukehaas/runjs#38]
I would, at times, like to see whatever the transpiled version of my code is actually being run by RunJS. This is useful for realizing why a bug may be happening.

I am thinking maybe there could just be an extra popup window or something that I could click a button to see the most recent transpiled code that ran.

Also, it would be **really** helpful if I could, perhaps with a preference option, turn off transpilation, and have RunJS just execute my code as-is. I imagine that maybe you're instrumenting code to get the line-by-line outputs printed, so I know you may actually still need to pass it through some Babel transformer. But you could use some options to Babel which turns off all its normal code transformations, and only do the transformations you need for your line outputs.

**Comment by lukehaas** [comment]
Transpilation is already an option in the preferences.
Showing the transpiled code seems reasonable. I'll add it to my to-do list.

**Comment by getify** [comment]
> Transpilation is already an option in the preferences.

Oh, sorry... missed that, thanks!

**Comment by lukehaas** [comment]
In version 1.3.0 you can now view transpiled code, via the View menu.

![screenshot 2019-02-17 at 16 16 28](https://user-images.githubusercontent.com/741344/52915746-915e3480-32cf-11e9-8f9f-8ecd38d5a858.png)
