### ISSUE TITLE
Toggle comment keyboard shortcut not working on German keyboard

### ISSUE THREAD

**Issue by paulgalow** [lukehaas/RunJS#381]
Hi @lukehaas,

I'm running RunJS on a Mac with a German keyboard and unfortunately cannot use the *Toggle comment* keyboard shortcut, i.e. `Cmd + /`. Here's my guess why this is not working: On a German keyboard, to actually invoke `Cmd + /`, you have to press three keys at the same time: `Cmd + Shift + 7`. This might be quick to fix by [switching to a different type of keyboard event your app is listening to](https://tkainrad.dev/posts/why-keyboard-shortcuts-dont-work-on-non-us-keyboard-layouts-and-how-to-fix-it/).

Issues like that are not uncommon with Non-US keyboard layouts. Perhaps you will find some time to look into this in the future. Please let me know how I can help.

Thanks so much for publishing RunJS. It's a delightful piece of software that I'm regularly drawn to. 🙏

**Comment by paulgalow** [comment]
Just updated my version to v2.3.0. Both related shortcuts, i.e. _Toggle Line Comment_ as well as the new _Toggle Block Comment_ work flawlessly on my German Mac keyboard.

Thanks so much for fixing this so quickly. 🚀

**Comment by lukehaas** [comment]
Excellent, thanks again for raising it.
