### ISSUE TITLE
Feature request -  Output differentiation

### ISSUE THREAD

**Issue by shahul01** [lukehaas/RunJS#384]
Each output type should have unique color.
Eg loop in 1 line should have diff colors ouput than loop or variable output from other line.

**Comment by lukehaas** [comment]
@shahul01 thanks for raising this. I've mocked up an example of what this would look like:
![Screenshot 2022-01-27 at 09 22 46](https://user-images.githubusercontent.com/741344/151329971-388bc5f7-1785-4480-a05a-650c1be7ddf8.png)

Unfortunately, this isn't something I'm keen to implement for the following reasons:
- output would no longer conform to theme colours
- its not clear why the output is multi-coloured
- there's no clear benefit that I can see to differentiating output of different statements via colour

Closing this for those reason but do feel free to raise more feature requests if you have other ideas 👍

**Comment by shahul01** [comment]
Here's the thing, what you implemented is just 1 line, output like 20 lines from each loop and it gets confusing, that's when output differentiation is useful. Yeah I could turn off same line number outputting but I want that too...

**Comment by lukehaas** [comment]
Sure, I recognise the problem, I just don't think this is the right solution.

**Comment by shahul01** [comment]
maybe you could create an option where the users choose for themselves
