### ISSUE TITLE
Feature request - misc

### ISSUE THREAD

**Issue by shahul01** [lukehaas/RunJS#385]
Testing w/ Mocha etc.
And close tab with middle mouse button.
Escape hotkey stops running the code.

**Comment by lukehaas** [comment]
Thanks @shahul01, closing a tab with a middle mouse button is not familiar to me, could you tell me where else you have seen this behaviour?

**Comment by shahul01** [comment]
No, thank you for the awesome software, makes me a better developer!

**Comment by lukehaas** [comment]
@shahul01 the latest release of RunJS now supports closing tabs via the middle mouse button.

Regarding the other suggestions:
- Using the escape key to stop running code - the escape key is used with Vim keys to exit insert mode, so can't be re-used for another purpose.

- Testing with mocha - this may already be possible, though I haven't attempted it.
