### ISSUE TITLE
Saving an existing file opened doesn't save it directly

### ISSUE THREAD

**Issue by kud** [lukehaas/RunJS#387]
Hello,

When you open a .js file from the finder to go to RunJS.app, it opens it well in RunJS.

However, when you do some modifications and you want to save it, it suggests you to save it as "Untitled", not the already existing file.

I'd like to use RunJS as an editor from time to time and I would like to be able to open a js file, edit it, and save it, without searching where the file is on my disk and overrides it.

Thank you 😊

**Comment by lukehaas** [comment]
Thanks for raising this, I'll look into it.

**Comment by kud** [comment]
Thanj you @lukehaas

**Comment by lukehaas** [comment]
@kud this is now fixed in the latest version of RunJS - 2.3.0
