### ISSUE TITLE
(Minor) Object property is highlighted as error in object destructuring statement

### ISSUE THREAD

**Issue by anthonylew1978** [lukehaas/RunJS#388]
Hi Luke,

When referencing a non-existing object prop in object destructuring with default value, the prop in bold is highlighted as an error.
Value is still printed out ok, despite the error alert, just not so convince that this error alert is actually valid.

```
let user = { fname: "Anthony", lname:"Lew" };
let { fname: firstname, **mname**: middlename = "San" } = user; 
console.log(middlename);
// Error on mname: Property 'mname' does not exist on type '{ fname: string; lname: string; }'
```

Thanks in advance.

Anthony

**Comment by lukehaas** [comment]
Thanks @anthonylew1978. The messages in the tooltips are just diagnostics, they don't show JavaScript errors.
If you would prefer not to see this kind of message, you can turn them off in the preferences by unticking type checking:
![Screenshot 2022-01-27 at 08 54 58](https://user-images.githubusercontent.com/741344/151325217-dd1f5bfb-41a3-4db9-8d28-d091ce5972f6.png)
