### ISSUE TITLE
bug/feature req - trees not working

### ISSUE THREAD

**Issue by shahul01** [lukehaas/RunJS#389]
```
/**
 * Definition for a binary tree node.
 * function TreeNode(val, left, right) {
 *     this.val = (val===undefined ? 0 : val)
 *     this.left = (left===undefined ? null : left)
 *     this.right = (right===undefined ? null : right)
 * }
 */
/**
 * @param {TreeNode} root
 * @return {TreeNode}
 */


function invertTree(root) {
  function recursion(node) {
    if (!node) return;
    
    const holder = node.left;
    node.left = node.right;
    node.right = holder;
    
    recursion(node.left);
    recursion(node.right);
    
  }
  
  recursion(root);
  // console.log("root", root);
  
  return root;
  
};


invertTree([2,1,3])
```

This code should return [4,2,7,1,3,6,9]
but instead it returns [ 2, 1, 3, left: undefined, right: undefined ]

maybe it doesnt recognise trees and runs the data as an array

// problem taken from https://leetcode.com/problems/invert-binary-tree/

**Comment by lukehaas** [comment]
@shahul01 this is because you have the Match Lines option turned on:
![Screenshot 2022-01-26 at 08 56 06](https://user-images.githubusercontent.com/741344/151132789-b11acdd5-babd-46ca-8303-711facd451a2.png)

**Comment by lukehaas** [comment]
Closing this as the same result is returned in the Chrome console and Node Repl:
![Screenshot 2022-01-26 at 09 41 42](https://user-images.githubusercontent.com/741344/151139771-aa854e3e-c547-42e4-a51d-884a8e6fdb71.png)

**Comment by shahul01** [comment]
I thought may be you could come up with ways of making it run trees data str in runjs

**Comment by lukehaas** [comment]
@shahul01 I'm not sure what you mean. RunJS runs JavaScript and TypeScript, if the output of your function is not what you expect then there is an issue with that code.

**Comment by shahul01** [comment]
Oh there is no issue with the code, I checked it on leetcode, it return the expected answer, you can try it..

**Comment by lukehaas** [comment]
@shahul01 RunJS is producing the true result of this code, as you can see above, this is the same as the Chrome console and the Node Repl. If you are seeing a different result on leetcode then leetcode is wrong.

**Comment by shahul01** [comment]
yeah I do get that result are the same that's why I am saying there should be an addon which checks for particular data structure in this case which is trees, and run accordingly.

[Here is a python version of the code](https://youtu.be/OnSn2XEQ4MY?t=197)

**Comment by shahul01** [comment]
maybe this has something to do with it
[How to create binary tree testcases](https://support.leetcode.com/hc/en-us/articles/360011883654-What-does-1-null-2-3-mean-in-binary-tree-representation-)

**Comment by lukehaas** [comment]
There is nothing stopping you from writing a binary tree inverter function in JavaScript. Here is an example: https://gist.github.com/kidGodzilla/9a834f6f531a95000587cc9d244f2b1a

**Comment by shahul01** [comment]
ah, got that
