### ISSUE TITLE
vimrc file?

### ISSUE THREAD

**Issue by brentluna** [lukehaas/RunJS#39]
Stoked that this includes vim bindings. Is there anyway to define some vim settings that persist in the app?

**Comment by lukehaas** [comment]
Not currently but I'll keep it in mind for future updates. Thanks.

**Comment by aeschylus** [comment]
Honestly I would use this all the time if I could just match my escape key sequence. Hitting escape isn't natural to me. There's no other setting I would really add in a `.vimrc`.

**Comment by lukehaas** [comment]
Closing this as vim keys are dependent on an upstream dependency and it looks unlikely that `.vimrc` will ever be supported there.
