### ISSUE TITLE
RunJS Keeps Freezing

### ISSUE THREAD

**Issue by bdJohnson72** [lukehaas/RunJS#390]
When I open a file, I get a fat cursor and it is unresponsive to keyboard commands.  I have uninstalled and reinstalled but still get the same issue.  My debug log is belog 

`[
  {
    "path": "C:\\Users\\bjohnson\\AppData\\Roaming\\runjs\\logs\\main.log",
    "lines": [
      "[2021-12-14 15:25:11.842] [error] Error: Invalid argument provided for port\n    at e.exports (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:223:270928)\n    at App.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:223:269195)\n    at App.emit (events.js:327:22)\n    at BrowserWindow.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:1:155362)\n    at BrowserWindow.emit (events.js:315:20)",
      "[2021-12-20 08:22:26.538] [error] Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected +6jDW4bCBNETWSC+IJOJLCklrUqKv3a1B04jtpMs5FZgnbfZ5yHLqDgOvU8mHBf4xzoIu/ZtI9h5s2cXlvMvew==, got og6gKCYkObWsORKoUXNwe8oPSjUJveJdh+vp8I8hY+4yfjukPoaHxk/GYTviF1KjPpB9EOHAccWawLjYnBhHYg==\n    at Object.t.newError (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:1:21698)\n    at y.validate (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:11:60496)\n    at m.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:11:79488)\n    at m.emit (events.js:315:20)\n    at emitCloseNT (internal/streams/destroy.js:87:10)\n    at processTicksAndRejections (internal/process/task_queues.js:79:21)",
      "[2022-01-25 15:46:42.235] [error] Error: Invalid argument provided for port\n    at e.exports (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:223:270928)\n    at App.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:223:269195)\n    at App.emit (events.js:327:22)\n    at BrowserWindow.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:1:155362)\n    at BrowserWindow.emit (events.js:315:20)",
      "[2022-01-26 05:01:52.818] [error] [renderer] Error: ERR_FAILED (-2) loading 'file:///C:/Users/bjohnson/AppData/Local/Programs/runjs/resources/app.asar/blank.html'\n    at rejectAndCleanup (node:electron/js2c/browser_init:161:7486)\n    at Object.stopLoadingListener (node:electron/js2c/browser_init:161:7861)\n    at Object.emit (node:events:394:28)",
      ""
    ]
  }
]`

**Comment by lukehaas** [comment]
Thanks, @bdJohnson72. Are you seeing this with all files or just a particular file?

**Comment by bdJohnson72** [comment]
I am seeing with any tab I have open even if it is an empty tab. 

`[
  {
    "path": "C:\\Users\\bjohnson\\AppData\\Roaming\\runjs\\logs\\main.log",
    "lines": [
      "[2021-12-14 15:25:11.842] [error] Error: Invalid argument provided for port\n    at e.exports (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:223:270928)\n    at App.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:223:269195)\n    at App.emit (events.js:327:22)\n    at BrowserWindow.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:1:155362)\n    at BrowserWindow.emit (events.js:315:20)",
      "[2021-12-20 08:22:26.538] [error] Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected +6jDW4bCBNETWSC+IJOJLCklrUqKv3a1B04jtpMs5FZgnbfZ5yHLqDgOvU8mHBf4xzoIu/ZtI9h5s2cXlvMvew==, got og6gKCYkObWsORKoUXNwe8oPSjUJveJdh+vp8I8hY+4yfjukPoaHxk/GYTviF1KjPpB9EOHAccWawLjYnBhHYg==\n    at Object.t.newError (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:1:21698)\n    at y.validate (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:11:60496)\n    at m.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:11:79488)\n    at m.emit (events.js:315:20)\n    at emitCloseNT (internal/streams/destroy.js:87:10)\n    at processTicksAndRejections (internal/process/task_queues.js:79:21)",
      "[2022-01-25 15:46:42.235] [error] Error: Invalid argument provided for port\n    at e.exports (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:223:270928)\n    at App.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:223:269195)\n    at App.emit (events.js:327:22)\n    at BrowserWindow.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:1:155362)\n    at BrowserWindow.emit (events.js:315:20)",
      "[2022-01-26 05:01:52.818] [error] [renderer] Error: ERR_FAILED (-2) loading 'file:///C:/Users/bjohnson/AppData/Local/Programs/runjs/resources/app.asar/blank.html'\n    at rejectAndCleanup (node:electron/js2c/browser_init:161:7486)\n    at Object.stopLoadingListener (node:electron/js2c/browser_init:161:7861)\n    at Object.emit (node:events:394:28)",
      ""
    ]
  }
]`

**Comment by lukehaas** [comment]
Which version of Windows are you on?

**Comment by bdJohnson72** [comment]
Windows 10 Enterprise

**Comment by lukehaas** [comment]
There are some errors in your debug log that are concerning and I'm not sure what kind of scenarios can cause such errors.

One thing to try could be to delete the user data directory for RunJS, this is located here: `%APPDATA%\runjs` Just make sure to quit RunJS and save anything important first.

**Comment by bdJohnson72** [comment]
I have tried to delete everything and un-install. I did a fresh install this morning and no luck. 

[
  {
    "path": "C:\\Users\\bjohnson\\AppData\\Roaming\\runjs\\logs\\main.log",
    "lines": [
      "[2021-12-14 15:25:11.842] [error] Error: Invalid argument provided for port\n    at e.exports (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:223:270928)\n    at App.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:223:269195)\n    at App.emit (events.js:327:22)\n    at BrowserWindow.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:1:155362)\n    at BrowserWindow.emit (events.js:315:20)",
      "[2021-12-20 08:22:26.538] [error] Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected +6jDW4bCBNETWSC+IJOJLCklrUqKv3a1B04jtpMs5FZgnbfZ5yHLqDgOvU8mHBf4xzoIu/ZtI9h5s2cXlvMvew==, got og6gKCYkObWsORKoUXNwe8oPSjUJveJdh+vp8I8hY+4yfjukPoaHxk/GYTviF1KjPpB9EOHAccWawLjYnBhHYg==\n    at Object.t.newError (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:1:21698)\n    at y.validate (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:11:60496)\n    at m.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:11:79488)\n    at m.emit (events.js:315:20)\n    at emitCloseNT (internal/streams/destroy.js:87:10)\n    at processTicksAndRejections (internal/process/task_queues.js:79:21)",
      "[2022-01-25 15:46:42.235] [error] Error: Invalid argument provided for port\n    at e.exports (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:223:270928)\n    at App.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:223:269195)\n    at App.emit (events.js:327:22)\n    at BrowserWindow.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:1:155362)\n    at BrowserWindow.emit (events.js:315:20)",
      "[2022-01-26 05:01:52.818] [error] [renderer] Error: ERR_FAILED (-2) loading 'file:///C:/Users/bjohnson/AppData/Local/Programs/runjs/resources/app.asar/blank.html'\n    at rejectAndCleanup (node:electron/js2c/browser_init:161:7486)\n    at Object.stopLoadingListener (node:electron/js2c/browser_init:161:7861)\n    at Object.emit (node:events:394:28)",
      "[2022-01-27 16:32:22.399] [error] [renderer] Error: ERR_FAILED (-2) loading 'file:///C:/Users/bjohnson/AppData/Local/Programs/runjs/resources/app.asar/blank.html'\n    at rejectAndCleanup (node:electron/js2c/browser_init:161:7486)\n    at Object.stopLoadingListener (node:electron/js2c/browser_init:161:7861)\n    at Object.emit (node:events:394:28)",
      "[2022-02-01 08:31:00.950] [error] Error: ENOENT: no such file or directory, lstat '--allow-file-access-from-files'\n    at lstatSync (node:fs:1514:3)\n    at Object.e.lstatSync (node:electron/js2c/asar_bundle:5:3740)\n    at listenForFileOpen (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:58928)\n    at App.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:63660)\n    at App.emit (node:events:394:28)",
      "[2022-02-10 05:56:01.351] [error] Error: ENOENT: no such file or directory, lstat '--allow-file-access-from-files'\n    at lstatSync (node:fs:1514:3)\n    at Object.e.lstatSync (node:electron/js2c/asar_bundle:5:3740)\n    at listenForFileOpen (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:58928)\n    at App.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:63660)\n    at App.emit (node:events:394:28)",
      "[2022-02-10 05:58:46.738] [error] Error: ENOENT: no such file or directory, lstat '--allow-file-access-from-files'\n    at lstatSync (node:fs:1514:3)\n    at Object.e.lstatSync (node:electron/js2c/asar_bundle:5:3740)\n    at listenForFileOpen (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:59074)\n    at App.<anonymous> (C:\\Users\\bjohnson\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:63664)\n    at App.emit (node:events:394:28)",
      ""
    ]
  }
]

**Comment by lukehaas** [comment]
The errors seem to suggest that RunJS is not able to access some key resources. Are you aware of any system settings you have enabled that might prevent RunJS from accessing its own resources via the filesystem?

**Comment by bdJohnson72** [comment]
No, it is a work machine. But RunJS did work fine. Then it stopped

**Comment by lukehaas** [comment]
@bdJohnson72 are you still seeing this issue in the latest release - version 2.7.1?
