### ISSUE TITLE
feature request - unsaved tab closing alert prompt

### ISSUE THREAD

**Issue by shahul01** [lukehaas/RunJS#392]
If a tab is unsaved and user wants to close that tab, he should get a prompt.
When saved tab are closed, he can just hit ctrl+shift+tab and the code is back.
however when is done the same mistakenly(especially when there is too many tabs open) for unsaved tab, the codes are gone.

**Comment by lukehaas** [comment]
Thanks, a ticket for this already exists: https://github.com/lukehaas/RunJS/issues/350
