### ISSUE TITLE
[Bug - minor] Console output sometimes appears halfway down the page

### ISSUE THREAD

**Issue by nialldbarber** [lukehaas/RunJS#394]
Firstly, love this app ❤️ 

This is an odd one and perhaps has a simple solution. But ever since installing RunJS on a new Mac, the console output sometimes appears halfway down the page. Not the end of the world, but would be nice if it appeared at the top. 

<img width="1440" alt="console-bug" src="https://user-images.githubusercontent.com/20539827/152576184-bbbd1f29-4949-4d05-8431-735f3bb75a3b.png">

Any information you might need, let me know!

**Comment by lukehaas** [comment]
Thanks @nialldbarber 
This behaviour is due to the Match Lines option:
![Screenshot 2022-02-04 at 17 42 37](https://user-images.githubusercontent.com/741344/152577114-a76d2770-3e24-4a2a-a6f4-428e4b271b5e.png)

You can turn this off in the preferences.

**Comment by nialldbarber** [comment]
Ah! Thanks.
