### ISSUE TITLE
Be able to reopen closed tabs. (CMD+SHIFT+T)

### ISSUE THREAD

**Issue by dotlouis** [lukehaas/RunJS#397]
Hello ! Thanks for RunJS, it's my goto tool for fetching request and drafting JS in general 😃 

My number one problem though is that I often find myself closing a tab by accident (whether by CMD+W or by clicking on x by inadvertence) which is a bummer!

I'd like to be able to reopen my previously closed tabs like on chrome or vscode.

Maybe a quick fix in the meantime would be to ask for confirmation before closing.
see https://github.com/lukehaas/RunJS/issues/350

Thanks !

**Comment by dvnrsn** [comment]
I just lost a decent amount of work because I closed a tab (was trying to close a browser tab). Probably my fault for doing so much unsaved work in RunJS but such a great tool.

**Comment by TreyOverton** [comment]
Have you considered moving the <guid>.js files in AppData/Roaming/runjs/ to the Recycle Bin instead of just permanently deleting them?
