### ISSUE TITLE
Add font ligatures for custom fonts.

### ISSUE THREAD

**Issue by L1ghtingBolt** [lukehaas/RunJS#398]
Hi! This is a quick feature request. I noticed font ligatures are only enabled for default fonts, but for a custom font I added (Cascadia Code PL) There's no font ligatues.
![image](https://user-images.githubusercontent.com/82386159/153581793-53f638b1-03f5-4acd-89ed-682208aac17a.png)

**Comment by L1ghtingBolt** [comment]
> Thanks @L1ghtingBolt. There's currently nothing stopping custom fonts from using ligatures if they support it. Are you certain you have the latest version of Cascadio Code installed?

Yes, I'm certain, I also use it in VSCode without a problem, with every font ligature. I'm using Windows 10.

**Comment by lukehaas** [comment]
Ok, that's odd. Also, the screenshot you've supplied doesn't look like  the Cascadio Code that I have:

![Screenshot 2022-02-11 at 11 43 30](https://user-images.githubusercontent.com/741344/153620588-aa0d984a-f214-49b8-86e1-ffc4bc2c178e.png)

Particularly the parentheses

**Comment by L1ghtingBolt** [comment]
> Ok, that's odd. Also, the screenshot you've supplied doesn't look like the Cascadio Code that I have:
> 
> ![Screenshot 2022-02-11 at 11 43 30](https://user-images.githubusercontent.com/741344/153620588-aa0d984a-f214-49b8-86e1-ffc4bc2c178e.png)
> 
> Particularly the parentheses

I'm using Cascadia Code PL 2111.01
![image](https://user-images.githubusercontent.com/82386159/153626148-4003434d-9d36-495a-8bd2-0285f9c2475a.png)
There's the screenshot using the same theme as yours.

**Comment by lukehaas** [comment]
Yep, sorry for the miss-spelling, it is Cascadia Code I'm looking at.
I've now taken a look at this on Windows and I do now see the issue you're describing. It seems to be a bug on Windows. I'll aim to get this resolved in the next release. Thanks for raising it 👍

**Comment by L1ghtingBolt** [comment]
> Yep, sorry for the miss-spelling, it is Cascadia Code I'm looking at. I've now taken a look at this on Windows and I do now see the issue you're describing. It seems to be a bug on Windows. I'll aim to get this resolved in the next release. Thanks for raising it 👍

I have Linux installed, gonna try and tell you if It works on there! Thanks

**Comment by lukehaas** [comment]
@L1ghtingBolt this is now resolved in the latest version of RunJS - version 2.3.1
