### ISSUE TITLE
[Feature Request] Syntax highlighting for files related to JS.

### ISSUE THREAD

**Issue by L1ghtingBolt** [lukehaas/RunJS#399]
It would be useful if RunJS supported JSON, HTML or CSS synstax highlighting, if possible.

**Comment by lukehaas** [comment]
Sorry, It's not clear to me what the benefit would be of supporting syntax highlighting for languages that RunJS doesn't run.

**Comment by L1ghtingBolt** [comment]
> Sorry, It's not clear to me what the benefit would be of supporting syntax highlighting for languages that RunJS doesn't run.

I'm gonna clarify:
I said JSON for fetching and using data on JS.
And HTML as a new way to make elements for javascript testing.

**Comment by L1ghtingBolt** [comment]
> This is actually a little less clear now. How would adding syntax highlighting for JSON and HTML change anything related to fetching data and making elements?

Sorry. I'm not a native english speaker, I'm Spanish.
I mean syntax highlighting to help creating files with JSON,  to be easier to make a data to fetch. It won't help to fetch data, it will help to make the data.

And with HTML, I meant another different request, maybe in future you could make a way to use the HTML files to make the "virtual" DOM. In future, after adding the syntax highlighting.
Feel free to close the issue if you don't like the idea.

**Comment by lukehaas** [comment]
No problem. I think I see now. There are other tools that provide the functionality you're looking for, such as codesandbox. This is not a direction that RunJS is aiming to go in as I believe it benefits from having a narrow focus. For that reason, I'm closing the ticket but do feel free to raise more if you have other ideas.
