### ISSUE TITLE
Can be converted to VSCode extension?

### ISSUE THREAD

**Issue by eladcandroid** [lukehaas/RunJS#4]

**Comment by lukehaas** [comment]
It's certainly a possibility 👌

**Comment by ozum** [comment]
Also allows to reach broader audiences.

**Comment by dsmr** [comment]
And other IDE's too, like Atom.

**Comment by p12y** [comment]
There is already the Quokka Vscode extension, which does this.

**Comment by lukehaas** [comment]
Best to install Quokka to get this functionality in an IDE.
