### ISSUE TITLE
Autocomplete for JavaScript is lacking

### ISSUE THREAD

**Issue by mattkaye** [lukehaas/RunJS#401]
I'd expect to see the most basic autocomplete prompts like a `for` loop, `Array.reduce` etc... but none of these are being shown to me.

<img width="252" alt="image" src="https://user-images.githubusercontent.com/2780089/153686992-b6544e81-7ce1-4f48-80af-5e8770055997.png">

How can I get this app to autocomplete basic JavaScript syntax?

**Comment by lukehaas** [comment]
Autocomplete shows suggestions based on the letters that you're typing. So, when typing the letters 'for' it will only show you suggestions that start with those letters. It won't show you suggestions that are unrelated to the letters you've typed because you're unlikely to be attempting to write a reduce if you have started typing a for loop.

**Comment by mattkaye** [comment]
@lukehaas not sure if I'm being clear. See the image in my first post. I did start typing `for`, and no for loop came up as a suggestion. Reduce was just another example but here's a screenshot for completeness. 

<img width="255" alt="image" src="https://user-images.githubusercontent.com/2780089/153711474-668580f7-3a30-403c-922c-781d549afb40.png">

Two other things I'm observing. One is that these suggestions seem to all be node functions. Where are the JavaScript functions? 

The second is that the selected autocomplete only completes the word but doesn't expand the whole signature of the method. I'm expecting that something like what [vscode does](https://code.visualstudio.com/docs/editor/intellisense) is possible

**Comment by lukehaas** [comment]
But a reduce would never be written in isolation like that as it exists on the prototype of Array. A reduce will be suggested if it's contextually relevant and you're also beginning to type it.

![Screenshot 2022-02-12 at 15 34 59](https://user-images.githubusercontent.com/741344/153717644-d4bf47c8-a284-4866-a891-12b3dce82089.png)

**Comment by mattkaye** [comment]
Ok I get your point about reduce. But what about a for loop? Why only node functions? Where are the JavaScript functions?

**Comment by lukehaas** [comment]
The autocomplete suggestions aren't just Node, for example:
![Screenshot 2022-02-12 at 16 08 39](https://user-images.githubusercontent.com/741344/153718884-70537748-aa08-4d80-aa42-7c62c3061a91.png)

As far as I'm aware completions for all JavaScript, Browser/DOM, Web APIs are all there.
