### ISSUE TITLE
TypeScript features

### ISSUE THREAD

**Issue by robertherber** [lukehaas/RunJS#403]
I love the TypeScript support - and I'd love it even more if:
- Type information when autocompleting was more exhaustive (similar to VSCode, see screenshot).
- It was possible to see this type info when hovering (similar to VSCode).
- It was possible to trigger the autocompletion with Ctrl-Space (similar to VSCode).
- Cmd-clicking on types to navigate to their definition. I'm using this all the time to "dig deeper" into types. But not quite sure how it'd look in the context of RunJS.

Example of the Type information I'm looking for :)
<img width="471" alt="Screenshot 2022-02-16 at 09 41 54" src="https://user-images.githubusercontent.com/1467411/154227283-8e1a3564-ef72-44d4-b7f0-995e669fb55f.png">

Thanks for a great tool @lukehaas!

**Comment by lukehaas** [comment]
@robertherber thanks for raising this. These are all good suggestions. Will consider them for possible future areas of improvement 👍

**Comment by amjerm** [comment]
It would be nice to support Typescript generics too. As of right now it looks like it tries to interpret the generic declaration as JSX.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/30279337/155375933-cf40c41b-8aad-4d2d-a451-5daab53f6d44.png">

**Comment by besserwisser** [comment]
Honestly I was totally expecting this to be there when I bought the license. Right now I am doing TypeScript Coding challenges and I use online TypeScript Playground for it, because of the missing hover information.
