### ISSUE TITLE
Importing node native module (robotjs 0.6) breaks code execution

### ISSUE THREAD

**Issue by odnodn** [lukehaas/RunJS#405]
I am trying to use the automation library robotjs with runjs. Installing it via npm (**robotjs 0.6**) works, intellisensense/autocomplete is available ☑️ . But I am not able to consume any library functions. As soon as I use any imported method, code execution seems to break (output panel clears) without error message.

Any suggestions for a workaround or how to get the missing error message?

`runJs 2.3.0`
```ts
import {
  keyTap,
  setKeyboardDelay,
  keyToggle,
  typeString,
  getPixelColor,
  getMousePos,
} from 'robotjs';			// -> works  👍 

// import robot from 'robotjs'		-> breaks 👎 
// robot.typeString('');		-> breaks 👎 
// import * as robot from 'robotjs';	-> breaks 👎 
// var robot = require("robotjs");
// var mouse = robot.getMousePos();
var number = 1;


const log = (value: string) => {
  console.log(value);
};

log('logging');
number;
//typeString('a');				-> breaks without any error message 👎 
//getMousePos();				-> breaks without any error message 👎 
//var point = getPixelColor(500,500)

try {
  // typeString('a'); 		-> breaks without any error message 👎 
  // getMousePos();		-> breaks without any error message 👎 
}
catch (error) { console.log(error); }

```

**Comment by lukehaas** [comment]
RunJS doesn't currently support native NPM packages.
It may be possible for you to get this working if you build the package outside of RunJS. Which OS are you on?

**Comment by odnodn** [comment]
windows 11

**Comment by lukehaas** [comment]
On WIndows, if you navigate to `%APPDATA%\runjs` you'll find the `node_modules` directory that RunJS uses, it may be possible to manually build the robotjs package there, using the build instructions: https://www.npmjs.com/package/robotjs#building

**Comment by odnodn** [comment]
Thanks for your feedback, I will try this out this weekend.
