### ISSUE TITLE
Prettier hot key

### ISSUE THREAD

**Issue by Reactiver** [lukehaas/RunJS#406]
Currently, only automatic code formatting is available. It would be great to add the ability to set a hotkey for formatting

**Comment by lukehaas** [comment]
You can format the code via the Action menu or via the `Alt+Shift+F` shortcut.
![Screenshot 2022-02-24 at 08 44 07](https://user-images.githubusercontent.com/741344/155489631-f2119d70-9c85-4d47-9228-520a8907063d.png)

**Comment by lukehaas** [comment]
@Reactiver hope that's all clear. Closing the issue now.
