### ISSUE TITLE
Add over scroll support

### ISSUE THREAD

**Issue by danew** [lukehaas/RunJS#407]
Thanks for creating RunJS!

One feature I would love to have is the ability to over scroll on the editor as I'm currently appending a lot of new lines to achieve the same effect. It's handy when testing long files as I like to be able to see the code I'm writing at the top of the screen.

VS Code has a setting for this feature which is enabled by default called `editor.scrollBeyondLastLine`.

I imagine it would be a good option to have within the General or Advance preferences tab.

Thanks

**Comment by lukehaas** [comment]
Thanks, will consider it.

**Comment by danew** [comment]
CodeMirror actually have a plugin for this already https://codemirror.net/doc/manual.html#addon_scrollpastend

**Comment by lukehaas** [comment]
@danew I've now given this some thought and I'm sorry to say RunJS won't be supporting this. This is because over-scroll would not work well with the line matching feature.
