### ISSUE TITLE
Cannot type in Vim commands

### ISSUE THREAD

**Issue by dvbsknd** [lukehaas/RunJS#411]
Whenever I try to type in a Vim command in `normal` mode, only the first character is briefly displayed in the status/tabline and then it reverts to `normal` mode: https://capture.dropbox.com/STpPBvwbUdZ2ptus.

**Comment by lukehaas** [comment]
Thanks for raising this. I'll get it fixed in the next release. 👍

**Comment by lukehaas** [comment]
@dvbsknd this should now be fixed in the latest release - 3.2.1

**Comment by dvbsknd** [comment]
Thanks @lukehaas, just tested and it's working perfectly.
