### ISSUE TITLE
Feature Request - Auto-run code with custom time/interval in milliseconds

### ISSUE THREAD

**Issue by rafaelmvargas** [lukehaas/RunJS#419]
Awesome product. I love how it auto-runs code on changes. However, I type slightly slower than it executes. Is it possible to add a custom interval in milliseconds so that I may add more time before it auto-runs code? Thanks.

**Comment by lukehaas** [comment]
@rafaelmvargas thanks for raising this. Supporting custom options comes with a lot of overheads, it also adds bloat and complexity to the app. If this was a commonly requested feature, I might consider including it but this has never been requested before, for those reasons I'm not going to be implementing this feature. I'd recommend just turning off auto-run and using the shortcut to run your code instead.
