### ISSUE TITLE
Minor layout annoyance (windows)

### ISSUE THREAD

**Issue by getify** [lukehaas/RunJS#420]
This minor layout annoyance has affected my RunJS installs on windows for a bunch of versions, I just never got around to reporting it until now.

When I only have one tab open, the "new tab" button ("+") overlaps the "Run" button, as shown here:

<img width="512" alt="runjs-layout-issue" src="https://user-images.githubusercontent.com/150330/162579727-ff7ad2bd-7555-4175-ae71-b2984d2002d1.png">

Once I have a second tab open, the "+" button is all the way over to the left next to the tabs themselves... but when just one tab is open -- I guess since the tab sorta stretches the whole width maybe? -- the "+ button is all the way over to the right where the "Run" button sits.

**Comment by getify** [comment]
I should note that if I turn on the "Appearance > Show tab bar for single tab" option it also fixes the layout overlap.

**Comment by lukehaas** [comment]
Thanks for raising this. I'll aim to get it fixed in the next release.
Looks like the overlap also requires the output pane to be hidden?

**Comment by getify** [comment]
I don't have the output pane hidden, I have it at the bottom using "Layout: Horizontal". But yes, if I have change the layout to "Vertical", the "Run" and "+" buttons do not overlap.

**Comment by lukehaas** [comment]
@getify this should now be resolved in the latest version of RunJS - 2.4.1
