### ISSUE TITLE
Incorrect results while creating `Boolean Objects`

### ISSUE THREAD

**Issue by ashutoshbhadoria** [lukehaas/RunJS#424]
I understand using Boolean "fundamental" objects is not a best practice, but I see some inconsistencies in the result.
Creating a new boolean object `const a = new Boolean(false)` results in an object having `true` as the value.

![image](https://user-images.githubusercontent.com/8150094/163670059-9dc7e0d0-c7d4-444e-8c9e-227acaf9abd4.png)

The same scenario on the browser dev tools shows expected results

![image](https://user-images.githubusercontent.com/8150094/163670088-9d16c51e-c691-4301-88e4-e63477715deb.png)

> RunJS Version: 2..3.1.0

**Comment by lukehaas** [comment]
@ashutoshbhadoria thanks for bringing this to my attention. I'll look into it 👍

**Comment by lukehaas** [comment]
@ashutoshbhadoria this is now fixed in version 2.4.1

**Comment by ashutoshbhadoria** [comment]
Thanks @lukehaas , tested on version 2.4.1.
