### ISSUE TITLE
Indented comments

### ISSUE THREAD

**Issue by Siregar** [lukehaas/RunJS#426]
![Bildschirmfoto 2022-04-29 um 09 00 43](https://user-images.githubusercontent.com/31287148/165898422-09f03ca5-863a-4ff8-90fa-cf6b02fc6781.png)

When I create a comment within a function via shortcut, it is not indented. Instead, the comment starts at the very left.

I would expect the comment to start at the current position of the cursor and thus already be indented at the beginning.

Lines that are already indented are commented out correctly, taking the indentation into account.

**Comment by lukehaas** [comment]
Thanks for raising this, I'll look into it 👍

**Comment by lukehaas** [comment]
@Siregar this issue is upstream, the solution is simple and I've raised a PR to fix it here: https://github.com/codemirror/CodeMirror/pull/6918

Whether it will actually get merged in is unknown.
