### ISSUE TITLE
Set home directory doesn't seem to work

### ISSUE THREAD

**Issue by keirk** [lukehaas/RunJS#429]
On MBP M1 (using NVM?) - setting the home directory doesn't seem to allow me to import other files in the same directory.  

![Screenshot 2022-05-06 at 15 28 07](https://user-images.githubusercontent.com/951885/167154961-6f4edbbe-b8fd-4cb9-842c-5d36371790ca.png)

**Comment by lukehaas** [comment]
When a working directory is set, imports will be relative to the directory rather than a file so the import will look like this `import x from 'filename'` instead of `import x from './filename'`

**Comment by keirk** [comment]
Could you write some documentation on how it should work? 

I have a directory, with ./index.js and ./test.js and I've set the working directory on both tabs ... 

./test.js contains - 

`export const test = "Hello, World";`

./index.js contains - 

`import { test } from 'test.js'; 
console.log(test);` 

and I get an error - `SyntaxError: Unexpected token 'export'`

**Comment by lukehaas** [comment]
External files are not transpiled or bundled so your test.js file will need to use commonJS exports.

**Comment by lukehaas** [comment]
Hope this is all clear now. Happy to answer further questions if needed.
