### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by jetuuuu** [lukehaas/RunJS#43]
Hi! Can you build runjs for windows ? I can help you with this issue.

**Comment by lukehaas** [comment]
Aiming to release a Windows version soon.

**Comment by lukehaas** [comment]
A Windows version is now available: https://runjs.dev/

**Comment by alexdevero** [comment]
@lukehaas Thank you. Any chance of adding portable version (Windows)?

**Comment by lukehaas** [comment]
@alexdevero Unfortunately not, purely because portable windows apps can't receive auto-updates.

**Comment by alexdevero** [comment]
@lukehaas Got it. Unrelated question. Will you make the source code available?
