### ISSUE TITLE
UI Theme related problem (Windows)

### ISSUE THREAD

**Issue by gavzla** [lukehaas/RunJS#431]
Doesn't this arrow pointed parts of the app has to be in the same color scheme as the selected theme? For example like vscode does. I will love more the app is they are... thank you!

<img width="1033" alt="Not_like_current_theme" src="https://user-images.githubusercontent.com/11657368/169665393-4db21282-928c-464b-9d7a-4a61ded2dcdc.png">

**Comment by lukehaas** [comment]
The theme just relates to the colours used in the editor and output panes. All other UI colours depend on the system theme, this will be either dark or light.
