### ISSUE TITLE
If an expression returns undefined show it on the right panel, don't display blank

### ISSUE THREAD

**Issue by visaru** [lukehaas/RunJS#432]
```
let myModule = {
  fullname: "Ray",
  getName: function() {
    return this.fullname;
  }
}

myModule.getName();

let someName = myModule.getName;
someName(); // this line returns undefined, but it doesn't show in the screen, it should
let bindedFunc = myModule.getName.bind({fullname:"visar"});
bindedFunc();
```

**Comment by lukehaas** [comment]
You can enable the 'Show Undefined' option in the preferences.

![Screenshot 2022-05-25 at 21 35 07](https://user-images.githubusercontent.com/741344/170362495-644fadb6-2478-486c-890e-6d98270241dd.png)

This is optional as the majority of statements will return undefined and so can create a lot of noise in the output panel.

**Comment by lukehaas** [comment]
@visaru hope that's all clear. Closing this now.
