### ISSUE TITLE
Function declaration error

### ISSUE THREAD

**Issue by EranosyanEduard** [lukehaas/RunJS#434]
RunJS version 2.3.1

I declare baz function then get "SyntaxError: Unexpected token ':'". I have this error because i use type annotation at idx parameter. If i delete this type annotation there no error.

```js
function foo(arg: string) {
  console.log(arg);
}

function bar() {
    function baz(idx: number) {
        console.log(`baz ${idx}`);
    }
    baz(1);
}

foo('foo');
bar();
```

**Comment by lukehaas** [comment]
TypeScript can be toggled regardless of an active license.
However, I've now taken a look and it seems this issue is caused by the 'Runtime values' feature. Please disable runtime values for now and I will aim to get this issue resolved in the next release.

**Comment by EranosyanEduard** [comment]
Ok. Thank you.

**Comment by jojojojojoj5564656465465** [comment]
Hello @lukehaas I am using RUNJS on Fedora linux and TYPESCRIPT IS not working what shall i do please ?

**Comment by jojojojojoj5564656465465** [comment]
![Screenshot_20220710_034114](https://user-images.githubusercontent.com/45184918/178128040-492a1175-c4da-4808-b474-0a295077a713.png)

**Comment by lukehaas** [comment]
@jojojojojoj5564656465465 this appears to be unrelated to the issue that this ticket describes. Please open a new ticket.
