### ISSUE TITLE
console.log displayed out-of-order?

### ISSUE THREAD

**Issue by CarstenNeubert** [lukehaas/RunJS#435]
Hello. While trying to print some debug output using console.log, I noticed that I don't get the output in the expected order.

```javascript
for (let i = 0; i < 10; i++) {
  if (i % 2 === 0) {
    console.log("even", i);
  } else {
    console.log("odd", i);
  }
}
```

Output I'm getting:
```
'even' 0
'even' 2
'odd' 1
'odd' 3
'even' 4
'odd' 5
'even' 6
'odd' 7
'even' 8
'odd' 9
```

Output I expected (and get in node.js directly):
```
'even' 0
'odd' 1
'even' 2
'odd' 3
'even' 4
'odd' 5
'even' 6
'odd' 7
'even' 8
'odd' 9
```

I'd understand a delay, but I'm having trouble figuring out why the order is wrong, especially since just printing the value of `i` directly inside the loop yields the correct order. I sincerely hope this is not just me being incredibly dense today...

**Comment by lukehaas** [comment]
This is because you have Match Lines enabled:

![Screenshot 2022-06-05 at 12 04 34](https://user-images.githubusercontent.com/741344/172047551-6d2d655c-416d-4317-b0b7-9fd19d2ac9e9.png)

**Comment by lukehaas** [comment]
@CarstenNeubert hope that's all clear. Closing this now.

**Comment by CarstenNeubert** [comment]
@lukehaas yep! All good now. Thanks
