### ISSUE TITLE
Can't buy RunJS license

### ISSUE THREAD

**Issue by difilippoagustin** [lukehaas/RunJS#436]
Hi! How are you? I'm trying to get the license from Argentina, but after select my country, I don't see the ZIP Code input and I can't continue.

![image](https://user-images.githubusercontent.com/52054509/172498978-8051d582-adda-4679-abda-4cd098b1fe88.png)

I love your app and I'd appreciate any help. Thanks!

**Comment by lukehaas** [comment]
@difilippoagustin this error means there is an issue with your internet connection. Try connecting to a different network.
If the issue persists try contacting Paddle at assist@paddle.com
