### ISSUE TITLE
No obvious way to hide search bar (find/change)

### ISSUE THREAD

**Issue by mark1bean** [lukehaas/RunJS#438]
After doing a find/change, I can't seem to be able to hide the search bar. See screen shot.

RunJS version: `2.4.1`
MacOS version: `12.4`
Processor: `Apple M1`

<img width="756" alt="Screen Shot 2022-06-12 at 2 20 04 pm" src="https://user-images.githubusercontent.com/29587184/173214319-10011c22-3422-42fe-b094-73444c4f3d89.png">

**Comment by lukehaas** [comment]
Please press the escape key.

**Comment by mark1bean** [comment]
Um. Yes that worked. Thank you. Nothing to see here people.
