### ISSUE TITLE
[feat req] minor - alt + click should add duplicate cursor

### ISSUE THREAD

**Issue by shahul01** [lukehaas/RunJS#439]
Just like ctrl + alt + arrow (on windows) adds multiple cursor, sometimes you would like to specify other locations for cursor.
It would be useful if I could alt + click on other areas to add cursor there.

**Comment by lukehaas** [comment]
@shahul01 this is already supported via cmd+click on mac and ctrl+click on windows and Linux.

**Comment by shahul01** [comment]
Got that, was using alt since vscode works like that.
Thank you.
