### ISSUE TITLE
Feature request - action buttons

### ISSUE THREAD

**Issue by lfrkovic-spaceiq** [lukehaas/RunJS#442]
Could we get the Run/Stop/Kill actions as buttons within the working tab please?

**Comment by lukehaas** [comment]
I'm reluctant to add the stop/kill buttons here as there isn't much space, also these are likely to be used in more edge case scenarios and shouldn't typically be needed. Additionally, there are shortcuts for these that I would have thought would be more natural to use than clicking a button.
