### ISSUE TITLE
Bug[minor] - pasting on newly opened tab gets deleted

### ISSUE THREAD

**Issue by shahul01** [lukehaas/RunJS#443]
When I open a new tab and paste something, it gets deleted and I have to paste again(I don't mind, just a bug I wanted to let you know).

**Comment by lukehaas** [comment]
Thanks @shahul01. 
I'm not able to replicate the issue. 
Are you seeing the pasted content disappear instantly or after a duration?
Are you pasting via a shortcut or via context menu or via the edit menu?

**Comment by shahul01** [comment]
Instantly after pasting, it disappears
I am pasting with ctrl + v shortcut

Oh
btw, I tried to replicate it, but it is not happening even after I restart the program.
but it has happened for a long time since I brought it..

**Comment by lukehaas** [comment]
Ok, if the issue can't be replicated then there is no possibility of fixing it. 
No one else has reported this issue before so it's likely to be an isolated issue.
