### ISSUE TITLE
runJS frozen on mac

### ISSUE THREAD

**Issue by moonkorea00** [lukehaas/RunJS#444]
hey the runJS app froze after i ran a function(assuming it continuously returned an error inside a loop).

i tried removing the app and reinstalled it but when opened, i started with the same code which again led to the app freezing.

wondering if theres a way i can reset the local data(?) since reinstalling it didnt work.

any solutions?

Thanks

**Comment by moonkorea00** [comment]
the actions do not work as well

**Comment by moonkorea00** [comment]
not sure why but changing the theme did the work!

**Comment by lukehaas** [comment]
Thanks @moonkorea00, I'm not sure why changing the theme would affect this either. Could you provide an example of the code that you ran?

**Comment by moonkorea00** [comment]
@lukehaas I ran code to test the Collatz conjecture i'm _assuming_ something went wrong along the way.

**Comment by lukehaas** [comment]
Ok, without the steps to reproduce there's no real way to know what happened here. Closing.
