### ISSUE TITLE
Chai library asserts not working properly

### ISSUE THREAD

**Issue by CharlyTalavera** [lukehaas/RunJS#448]
Hi! First of all, congratz for the playground, i really love it.

It looks like `expect` from `chai` library is not working as expecting when you have 2 consecutives. 

For example, the following code:
```js
import { expect } from "chai";

const foo = () => {
  return true;
}

expect(foo()).to.be.true;
expect(foo()).to.be.false;
```

doesn't show any error in the console. (The second assert should be false, and since it fails, should show an AssertionError in the console). 

But, if you comment the first expect, this way:

```js
import { expect } from "chai";

const foo = () => {
  return true;
}

//expect(foo()).to.be.true;
expect(foo()).to.be.false;
```

It shows the corresponding message "AssertionError: expected true to be false".

Expected behavior: It should show the "AssertionError: expected true to be false" always, since the second expect fails.
The version of RunJS is 2.4.1
OS: Manjaro/Linux

**Comment by lukehaas** [comment]
@CharlyTalavera thanks for raising this. I'll look into it.

**Comment by CharlyTalavera** [comment]
Great! Working like a charm on latest version. Thanks!
