### ISSUE TITLE
This feature requires Node.js to be installed on the host machine

### ISSUE THREAD

**Issue by jamescodesthings** [lukehaas/RunJS#45]
When trying to run `Action` > `Install NPM Packages` I get the error `This feature requires Node.js to be installed on the host machine`.

Node is installed via [nodenv](https://github.com/nodenv/nodenv) which I'm guessing is the problem.

To give you an example of where things end up using nodenv:
![image](https://user-images.githubusercontent.com/32203362/51534769-9a79f400-1e3e-11e9-9e04-c95be2cc8c93.png)

Are node version managers, `nvm` or `nodenv` supported by RunJS? If not, Feature request 😄.

# Workaround
For anyone else who lands here: as a workaround I've set the working directory (`Action` > `Set Working Directory`) and manually install NPM packages on the command line.

**Comment by lukehaas** [comment]
Thanks for raising this.
This means RunJS isn't finding Node in your PATH. 
Are you certain that nodenv is correctly adding the shims to the front of your PATH?

I'm using nvm myself, without issue.

**Comment by jamescodesthings** [comment]
Cheers!

So, `nodenv` was configured fine, but in `zsh` via `Hyper`.

Adding the nodenv path and `nodenv init` to a blank `~/.bash_profile` fixed things.

The main issue there is my shell wasn't set to `zsh`. My bad.

Setting it to `zsh` has lead me to trash my user account on my mac (woo). But, basically happy days, works as expected when node is on the path that `RunJs` is looking at.

**Comment by jamescodesthings** [comment]
So, I'm back up; reinstalling OSX over the original user profile fixed things (woo).

My Mac is connected to an AD domain without privileges to change the default shell. So for me the long term solution is to add the nodenv initialization to the default shell's .bash_profile.

Thanks again for the help, cracking job with Runjs.

**Comment by lukehaas** [comment]
Thanks, glad it worked in the end.

**Comment by Cretezy** [comment]
Having issues on Linux for this. Seems like being able to manually put the `node` path would help with this issue.

I'm currently using `nvm` too, and even if I add the `nvm` script in my `~/.bash_profile`, RunJS can't find my `node` (Bash does though)

**Comment by lukehaas** [comment]
@Cretezy thanks, manually setting the node path could be a could solution for these edge cases. I'll reopen this ticket.

**Comment by awmottaz** [comment]
I'm also having issues with `nvm` on Linux. Is there a confirmed workaround? My setup is zsh with antibody loading the `lukechilds/zsh-nvm` plugin in my `.zshrc`.

**Comment by gastonmorixe** [comment]
Opened from terminal writting 

`$ /Applications/RunJS.app/Contents/MacOS/RunJS`

**Comment by malammar** [comment]
Same issue here with FNM on linux.

**Comment by lukehaas** [comment]
With the release of RunJS 1.10.0 - NPM is now bundled with RunJS so there is no longer a dependence on NPM being available on the host machine. Hope this fixes the issues for you all.
