### ISSUE TITLE
Feature Request - Placeholders for Snippets

### ISSUE THREAD

**Issue by egerardoqd** [lukehaas/RunJS#451]
The snippets really are a great feature. But I wish I could have more control over how they act. Placeholders would be solution ($0, $1, etc). 

**Example:**
`console.log($0)` should position the cursor  inside the parenthesis after the snippet is called.

Here more examples:
[https://help.gnome.org/users/gedit/stable/gedit-plugins-snippets.html.en](https://help.gnome.org/users/gedit/stable/gedit-plugins-snippets.html.en)

**Comment by shahul01** [comment]
Can you also add [tabstops ](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_tabstops) and [placeholders](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_placeholders)


![image](https://user-images.githubusercontent.com/53307156/178067971-118a9f52-6a36-433e-ac15-2f327ae2a407.png)
`

**Comment by lukehaas** [comment]
@egerardoqd the `$0` placeholder is now supported in version 2.7.1
