### ISSUE TITLE
Benchmark like jsbench directly in app

### ISSUE THREAD

**Issue by kazax-inc** [lukehaas/RunJS#452]
Add the ability to run comparative benchmark directly inside runjs like jsbench or other

just a basic drawing to illustrate:

![feature](https://user-images.githubusercontent.com/7147908/177963845-c0fad7df-dc4d-4f46-ba2a-4c186f515e32.png)

**Comment by lukehaas** [comment]
@kazax-inc thanks for raising this. However, this change would require a significant amount of development time to implement and the value it adds is relatively small given that roughly the same insight can be achieved just by adding `console.time` to your code. Closing for this reason.
