### ISSUE TITLE
Trying to add a new packge results in an error

### ISSUE THREAD

**Issue by decpk** [lukehaas/RunJS#453]
I'm trying to install any package but always end up in an error. Is there something that I have to add or change after having a license?

I'm using **Version 2.5.1 (2.5.1)**

<img width="554" alt="image" src="https://user-images.githubusercontent.com/37063026/178061747-6cff5b8e-06bb-4f3c-b477-47b611905541.png">

**Comment by lukehaas** [comment]
Please provide your debug log. You can access this from the `Help` menu:
![Screenshot 2022-07-09 at 11 33 39](https://user-images.githubusercontent.com/741344/178102114-0fe9c5bc-dd3b-4f02-ab46-52b449d7a555.png)

Also, what version of macOS are you using and is the CPU Intel or Apple?

**Comment by decpk** [comment]
Hi @lukehaas I was using Macos Big sur on Intel chip till today. But today I updated it and it is working as expected.
