### ISSUE TITLE
Choose(or update) Node.js version used by Runjs

### ISSUE THREAD

**Issue by johnny4young** [lukehaas/RunJS#456]
I want an option to choose(or install) a specific(18) node.js version in Runjs.

<img width="481" alt="CleanShot 2022-07-18 at 07 36 53@2x" src="https://user-images.githubusercontent.com/112983/179512655-7cd37059-d4d9-405d-be66-6843aa86d08f.png">

**Comment by lukehaas** [comment]
The Node version is inherited from Electron. Unfortunately, this means there is no way to specify a custom Node version.
