### ISSUE TITLE
Feature Request - Allow version specification for npm modules

### ISSUE THREAD

**Issue by 34fame** [lukehaas/RunJS#457]
I would like to specify the version of the npm package I want to install.

My specific use case was attempting to add the `chalk` package to test something; however, the latest version of `chalk` only supports ES Module imports.  Older versions would work fine.

**Comment by lukehaas** [comment]
@34fame you can install specific versions of packages by including the version number like this:

![Screenshot 2022-07-22 at 12 45 50](https://user-images.githubusercontent.com/741344/180432913-27b78ef4-56a0-442a-91f2-e5528df77726.png)

I'm not sure how useful the chalk package will be in RunJS as it's typically used for styling terminal output.

**Comment by lukehaas** [comment]
@34fame hope that's all clear. Closing now.
