### ISSUE TITLE
I accidentally pasted a large SVG symbol into a tab, which then froze all tabs and then made JSRun unusable

### ISSUE THREAD

**Issue by Outcan** [lukehaas/RunJS#458]
I accidentally pasted a large SVG symbol into a tab, which then froze all tabs and then made JSRun unusable.

I managed to gain access by quitting and then re-opening and quickly selecting a new tab but only after quite a few tries.

In the the comment panel : "<" unrecognised character

Suggest preventing the pasting of large clipboard content of the wrong type or more elegant  recovery method.

**Comment by lukehaas** [comment]
Thanks, @Outcan. I will add some guarding against pasting large files in the next release 👍

**Comment by lukehaas** [comment]
The latest release has a guard against pasting large files.
