### ISSUE TITLE
Annoying Time To Renew pop-up

### ISSUE THREAD

**Issue by jcandrade** [lukehaas/RunJS#461]
My license has expired, though every time that I open the application it shows a modal asking me to renew it.
The only 2 options are `Renew` or `Remind me later`. 
It would be cool to have another option for not showing that pop-up anymore.

**Comment by lukehaas** [comment]
I think it would be unwise to have an option to permanently dismiss this message for the following reasons:

When you see this, it means that you are no longer receiving updates which means that your versions of Node, V8, Chromium, Babel, TypeScript etc will not get updated. If this message were dismissed permanently, it would be very easy to forget that you're missing these updates and as a result, you'd soon be running your code against an outdated environment. So I see this as an important reminder.

**Comment by jcandrade** [comment]
I can see that it's important, though I suggest to add something else, like a bar on the bottom that shows that the license is no longer active. Or at least do not display the message more than once per day. I'm only suggesting that because there are days that I reopen RunJS multiple times just for testing something real quick, though when I start typing, I'm automatically interrupted by the message.
I know that the updates are important and I intend to renew my license soon, but just sharing these notes because I also think they are important. 
And thanks for the quick response!

**Comment by lukehaas** [comment]
In the latest release, this message appears as soon as you open the app. Hopefully, this should be more convenient.

**Comment by lukehaas** [comment]
@jcandrade I've made a further update to this in the latest release. 2.7.1.
The message is now displayed inline instead of a popup dialog box.
