### ISSUE TITLE
Error occured while installing packages

### ISSUE THREAD

**Issue by decpk** [lukehaas/RunJS#462]
Hi @lukehaas 

I'm trying to install new packages but everytime it says **An error occured while installing _package_name_**

OS: macos Monteray 12.5
Runjs version: 2.5.1 (2.5.1)

<img width="637" alt="image" src="https://user-images.githubusercontent.com/37063026/183044265-3cee03d5-128d-4635-9901-021a437044d5.png">

**Comment by decpk** [comment]
This is the second time I'm facing this issue. First time there was an update for runjs and I installed it and it remove the error and was able to install. But today again same issue.

**Comment by lukehaas** [comment]
Please provide your debug log. You can access this from the Help menu:
![image](https://user-images.githubusercontent.com/741344/183050129-6dfedfca-511a-42bc-ac07-94ed66c0f43f.png)

Also, what version of macOS are you using and is the CPU Intel or Apple?

**Comment by decpk** [comment]
It is intel based

**DEBUG LOGS**

[
  {
    "path": "/Users/praveenkumar/Library/Logs/runjs/main.log",
    "lines": [
      "[2022-04-11 16:19:51.896] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
      "sysctl: unknown oid 'sysctl.proc_translated'",
      "",
      "[2022-05-01 10:20:50.611] [error] Error: Error: net::ERR_INTERNET_DISCONNECTED",
      "    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7068)",
      "    at SimpleURLLoaderWrapper.emit (node:events:394:28)",
      "[2022-05-01 10:20:50.616] [error] Error: net::ERR_INTERNET_DISCONNECTED",
      "    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7068)",
      "    at SimpleURLLoaderWrapper.emit (node:events:394:28)",
      "[2022-05-30 11:03:46.852] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
      "sysctl: unknown oid 'sysctl.proc_translated'",
      "",
      "[2022-06-30 19:30:31.640] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
      "sysctl: unknown oid 'sysctl.proc_translated'",
      "",
      "[2022-07-05 15:55:24.154] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
      "sysctl: unknown oid 'sysctl.proc_translated'",
      "",
      "[2022-07-11 09:41:39.108] [error]",
      "[2022-07-11 16:58:27.095] [error]",
      "[2022-07-12 12:04:55.456] [error]",
      "[2022-07-18 08:32:02.893] [error]",
      "[2022-07-20 08:07:33.283] [error]",
      "[2022-07-22 21:04:59.840] [error]",
      "[2022-07-29 23:14:22.061] [error]",
      "[2022-07-30 12:35:16.101] [error]",
      ""
    ]
  }
]

**Comment by lukehaas** [comment]
Thanks. From the logs, it looks like there have been some internet connection issues. Is it possible that you were disconnected from the internet at the time that you were attempting to install a package?

**Comment by decpk** [comment]
No @lukehaas That's not a chance. I've tried multiple times with multiple connections

**Comment by lukehaas** [comment]
Ok, you mentioned that installing packages worked and then stopped working; this likely means that the issue is external to RunJS. Are you aware of any changes on your system that coincide with this issue, such as changes to system settings or removing/updating Node?

One thing for you to test is if installing packages through the terminal works for you. 
Try opening your terminal app and executing the following command:
```
cd /Users/praveenkumar/Library/Application Support/runjs && npm install chai -S
```

**Comment by decpk** [comment]
Yes, Installing via npm worked. But still not working from runjs

**Comment by lukehaas** [comment]
If you remove packages via RunJS, does that work?

**Comment by decpk** [comment]
Yes, I'm able to remove packages with **remove** button

**Comment by lukehaas** [comment]
@decpk in version 2.6.0 I've made some improvements to the error logging that may provide some better insights into the issues you're facing.
Could you try updating and then attempting again to install an NPM package? After that, copy your debug log again from the help menu and paste it here, please.

**Comment by decpk** [comment]
After updation, I'm able to install packages.
