### ISSUE TITLE
Question about logged result

### ISSUE THREAD

**Issue by benjaminmodayil** [lukehaas/RunJS#463]
I was trying to run a code exercise from [this week's Bytes newsletter](https://bytes.dev/) and saw a weird result.

```
const arr = [7, 1, 4, 3, 2];

for (const elem of arr) {
  setTimeout(() => console.log(elem), elem);
}
```

<img width="778" alt="CleanShot 2022-08-08 at 16 19 57@2x" src="https://user-images.githubusercontent.com/12306850/183507315-a52f8985-3ef9-4828-a5f2-3e14d0b46349.png">

I assume the 5 is related to the amount of items in the array, **but why is that logging?** If I comment out the for loop it doesn't log.

**Comment by lukehaas** [comment]
The 5 you're seeing is the ID that gets returned from `setTimeout`.

**Comment by benjaminmodayil** [comment]
Whoops. Forgot setTimout returns that… 🤦‍♂️

**Comment by btecu** [comment]
Is it?
```js
const arr = [7, 1, 4, 3, 2];

for (const elem of arr) {
  console.log('Queing element', { elem });
  setTimeout(() => console.log(elem), elem);
}
```

Returns an extra 10. Why would it change?

```js
[7, 1, 4, 3, 2].forEach(x => setTimeout(() => console.log(x), x))
```
Doesn't return a 5.

**Comment by lukehaas** [comment]
@btecu the ID that gets returned by `setTimeout` won't always be the same.
