### ISSUE TITLE
No output shown for a `for...loop`, keeps on loading instead.

### ISSUE THREAD

**Issue by MazahirHaroon** [lukehaas/RunJS#464]
Hi @lukehaas ,the RunJS sometimes does not show an output for even the basic for loop and all we see is a loading icon.
It is quite frequent and it doesn't even get fixed on restarting the same. 
- Video walk-through of the same: https://www.loom.com/share/65633811913a402c8000b22567106898

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/19510062/183627613-799b4ca8-e4d8-4e6d-ac6b-ef47f568a8c7.png">

**Comment by MazahirHaroon** [comment]
@lukehaas 
- As per your response on the email, sharing the system details here:
  - System Details:
    - OS: macOS Monterey (Version 12.5)
    - Chip: Apple M1
- And I did the check the debug log as you had asked,  but when I pasted the same all I got was an empty array.
- More on it and also about a probable cause for this issue is discussed in this video: https://www.loom.com/share/6f03076c12b74cb28b2efa80af14f33a

**Comment by btecu** [comment]
In the video example you had an infinite loop, `i = 0; i < -1; i++`.

**Comment by lukehaas** [comment]
@MazahirHaroon the video shows you're running an infinite loop.

**Comment by MazahirHaroon** [comment]
@lukehaas You are right, the infinite loop that occurs because of the auto run (before I add the increment code in for...loop) was the cause here. 

The kill command helped stop the loading. 

In situations where I need work with such examples I will try switching off the auto-run. Thank you!

**Comment by MazahirHaroon** [comment]
I would suggest though that it would be really good, if there was a better way handle the infinite loop conditions that arise as the auto-run feature was the major selling point for me in RunJS.

**Comment by lukehaas** [comment]
Thanks, @MazahirHaroon you're right, it would be good if there were better ways of handling this. The difficulty is that there isn't much difference between a script that is running infinitely and one that is just long-running. 
If I think of a good solution, I'll be sure to implement it 👍
