### ISSUE TITLE
RunJS freezes when trying to find unique values from array of objects with 20k+ lines

### ISSUE THREAD

**Issue by hakansoylu1** [lukehaas/RunJS#468]
Whenever I input data which is more than 20,000 lines, RunJS will crash and not respond. I must reboot it, quickly close the tab and reboot once more. This does not happen if I restrict the data to 15,000 lines.

Example code block:

`import _ from 'lodash'

const duplicates = [
  {
    colorGroupId: "333",
    styleGroupId: "131555"
  },
  {
    colorGroupId: "333",
    styleGroupId: "131555"
  },
  {
    colorGroupId: "111",
    styleGroupId: "131555"
  },
  {
    colorGroupId: "111",
    styleGroupId: "131555"
  }
];

const uniqueValues = _.uniqWith(duplicates, (a, b) => {
  const areStyleGroupIdsEqual = a.styleGroupId === b.styleGroupId;
  const areColorGroupIdsEqual = a.colorGroupId === b.colorGroupId;
  return areStyleGroupIdsEqual && areColorGroupIdsEqual;
});

console.log(uniqueValues);`

**Comment by lukehaas** [comment]
Thanks, @hakansoylu1. RunJS isn't well suited to dealing with very large amounts of code.
You could try putting your large array in a separate js file and importing it.

**Comment by hakansoylu1** [comment]
Hey Luke, Ah yes that works great. No lag and no crashing with the full data

**Comment by lukehaas** [comment]
Great! Performance is an area of ongoing improvement. Hopefully, with future updates, 20k+ lines will run without issue.
