### ISSUE TITLE
Bug: function declarations are remembered between executions

### ISSUE THREAD

**Issue by getify** [lukehaas/runjs#47]
If you have a function declaration and run the code, then delete the function declaration and re-run the code, the function still executes, because apparently the whole env wasn't actually reset between runs they way I'd expect.

See this:

![bug-1](https://user-images.githubusercontent.com/150330/51719072-af58b200-200d-11e9-89ee-88ee5263cab4.gif)

**Comment by lukehaas** [comment]
I'm not able to recreate this issue myself. Are you certain there were no preliminary steps? 
Could you restart the app and see if it still happens?

**Comment by getify** [comment]
That was from a clean start. Each time I restart RunJS it resets back to fresh, but then always remembers any function declarations between subsequent runs.

**Comment by lukehaas** [comment]
Ok, after playing around a bit more I see that this happens if transpilation is turned off.
I'll get this fixed soon.

**Comment by lukehaas** [comment]
This is now resolved in version 1.2.2
Thanks for raising it.
