### ISSUE TITLE
Buying Options on Website are not responding

### ISSUE THREAD

**Issue by AlvisonHunterArnuero** [lukehaas/RunJS#471]
**Hi there!**
Dunno how many clients have attempted to buy your products, but when one tries to click on any of the save 5%, save 10%, etc buttons, one is not able to get any response from this event.  if one goes to the Buy option on the main menu, this redirects to https://runjs.app/buy, however, when you click on Buy RunJS, this thing does not work either, are you guys aware of this already?

**Comment by Jean-Cairoli** [comment]
Hello Team
I am facing the same issue.

**Comment by lukehaas** [comment]
@AlvisonHunterArnuero @Jean-Cairoli thanks for bringing this to my attention.
I've not been able to replicate the issue. Could you tell me what browser you are using?

**Comment by Jean-Cairoli** [comment]
Hello @lukehaas 

Thanks for your prompt response, in my case I am using Google Chrome & Brave 

If I click on Save 5% button to buy 5 licenses, this error appear in the console 

```
framework-5f4595e5518b5600.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'Checkout')
    at override (buy-7e81ea7a1e3fa5ac.js:1:16128)
    at onClick (buy-7e81ea7a1e3fa5ac.js:1:16169)
    at Object.$e (framework-5f4595e5518b5600.js:1:16252)
    at Ye (framework-5f4595e5518b5600.js:1:16406)
    at framework-5f4595e5518b5600.js:1:34631
    at Nr (framework-5f4595e5518b5600.js:1:34725)
    at Tr (framework-5f4595e5518b5600.js:1:35140)
    at framework-5f4595e5518b5600.js:1:40781
    at Ie (framework-5f4595e5518b5600.js:1:116458)
    at framework-5f4595e5518b5600.js:1:36601
```

**Comment by AlvisonHunterArnuero** [comment]
> @AlvisonHunterArnuero @Jean-Cairoli thanks for bringing this to my attention. I've not been able to replicate the issue. Could you tell me what browser you are using? Also, are you able to observe any errors in the console?

It happens in Chrome, Brave and Safari, Sir!

**Comment by lukehaas** [comment]
@Jean-Cairoli thanks for providing that.
It could be that a script required for the checkout is being blocked. If you take a look in the network tab, do you see any scripts that are failing to load?

**Comment by Jean-Cairoli** [comment]
Yes, the one failing is ` paddle.js`

![image](https://user-images.githubusercontent.com/93626102/186465226-fe711499-cacf-4445-ac31-9a851f7bad30.png)

**Comment by lukehaas** [comment]
Thanks, I've contacted Paddle support and provided them with those details. Hopefully, they should be able to get this resolved soon.

**Comment by Jean-Cairoli** [comment]
Great, thank you

**Comment by AlvisonHunterArnuero** [comment]
> Thanks, I've contacted Paddle support and provided them with those details. Hopefully, they should be able to get this resolved soon.

This is good man, this issue is not good for the business. Thanks for your prompt response!

**Comment by lukehaas** [comment]
@AlvisonHunterArnuero @Jean-Cairoli Paddle are investigating the issue and have asked if you could provide your IP addresses. You can find your IP address on this site: https://whatismyipaddress.com/
If you'd prefer not to post this publicly here, please email mail@runjs.app

**Comment by AlvisonHunterArnuero** [comment]
> @AlvisonHunterArnuero @Jean-Cairoli Paddle are investigating the issue and have asked if you could provide your IP addresses. You can find your IP address on this site: https://whatismyipaddress.com/ If you'd prefer not to post this publicly here, please email [mail@runjs.app](mailto:mail@runjs.app)

**Yikes!** It is not a great idea to share my IP address, even if I am behind a router or modem using a DHCP server and this one changes it dynamically. Sorry, can't really help you with this one, pal,  not even to your email.

**Comment by lukehaas** [comment]
@AlvisonHunterArnuero sure, I understand.

**Comment by lukehaas** [comment]
@AlvisonHunterArnuero @Jean-Cairoli I have now heard back from Paddle. It looks like the issue is due to your location being in one of Paddle's sanctioned countries. You can see this list here: https://www.paddle.com/help/start/intro-to-paddle/which-countries-are-supported-by-paddle

I'm Very sorry to say this means you won't be able to Purchase RunJS while you're connected to a Network in your current location.

**Comment by AlvisonHunterArnuero** [comment]
> @AlvisonHunterArnuero @Jean-Cairoli I have now heard back from Paddle. It looks like the issue is due to your location being in one of Paddle's sanctioned countries. You can see this list here: https://www.paddle.com/help/start/intro-to-paddle/which-countries-are-supported-by-paddle
> 
> I'm Very sorry to say this means you won't be able to Purchase RunJS while you're connected to a Network in your current location.

Oh, ok, we understand. Thanks for checking this out, you're awesome. It would be ideal, mostly for **UX/UI purposes**, to display a toast or change the color or the button or simply show a helper error stating this when a customer from any of these restricted countries tries to buy, so that we are all aware of what is going on. Thanks again for your responses, have a great day!

**Comment by lukehaas** [comment]
@AlvisonHunterArnuero thanks. You're right about the UX, I'll improve the error handling.
