### ISSUE TITLE
ffmpeg.dll was not found

### ISSUE THREAD

**Issue by markthbkk** [lukehaas/RunJS#472]
When trying to install RunJS.exe v2.6.0 the install succeeds but after closing the program the next load produces the message "The code execution cannot proceed because ffmpeg.dll was not found". It is then possible to re-install the same version again but with the same subsequent result. I also experienced this with an auto-upgrade from v.2.3.0. The operating system is Windows 11 (22000.856)

**Comment by lukehaas** [comment]
@markthbkk this error can occur if your system files are corrupt or missing. Try using the Windows built-in SFC tool to scan and repair your system files.
Here are some instructions on how to perform this scan https://appuals.com/how-to-run-sfc-scan-in-windows-10/

**Comment by markthbkk** [comment]
Issue resolved after running sfc /scannow
