### ISSUE TITLE
Unable to fix "cannot use import statement outside a module" error with Babel transpilation

### ISSUE THREAD

**Issue by moracabanas** [lukehaas/RunJS#474]
When I import a module I get `cannot use import statement outside a module` error. 

I tested the [purposed ](https://runjs.app/blog/how-to-solve-cannot-use-import-statement-outside-a-module)Babel configuration and still getting this error

![image](https://user-images.githubusercontent.com/4382333/188792668-d4ee92a5-80a7-4743-9f36-2adedc5593ae.png)

![image](https://user-images.githubusercontent.com/4382333/188792680-fda62b3b-cfae-4e39-923e-e481cd3d2e96.png)

**Comment by lukehaas** [comment]
It looks like the pizzly-js library has import statements in its distributed output js. 
To use this library, you will either need to enable bundling from the advanced preferences or switch to the Node version of the library `pizzly-node`.

**Comment by lukehaas** [comment]
@moracabanas hope that's all good. Closing now.
