### ISSUE TITLE
Unable to close 'find' dialogue

### ISSUE THREAD

**Issue by danirons** [lukehaas/RunJS#476]
Hey firstly amazing app, use it constantly while I'm working.

One issue I keep noticing, is I accidentality open 'find' when I go for a shortcut to format code (my mistake), but when I do, there are a couple of issues:

1 - Unable to close the 'find' search field that opens up.
2 - the search dialogue covers the first line in the editor, which coupled with not being able to discard the search field is where it becomes an irritant.

**Comment by lukehaas** [comment]
@danirons you can close find by pressing the Escape key.
