### ISSUE TITLE
importing from another file is cumbersome

### ISSUE THREAD

**Issue by mmikeyy** [lukehaas/RunJS#478]
In file A, I want to import a function from another file B.

In that other file B, I have

import * as R from 'ramda'

When that file is open, I can test the functions defined within it without problems.

Let's say function "fn" is defined in file B and I want to import if into  file A.

In that file A, I have "import {fn} from 'B'. It's super annoying that 'B' has to be defined with a full path.

But what is even more annoying is that if fn refers to R, the function that was working when tested in the context of the file B no longer works when imported into file A. We get a 'ramda' not defined error.

The only way that I could make this work is by replacing 

import * as R from 'ramda' in file B, with 

import * from R from 'full path to ramda'.

This makes no sense and it that's the way the program is intended to work, it's too much trouble to be of any use.

**Comment by lukehaas** [comment]
Thanks, @mmikeyy. 
In RunJS you can think of each tab as its own sandboxed playground. If you reach a point where you need multiple files, it's best to switch to a more appropriate tool like VS Code. 
However, for the situation you've described there are a couple of things you can do to avoid the issues you're having. Firstly, to avoid long import paths, you can set a working directory and import files relative to it. You can do this from the action menu: `Action -> Set Working Directory`.
Secondly, the error when importing a file that imports ramda, you can avoid this by enabling bundling. This is an option in the advanced preferences.

**Comment by mmikeyy** [comment]
Thanks for the reply. And sorry for the delay. Overwhelmed with tight deadline...

I've been using the tool finally and find it useful to quickly test simple stuff. It just takes some time to get used to some quirks like the ones mentioned. 

Thanks again!

**Comment by lukehaas** [comment]
@mmikeyy thanks. Hopefully, those suggestions were helpful. Closing this ticket now.
