### ISSUE TITLE
Feature Request: Add Windows

### ISSUE THREAD

**Issue by izuchukwu** [lukehaas/RunJS#479]
Hello. Great product. Paying customer. Please add windows. I frequently really want to see playgrounds side by side and group tabs by related work.

Thank you.

**Comment by lukehaas** [comment]
@izuchukwu, thanks for raising this. However, this would be a significant change and require a lot of dev time to implement. 
Also, as this is the only time this has been requested I don't think there is enough demand to justify taking this on. Closing for that reason.
