### ISSUE TITLE
Feature Request: cleaner stack traces

### ISSUE THREAD

**Issue by getify** [lukehaas/runjs#48]
(Note: I have transpilation turned off. I know that feature would mess with this request significantly, and would require sourcemaps support to get right. So I'm only asking for the fix in non-transpiled mode at the moment.)

See this stack trace:

<img width="679" alt="screen shot 2019-02-07 at 12 00 15 pm" src="https://user-images.githubusercontent.com/150330/52432470-14ada800-2ad0-11e9-8597-6f14aa4ab48e.png">

As you can see, most of that stack trace is entirely irrelevant to me, as it's stuff happening inside of RunJS (node, I guess?)... including the promise resolution, etc.

I know that the stack trace is not your doing, but it would be nice if you could edit its output to make it more friendly to read.

For example, this stack trace:

```cmd
SyntaxError: Unexpected token :
    at <anonymous>:5:41
    at <anonymous>:5:65
    at resolve (/Applications/RunJS.app/Contents/Resources/electron.asar/renderer/web-frame-init.js:15:33)
    at new Promise (<anonymous>)
    at EventEmitter.ipcRenderer.on (/Applications/RunJS.app/Contents/Resources/electron.asar/renderer/web-frame-init.js:14:5)
    at EventEmitter.emit (events.js:182:13)
```

could maybe be truncated to just:

```cmd
SyntaxError: Unexpected token :
    at <anonymous>:5:41
    at <anonymous>:5:65
```

or even better, fixing the line/column numbers:

```cmd
SyntaxError: Unexpected token :
    at <anonymous>:1:7
```

I know this is challenging to do, but it would be really nice to have at some point.

**Comment by lukehaas** [comment]
Could you tell me which version of RunJS you're using?
I thought this had been resolved in 1.2.4

**Comment by getify** [comment]
I just made sure I was on 1.2.4, and now I'm seeing something different, which is that if I have a syntax error with only one line of code, no error shows... 

<img width="463" alt="screen shot 2019-02-09 at 2 27 38 pm" src="https://user-images.githubusercontent.com/150330/52525946-16fe3680-2c77-11e9-969e-58fae9d6e7fc.png">

<img width="443" alt="screen shot 2019-02-09 at 2 28 18 pm" src="https://user-images.githubusercontent.com/150330/52525950-1c5b8100-2c77-11e9-8b7a-5d1511568dfa.png">



...but if all I do is add an extra blank line to the program, now exceptions show up:

<img width="639" alt="screen shot 2019-02-09 at 2 29 04 pm" src="https://user-images.githubusercontent.com/150330/52525955-372df580-2c77-11e9-925d-57768695b0e2.png">

<img width="571" alt="screen shot 2019-02-09 at 2 28 36 pm" src="https://user-images.githubusercontent.com/150330/52525952-2a110680-2c77-11e9-9c0c-75cdd44aaf6e.png">


Also, not sure what the "unknown" part in those errors is supposed to indicate. The first snippet should say "ReferenceError" and the second one should say "SyntaxError".

**Comment by lukehaas** [comment]
The missing error for one line of code is a simple, dumb bug in my code. I will have a fix in my next release.
Regarding the error messages, this has been more interesting. These error messages are from Babel and they come out of a caught exception. The original error message in both these cases starts with "SyntaxError:  unknown: " but I was outputting the `message` property of the error which dropped the "SyntaxError: " part.
The "unknown" part is where Babel would typically name the file that the error came from, so not relevant in this case.

In my solution I will be dropping the "unknown: " part of the error and preserving the "SyntaxError: ".
Unfortunately it doesn't look like there's a way for me to differentiate between a "ReferenceError" and a "SyntaxError" here.

**Comment by getify** [comment]
> The original error message in both these cases starts with "SyntaxError...

Hmmm... ok, that seems like a Babylon bug. I will confirm and file that.

**Comment by lukehaas** [comment]
1.3.0 resolves the above issues apart from the Babylon bug.
