### ISSUE TITLE
prompting to save only when necessary

### ISSUE THREAD

**Issue by grok314** [lukehaas/RunJS#480]
Proposing a feature:
When closing a tab, only prompting to save if the document has changed since the last save or hasn't been saved. 

I am aware of the "confirm close" option, but that prompts every time regardless of editing state.

Thanks!

**Comment by lukehaas** [comment]
Thanks, @grok314. My concern with this is that I think promoting to save when the tab contents haven't been saved will essentially cause this prompt to almost always appear when closing a tab as working with files isn't a core part of RunJS.

**Comment by grok314** [comment]
Could you make it an option? Maybe replacing the  current confirm close option?

**Comment by lukehaas** [comment]
The confirm close option is there to help prevent the accidental closing of tabs, regardless of the save status of the tab. Changing it to relate to the save status would reduce its usefulness.

One scenario where it may be good to add a prompt is when closing a tab that has been saved and then updated. So when there are unsaved changes.
