### ISSUE TITLE
es6 class properties support - babel support

### ISSUE THREAD

**Issue by vimalkodoth** [lukehaas/RunJS#481]
Problem:
SyntaxError: Class fields are not enabled. Please add `@babel/plugin-proposal-class-properties` to your configuration.

I'm not able to use class fields in RUNJS. Is there someway I can use the same ?. Good if we have a hook to change babel script.

**Comment by lukehaas** [comment]
`@babel/plugin-proposal-class-properties` is included in `@babel/preset-env` now, so there is no need to add it.

There is a compatibility issue with class properties and decorators: https://babeljs.io/docs/en/babel-plugin-proposal-decorators#note-compatibility-with-babelplugin-proposal-class-properties
Disable the decorators plugin to enable class properties.
