### ISSUE TITLE
Changing tab width has no effect (Windows)

### ISSUE THREAD

**Issue by byronthe123** [lukehaas/RunJS#483]
As stated in the title - changing the tab width does not change the tab spacing, it's stuck on 2 spaces. I am on Windows with version 2.6.0 installed.

**Comment by byronthe123** [comment]
Preferences -> Formatting -> Tab Width
![image](https://user-images.githubusercontent.com/22138809/193883565-9eda57ec-2b41-471b-bde6-cb65073eb60c.png)

**Comment by lukehaas** [comment]
I see. This is because you've toggled "Use Tabs" on. Tab width defines the number of spaces to use when you're not using tabs. Further documentation about this behaviour can be found here: https://prettier.io/docs/en/options.html#tab-width

**Comment by byronthe123** [comment]
I turned off the "Use tabs" option but the default indendation is still 2 spaces. If I run use the Format Code action (from Actions), it correctly formats all the code to the specified tab width, but the default indentation on a new line remains 2 spaces. 

Also, I don't see any option to edit the Prettier settings directly via JSON (like in VSCode) - is this option not available in the Windows version?

**Comment by lukehaas** [comment]
The formatting options are purely for Prettier. They don't influence the editor options. A new option would need to be added in the appearance tab to set the indent units.

There isn't an alternative option to edit the Prettier settings via JSON, the options you see in the formatting tab map 1:1 to the Prettier options

**Comment by byronthe123** [comment]
Understood - thank you for clarifying. I'll close the issue out, but do you have a plan to implement the option to set the indent units in the appearance tab?

**Comment by lukehaas** [comment]
Thanks. Happy to consider implementing the option if you and others want it. 👍

**Comment by byronthe123** [comment]
Thanks and just wanted to say that this is an excellent piece of software - I plan to use it more instead of other web options such as replit because of the faster code execution speed and the fact that there's no initial load time.

**Comment by lukehaas** [comment]
Thanks, really glad to hear that.

**Comment by Tazintosh** [comment]
Hi,
I would definitely love to be able to "always" use tabs (eq. to 4 spaces) when coding.

**Comment by byronthe123** [comment]
@lukehaas - I noticed that the `Tab Width` in the Formatting section is now affecting tab spacing. I'm assuming this feature was implemented in a recent update?

**Comment by lukehaas** [comment]
@byronthe123 yes, sorry this got missed from the release notes.
