### ISSUE TITLE
Feature Request: Option to hide space dots

### ISSUE THREAD

**Issue by kevinlens** [lukehaas/RunJS#484]
when I'm writing code it's very distracting to see the dots to fill in the spaces I've used and would love and option to disable those annoying looking dots. Thanks.
<img width="100" alt="CleanShot 2022-10-07 at 12 16 57@2x" src="https://user-images.githubusercontent.com/48570648/194637712-9137b918-b10d-4d1f-8eb3-b8dd59df62a1.png">

**Comment by lukehaas** [comment]
@kevinlens you're seeing the dots because you've turned on the option to show invisible characters:

![Screenshot 2022-10-08 at 12 37 28](https://user-images.githubusercontent.com/741344/194705566-f8d3d48a-7f07-4e0c-943c-6d81d7d9ecfb.png)

**Comment by lukehaas** [comment]
@kevinlens is this all clear and ok to be closed?
