### ISSUE TITLE
[enhancement] npm package update

### ISSUE THREAD

**Issue by liucaihe** [lukehaas/RunJS#487]
The npm package cannot detect the new version, I hope to increase the detection of the new version and prompt the update

It is hoped that the left and right panes of multiple files can be set uniformly, rather than individually.

When multiple files are opened, drag-and-drop applications appear unfriendly

**Comment by lukehaas** [comment]
"It is hoped that the left and right panes of multiple files can be set uniformly, rather than individually."
I'm not sure what this means and how it relates to NPM packages. @liucaihe please provide more detail.

**Comment by liucaihe** [comment]
> > "It is hoped that the left and right panes of multiple files can be set uniformly, rather than individually."
> 
> I'm not sure what this means and how it relates to NPM packages. @liucaihe please provide more detail.

@lukehaas Thank you for your reply

you can only install and remove here, you can't detect new versions and updates

<img width="569" alt="image" src="https://user-images.githubusercontent.com/1629293/195157899-1ae15e02-435d-45ed-b74f-79751d76dc5a.png">

**Comment by lukehaas** [comment]
@liucaihe ok, and what does this mean:
> When multiple files are opened, drag-and-drop applications appear unfriendly

**Comment by liucaihe** [comment]
> @liucaihe ok, and what does this mean:
> 
> > When multiple files are opened, drag-and-drop applications appear unfriendly

@lukehaas 

The area that can be dragged is very small, limited to a small area in the upper left corner, which is very unfriendly, Other areas cannot be dragged.


![Kapture 2022-10-13 at 16 12 31](https://user-images.githubusercontent.com/1629293/195540972-d8856c84-e9e8-4ea8-82ec-7bc66f980e7c.gif)


> It is hoped that the left and right panes of multiple files can be set uniformly, rather than individually.


![Kapture 2022-10-13 at 15 08 28](https://user-images.githubusercontent.com/1629293/195541179-06713724-a113-4102-bf6a-5a60c9e99a69.gif)

**Comment by lukehaas** [comment]
I see. The gap that is provided here is intended for dragging the window when the tab bar is full.
![Screenshot 2022-10-13 at 09 45 08](https://user-images.githubusercontent.com/741344/195548661-08973a85-30ba-45c9-8aa5-076af7375d57.png)
Are you saying the width of this space should be increased?

**Comment by liucaihe** [comment]
> I see. The gap that is provided here is intended for dragging the window when the tab bar is full. ![Screenshot 2022-10-13 at 09 45 08](https://user-images.githubusercontent.com/741344/195548661-08973a85-30ba-45c9-8aa5-076af7375d57.png) Are you saying the width of this space should be increased?


Yes, currently only this area can be dragged.
It is recommended to expand the space in the "+" area in the upper right corner.

<img width="142" alt="image" src="https://user-images.githubusercontent.com/1629293/195676307-e157c77c-5215-4ea1-846d-6cba304b9f30.png">

**Comment by lukehaas** [comment]
The latest release adds the ability to update outdated NPM packages:
![npm-packages](https://user-images.githubusercontent.com/741344/233046535-1dbe86db-0ae6-4d51-a0d4-a5b34a51b47f.png)
