### ISSUE TITLE
Snippets don't works writting the full alias [v2.7.1][BUG]

### ISSUE THREAD

**Issue by gielfull** [lukehaas/RunJS#488]
Actually on version v2.7.1, when we create a snippet and then try to use it. It only works when you write the alias minus 1 letter.

example:

<img width="155" alt="image" src="https://user-images.githubusercontent.com/1095936/195456783-f92baa2d-7f46-4b40-ac88-731213e0237e.png">

<img width="296" alt="image" src="https://user-images.githubusercontent.com/1095936/195456830-659545ff-513a-4379-873f-84a3616205c4.png">

<img width="185" alt="image" src="https://user-images.githubusercontent.com/1095936/195456854-49d9632b-e120-4c68-90d8-e7ad3576a7dc.png">

**Comment by lukehaas** [comment]
Thanks, @gielfull. I'll look into it 👍
