### ISSUE TITLE
Feature Request: Case insensitive autocomplete suggestions

### ISSUE THREAD

**Issue by jurajkapsz** [lukehaas/RunJS#489]
RunJS `v2.7.1`

When I type JS expressions, I'd welcome to have autocomplete suggestions to be case insensitive, as they are in other text editors like vscode, sublime etc.

As of now, in RunJS, I have to match the capital letters to get certain suggestions. Eg. `document.getele` breaks off from eg a `.getElementById` suggestion etc.

**Comment by jurajkapsz** [comment]
Sounds great! Thanks very much @lukehaas !

**Comment by xfrancool** [comment]
Hola! Si, a mi en lo personal no me esta funcionando el autocompletado a pesar de que en la preferencia tenga marcada esa casilla.  Si reinstalo la aplicación se me solucionaría el error?

**Comment by lukehaas** [comment]
@xfrancool autocompletar no funciona es un problema no relacionado con esto. Eche un vistazo a este ticket: https://github.com/lukehaas/RunJS/issues/492

**Comment by lukehaas** [comment]
This is now implemented in version 2.7.4
