### ISSUE TITLE
I'm unable to quit the application on MacOS

### ISSUE THREAD

**Issue by jkohlin** [lukehaas/runjs#49]
This is hard to reproduce, but it's often hard to quit the app on MacOS. After having it open for a while it has to be force quitted.

**Comment by lukehaas** [comment]
Apologies for this. This issue was introduced in version 1.2.3 in a bug fix that prevented user code from triggering a reload.
It was resolved in version 1.2.4.

**Comment by jkohlin** [comment]
Oh, i didnt know there was a new update. 
Perhaps  The app does not suggest the user to update whenever there is a new version available?

**Comment by lukehaas** [comment]
If there's a new version it will give you a notification when you open the app.

**Comment by Magistern** [comment]
Ok, good. Well I do have  v1.2.4 Is it silently installed? 
Anyway, If it happens again, I'll return to this thread (unless you close it of course )

**Comment by lukehaas** [comment]
Closing this now as most people have updated from 1.2.3
