### ISSUE TITLE
Non-existing file history

### ISSUE THREAD

**Issue by jurajkapsz** [lukehaas/RunJS#490]
## Version
RunJS: `v2.7.1`
OS: Linux

## Issue
When I open an existing file and hit `Undo` or `Ctrl+Z`, the file's whole content gets removed or deleted. 
`Redo` brings it back, but it's scary :)

This also happens for reopened remembered file tabs, when I launch RunJS.

## Expected
The `Undo` would work only up to the changes I made on the file myself. 
Reading the file into the app wouldn't be part of history.

**Comment by lukehaas** [comment]
Thanks again @jurajkapsz. I'll resolve this in the next release 👍

**Comment by jurajkapsz** [comment]
Thank you @lukehaas !

**Comment by lukehaas** [comment]
@jurajkapsz this is now resolved in the latest release - 2.7.4
