### ISSUE TITLE
the autocomplete function does not work

### ISSUE THREAD

**Issue by sergal-developer** [lukehaas/RunJS#492]
It may be a configuration of my environment but I have 2 computers with the license activated and it does not autocomplete the functions

![image](https://user-images.githubusercontent.com/13501275/195927734-e67dedcb-25e9-4e3e-8e60-d15f74d2ab3b.png)

![image](https://user-images.githubusercontent.com/13501275/195927251-3ee6553d-18b0-4522-bfa0-3d31e1883da8.png)

**Comment by lukehaas** [comment]
@sergal-developer please provide your debug log.
![Screenshot 2022-10-15 at 14 36 25](https://user-images.githubusercontent.com/741344/195989349-a00b7227-11aa-40fd-8ac5-76ea91ba2839.png)

**Comment by sergal-developer** [comment]
the function only return the next code:

{
  "version": "2.7.1",
  "platform": "win32",
  "arch": "x64",
  "logs": []
}

**Comment by lukehaas** [comment]
@sergal-developer thanks. 
Are you seeing hover info when you hover over your code?
Could you check what version of Node is installer by running `node -v` in your terminal?

**Comment by sergal-developer** [comment]
Uninstall and reinstall RunJs and activate it again and that is the log that appears

{
  "version": "2.7.1",
  "platform": "win32",
  "arch": "x64",
  "logs": [
    {
      "path": "C:\\Users\\sergio.gallegos\\AppData\\Roaming\\runjs\\logs\\main.log",
      "lines": [
        "[2022-10-19 22:10:28.502] [error] [renderer] Error: ERR_ABORTED (-3) loading 'data:text/html;base64,CiAgICA8aHRtbD4KICAgICAgPGhlYWQ+CiAgICAgICAgPHRpdGxlPlByZXZpZXc8L3RpdGxlPgogICAgICA8L2hlYWQ+CiAgICA8L2h0bWw+CiAg'\n    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)\n    at EventEmitter.navigationListener (node:electron/js2c/browser_init:161:7953)\n    at EventEmitter.emit (node:events:526:28)",
        ""
      ]
    }
  ]
}


My node development environment is
![image](https://user-images.githubusercontent.com/13501275/197025930-768cfa4a-cdde-42bd-9ff6-f1b4a103a778.png)
![image](https://user-images.githubusercontent.com/13501275/197025949-3272e30f-032d-42f1-9146-c1b0fc7c4c1f.png)

**Comment by lukehaas** [comment]
Thanks, @sergal-developer. Your Node version is a few years old, would it be ok for you to update this to at least version 14?

**Comment by sergal-developer** [comment]
Ok, I updated and it works correctly, thanks for the answer
