### ISSUE TITLE
Some newer methods cause a warning, but still work

### ISSUE THREAD

**Issue by OussamaRomdhane** [lukehaas/RunJS#493]
This happened to me with `flatMap` and `flat`, I think it's a tsconfig thing most probably 

<img width="1280" alt="Screenshot 2022-10-19 at 08 26 42" src="https://user-images.githubusercontent.com/4337769/196613218-09db92ef-22e2-4efb-b907-d294de92c4c5.png">

**Comment by lukehaas** [comment]
Try deleting the tsconfig file located in `~/Library/Application\ Support/runjs` and restart RunJS.
