### ISSUE TITLE
'this' has the implicit type 'any' because it does not have a type annotation. any

### ISSUE THREAD

**Issue by diegoMrSM** [lukehaas/RunJS#494]
Version 2.7.1
I have a class : 
function Queue(){
  this.array = [];
}
Issue:
But there a compilation error in the 'this' , :
'this' has the implicit type 'any' because it does not have a type annotation. any // 
'this' tiene el tipo implícito 'any' porque no tiene una anotación de tipo.
any

**Comment by lukehaas** [comment]
@diegoMrSM could you explain further how this is an issue and what your expectation is?

**Comment by diegoMrSM** [comment]
Hello Lukas.
If I declare a Class correctly, my expect is that doesn`t there compilation error any.  I did pay the license for the aplication runJs.
This is the Class :
  function Queue(){
this.array = [];
}    and the error is in the this, Not there so much that explain about it issue. The  error compilation says: 
"'this' has the implicit type 'any' because it does not have a type annotation. any"

**Comment by diegoMrSM** [comment]
![image](https://user-images.githubusercontent.com/102711304/198139460-b055d252-ca83-4b6e-af79-372d47c93393.png)

**Comment by lukehaas** [comment]
@diegoMrSM You're seeing the error because you haven't added a type annotation for `this`.
You can avoid the error by adding a type annotation, for example:

![Screenshot 2022-10-27 at 09 09 22](https://user-images.githubusercontent.com/741344/198228277-8b58e7f8-fd0d-404a-a357-05d5a043be35.png)

**Comment by diegoMrSM** [comment]
Good!! , thanks Lukehaas !! I didn't know  and  my teacher also not which was the problem.  
Thank you very much.
