### ISSUE TITLE
App freezes with with the following code 

### ISSUE THREAD

**Issue by bresson** [lukehaas/RunJS#495]
There is also no potential for recovery. Closing and starting the app triggers the function with no options to bail.

```
function dSteps(target, memo={}) {
  if (target === 0) return 1
  if (target in memo) return memo[target]

 memo[target] = dSteps(target-1, memo) + dSteps(target-2, memo)
 return memo[target]
}

console.log(dSteps(1))

```

**Comment by lukehaas** [comment]
@bresson click on `Kill` in the `Action` menu: `Action -> Kill`:
![Screenshot 2022-10-30 at 11 38 58](https://user-images.githubusercontent.com/741344/198876500-c640aecc-37ed-4ccc-9fe8-aafdb823afdf.png)
