### ISSUE TITLE
every time I open the app the cursor is on "block" style, not the typical "line"

### ISSUE THREAD

**Issue by paultumabini** [lukehaas/RunJS#498]
Hi Luke,

I'm not sure if this is only happening on my end, but after I transferred to a new laptop, installed the app and got activated. Every time, I opened the app the cursor style is on "block" style, and it's not responding to whatever I type on the keyboard.  I found out the way to get the typing to work is to press the "insert" on the keyboard and the cursor style switches back to the normal "line" style. It looks like every time I opened the app, the keyboard is on "insert" mode or something. It's not responding to typing unless I press the "insert" key on my keyboard first.  I don't see any settings for the cursor style though.

![image](https://user-images.githubusercontent.com/68520026/200170015-7a77bd25-683f-4845-a85f-092d1d65d04b.png)

Thanks,
Paul

**Comment by lukehaas** [comment]
Hi @paultumabini, you're seeing this as a result of turning on the Vim keys option:

![Screenshot 2022-11-06 at 15 57 01](https://user-images.githubusercontent.com/741344/200181032-17ba3af2-06dc-42ab-8186-ca91e681c346.png)

**Comment by paultumabini** [comment]
Thanks @lukehaas !

Got it. Never thought that's the reason behind.  Though, I was playing all those check boxes on the preferences menu to figure out why. Perhaps, I overlooked the changes when I toggled the "Vim Keys."

Cheers!
