### ISSUE TITLE
[Bug] Mishandling a narrowing type

### ISSUE THREAD

**Issue by K3ARN3Y** [lukehaas/RunJS#499]
TypeScript has the ability to narrow types. RunJS is not handling this correctly. Below is an example.

Example:

```ts
type User = {
  email: string
  admin: boolean
};
let amir: User = {
  email: 'amir@example.com',
  admin: true,
};

type HasEmail = {
  email: string
};
let amirEmail: HasEmail = amir;
amirEmail.admin;
```

RunJS :
`amirEmail.admin`  returns `true`. 

TypeScript Playground
`amirEmail.admin`  returns `Property 'admin' does not exist on type 'HasEmail'.`.

**Comment by lukehaas** [comment]
I am seeing the expected error message:
![Screenshot 2022-11-07 at 09 25 49](https://user-images.githubusercontent.com/741344/200274753-6a9eb9dd-b6f5-40bb-9702-a32ecd1daa9a.png)

**Comment by K3ARN3Y** [comment]
Maybe I am missing a feature turned on?

![image](https://user-images.githubusercontent.com/5862727/200323560-9992130b-895b-4ee3-ae5c-4773be11cafc.png)

I have Type Checking enabled and preset-typescript enabled.

**Comment by lukehaas** [comment]
That's odd. Are the other language services such as autocomplete and hover info working for you?
