### ISSUE TITLE
RunJS is stateful, it remembers everything previously typed during the session

### ISSUE THREAD

**Issue by MinimumViablePerson** [lukehaas/RunJS#50]
This can lead to confusion, because once you've deleted something you expect it to no longer exist, but it does, which has lead to wrong assumption confirmation when writing code.

![stateful-runjs](https://user-images.githubusercontent.com/16916098/52696255-79e91980-2f66-11e9-949d-8487d7bfd85d.gif)

**Comment by lukehaas** [comment]
Thanks for raising this. Will aim to resolve this in a future release.

**Comment by lukehaas** [comment]
This is now resolved in version 1.3.1
