### ISSUE TITLE
Bug: too many tsserver.js processes left in the system

### ISSUE THREAD

**Issue by KennanChan** [lukehaas/RunJS#502]
I noticed that a bunch of tsserver.js processes were left in my system after I quit RunJS. 

The number of tsserver.js process seems to be equal to the number of tabs I open during last usage.

I don't know if it was intended or by mistake.

It seems those processes are slowing down my system, because of which I have to kill those processes manually.

**Comment by lukehaas** [comment]
@KennanChan thanks; yes, I've recently become aware of this issue. The cause is upstream and has been resolved with this fix: https://github.com/typescript-language-server/typescript-language-server/pull/600
The next release of RunJS will include this fix.

**Comment by KennanChan** [comment]
Perfect

**Comment by lukehaas** [comment]
@KennanChan, this is now resolved in the latest release - 2.7.4
