### ISSUE TITLE
RunJs Frozen after Pasting long JSON

### ISSUE THREAD

**Issue by JorgeM18** [lukehaas/RunJS#503]
Hi 👋 

My RunJs App got frozen when i copy/pasted a Long JSON Object. It does not even open now, it just shows a blank screen. I'm on an intel mac OS Monterey version 12.5.1

Any help would be very appreciated. Thanks 🙏

**Comment by lukehaas** [comment]
Recent versions of RunJS have guards in place to prevent pasting large objects etc.
What version of RunJS are you using?

**Comment by JorgeM18** [comment]
I'm running version 2.7.1
