### ISSUE TITLE
Maximum call stack size exceeded and old code load

### ISSUE THREAD

**Issue by GustavoHenrique18n** [lukehaas/RunJS#506]
i think the runJS store the old code in  cache  or something like that like a text file  ... So that when i reopen the runJS i can see the old code .  But when i do a recursive function and the compile throw the error i cant exit . Runjs freeze , stopping the process and reopen the old code appear again and i stay  in same situation

**Comment by lukehaas** [comment]
To resolve this, click on `Kill` in the `Action` menu:
<img width="230" alt="Screenshot 2022-11-28 at 15 24 49" src="https://user-images.githubusercontent.com/741344/204315819-6f96bb0e-6ea9-4ec5-809c-696ae5ac5545.png">
