### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by ByJuan** [lukehaas/RunJS#507]
When I run the program, it opens normally, but tells me to update it when I have the latest version installed. I'm on Linux.

**Comment by lukehaas** [comment]
@ByJuan what version of RunJS are you using?

**Comment by FernandoClasslife** [comment]
Same problem:
V 2.7.3
just downloaded

**Comment by MichelD-dev** [comment]
Same problem here:
v2.7.3
Ubuntu 22.10

**Comment by malammar** [comment]
Same issue here as OP on Linux Mint 21.

I have the pre-release 2.7.3 version but it keeps asking me to update.

**Comment by lukehaas** [comment]
@ByJuan @FernandoClasslife @malammar the latest release, 2.7.4, resolves this issue.
