### ISSUE TITLE
Feature Request: Auto install npm dependency

### ISSUE THREAD

**Issue by ckuijjer** [lukehaas/RunJS#508]
Would it be possible to auto install the latest version of a npm dependency whenever I type, e.g. `import { faker } from '@faker-js/faker'` into RunJS' editor. Manually installing npm dependencies feels a bit tedious.

**Comment by lukehaas** [comment]
Thanks, @ckuijjer. Just to confirm, you're saying clicking on the install button next to the error message is tedious?

![Screenshot 2022-12-01 at 16 35 53](https://user-images.githubusercontent.com/741344/205109037-b0ea74a7-0d1d-484c-9e78-2fc4c969823d.png)

**Comment by ckuijjer** [comment]
Guess I messed something up, can't see the _Install_ option. _Install_ button is perfect of course :)

<img width="1840" alt="Screenshot 2022-12-01 at 19 18 55" src="https://user-images.githubusercontent.com/36165/205130085-a6d6e113-c0bc-4f93-ad73-e99b4212bb07.png">

**Comment by lukehaas** [comment]
I see now. Thanks for clarifying. 
It looks like there is an issue here. When bundling is enabled the install option is not appearing. I'll aim to get this resolved in the next release 👍

**Comment by ckuijjer** [comment]
You're awesome! Thanks 🥳 !

**Comment by lukehaas** [comment]
This is now resolved in the latest release:
![Screenshot 2023-01-28 at 13 18 54](https://user-images.githubusercontent.com/741344/215268480-d09280fc-8ec2-47f4-a918-39c9931cbf27.png)

**Comment by ckuijjer** [comment]
Thanks!
