### ISSUE TITLE
syntax highlighting parsing incorrect

### ISSUE THREAD

**Issue by MinimumViablePerson** [lukehaas/runjs#51]
As you can see below, since strings are not being output with quotes, the syntax highlighter tool changes colour every time it encounters quotes.

<img width="618" alt="syntax-highlighting" src="https://user-images.githubusercontent.com/16916098/52696634-60949d00-2f67-11e9-8363-4fefa487ba2a.png">

**Comment by lukehaas** [comment]
I'm aiming to get this resolved soon 👍

**Comment by lukehaas** [comment]
This is now resolved in version 1.3.0
