### ISSUE TITLE
Unchecking the (show runtime values) still displays the empty strings

### ISSUE THREAD

**Issue by AmJustSam** [lukehaas/RunJS#511]
Unchecking the (show runtime values) still displays the empty strings.

![image](https://user-images.githubusercontent.com/11780229/207008703-57ac8bf0-4c6e-47a2-af5d-915f4ab10158.png)
![image](https://user-images.githubusercontent.com/11780229/207008675-f9b04f4b-a60f-43d6-81e7-b694e25c641e.png)

**Comment by lukehaas** [comment]
The result of your code on the left is an empty string due to line 25: `personProxy.name = ''`
