### ISSUE TITLE
Courier NodeJS SDK always shows TypeError: Failed to fetch

### ISSUE THREAD

**Issue by yusef-ho** [lukehaas/RunJS#513]
NodeJS SDK of [Courier](https://www.courier.com/)
is always showing "TypeError: Failed to fetch"

But same snippet runs successfully by ts-node

![Screen_Shot_2022-12-14_at_12_26_51_AM](https://user-images.githubusercontent.com/33569998/207389708-2288032f-7361-48ff-b178-93d58d7f941c.jpg)

**Comment by lukehaas** [comment]
Sorry, @yusef-ho, I'm not familiar with the Courier package, and I don't know why it would fail with this message.
I'd recommend conducting your own experiments to figure out what the issue is.

**Comment by yusef-ho** [comment]
> 

How can i get full error from RunJS?

**Comment by yusef-ho** [comment]
> Sorry, @yusef-ho, I'm not familiar with the Courier package, and I don't know why it would fail with this message. I'd recommend conducting your own experiments to figure out what the issue is.

Thanks reply @lukehaas 
It seems RunJS problem. same snippet works well in [RunKit](https://npm.runkit.com/) and ts-node in my local.

How can i try to figure out the problem through getting full error from RunJS??

**Comment by lukehaas** [comment]
Have you tried changing any of the preference options that affect how RunJS runs your code?
For example, runtime values and bundling.

**Comment by yusef-ho** [comment]
> Have you tried changing any of the preference options that affect how RunJS runs your code? For example, runtime values and bundling.

Nope. Using Default setting.
And Another Mac with new installed RunJS causing the same issue

**Comment by lukehaas** [comment]
@yusef-ho I took a closer look at this issue and realised it was due to CORS. I've released a fix for this in version 2.7.5

**Comment by yusef-ho** [comment]
> @yusef-ho I took a closer look at this issue and realised it was due to CORS. I've released a fix for this in version 2.7.5

@lukehaas Thanks!!
