### ISSUE TITLE
Assignment to constant variable error message change position

### ISSUE THREAD

**Issue by ddzieduch** [lukehaas/RunJS#514]
The assignment to the constant variable changes the position of the error message, and is placed on the next line after the empty line.

![Screen Shot 2022-12-29 at 1 48 47 pm](https://user-images.githubusercontent.com/870473/209953802-6a8165ba-f7c8-4eb1-a62e-9f27d52a893d.png)

![Screen Shot 2022-12-29 at 1 48 56 pm](https://user-images.githubusercontent.com/870473/209953834-7d4a8b68-bd40-4d10-87e1-8aa34a8fc91e.png)

Version 2.7.4 (2.7.4)

**Comment by lukehaas** [comment]
Thanks, @ddzieduch. I'll address this in the next release.

**Comment by lukehaas** [comment]
This is now resolved in the latest release - version 2.7.5
