### ISSUE TITLE
The CommonJS module scope is for another module

### ISSUE THREAD

**Issue by withIssues** [lukehaas/RunJS#519]
The ```__filename```, ```__dirname```, ```module``` and the ```require``` function are for another module.
```javascript
console.log(__dirname); // always at [...]/renderer

console.log(__filename); // always at [...]/renderer/init.js

console.log(module); // always for the module 'electron/js2c/renderer_init'

// relative module references with leading './' or '../' can *not* work properly
require('./a-local-module'); 
```

**Comment by lukehaas** [comment]
@withIssues use the `Set Working Directory` action to point RunJS to a directory you want to require files from:

![Screenshot 2023-01-03 at 10 09 11](https://user-images.githubusercontent.com/741344/210337102-5831f332-80d5-4242-a645-8b94787ac342.png)

**Comment by withIssues** [comment]
Thank you for your prompt replies.

Setting a working directory is kind of a hassle and only resolves the ```require``` issue witch can also be done within the file with:

```javascript
module.paths.unshift("<working directory>");
```
You could use a wrapper to create a proper CommonJS module from the actual filename of the edited file, transparently for the user, like so:

```javascript
// BEGIN internal wrapper prefix
let m = (function createModule(filename){
  let path = require('path'),
  ext = path.extname(filename).toLowerCase(),
  oldLoader = require.extensions[ext];
  require.extensions[ext] = function(){}; // fake loader
  require(filename); // create a proper module for the filename
  require.extensions[ext] = oldLoader;
  let m = require.cache[filename];
  m.paths.unshift(m.path);
  return m;
})("<actual filename of the edited file>");

!function(module, exports, require, __dirname, __filename) {
// END internal wrapper prefix
// BEGIN what the user sees and edits  
	console.log(__dirname);
	console.log(__filename);  
	console.log(module);
	require('./a-local-module');
// END what the user sees and edits
// BEGIN internal wrapper postfix  
}(m, m.exports, m.require.bind(m), m.path, m.filename);
// END internal wrapper postfix
``````

**Comment by lukehaas** [comment]
Thanks, I understand the issue now. I'll aim to get this resolved in the next release 👍

**Comment by lukehaas** [comment]
This should now be fixed in the latest release, version 2.7.5 @withIssues

**Comment by lukehaas** [comment]
@withIssues can you confirm if this is working in line with your expectations?

**Comment by lukehaas** [comment]
Closing as there is no response from @withIssues
