### ISSUE TITLE
Bug: handling of `undefined`

### ISSUE THREAD

**Issue by getify** [lukehaas/runjs#52]
This is a two part issue (but both parts are related).

1. When the string `"undefined"` (not the actual `undefined` value) is sent as the output, it's actually treated (color highlighted, etc) as if it was the actual `undefined` value. This is confusing, but it also relates to the second part of the bug below.

   <img width="718" alt="screen shot 2019-02-13 at 9 50 53 am" src="https://user-images.githubusercontent.com/150330/52724636-56799b00-2f75-11e9-8a55-d1475c5e7147.png">

   Compared to Chrome's handling:

   <img width="448" alt="screen shot 2019-02-13 at 9 55 14 am" src="https://user-images.githubusercontent.com/150330/52724708-7ad57780-2f75-11e9-9131-7f2b82a4c90a.png">

   If you look closely, in Chrome the `"undefined"` string is actually recognized and treated (coloring wise) as a string. But in the RunJS one, the `"undefined"` string comes out looking like the `undefined` value.

2. The second part is, because `"undefined"` is treated as `undefined`, and any `undefined` is removed from the output lines, that means the string `"undefined"` is erroneously removed, too.

   I would argue that `undefined` should not be removed from the output, except for (perhaps) the very last line (if it was a statement, not expression, that resulted in `undefined`). But as you can see here, it's quite strange for `undefined` (and indeed, the string `"undefined"`) to be removed:

   <img width="677" alt="screen shot 2019-02-13 at 10 02 42 am" src="https://user-images.githubusercontent.com/150330/52725381-b7ee3980-2f76-11e9-8565-e3c53f49065f.png">

   Here I think it seems pretty reasonable to assume that the two removed outputs (`undefined` and `"undefined"`) should have been included in the outputs pane, without having to resort to `console.log(..)`.

**Comment by getify** [comment]
Addendum to part 1:

It's not just the string `"undefined"` which gets incorrectly colored in the output. Apparently it's all literals. These are all colored the same, even though the second in each pairing should be treated/colored as a string:

* `undefined` and `"undefined"`
* `true` and `"true"`
* `null` and `"null"`
* `42` and `"42"`
* `[1,2,3]` and `"[1,2,3]"`
* `{a:1}` and `"{a:1}"`

**Comment by lukehaas** [comment]
The issue with syntax highlighting in the output is on my todo list. Now that you've raised it I'll prioritise it for the next release.

Regarding undefined in the output. The string 'undefined' not appearing is a bug, I'll fix that.
I'm currently suppressing actual undefined in the output as otherwise it will appear very frequently, as you can imagine. Any function without a return, including things like console.log, and all declarations will result in undefined. It would be quite noisy and maybe a little confusing for some. I'm a little reluctant to change this for that reason.

**Comment by getify** [comment]
Could you make an option for showing `undefined` in the output?

**Comment by lukehaas** [comment]
Sure, happy to make it an option.

**Comment by getify** [comment]
I think this option together with the option (discussed in another thread) to only show the results of the last actual statement/expression (+ any explicit console messages) -- like browser devtools do -- would give solid control over whether we were being spammed by `undefined`s or not. :)

**Comment by lukehaas** [comment]
1.3.0 resolves the syntax highlighting issues and also introduces a preference option for showing undefined values.

![screenshot 2019-02-17 at 16 21 01](https://user-images.githubusercontent.com/741344/52915805-19dcd500-32d0-11e9-9f4b-b7406c00b574.png)
