### ISSUE TITLE
Implement "*" suffix for unsaved file in tab title

### ISSUE THREAD

**Issue by suns-echoes** [lukehaas/RunJS#521]
It would be nice to know if the file is not saved (or changed) by adding star "*" to the title in the tab.

Right now I don't know if files are up-to-date.

**Comment by lukehaas** [comment]
@suns-echoes which version of RunJS are you using?

**Comment by suns-echoes** [comment]
2.7.4 / Windows

**Comment by lukehaas** [comment]
This version indicates an unsaved status using a circle:
![Screenshot 2023-01-10 at 14 07 35](https://user-images.githubusercontent.com/741344/211572935-5b245aad-2e68-4a52-bb1e-e9bfed495fa4.png)

**Comment by suns-echoes** [comment]
Thank you for explanation. I think this issue can be closed.
