### ISSUE TITLE
remove renew license bar

### ISSUE THREAD

**Issue by shahul01** [lukehaas/RunJS#522]
the bar makes me regret buying the license in the first place, at least I didn't have to click every time i open the program before, do remove it..

![image](https://user-images.githubusercontent.com/53307156/212539831-ff8f9c3f-e1b9-4314-a3b4-5a3e38275160.png)

**Comment by lukehaas** [comment]
This is an important message, it's there to inform you that you are no longer receiving updates, which means that your versions of Node, V8, Chromium, Babel, TypeScript etc, will not get updated. Without updating, you'd soon be running your code against an outdated environment. This message should not be removed for this reason.

**Comment by shahul01** [comment]
I don't like nag screens or its alteration, really messes up the repl experience

**Comment by lukehaas** [comment]
The purpose of the banner is to inform, not to nag. Plus, it's simple enough to make it go away. I don't see the issue.

**Comment by shahul01** [comment]
you can close the issue but this definitely affected your credibility and your software's ux...
