### ISSUE TITLE
Error loading models with AdonisJs

### ISSUE THREAD

**Issue by if4lcon** [lukehaas/RunJS#524]
I recently purchased a license for RunJs in hopes of tinkering with AdonisJs, but am unable to get it to work. Specifically, I am receiving the following error message when attempting to load a model:

```
Error: Could not resolve `@ioc:Adonis/Lucid/Orm
```

It seems the error comes from AdonisJs uses package [ioc-transformer](https://github.com/adonisjs/ioc-transformer) to transform `@ioc` calls

**Comment by lukehaas** [comment]
@if4lcon please provide an example of the code you are running.

**Comment by if4lcon** [comment]
@lukehaas 

```js

import User from 'models/User'

(async() => {
  await User.find(1)
})()
```

**Comment by lukehaas** [comment]
Is `models/User` a local module or from NPM?

**Comment by if4lcon** [comment]
working directory is set to project that uses `@adonisjs/lucid`

**Comment by if4lcon** [comment]
ok :

1 - create new folder 
2 - follow this guide https://github.com/adonisjs/lucid/issues/493#issuecomment-1360978165
3 - try with RunJs

**Comment by if4lcon** [comment]
By the way, I believe the issue is not with RunJs but rather with the Adonis IoC container

**Comment by lukehaas** [comment]
Ok, if this is not a RunJS issue then it should be closed.

**Comment by if4lcon** [comment]
it works with ts-node, Run.js should handle imports in a similar manner as ts-node or tsc, as it runs with them. Adonis.js, however, can make imports more complex.

**Comment by lukehaas** [comment]
Have you tried enabling bunding?

**Comment by if4lcon** [comment]
yes, also RunJs doesn't load `.env`  

```js
process.env.MYSQL_HOST
```

output is blank

**Comment by lukehaas** [comment]
That's right, RunJS isn't going to load a `.env` unless it is required.
Alternatively, you can set environment variables in RunJS from the tools menu.

**Comment by if4lcon** [comment]
never mind i just give up couldn't make it work

**Comment by lukehaas** [comment]
> what strange now is i'm getting different error
> 
> ```
> Error: Could not resolve "better-sqlite3" Install
> ```

This is just a missing dependency.

**Comment by if4lcon** [comment]
@lukehaas I hope you find a way to integrate `@ioc:` imports

**Comment by lukehaas** [comment]
This is not a RunJS issue, this is an issue with the code you’re running.

**Comment by if4lcon** [comment]
@lukehaas after a lot of struggle I made it work but now looks async/await doesn't work with RunJs?

**Comment by if4lcon** [comment]
```js

'The vm module of Node.js is deprecated in the renderer process and will be removed.'



Promise { <pending> }
```

**Comment by if4lcon** [comment]
never mind i forgot to console.log thanks again for this great app
