### ISSUE TITLE
Runs previous code immediately after Start

### ISSUE THREAD

**Issue by elhadjx** [lukehaas/RunJS#529]
I was writing this code and I forgot the await before sleep and couldn't change, whenever i close/reopen RunJS it immediately starts running the code and I cant use RunJS until I kill the RunJS process from Task Manager
`function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

function openlink(URL){
  window.open(URL, '_blank');
}

async function demo() {
    for (let i = 0; i < 10; i++) {
        sleep(10000)
        openlink('https://github.com/elhadjx')
    }
}

demo();`

**Comment by elhadjx** [comment]
it'd be better to run make the start runnable until a change happen after starting RunJS

**Comment by lukehaas** [comment]
Thanks, @elhadjx. You can disable auto-run from the preferences:

![Screenshot 2023-01-27 at 16 19 41](https://user-images.githubusercontent.com/741344/215137569-d19b9122-2ac0-41b7-89d7-89efa5503118.png)

**Comment by lukehaas** [comment]
>  I cant use RunJS until I kill the RunJS process from Task Manager

There's no need to kill RunJS from the Task Manager. Just click on `Kill` in the action menu:
![Screenshot 2023-01-27 at 16 21 19](https://user-images.githubusercontent.com/741344/215138242-4da9a54a-f4b5-4cd4-bd49-ea75677872c2.png)

**Comment by elhadjx** [comment]
The Autorun is helpful and it's why I'm using this software, except when it runs after start the software.
The Kill on the action menu is helpful! thanks for answering this.

**Comment by lukehaas** [comment]
When auto-run is enabled, the expectation is that RunJS will always auto-run the code. This includes after starting the software.
