### ISSUE TITLE
Bug: strange case of missing exception output

### ISSUE THREAD

**Issue by getify** [lukehaas/RunJS#53]
This one is weird, I haven't been able to narrow down a hypothesis on why it's happening, but I at least have a fairly narrow use-case that demonstrates it.

Notice the missing exception output here?

<img width="671" alt="screen shot 2019-02-20 at 10 43 26 am" src="https://user-images.githubusercontent.com/150330/53108684-12e6da00-34fd-11e9-8a33-05bffed4d0d9.png">

But then in these 3 variations, the exception output shows:

<img width="674" alt="screen shot 2019-02-20 at 10 43 42 am" src="https://user-images.githubusercontent.com/150330/53108699-1da16f00-34fd-11e9-8572-21b93ad6036c.png">

<img width="657" alt="screen shot 2019-02-20 at 10 44 24 am" src="https://user-images.githubusercontent.com/150330/53108702-209c5f80-34fd-11e9-8937-f52f8657fef0.png">

<img width="636" alt="screen shot 2019-02-20 at 10 44 59 am" src="https://user-images.githubusercontent.com/150330/53108724-23975000-34fd-11e9-969e-2c052e9c3dc2.png">

**Comment by getify** [comment]
I should also mention, the first snippet "works" (shows the exception) if I turn on the "Holistic Evaluation" option (which I typically have turned off but turn on for specific actions).

**Comment by lukehaas** [comment]
Thanks, this will be fixed in the next release.

**Comment by lukehaas** [comment]
This is now resolved in version 1.3.1
