### ISSUE TITLE
Optional auto-folding of nested objects

### ISSUE THREAD

**Issue by alcovegan** [lukehaas/RunJS#531]
Hello. 

Today I installed the latest version of RunJS and, according to the changelog, now nested objects are auto-folded. Can this be made optional? Sometimes I need to convert data from one structure to another, and this is very inconvenient when every time the code changes, the objects have to be unwrapped back.

Thank you.

**Comment by didaquis** [comment]
In my opinion, I also think it would be interesting to make this behavior optional.

**Comment by lukehaas** [comment]
@alcovegan The latest release has an update for this. 
Nested objects are no longer auto-folded, now, only `__proto__` properties are auto-folded.
