### ISSUE TITLE
Unable to Close file

### ISSUE THREAD

**Issue by kmandirsoftware** [lukehaas/RunJS#532]
dialog box does not allow me to close file. I tried not saving but that does not work. I do not want to save the changes.

**Comment by lukehaas** [comment]
@kmandirsoftware is this related to this issue: https://github.com/lukehaas/RunJS/issues/486

**Comment by kmandirsoftware** [comment]
Yes, Same issue.

**Comment by lukehaas** [comment]
For now, you will need to use the arrow keys to close the dialog.
