### ISSUE TITLE
When open application, window not shown

### ISSUE THREAD

**Issue by ricardosa6** [lukehaas/RunJS#537]
After fresh install, when I open the app, I can't found the actual window, it appears on task bar, but it does not show up.

![image](https://user-images.githubusercontent.com/92020893/221894869-d6bc1f44-318c-4a16-beee-dfb5a9edd982.png)

**Comment by lukehaas** [comment]
@ricardosa6 here are some instructions for how to resolve this:
https://support.microsoft.com/en-us/topic/some-programs-are-displayed-off-the-screen-b2a915b7-4705-c455-febf-8ddb6e7f0ae4
