### ISSUE TITLE
Bug: strange order of exceptions vs console output

### ISSUE THREAD

**Issue by getify** [lukehaas/RunJS#54]
(NOTE: this may be related to #53, not sure)

I would expect any "regular" outputs to come first, in order, before an exception message is shown, but it seems like the exception is "hoisted" to the top of the output. Led me to incorrectly trying to fix a bug in my code that wasn't actually a bug.

<img width="662" alt="screen shot 2019-02-20 at 10 51 35 am" src="https://user-images.githubusercontent.com/150330/53109721-1a0ee780-34ff-11e9-88ec-a86eeee31fd2.png">

**Comment by lukehaas** [comment]
Good spot. Will have a fix for this in the next release.

**Comment by lukehaas** [comment]
This is now resolved in version 1.3.1
