### ISSUE TITLE
[Feature Request] Sync config between pc's 

### ISSUE THREAD

**Issue by RodrigoTomeES** [lukehaas/RunJS#541]
Hi!

It would be amazing to be able to sync settings between computers,

Thanks!

**Comment by lukehaas** [comment]
Thanks, @RodrigoTomeES. Could you provide more detail about how this would work? Also, could you provide examples of other apps that do this?

**Comment by RodrigoTomeES** [comment]
Hi!,

This feature should sync your all app settings like theme, compilations... between the different PC's (for example, pc and laptop). Other apps like VSCode use Microsoft account or Github Account to sync it. Also another apps use Google Drive, OneDrive... to save the JSON with the setting or something like that. This also open the posibility to share your configurations (with the JSON),

I hope this helps you,

Rodrigo

**Comment by RodrigoTomeES** [comment]
Hi,

Also it will be awesome if this functionality sync the npm packages and env that you have configured

**Comment by lukehaas** [comment]
I've given this some thought, and I don't plan to add this to the roadmap. It would be a very large undertaking, and I think the benefits are pretty small. It doesn't take much effort to adjust settings on different devices, also, this would add bloat and make the app harder to maintain. Closing for those reasons.
