### ISSUE TITLE
display error

### ISSUE THREAD

**Issue by ckwlghks123** [lukehaas/RunJS#542]
![image](https://user-images.githubusercontent.com/83552466/223321594-f9ee19d8-d36e-4f16-86be-5c3744a503e9.png)

nothing typed

display undefined

**Comment by lukehaas** [comment]
If you prefer not to see undefined values, you can turn this off in the preferences:
![Screenshot 2023-03-07 at 09 38 31](https://user-images.githubusercontent.com/741344/223383258-0ec60493-1cff-4c37-8667-bfb134abc49d.png)
