### ISSUE TITLE
Website not working for purchasing licenses

### ISSUE THREAD

**Issue by GustavoGomez092** [lukehaas/RunJS#543]
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/45272016/223754951-84286a1b-1a18-4042-beff-6b725bf8b2e8.png">

**Comment by lukehaas** [comment]
Thanks, @GustavoGomez092. The checkout is provided by Paddle and is not something I have control over. If you click on the button labelled "Contact support" they will be able to assist you with this issue.
