### ISSUE TITLE
[Feature Request] Don't show result of import when "Show result in execute" is enabled

### ISSUE THREAD

**Issue by RodrigoTomeES** [lukehaas/RunJS#544]
Hi,

Could be possible to add an option to doesn't show the import value when is enabled "Show value in execution"?

![imagen](https://user-images.githubusercontent.com/13077343/224156992-ef7a6b65-a189-43e3-ad2e-18caf60a7988.png)

Thanks!

**Comment by lukehaas** [comment]
Turning off runtime values would achieve the result you want:

<img width="565" alt="Screenshot 2023-03-10 at 09 04 18" src="https://user-images.githubusercontent.com/741344/224272798-58d06afd-7883-4715-b966-e9acdb48c00f.png">
