### ISSUE TITLE
[Feature request] Add option to change the language manually

### ISSUE THREAD

**Issue by RodrigoTomeES** [lukehaas/RunJS#545]
Hi,

Could be posible to add an option to change the language of RunJS? I have my computer in Spanish but I want to have RunJS in English,
 
Thanks!

**Comment by lukehaas** [comment]
Why do you have your system set to Spanish if you want to use apps in English?

**Comment by RodrigoTomeES** [comment]
I prefer to have the tools I use to code in English because it is easy to search for help. For example, if I open an issue I think is easy for all that I use the name of the setting in English that have the error not my translation of the spanish translation of the setting name because this can be very confused. In the other hand this setting is very common for example: VSCode, browsers...

![Captura de pantalla 2023-03-10 a las 10 16 24](https://user-images.githubusercontent.com/13077343/224275432-df906ae7-aca5-42f4-888d-342ae13153de.jpg)

**Comment by lukehaas** [comment]
Ok, makes sense.

**Comment by guillermodelrio** [comment]
I also need this

**Comment by lukehaas** [comment]
@RodrigoTomeES @guillermodelrio you can now set your preferred language in the latest version of RunJS.

**Comment by RodrigoTomeES** [comment]
@lukehaas in the 2.10.1 version? because I didn't find it 😅

**Comment by lukehaas** [comment]
@RodrigoTomeES yes, 2.10.1
![Screenshot 2024-01-02 at 12 13 57](https://github.com/lukehaas/RunJS/assets/741344/3128f809-0ce3-4679-a618-018b5c415d0c)

**Comment by RodrigoTomeES** [comment]
mmm it doesn't appear to me

![Screenshot 2024-01-02 at 13 22 19](https://github.com/lukehaas/RunJS/assets/13077343/f8d25f3e-f929-466f-9dd2-e5562cc4a8cd)

**Comment by lukehaas** [comment]
@RodrigoTomeES looks like your system is set to English? This option has been added for people with their system language set to Spanish.

**Comment by RodrigoTomeES** [comment]
@lukehaas yes, I updated my comment mentioning that. I changed my computer 1 month ago I decided to put it in English. Despite that, I don't understand why not put a language selector for everyone where the default is the system language and which can then be changed.

**Comment by lukehaas** [comment]
This option has been added purely to enable people to use RunJS in English. If their system is already in English, there's no reason to provide the option.
