### ISSUE TITLE
NPM install utility displays installed packages in search results

### ISSUE THREAD

**Issue by RodrigoTomeES** [lukehaas/RunJS#546]
https://user-images.githubusercontent.com/13077343/224259773-de4fab27-97ca-4ad1-a06a-ca767fca011d.mov

**Comment by lukehaas** [comment]
There are some cases where someone would want to update or install a different version of a package they have already added. This behaviour caters for that.

**Comment by RodrigoTomeES** [comment]
Mmmm but you can't select witch version want to install (or I didnt see how can i do it) so I think the text button should be "update" if there is an update and not install and only should be "update" if there is avalible an update.

**Comment by lukehaas** [comment]
You can specify the version to install in the same way you would via the cli, for example `react@17.0.0`

**Comment by RodrigoTomeES** [comment]
WoW interesting thanks!

**Comment by btecu** [comment]
It would be good to at least document this option (`package@version`), although having the UI display other versions when clicking on the package or in a dropdown would be even better.

**Comment by lukehaas** [comment]
@btecu this is documented here: https://runjs.app/docs#tools

**Comment by lukehaas** [comment]
The latest release of RunJS has some updates for this.
Now, when you search for a package that you already have installed, the result will should you what version you have installed:
![Screenshot 2023-04-19 at 11 13 59](https://user-images.githubusercontent.com/741344/233044486-2d6dfe37-9613-4081-a954-ea6d1f795739.png)
