### ISSUE TITLE
Not showing results

### ISSUE THREAD

**Issue by juanjzb** [lukehaas/RunJS#547]
On the last version, playground is not showing results of nothing, and it only shows a loader in the top-right corner of the code editor

**Comment by lukehaas** [comment]
Please provide your debit log. You can get this via the help menu.

**Comment by lukehaas** [comment]
@juanjzb please provide your debug log:

![Screenshot 2023-03-13 at 16 38 28](https://user-images.githubusercontent.com/741344/224767674-f86156c9-2e4d-461d-9dcf-075f7240478e.png)

**Comment by lukehaas** [comment]
Closing as there has been no response from @juanjzb

**Comment by juanjzb** [comment]
{
  "version": "2.8.0",
  "platform": "win32",
  "arch": "x64",
  "activated": false,
  "logs": [
    {
      "path": "C:\\Users\\jjsis\\AppData\\Roaming\\runjs\\logs\\main.log",
      "lines": [
        "[2022-06-23 13:37:21.254] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from \n    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)\n    at IpcMainImpl.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:71229)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)",
        "[2022-06-23 13:37:22.613] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from \n    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)\n    at IpcMainImpl.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:71229)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)",
        "[2022-06-23 13:37:23.613] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from \n    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)\n    at IpcMainImpl.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:71229)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)",
        "[2022-06-23 13:37:39.478] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from \n    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)\n    at IpcMainImpl.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:71229)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)",
        "[2022-06-23 13:38:42.685] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from \n    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)\n    at IpcMainImpl.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:71229)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)",
        "[2022-06-23 13:38:42.844] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from \n    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)\n    at IpcMainImpl.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:71229)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)",
        "[2022-06-23 13:38:43.005] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from \n    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)\n    at IpcMainImpl.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:71229)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)",
        "[2022-06-23 13:38:52.822] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from \n    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)\n    at IpcMainImpl.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:71229)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)",
        "[2022-06-23 13:38:53.192] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from \n    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)\n    at IpcMainImpl.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:71229)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)",
        "[2022-06-23 13:38:53.325] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from \n    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)\n    at IpcMainImpl.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:71229)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)",
        "[2022-06-23 13:38:56.902] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from \n    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)\n    at IpcMainImpl.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:71229)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)",
        "[2022-06-26 12:28:39.440] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from \n    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)\n    at IpcMainImpl.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:71229)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)",
        "[2022-06-26 12:28:39.799] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from \n    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)\n    at IpcMainImpl.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:71229)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)",
        "[2022-06-26 12:28:39.991] [error] Unhandled Exception TypeError: Error processing argument at index 2, conversion failure from \n    at EventEmitter.a.popup (node:electron/js2c/browser_init:81:3188)\n    at IpcMainImpl.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:71229)\n    at IpcMainImpl.emit (node:events:390:28)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)",
        "[2022-08-04 10:05:11.135] [warn]  disableWebInstaller is set to false, you should set it to true if you do not plan on using a web installer. This will default to true in a future version.",
        "[2022-08-04 10:05:58.147] [warn]  Signature validated using only CN Haas Labs Ltd. Please add your full Distinguished Name (DN) to publisherNames configuration",
        "[2022-08-27 19:32:35.425] [warn]  disableWebInstaller is set to false, you should set it to true if you do not plan on using a web installer. This will default to true in a future version.",
        "[2022-08-27 19:33:56.326] [warn]  Signature validated using only CN Haas Labs Ltd. Please add your full Distinguished Name (DN) to publisherNames configuration",
        "[2022-09-26 08:19:38.881] [error] Error: Error: net::ERR_INTERNET_DISCONNECTED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)\n    at SimpleURLLoaderWrapper.emit (node:events:526:28)",
        "[2022-09-26 08:19:38.885] [error] Error: net::ERR_INTERNET_DISCONNECTED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)\n    at SimpleURLLoaderWrapper.emit (node:events:526:28)",
        "[2022-10-09 16:34:54.357] [warn]  disableWebInstaller is set to false, you should set it to true if you do not plan on using a web installer. This will default to true in a future version.",
        "[2022-10-09 16:35:10.798] [warn]  Signature validated using only CN Haas Labs Ltd. Please add your full Distinguished Name (DN) to publisherNames configuration",
        "[2022-12-01 18:18:51.952] [error] Error: Error: net::ERR_NETWORK_CHANGED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)\n    at SimpleURLLoaderWrapper.emit (node:events:526:28)",
        "[2022-12-01 18:18:51.957] [error] Error: net::ERR_NETWORK_CHANGED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)\n    at SimpleURLLoaderWrapper.emit (node:events:526:28)",
        "[2022-12-10 09:51:53.270] [warn]  disableWebInstaller is set to false, you should set it to true if you do not plan on using a web installer. This will default to true in a future version.",
        "[2022-12-10 09:56:58.644] [error] Cannot download differentially, fallback to full download: HttpError: 401 \nHeaders: {\n  \"x-github-backend\": \"Kubernetes\",\n  \"x-github-request-id\": \"C0E4:76DC:3E1377:1ACE4E1:6394AC4A\",\n  \"accept-ranges\": \"bytes\",\n  \"date\": \"Sat, 10 Dec 2022 15:56:58 GMT\",\n  \"via\": \"1.1 varnish\",\n  \"x-served-by\": \"cache-mia11329-MIA\",\n  \"x-cache\": \"MISS\",\n  \"x-cache-hits\": \"0\",\n  \"x-timer\": \"S1670687819.636958,VS0,VE29\",\n  \"content-length\": \"0\"\n}\n    at Object.u (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:8:134235)\n    at ClientRequest.<anonymous> (C:\\Users\\jjsis\\AppData\\Local\\Programs\\runjs\\resources\\app.asar\\entry-bundle.js:14:155835)\n    at ClientRequest.emit (node:events:526:28)\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6917)\n    at SimpleURLLoaderWrapper.emit (node:events:526:28)",
        "[2022-12-22 10:15:02.866] [warn]  disableWebInstaller is set to false, you should set it to true if you do not plan on using a web installer. This will default to true in a future version.",
        "[2022-12-22 10:19:49.524] [warn]  Signature validated using only CN Haas Labs Ltd. Please add your full Distinguished Name (DN) to publisherNames configuration",
        "[2023-02-02 10:32:33.020] [error] Error: Error: net::ERR_INTERNET_DISCONNECTED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7167)\n    at SimpleURLLoaderWrapper.emit (node:events:527:28)\n    at SimpleURLLoaderWrapper.emit (node:domain:475:12)",
        "[2023-02-02 10:32:33.022] [error] Error: net::ERR_INTERNET_DISCONNECTED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7167)\n    at SimpleURLLoaderWrapper.emit (node:events:527:28)\n    at SimpleURLLoaderWrapper.emit (node:domain:475:12)",
        "[2023-02-02 10:38:37.389] [error] Error: Error: net::ERR_INTERNET_DISCONNECTED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7167)\n    at SimpleURLLoaderWrapper.emit (node:events:527:28)\n    at SimpleURLLoaderWrapper.emit (node:domain:475:12)",
        "[2023-02-02 10:38:37.399] [error] Error: net::ERR_INTERNET_DISCONNECTED\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7167)\n    at SimpleURLLoaderWrapper.emit (node:events:527:28)\n    at SimpleURLLoaderWrapper.emit (node:domain:475:12)",
        "[2023-02-02 18:01:37.032] [warn]  disableWebInstaller is set to false, you should set it to true if you do not plan on using a web installer. This will default to true in a future version.",
        "[2023-02-02 18:02:12.156] [warn]  Signature validated using only CN Haas Labs Ltd. Please add your full Distinguished Name (DN) to publisherNames configuration",
        "[2023-03-11 10:19:27.302] [warn]  disableWebInstaller is set to false, you should set it to true if you do not plan on using a web installer. This will default to true in a future version.",
        "[2023-03-11 10:21:22.327] [warn]  Signature validated using only CN Haas Labs Ltd. Please add your full Distinguished Name (DN) to publisherNames configuration",
        ""
      ]
    }
  ]
}

**Comment by juanjzb** [comment]
The code that i am trying to execute works fine in version 2.7 4 without changes.

**Comment by lukehaas** [comment]
@juanjzb have you tried doing a fresh install of 2.8.0?

**Comment by lukehaas** [comment]
Are you constantly seeing this issue, or is it just when you execute some particular code?

**Comment by juanjzb** [comment]
Always, even without writing code

**Comment by lukehaas** [comment]
Try deleting this folder and then restart the app:
`C:\Users\jjsis\AppData\Roaming\runjs`
