### ISSUE TITLE
Update app on Windows 11 is just uninstalling the app 

### ISSUE THREAD

**Issue by kad1r** [lukehaas/RunJS#559]
Hello,

This is happening for the last 2 releases. I saw there is an update and when I click it's just uninstalling the local version of app and not installing new version again. I had to download new version and install it from scratch. Plus I'm losing all my tabs :( 

**OS: Windows 11**

**Comment by lukehaas** [comment]
Thanks, the logs array is empty so not much info to go on.
The issue could be due to a lack of space on your hard drive or it could be due to some security settings that prevent RunJS from installing its own update.
