### ISSUE TITLE
Bug: Cannot update app after notification about new version

### ISSUE THREAD

**Issue by yonifra** [lukehaas/RunJS#56]
I get the notification that a new version has been downloaded, but I cannot actually update when clicking on it (doesn't do anything, and there's no way to update from within the application)

**Comment by lukehaas** [comment]
The update notification is just there to notify you that a new version has been downloaded and will be installed next time you open the app. It requires no other action from you.
Apologies for the confusion.

**Comment by yonifra** [comment]
Gotcha, thanks for clarifying!
Love RunJS! great learning tool and fast prototyping asset
