### ISSUE TITLE
Wrong Spanish Translation in Actions Menu

### ISSUE THREAD

**Issue by ricardoantonio** [lukehaas/RunJS#562]
<img width="309" alt="Captura de pantalla 2023-05-22 a la(s) 9 57 06" src="https://github.com/lukehaas/RunJS/assets/11904265/5ec8e631-47c7-4af6-98e4-a75b3c2d3134">

It must say **"Formatear código"**

**Comment by lukehaas** [comment]
Thanks, @ricardoantonio. Would you be able to explain why it should say "Formatear código" instead?

**Comment by ricardoantonio** [comment]
"Código de formato" has no significant meaning in Spanish with out context. I did not understand what it means or what it do until I test it. 

**"Dar formato al código"** or **"Formatear código"** means exactly what it do. The first is more formal than the second one but the second is consistently with the translation in the configuration dialog. 

<img width="602" alt="Captura de pantalla 2023-05-22 a la(s) 10 15 57" src="https://github.com/lukehaas/RunJS/assets/11904265/248f8280-a6f0-4ccf-a05e-1d5003fa7e38">

**Comment by lukehaas** [comment]
Ok, thanks. I'll update it in the next release. 

Are there any other translation issues you've noticed?

**Comment by ricardoantonio** [comment]
Not wrong, but for an easy understanding, optionally can change "Despejar" for **"Borrar todo"**. The same, I had to try it to know exactly what it do, now I know it and don't looks wrong for me, but it could be consistently with previous option "Seleccionar todo" together they could provide a better context.

<img width="286" alt="Captura de pantalla 2023-05-22 a la(s) 10 36 05" src="https://github.com/lukehaas/RunJS/assets/11904265/92ca449d-ac20-4f6f-a7ff-ed501548913a">

**Comment by lukehaas** [comment]
Thanks, @ricardoantonio. I'll update those in the next release.

**Comment by lukehaas** [comment]
These translation are now updated in the latest version of RunJS - version 2.10.1
