### ISSUE TITLE
Add - file explore

### ISSUE THREAD

**Issue by Vsevolod-IT** [lukehaas/RunJS#564]
add file explore like in VS-vode, WebShtorm and etc... maby integrate with plugins like neo-tree, telescope file explore
it is really hard to work with diffrence files without it

**Comment by lukehaas** [comment]
Thanks, @Vsevolod-IT. Could you describe the kinds of tasks you're using RunJS for and how a file explorer would help you?

**Comment by lukehaas** [comment]
Closing as no further detail has been provided.
RunJS is not trying to emulate VS Code etc. It's a playground app, not an IDE for developing apps.
