### ISSUE TITLE
Only output from last statement is visible

### ISSUE THREAD

**Issue by kevinboosten** [lukehaas/RunJS#565]
If I put multiple statements in my editor, only the last statement is visible on the output screen. 

![image](https://github.com/lukehaas/RunJS/assets/3380927/8c7da0ff-2352-4959-9f5b-b36d5b2462e7)

**Comment by lukehaas** [comment]
@kevinboosten This could be due to runtime values being toggled off in your settings:

![Screenshot 2023-06-08 at 14 15 53](https://github.com/lukehaas/RunJS/assets/741344/275d6e16-1841-48ff-ad00-8dbed1a60e3a)

**Comment by kevinboosten** [comment]
Ah excellent 😁 I thought I had already toggled everything, but I needed to disable "Enable top-level await" in order to toggle that setting. Now it works. 

Thanks 🤝.

![image](https://github.com/lukehaas/RunJS/assets/3380927/f6c6a9db-eaea-4f5b-b495-8dcde33d6879)
