### ISSUE TITLE
Increase text buffer size

### ISSUE THREAD

**Issue by paul-uz** [lukehaas/RunJS#567]
I need to test the conversion of XML to JSON, and the XML is about 12k lines. Trying to console out the result, I cannot see anything in the right hand panel, as it stops at 10k lines.

Is there a way to increase the text buffer size?

**Comment by lukehaas** [comment]
@paul-uz currently not, for performance reasons. I'd recommend writing the output to a file instead of console out.

**Comment by paul-uz** [comment]
What's the quickest way to write the data to a file?

**Comment by lukehaas** [comment]
Something like this:
```
const fs = require('fs');

const content = 'Some content!';

fs.writeFile('/Users/joe/test.txt', content, err => {
  if (err) {
    console.error(err);
  }
  // file written successfully
});
```
