### ISSUE TITLE
Feature request - Add shortcut to trigger suggest

### ISSUE THREAD

**Issue by oscarhn27** [lukehaas/RunJS#568]
Suggestions in pro version are very useful. But they has a problem, if you don't type anything the suggestions not appear.
Has sense because the app can't predict what the user wants, but in some cases it could and is a big help.

In the next example, the app knows the type of the first param, is an interface, but the user can't be helped if not type a letter:
![Screenshot_20230708_125224](https://github.com/lukehaas/RunJS/assets/52781505/26d16313-a602-4227-8ff1-a6c7cb1639b3)

This problem is solved in VSC with the action `Trigger Suggest` with the shortcut `Ctrl + Space` and I think is very useful.

**Comment by lukehaas** [comment]
Thanks, @oscarhn27. Aiming to add support for this in a future release 👍

**Comment by lakardion** [comment]
Please. I have this issue from some time as well. The information is there we just need the prompt to appear so that we know what options we have from TS inference

**Comment by lukehaas** [comment]
@oscarhn27 @lakardion this is now supported in the latest release of RunJS. 
The shortcut is `ctrl+space`
