### ISSUE TITLE
Bug: Cannot find any NPM package due to error

### ISSUE THREAD

**Issue by yonifra** [lukehaas/RunJS#57]
In the NPM package search window, I always get an internal error:
![image](https://user-images.githubusercontent.com/726718/53726947-be861780-3e77-11e9-9809-3f823b11b521.png)

**Comment by lukehaas** [comment]
This could mean there's an issue with NPM on your system. Are you able to install NPM packages from the terminal without issues?

**Comment by yonifra** [comment]
Yes, I'm always using NPM on my machine without any issues from the terminal

**Comment by Sevody** [comment]
I got this error too because I used taobao npm registry. And I fixed this problem after changing my npm registry to https://registry.npmjs.org

**Comment by yonifra** [comment]
Seems to actually be a local issue with my registry setup. Closing
