### ISSUE TITLE
npm package function issue

### ISSUE THREAD

**Issue by fullstackneo** [lukehaas/RunJS#575]
https://github.com/lukehaas/RunJS/assets/97574983/9080a8b7-4431-43eb-93b0-7a1a2855384d

Hi, it seems the 'NPM Packages' is not working properly. I have tried reinstall and it is still not working.

I installed `RunJS-2.9.0-universal.dmg` and my system is Ventura 13.4.1 (c) , M1 pro chip.

**Comment by lukehaas** [comment]
@fullstackneo please provide your debug log. You can access this from the help menu.

**Comment by fullstackneo** [comment]
Thank you@lukehaas. Just fixed it by deleted all the cache files.
