### ISSUE TITLE
for loop was misbehaving 

### ISSUE THREAD

**Issue by gopichand2131** [lukehaas/RunJS#576]
<img width="1011" alt="for_error_runjs" src="https://github.com/lukehaas/RunJS/assets/126584587/bf544b86-461d-446e-99df-1b2820ead825">

**Comment by gopichand2131** [comment]
6 has to print at last

**Comment by lukehaas** [comment]
@gopichand2131 please see the explanation for this here: https://github.com/lukehaas/RunJS/issues/497

**Comment by lukehaas** [comment]
@gopichand2131 closing this now. Hope it is clear from the explanation how to resolve this.
