### ISSUE TITLE
Splice function misbehaving 

### ISSUE THREAD

**Issue by gopichand2131** [lukehaas/RunJS#577]
<img width="1011" alt="runjs_splice" src="https://github.com/lukehaas/RunJS/assets/126584587/16095502-1197-470b-a2a4-e4bcf9331820">

**Comment by lukehaas** [comment]
@gopichand2131 this is correct.
The return value for `splice` is an array containing deleted elements. You are not deleting any elements so the returned array is empty.

![Screenshot 2023-08-21 at 09 57 42](https://github.com/lukehaas/RunJS/assets/741344/a8700ebd-f34f-4b7b-be53-dee31b14f9ff)


Please take a look here for more detail on `splice`:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

**Comment by lukehaas** [comment]
@gopichand2131 is it clear why the returned value is an empty array?
