### ISSUE TITLE
Bug: Less helpful outputs

### ISSUE THREAD

**Issue by rsoares** [lukehaas/RunJS#58]
I'm on macOS Mojave and I've just updated runJS to `v1.3.1` and the outputs seem less helpful now:

![screenshot 2019-03-05 at 11 17 00](https://user-images.githubusercontent.com/81978/53802015-a0ccb700-3f38-11e9-9937-bb2554494bc9.png)

Not sure if this is intended or a legit bug?

**Comment by lukehaas** [comment]
Definitely a bug. Thanks for raising this.

**Comment by rsoares** [comment]
Thank you! 🙇

**Comment by lukehaas** [comment]
This is now resolved in version 1.4.0
