### ISSUE TITLE
Bug: Generic breaks code highlights

### ISSUE THREAD

**Issue by RodrigoTomeES** [lukehaas/RunJS#584]
Hi,

Write a generic function break the code highlights, looks:

https://github.com/lukehaas/RunJS/assets/13077343/598ec768-af8b-4f4f-9ab9-abff12dcf74a

The code:

```ts
export const isNumber = <T,>(value: T): value is NonNullable<T> =>
  value !== '' &&
  typeof value !== 'object' &&
  typeof value !== 'boolean' &&
  !Number.isNaN(Number(value));
```

SO:
<img width="202" alt="Captura de pantalla 2023-10-20 a las 14 15 47" src="https://github.com/lukehaas/RunJS/assets/13077343/2b48864e-89da-4129-877e-9aace57c7d5b">
Version: `2.9.0`
Config (is in spanish, I can't change the language of RunJS):
![Captura de pantalla 2023-10-20 a las 14 13 43](https://github.com/lukehaas/RunJS/assets/13077343/af444428-c86c-468c-a376-ae4167bc5a57)

![Captura de pantalla 2023-10-20 a las 14 14 17](https://github.com/lukehaas/RunJS/assets/13077343/2014267d-f752-40b7-9347-9ea1c084a15d)

![Captura de pantalla 2023-10-20 a las 14 14 29](https://github.com/lukehaas/RunJS/assets/13077343/3e48137e-d87b-49ad-a4f0-8d2c96bb8e52)

![Captura de pantalla 2023-10-20 a las 14 14 45](https://github.com/lukehaas/RunJS/assets/13077343/193e821a-d467-4894-aa70-b91d5c06d080)

![Captura de pantalla 2023-10-20 a las 14 14 58](https://github.com/lukehaas/RunJS/assets/13077343/8cb26b52-257c-4f9c-8630-caf84cf4f0e0)

**Comment by btecu** [comment]
Seems to work fine for me (`2.9.0`):
<img width="882" alt="image" src="https://github.com/lukehaas/RunJS/assets/7517745/52a374bd-838d-437f-9b5e-ec2c7d5130c0">

**Comment by RodrigoTomeES** [comment]
Mmm I am also in `2.9.0`

**Comment by RodrigoTomeES** [comment]
@lukehaas one question, as you said if I disable `react-preset` it works well but why react preset should break generic in TS? I use it in my .tsx files in vscode

**Comment by lukehaas** [comment]
It works in VS Code due to the comma before the closing bracket `<T,>`. Unfortunately, this is not supported in Codemirror.

**Comment by lukehaas** [comment]
Reopening as I will try and get this supported.
