### ISSUE TITLE
Feature Request: changing the font 

### ISSUE THREAD

**Issue by enzime4u** [lukehaas/RunJS#59]
It would be possible in the future to change the Font used ?
Thank you

**Comment by lukehaas** [comment]
This is actually coming in the next version! 👍

**Comment by enzime4u** [comment]
Thank you BIG TIME, when do you think that will come out ?

**Comment by lukehaas** [comment]
This is now available in version 1.4.0

![Screenshot 2019-03-10 at 20 15 41](https://user-images.githubusercontent.com/741344/54090910-5f416f00-4371-11e9-98dd-f273a5c68b0f.png)

**Comment by enzime4u** [comment]
Great ! super thank you
