### ISSUE TITLE
feature request: save session

### ISSUE THREAD

**Issue by shahul01** [lukehaas/RunJS#590]
bulk save all opened js/ts code as zip or any other format
and if they're saved, add title and location

eg
say zip is an array with collection of js / ts files
[
{isSaved: true, title: 'hello', location: 'x:/y/z', code: "<js/ts code here>"}, // already saved file
{isSaved: false, title: 'world', location: '', code: "<js/ts code here>"}, // unsaved file
]

I use RunJS for coding challenges.
This will help me save the session as recurring backup instead of saving every single temporary file that I go through every now and then trying to solve it and deleting the solved file if its not that important..

**Comment by lukehaas** [comment]
I can't really see why this would be needed when RunJS already auto-saves on run.
