### ISSUE TITLE
User installed fonts are not displayed in RunJS/settings/appearance/font in MacOS Sonoma 14.1

### ISSUE THREAD

**Issue by nunatix** [lukehaas/RunJS#592]
The latest version of RunJS (2.9.0) is not able to display all user fonts on MacOS Sonoma 14.1. Only system fonts are displayed, user installed fonts are not displayed. This makes it impossible to use user-installed fonts (e.g. Microsoft/CascadiaCode) as MacOS Sonoma 14.1 by default does not allow the installation of personal fonts on the system or computer.

**Comment by lukehaas** [comment]
@nunatix the next version of RunJS will be using a different method for retrieving the user fonts. Hopefully, this will resolve the issue.

**Comment by nunatix** [comment]
@lukehaas Thank you very much for the prompt response. Thanks for informing us that it will be resolved in an upcoming version of RunJS. Thanks for the great work. I am already anxious and excited to have a new version of the program very soon. Have a good day.

**Comment by lukehaas** [comment]
@nunatix this should now be resolved in the latest version of RunJS.
