### ISSUE TITLE
node and tensorFlow error

### ISSUE THREAD

**Issue by Gravitad** [lukehaas/RunJS#595]
I have a problem installing the @tensorflow/tfjs-node libraries

mistake:

```
Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: C:Usersdavid zuccariniAppDataRoaming
unjs
ode_modules@tensorflow fjs-nodelib
api-v8 fjs_binding.node.
```
I also have a problem when trying to import any file. It doesn't recognize my route. and if I set the working directory, it doesn't take the directory either.

**Comment by lukehaas** [comment]
@Gravitad RunJS is not able to build native dependencies. You could try building manually by following the instructions here: https://www.npmjs.com/package/@tensorflow/tfjs-node

Or you could use the non-native version of TensorFlow instead: `@tensorflow/tfjs`
https://www.npmjs.com/package/@tensorflow/tfjs
