### ISSUE TITLE
Can't use React in a scratch file

### ISSUE THREAD

**Issue by vladyn** [lukehaas/RunJS#596]
<img width="1128" alt="image" src="https://github.com/lukehaas/RunJS/assets/107272/5102a964-7fab-4664-95fa-44c481933172">
Hi there, 
I'm trying to play with a React JS functional component, and I've installed React as a dependency, But for some reason, RunJS warns me that the module could not be loaded/found. Could you please advise me on what I'm doing wrong?

**Comment by lukehaas** [comment]
The warning is for the declaration file, not the module itself.
You will either need to install the declaration file for react or disable
TypeScript.

**Comment by vladyn** [comment]
how can I disable the typescript?
________________________________

**Comment by vladyn** [comment]
I handled it. Thanks for the fast advise!
