### ISSUE TITLE
I broke it :( 

### ISSUE THREAD

**Issue by pallymore** [lukehaas/runjs#6]
Hi, 

First of all, great app! I've been having fun with it.
However, I accidentally pasted `document.location.reload()` into the window and now it just reloads indefinitely every time when I open the app - even after I unchecked the auto evaluate option.

The issue persists even after I have re-installed the app so I had to manually edit the `config.json` file under `~/Library/Application\ Support/runjs` to remove the code.

**Comment by malammar** [comment]
Try leaving a `while (true)` loop in there. The app will max CPU and the only way to fix it is by clearing out the input in the config.json file.

Why not have the application run only on Ctrl+Enter?

**Comment by skuligowski** [comment]
Me too! I've accidentally created an infinite loop. 
How to break the loop and run RunJS again with blank page?

**Comment by pallymore** [comment]
> Me too! I've accidentally created an infinite loop.
> How to break the loop and run RunJS again with blank page?

Close the app (force quit) and go to `~/Library/Application\ Support/runjs/config.js` to change the `input`.

@malammar I was wondering about the shortcut as well, good to know it is Cmd + R. 👍 
I tried to turn off auto evaluation but it didn't help in my case even after re-opening the app

**Comment by pallymore** [comment]
![flashing_error](https://user-images.githubusercontent.com/2566530/50745795-1c8cda80-11fa-11e9-88d0-63a680761638.gif)

also ran into this today. 

I forgot I put a huge loop in the code for testing before I opened the app - then I tried to quit the app via the right-click menu in the dock and then this happened. 
Had to Force Quit the app with Activity Manager.

Maybe can we disable auto-execution upon launching the app if auto evaluation is disabled in the setting?

**Comment by stanleyswu** [comment]
Me too! I have accidentally created an infinite loop!

@pallymore, unfortunately the "runjs" folder and "config.js" file are not at this location:
 ~/Library/Application\ Support/runjs/config.js

How else can we resolve this issue?

**Comment by pallymore** [comment]
> Me too! I have accidentally created an infinite loop!
> 
> @pallymore, unfortunately the "runjs" folder and "config.js" file are not at this location:
> ~/Library/Application\ Support/runjs/config.js
> 
> How else can we resolve this issue?

It should be `config.json` instead of .js. 😅 

This should be the default location when using macOS.

**Comment by stanleyswu** [comment]
Are you sure that is the default location? There is no "runjs" folder in "application Support". I am running OSX High Sierra 10.13.6.

**Comment by pallymore** [comment]
> Are you sure that is the default location? There is no "runjs" folder in "application Support". I am running OSX High Sierra 10.13.6.

It should be. Maybe you could perform a search in the terminal: 
`find ~/Library -type d -name runjs`

One thing to note that there is also another Application Support folder under the root `/Library`(notice the absence of `~` at the beginning). It might be there if you installed the app as `root`

**Comment by stanleyswu** [comment]
Thank you!

**Comment by yonifra** [comment]
Happened to me as well, bummer to see this hasn't been resolved. I'll turn off auto evaluation for now. Thanks

**Comment by lukehaas** [comment]
The original issue of calling `document.location.reload()` is now resolved in version 1.2.3.

Additionally, in 1.2.3 there is now guarding against long running loops.

![screenshot 2019-02-02 at 17 39 27](https://user-images.githubusercontent.com/741344/52167437-d7819880-2712-11e9-80ea-29024976df3e.png)

**Comment by peter81git** [comment]
I now have kind of the same situation, but on windows. Anyone knows where the config file is located?

**Comment by hunterwilhelm** [comment]
There is no guarding against infinite recursion!

**Comment by nikoewe** [comment]
This loop is also not being caught.
```js
const arr = [1,2,3,1,213,21,1,1,231,1]

for (const a of arr){
  console.log(a)
  arr.push('')
}
```

**Comment by lukehaas** [comment]
@nikoewe please turn on loop protection:
![Screenshot 2024-11-13 at 09 36 05](https://github.com/user-attachments/assets/f1336ff0-118f-4d89-8e9e-09e6f75a5118)
