### ISSUE TITLE
Feature Request: Adding keyboard shortcuts for commenting code

### ISSUE THREAD

**Issue by imri29** [lukehaas/RunJS#60]
Hello,
First of all thank you for this tool, I've been looking for something like this for a surprisingly long time.
Is it possible to add a keyboard shortcut to commenting/uncommenting code? It's usually `Ctrl`/`⌘` + `/` from what I'm familiar with.

Thank you again.

**Comment by lukehaas** [comment]
Glad you raised this. Guess this means you're either on the Linux or Windows version. Currently this shortcut is mapped to `Cmd+/` I will update it so that `Ctr+/` also works.

**Comment by imri29** [comment]
Running the Windows version, yes.|

That'll be awesome, thanks!
