### ISSUE TITLE
Bug: Installing `sweph` package from REPL does not run builld properly

### ISSUE THREAD

**Issue by iki** [lukehaas/RunJS#600]
Steps to reproduce:

  1. Put the following into a new tab:
  ```ts
  import sweph from 'sweph'
  
  sweph.version()
  ```
    
  2. Install `sweph` from evaluation window prompt
 
Expected result:: `'2.10.03'`
Actual result: Error stating `build/Release/sweph.node` is missing
 
Actually the `build` is missing completely.
Probably, the [install script](https://github.com/timotejroiko/sweph/blob/main/package.json#L39) was not executed properly and/or package installation error is not reported by the app.

Workaround:
- remove `%AppData%\runjs\node_modules\sweph`
- run `npm install` in `%AppData%\runjs`
 
Platform: Win 11 x64 latest

**Comment by lukehaas** [comment]
Thanks @iki. RunJS, unfortunately, can't build native dependencies.
The workaround that you've found is the recommended solution. Alternatively, there are often JS alternatives to a lot of native packages, but that might not be the case for this one.
