### ISSUE TITLE
Loop inside a loop - is not rendered correctly in the visualizer

### ISSUE THREAD

**Issue by leonardodawinci** [lukehaas/RunJS#602]
Hi, when I log a loop inside a loop:

Example:

for (let exercise = 1; exercise < 3; exercise++) {
  console.log(`---Bicep Curl ${exercise}`);

  for (let rep = 5; rep < 6; rep++) {

      for (let set = 1; set < 4; set++) {
    console.log(`set ${set} reps ${rep}`)}
      
      }

}

The visualizer shows it as:

'---Bicep Curl 1'
'---Bicep Curl 2'

'set 1 reps 5'
'set 2 reps 5'
'set 3 reps 5'
'set 1 reps 5'
'set 2 reps 5'
'set 3 reps 5'

Instead of:

'---Bicep Curl 1'
'set 1 reps 5'
'set 2 reps 5'
'set 3 reps 5'
'---Bicep Curl 2'
'set 1 reps 5'
'set 2 reps 5'
'set 3 reps 5'

**Comment by lukehaas** [comment]
@leonardodawinci please take a look here: https://github.com/lukehaas/RunJS/issues/497
