### ISSUE TITLE
tooltip width bug

### ISSUE THREAD

**Issue by joonseokhu** [lukehaas/RunJS#605]
<img width="986" alt="스크린샷 2024-02-16 오후 7 23 53" src="https://github.com/lukehaas/RunJS/assets/19492260/3f6c7de8-9bbb-43b2-8fab-85b621044476">

When content text of tooltip is long enough and has no linebreak,
tooltip box overflows the window which make viewport scrollable.

I think the tooltipbox should have max width which is relative to viewport size and tooltip position

**Comment by lukehaas** [comment]
@joonseokhu thanks for raising this. I'll get this resolved in the next release 👍

**Comment by lukehaas** [comment]
@joonseokhu this is now resolved in version 2.11.0
