### ISSUE TITLE
[Feature Request] Closing tabs with mouse wheel

### ISSUE THREAD

**Issue by jurajkapsz** [lukehaas/RunJS#607]
I am used to close tabs with mouse wheel click, which works in browsers.

It also works in RunJS, but when I wheel click a tab, my clipboard data gets pasted into the editor window first, which I don't want to do; and I am prompted if I want to save the changes first (nb [in this fashion](https://github.com/lukehaas/RunJS/issues/486), but I usually avoid this dialog).

Can be the paste action disabled when closing a tab using wheel click?
Or, if not possible, disabling the wheel click action on tabs could be fine imho (to prevent the paste issue).

Using RunJS v2.10.1 @ GNU/Linux

**Comment by lukehaas** [comment]
I'm not sure why a middle mouse click would be triggering a paste. This is not something that RunJS is doing.
This is most likely something your OS is triggering.

**Comment by jurajkapsz** [comment]
> I'm not sure why a middle mouse click would be triggering a paste. This is not something that RunJS is doing.

Yep, this is what my OS does. Doesn't it work also on eg Windows? I use it on Linux regularly for years now.
This unintentional paste does not happen on any other tabbed text editor that I've used, eg gedit, vscode, sublime text.

**Comment by lukehaas** [comment]
I see. I'll look into getting this resolved in the next release. 👍

**Comment by jurajkapsz** [comment]
> I see. I'll look into getting this resolved in the next release.

Uh, ok, thanks very much Luke!

**Comment by jurajkapsz** [comment]
Thanks, Luke! In recently released `RunJS v2.11.0` this works great, but maybe it introduced this [new bug](https://github.com/lukehaas/RunJS/issues/609).
