### ISSUE TITLE
No warning to save changes prior closing a file

### ISSUE THREAD

**Issue by jurajkapsz** [lukehaas/RunJS#609]
Using `RunJS v2.11.0` @ GNU/Linux.

When I have unsaved changes in a file and close the file via tab, the file closes without prior "Save changes?" dialog.

**How to reproduce:**

1. Open a new tab.
2. Make some changes.
3. Close the tab. The file closes without any warning of having unsaved changes.

**Expected result:**

Show a dialog with option to save changes before closing a modified file.

**Comment by lukehaas** [comment]
You can enable the confirm close option if you want this behaviour:
![Screenshot 2024-02-26 at 08 11 28](https://github.com/lukehaas/RunJS/assets/741344/8d5a8392-b51a-41a4-aa81-8864798d7291)

**Comment by jurajkapsz** [comment]
Ah, ok, I see. I've missed the save changes dialog, but I've read [this issue](https://github.com/lukehaas/RunJS/issues/480) and understand better this behaviour.

Thanks Luke! I decided not to use the confirm option, as it fits better the way I use RunJS.
