### ISSUE TITLE
option to disable Strict mode

### ISSUE THREAD

**Issue by brandonmcconnell** [lukehaas/RunJS#612]
I am attempting to demonstrate the former usage of `with`, but I get the error `SyntaxError: 'with' in strict mode.`. I don;t see any option to opt out of strict mode, and I am not explicitly setting it in my source, so it would be helpful to add an option to disable strict mode.

**Comment by lukehaas** [comment]
@brandonmcconnell I've attempted to see the same syntax error you saw, but I'm not able to.
I'm able to use `with` without any issues. Could you provide an example of the code you're running? Also, which version of RunJS are you using?

**Comment by brandonmcconnell** [comment]
I am running RunJS Version 2.11.0 (2.11.0), but I cannot seem to reproduce it myself now either. I'll open a new ticket if I run into this again.
