### ISSUE TITLE
Async code console prints wrong timeline

### ISSUE THREAD

**Issue by Biki-das** [lukehaas/RunJS#613]
![Screenshot 2024-03-15 at 11 40 01 AM](https://github.com/lukehaas/RunJS/assets/72331432/eb7ac6c2-3949-472d-98b9-081d66119068)

? the console print conveying the execution timeline is wrong? is there any setting?

**Comment by lukehaas** [comment]
@Biki-das please take a look here for the explanation: https://github.com/lukehaas/RunJS/issues/497
