### ISSUE TITLE
Code lost on update

### ISSUE THREAD

**Issue by cfjedimaster** [lukehaas/RunJS#615]
I had a tab with some edited code, got the notification that a new version of RunJS was available and told it to update. When RunJS came back, the modified code was gone. (I didn't lose a lot, just like 3 lines or so.)

**Comment by lukehaas** [comment]
Older versions of RunJS would auto-save when the code is run. If you wrote code and didn't run it, this would explain why it wasn't saved.

**Comment by cfjedimaster** [comment]
Ah, I definitely didn't run it.
