### ISSUE TITLE
Revert "Open with" setting RunJS assigned itself on install

### ISSUE THREAD

**Issue by basememara** [lukehaas/RunJS#620]
Great product, but upset that it assigned itself as an opener to a bunch of file extensions without asking.

What file extensions did it assign itself to open with so I can go one by one and revert them to the previous app that was used to open them?

**Comment by lukehaas** [comment]
It has associations with the following file extensions: `js`, `jsx`, `ts`, `tsx`.
I think it would only become the default editor for these if nothing was previously set as the default.

**Comment by basememara** [comment]
Thanks for looking into this. If that's the way it works then that's fair. Though I can't confirm that what it does and have a suspicion because they were assigned to VS Code for me before.
