### ISSUE TITLE
Error: Cannot find module always

### ISSUE THREAD

**Issue by vghernandz** [lukehaas/RunJS#623]
I have a license for runjs, it works great for me but from one moment to the next I get the error

<img width="461" alt="Captura de pantalla 2024-05-21 a la(s) 3 39 32 p  m" src="https://github.com/lukehaas/RunJS/assets/75815658/c1b949b2-847c-4d4e-ad8c-55a7afc57f37">

I hit install, it loads for a moment and remains at the same message. I went to the menu,  `tools`  > `npm packages` and installed it and it still does the same thing.

<img width="652" alt="Captura de pantalla 2024-05-21 a la(s) 3 41 49 p  m" src="https://github.com/lukehaas/RunJS/assets/75815658/9be962f2-b41c-4294-9f65-75f9bbb0c6d1">

**_I clarify that what happens with any package need_**, it is always the same.

I tried to install it and it doesn't work. I have attached a copy of the debug file.

`
{
  "version": "2.12.0",
  "platform": "darwin",
  "arch": "arm64",
  "activated": true,
  "logs": [
    {
      "path": "/xxxx/xxxx/Library/Logs/runjs/main.log",
      "lines": [
        "[2024-05-21 15:37:19.141] [error] Unhandled TypeError: Cannot read properties of undefined (reading 'libraryDefaultDir')",
        "    at Function.resolvePathFn (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:14:97807)",
        "    at Function.readAllLogs (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:14:97314)",
        "    at click (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:8:90918)",
        "    at MenuItem.click (node:electron/js2c/browser_init:2:29559)",
        "    at a._executeCommand (node:electron/js2c/browser_init:2:34987)",
        ""
      ]
    }
  ]
}
`

**Comment by lukehaas** [comment]
Thanks @vghernandz.
Have you previously managed to successfully install packages via RunJS or have they always failed to install?

Could you verify that you can manually install NPM packages - to do this, navigate to `~/Library/Application\ Support/runjs` in your terminal app and run `npm i web3` - then open RunJS and see if you can successfully import the package.

Another thing to try could be re-downloading and installing RunJS.

**Comment by vghernandz** [comment]
answers...

1- _Have you previously managed to successfully install packages via RunJS or have they always failed to install?_
Yes, I had runjs for a few months and it worked perfectly, but from one moment to the next it stopped working.

2- _Could you verify that you can manually install NPM packages - to do this, navigate to ~/Library/Application\ Support/runjs in your......._
Yes, it installs without problems, the package.json is fine with the list of installed packages, but in runjs the error continues.

3- _Another thing to try could be re-downloading and installing RunJS._
As I mentioned, I had already tried it and it did not solve the error.

💡 **What occurred to me was to delete the folder you mentioned `~/Library/Application\ Support/runjs` and everything works again. I don't know if it is the most recommended solution, but it worked for me.** ✅

I appreciate your help @lukehaas 🧑‍💻
