### ISSUE TITLE
ubuntu 24.04 launch issue

### ISSUE THREAD

**Issue by 5erg10** [lukehaas/RunJS#626]
since i update ubuntu to 24.04, try to launch runjs but nothing happen. No error message, no launched icon on toolbar... nothing. it worse, I reinstalled the app to see if this solves the problem but doesnt work and now I'm afraid I have lost my license

**Comment by lukehaas** [comment]
@5erg10 I've just installed RunJS on Ubuntu 24.04, and it's working fine for me. 
Are you on Arm or x86?

Regarding your license, it's not possible to lose it as you can always access it from the license manager: https://runjs.app/license-manager

**Comment by lukehaas** [comment]
@5erg10 any update on this?

**Comment by lukehaas** [comment]
The version I installed was runjs_2.12.1_arm64.deb as I tested on Arm.

Are you installing runjs_2.12.1_amd64.deb?

**Comment by 5erg10** [comment]
I've installed the same version. runjs_2.12.1_amd64.deb. the first time I try to lauch, throw this error

![Captura desde 2024-06-04 21-30-07](https://github.com/lukehaas/RunJS/assets/7993728/a2f32a6b-d95d-45f4-8172-4d3d2fd3574f)

![Captura desde 2024-06-04 21-30-45](https://github.com/lukehaas/RunJS/assets/7993728/c06b306a-2d74-483d-8720-d4ac8f1e1f24)

after this first attemp, simply app dont launch, without error message.

**Comment by 5erg10** [comment]
this is the complete error log 
[_opt_RunJS_runjs.1000.txt](https://github.com/user-attachments/files/15569640/_opt_RunJS_runjs.1000.txt)

**Comment by lukehaas** [comment]
@5erg10 what method did you use to install RunJS?
Are you able to install previous version? You can access previous versions here: https://runjs.app/releases

**Comment by 5erg10** [comment]
i have installed 2.9.0, 2.10.1, 2.12.0 and 2.12.1 versions to test, but have the same result. I only made double click on .deb package

**Comment by 5erg10** [comment]
any idea @lukehaas ??

**Comment by lukehaas** [comment]
@5erg10 could you try installing the AppImage instead?
You can download it here: https://github.com/lukehaas/RunJS/releases/download/v2.12.1/RunJS-2.12.1.AppImage

**Comment by lukehaas** [comment]
@5erg10 did you manage to install the AppImage?

**Comment by lukehaas** [comment]
Ok, glad to hear it's resolved now. Will close the ticket.
