### ISSUE TITLE
NPM Window can obscure version #

### ISSUE THREAD

**Issue by cfjedimaster** [lukehaas/RunJS#627]
While searching for Cheerio, I got the following:

![image](https://github.com/lukehaas/RunJS/assets/393660/c15602bb-72d7-4d3f-9de7-26d8acbb8319)

As you can see, I have a version installed, but there is no way to tell as the full version isn't fully displayed. I tried mouseovering to see if it would reveal in a tool tip, but that didn't work, nor did trying to resize the columns or the window itself.

**Comment by lukehaas** [comment]
Thanks, @cfjedimaster. I'll get this sorted in the next release.

**Comment by lukehaas** [comment]
@cfjedimaster this should now be resolved in version 3.0.3

**Comment by cfjedimaster** [comment]
Confirmed, thank you. (I'm clicking close, which feels weird as it's your repo, so if that's wrong, I apologize. :)

**Comment by lukehaas** [comment]
@cfjedimaster that's all fine, as the opener you can close it if it's resolved 👍
