### ISSUE TITLE
Add current most used frameworks/libraries, i.e. react, angular, vue

### ISSUE THREAD

**Issue by seyade** [lukehaas/RunJS#63]
Hi Luke

I like this toy, really helpful!
This is just a suggestion, maybe you could also add libraries and frameworks for quick component testing.
For example if I want to try some array iteration with `someArray.map()` or others, with complex algorithm, etc., to see how it will work before putting the solution in my project.

**Comment by lukehaas** [comment]
Every NPM package is already available to you 😉
Go to the `Action` menu, then `Install NPM Packages`

**Comment by seyade** [comment]
Ah cool! Sorry I didn't look deeper in the app! But thanks for showing me.

**Comment by lukehaas** [comment]
👍
