### ISSUE TITLE
[Feature] Remove upgrade nags

### ISSUE THREAD

**Issue by sgolovine** [lukehaas/RunJS#632]
I bought a version of RunJS > 1 year ago and every time I start it up I get a nag to upgrade to the latest version. I do not want to upgrade and would like a way to suppress this message so that it does not keep nagging me every time I open the app.

**Comment by lukehaas** [comment]
@sgolovine just select the option labelled "Don't remind me again".

**Comment by lukehaas** [comment]
@sgolovine were you able to resolve the issue?
