### ISSUE TITLE
装饰器Decorator error

### ISSUE THREAD

**Issue by amandaXCY** [lukehaas/RunJS#634]
function observable(fnName:any) {  // 装饰器工厂函数
  return function (target: any, key: string): any { 
     console.log(1,target)// 装饰器
     console.log(2,key)// 装饰
    let prev = target[key];
   
    Object.defineProperty(target, key, {
      set(next) {
        target[fnName](prev, next);
        prev = next;
      }
    })
  }
}

class Store {
  @observable('onCountChange')
  count = -1;
}

const store = new Store();
store.count = 10

**out** 

1 undefined
2 {
  kind: 'field',
  name: 'count',
  metadata: [Object: null prototype] {},
  addInitializer: ƒ bound (),
  static: false,
  private: false,
  access: { has: ƒ (), get: ƒ k(), set: ƒ F() }
}

**but in https://www.typescriptlang.org/play/**

[LOG]: 1,  Store: {} 
[LOG]: 2,  "count" 

node packs:
babel/core:7.24.5
babel/preset-env:7.24.7

**Comment by lukehaas** [comment]
Thanks @amandaXCY.
I'm seeing the same result in both RunJS and the typescript playground:

![Screenshot 2024-07-09 at 09 41 18](https://github.com/lukehaas/RunJS/assets/741344/8b2f836b-20d3-46c2-ba3e-4da637110032)

![Screenshot 2024-07-09 at 09 41 10](https://github.com/lukehaas/RunJS/assets/741344/3658f397-01a5-4683-b786-44593fbaed44)

What version of RunJS are you using?

**Comment by lukehaas** [comment]
Closing as there's not been a response from @amandaXCY 😔
