### ISSUE TITLE
[Feature] Add setting to change the hover tooltip delay

### ISSUE THREAD

**Issue by ChristopherHaws** [lukehaas/RunJS#635]
I find the default hover tooltip delay to be slightly too fast for me. Would it be possible to add a config setting for the hover tooltip delay? Thanks!

**Comment by lukehaas** [comment]
@ChristopherHaws thanks for raising this.
It does seem that the delay is a little shorter than other editors. I will increase the delay in the next release.

**Comment by ChristopherHaws** [comment]
@lukehaas Thanks! Great last name btw ;)

**Comment by lukehaas** [comment]
@ChristopherHaws thanks!
The latest release has an increased hover delay. Let me know what you think.

**Comment by lukehaas** [comment]
@ChristopherHaws can this now be closed?
