### ISSUE TITLE
Bug Report: Formatting Resets Editor View to Top

### ISSUE THREAD

**Issue by mayfairstrange** [lukehaas/RunJS#639]
### Bug Description
When formatting code in the editor, the view resets to the top of the file. This causes the user to lose their vertical position in the file, making it difficult to continue editing from where they left off. In most code editors, formatting preserves the current view, allowing users to maintain their position in the file.

### Reproduction

1. Open a large file in the code editor.
2. Scroll down to any line in the middle or bottom of the file.
3. Trigger the code formatting action (Action->Format Code or ALT + Shift + F
4. The editor view resets to the top of the file.

**Comment by DesBw** [comment]
I am having this exact issue. 
Latest version: Mac_monterey.

**Comment by lukehaas** [comment]
@DesBw are you using RunJS version 3.0.3?

**Comment by DesBw** [comment]
> @DesBw are you using RunJS version 3.0.3?
oh, I didn´t know that you released version 3. i will test it out.

**Comment by lukehaas** [comment]
@DesBw @mayfairstrange, this should now be resolved in version 3.0.3. Are you able to confirm?
