### ISSUE TITLE
'Select All' does not work when CMD+A is pressed.

### ISSUE THREAD

**Issue by einsub** [lukehaas/RunJS#64]
Perhaps it's because I've turned on the 'Always use Vim keys' setting. When copying and pasting codes from elsewhere, I need to manually select all of them to erase existing code.

**Comment by lukehaas** [comment]
If you're using vim keys then you will need to be in insert mode to do this

**Comment by einsub** [comment]
Thank you for your answer and confirmed that it works perfectly in insert mode. I'm not sure what is a proper action of cmd+a in visual mode, but I've never experienced this on any other editors like vscode, macvim. I even could not think that I can try it in insert mode as well because I always do this on visual mode.

**Comment by lukehaas** [comment]
That's a valid point. I will investigate further and see if I can support the same behaviour as VScode

**Comment by lukehaas** [comment]
@einsub this appears to be working now.
