### ISSUE TITLE
No indication of meaning of red squiggles

### ISSUE THREAD

**Issue by debrisapron** [lukehaas/RunJS#640]
Hi Luke! My problem is I'm seeing red squiggles in the editor - presumably indicating a problem with the type signature - but no description of the error anywhere? I've clicked & hovered over everything I could think of but no luck. Example:
<img width="578" alt="Screenshot 2024-09-05 at 1 30 51 PM" src="https://github.com/user-attachments/assets/f31a7612-bd65-481a-a66d-adf8c762ce94">

**Comment by lukehaas** [comment]
A tooltip should appear on hover like this:

![2024-09-06 09 36 55](https://github.com/user-attachments/assets/92cb51d4-db35-4f6d-bf1d-fd3cd720b481)

**Comment by lukehaas** [comment]
I see, it seems to be an issue with multiline errors. I'll include a fix for this in the next release. Thanks for raising it.

**Comment by lukehaas** [comment]
@debrisapron this should be resolved in the latest version of RunJS.
