### ISSUE TITLE
Version 3.0 was Release but RunJS Version 2.12.1 (2.12.1) shows no Updates

### ISSUE THREAD

**Issue by alankleindev** [lukehaas/RunJS#643]
Version 3.0 was Release but RunJS Version 2.12.1 (2.12.1) shows no Updates, is that expected?

**Comment by lukehaas** [comment]
Version 3 has not been rolled out to all users yet.

**Comment by gander** [comment]
![obraz](https://github.com/user-attachments/assets/64a32ff7-7afd-4f4a-9b0e-d8ca1e65317b)

This is like `Release Candidate`, not `Release`.
