### ISSUE TITLE
console.log timing wrong, simple code runs with wrong output, whereas in console, chrome the output of the same code is right

### ISSUE THREAD

**Issue by visaruruqi** [lukehaas/RunJS#645]
RUN THIS IN RUNJS you will see a wrong output

for (let i = 1; i <= 100; i++) {
    if (i % 3 == 0 && i % 5 == 0) {
    console.log("FizzBuzz");
  } else if (i % 3 == 0) {
     console.log("Fizz");
  } else if (i % 5 == 0) {
     console.log("Buzz");
  } else {
    console.log(i);
  }
}

run the same in chrome, it will come just with right order

**Comment by lukehaas** [comment]
Here is a side-by-side comparison of this code in RunJS and the chrome console:

![Screenshot 2024-10-07 at 18 10 47](https://github.com/user-attachments/assets/f3bd97f9-7365-4835-9e07-306d5928edbc)

**Comment by visaruruqi** [comment]
<img width="1124" alt="Screenshot 2024-10-07 at 22 30 27" src="https://github.com/user-attachments/assets/81857f06-6583-411c-aa30-832a4d237bc3">

**Comment by visaruruqi** [comment]
https://github.com/user-attachments/assets/645736e3-888d-416a-a3e7-e5cad539231b

found the guilty feature
