### ISSUE TITLE
Bug: incorrect behavior - var variables are not hoisted

### ISSUE THREAD

**Issue by alexdevero** [lukehaas/RunJS#65]
Example:
```
console.log(x)

var x = 'The variable should be hoisted.'
```
The output is `ReferenceError: x is not defined`. This is not correct. It should be `undefined` since `var` variables are hoisted.

**Comment by alexdevero** [comment]
Similar issue happens also with back-ticks.

Example:
`console.log('This text\n' + ' should be printed\n' + ' on multiple lines.')`

Result:
```
`This text
 should be printed
 on multiple lines.`
```

Correct behavior:
```
"This text
should be printed
on multiple lines."
```

_Note: The "Always transpile" option is turned off._

**Comment by lukehaas** [comment]
These are very different issues.
```
`This text
 should be printed
 on multiple lines.`
```
Is the expected behaviour. RunJS will convert multiline string to template strings to avoid breaking the syntax highlighting.

**Comment by alexdevero** [comment]
Understand @lukehaas 👍 .

**Comment by lukehaas** [comment]
Closing as this is now resolved.
