### ISSUE TITLE
Unable to update RunJS

### ISSUE THREAD

**Issue by didaquis** [lukehaas/RunJS#655]
For some unknown reason, I am unable to update the application to new versions as the "Check for Updates" option is disabled.
I have an active license.

<img width="354" alt="Captura de pantalla 2024-10-28 a las 9 18 42" src="https://github.com/user-attachments/assets/42e77a29-652b-47c1-a6e0-ca5eef90ce7d">

<img width="318" alt="Captura de pantalla 2024-10-28 a las 9 18 50" src="https://github.com/user-attachments/assets/11537b8f-30b0-4f39-9851-ecfcaa469e86">

Logs: 

`{
  "version": "2.10.1",
  "platform": "darwin",
  "arch": "x64",
  "activated": true,
  "logs": [
    {
      "path": "/Users/didac/Library/Logs/runjs/main.log",
      "lines": [
        "[2020-12-24 11:37:39.299] [info] Checking for update",
        "[2020-12-24 11:37:39.547] [info] Generated new staging user ID: 0543fef4-faa6-58a7-b8af-792d7e05b864",
        "[2020-12-24 11:37:41.219] [info] Update for version 1.12.2 is not available (latest version: 1.12.2, downgrade is disallowed).",
        "[2020-12-24 11:38:19.645] [info] Checking for update",
        "[2020-12-24 11:38:21.168] [info] Update for version 1.12.2 is not available (latest version: 1.12.2, downgrade is disallowed).",
        "[2021-01-25 08:27:39.894] [info] Checking for update",
        "[2021-01-25 08:27:41.603] [info] Update for version 1.12.2 is not available (latest version: 1.12.2, downgrade is disallowed).",
        "[2021-01-25 08:34:22.909] [info] Checking for update",
        "[2021-01-25 08:34:24.612] [info] Update for version 1.12.2 is not available (latest version: 1.12.2, downgrade is disallowed).",
        "[2021-01-25 08:34:58.839] [info] Checking for update",
        "[2021-01-25 08:35:00.327] [info] Update for version 1.12.2 is not available (latest version: 1.12.2, downgrade is disallowed).",
        "[2021-01-27 14:38:35.143] [info] Checking for update",
        "[2021-01-27 14:38:36.857] [info] Update for version 1.12.2 is not available (latest version: 1.12.2, downgrade is disallowed).",
        "[2021-01-28 14:20:45.261] [info] Checking for update",
        "[2021-01-28 14:20:47.079] [info] Update for version 1.12.2 is not available (latest version: 1.12.2, downgrade is disallowed).",
        "[2021-02-12 11:32:19.721] [info] Checking for update",
        "[2021-02-12 11:32:21.492] [info] Found version 1.13.1 (url: RunJS-1.13.1-mac.zip, RunJS-1.13.1.dmg)",
        "[2021-02-12 11:32:21.493] [info] Downloading update from RunJS-1.13.1-mac.zip, RunJS-1.13.1.dmg",
        "[2021-02-12 11:32:26.221] [info] New version 1.13.1 has been downloaded to /Users/didac/Library/Application Support/Caches/runjs-updater/pending/RunJS-1.13.1-mac.zip",
        "[2021-02-12 11:32:26.287] [info] / requested",
        "[2021-02-12 11:32:26.294] [info] /1613125946225-9065.zip requested",
        "[2021-02-12 11:32:26.294] [info] /1613125946225-9065.zip requested by Squirrel.Mac, pipe /Users/didac/Library/Application Support/Caches/runjs-updater/pending/RunJS-1.13.1-mac.zip",
        "[2021-02-12 11:32:31.540] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v1.13.1/RunJS-1.13.1-mac.zip)",
        "[2021-04-26 13:19:21.827] [info] Checking for update",
        "[2021-04-26 13:19:22.878] [info] Found version 1.15.1 (url: RunJS-1.15.1-mac.zip, RunJS-1.15.1.dmg)",
        "[2021-04-26 13:19:22.879] [info] Downloading update from RunJS-1.15.1-mac.zip, RunJS-1.15.1.dmg",
        "[2021-04-26 13:19:22.889] [info] Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: /cjD64JR11CkbYwOONN5ub6yo9eB2OI92mI3RQ16OP4m2WzFACnUgW2R+WHhCsshYpYu9Ls8ukGqYNxPFIeN8g==, expected: nAoGruQkjk/6qHbPfTwCxVfEgjRwA4x9TyDDLY4sqM/OFzeSQljw6BG3p2brdMPjTsCA8rEvFH/6Tal44k8fqw==. Directory for cached update will be cleaned",
        "[2021-04-26 13:19:28.538] [info] New version 1.15.1 has been downloaded to /Users/didac/Library/Application Support/Caches/runjs-updater/pending/RunJS-1.15.1-mac.zip",
        "[2021-04-26 13:19:28.589] [info] / requested",
        "[2021-04-26 13:19:28.593] [info] /1619435968540-6008.zip requested",
        "[2021-04-26 13:19:28.593] [info] /1619435968540-6008.zip requested by Squirrel.Mac, pipe /Users/didac/Library/Application Support/Caches/runjs-updater/pending/RunJS-1.15.1-mac.zip",
        "[2021-04-26 13:19:33.877] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v1.15.1/RunJS-1.15.1-mac.zip)",
        "[2021-04-29 13:21:19.913] [info] Checking for update",
        "[2021-04-29 13:21:20.990] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-05-04 12:06:53.922] [info] Checking for update",
        "[2021-05-04 12:06:55.126] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-05-10 13:43:58.220] [info] Checking for update",
        "[2021-05-10 13:43:59.379] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-05-10 16:29:22.584] [info] Checking for update",
        "[2021-05-10 16:29:23.719] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-05-11 18:10:37.211] [info] Checking for update",
        "[2021-05-11 18:10:40.483] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-05-13 10:32:45.597] [info] Checking for update",
        "[2021-05-13 10:32:46.791] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-05-13 13:38:52.568] [info] Checking for update",
        "[2021-05-13 13:38:53.863] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-05-19 11:26:32.223] [info] Checking for update",
        "[2021-05-19 11:26:33.606] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-05-25 13:22:28.202] [info] Checking for update",
        "[2021-05-25 13:22:29.907] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-06-14 11:32:39.392] [info] Checking for update",
        "[2021-06-14 11:32:41.146] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-06-14 16:34:06.373] [info] Checking for update",
        "[2021-06-14 16:34:07.520] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-06-15 14:06:09.354] [info] Checking for update",
        "[2021-06-15 14:06:10.598] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-06-15 16:06:34.883] [info] Checking for update",
        "[2021-06-15 16:06:36.318] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-06-16 08:48:50.303] [info] Checking for update",
        "[2021-06-16 08:48:51.617] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-06-16 14:58:28.827] [info] Checking for update",
        "[2021-06-16 14:58:29.480] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-06-17 09:58:47.060] [info] Checking for update",
        "[2021-06-17 09:58:48.543] [info] Update for version 1.15.1 is not available (latest version: 1.15.1, downgrade is disallowed).",
        "[2021-06-29 15:01:13.546] [info] Checking for update",
        "[2021-06-29 15:01:15.458] [info] Found version 2.0.1 (url: RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg)",
        "[2021-06-29 15:01:15.458] [info] Downloading update from RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg",
        "[2021-06-29 15:01:15.470] [info] Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: nAoGruQkjk/6qHbPfTwCxVfEgjRwA4x9TyDDLY4sqM/OFzeSQljw6BG3p2brdMPjTsCA8rEvFH/6Tal44k8fqw==, expected: uO3wmY/SUcPnV1PriZzLEWF+F0Qk+R9HO2MDmr6gQQPcSDHe1nEZvwRSnvDA0UMSqJL+ktQMgRt3I0JynchXjQ==. Directory for cached update will be cleaned",
        "[2021-06-29 15:02:29.653] [info] New version 2.0.1 has been downloaded to /Users/didac/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
        "[2021-06-29 15:02:29.698] [info] / requested",
        "[2021-06-29 15:02:29.701] [info] /1624971749657-2721.zip requested",
        "[2021-06-29 15:02:29.701] [info] /1624971749657-2721.zip requested by Squirrel.Mac, pipe /Users/didac/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
        "[2021-06-29 15:02:34.977] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-2.0.1-mac.zip)",
        "[2021-06-29 15:02:47.906] [info] Checking for update",
        "[2021-06-29 15:02:48.413] [info] Found version 2.0.1 (url: RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg)",
        "[2021-06-29 15:02:50.462] [info] Downloading update from RunJS-2.0.1-mac.zip, RunJS-2.0.1.dmg, RunJS-2.0.1-arm64.dmg",
        "[2021-06-29 15:02:51.326] [info] / requested",
        "[2021-06-29 15:02:51.329] [info] /1624971770489-9037.zip requested",
        "[2021-06-29 15:02:51.330] [info] /1624971770489-9037.zip requested by Squirrel.Mac, pipe /Users/didac/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.0.1-mac.zip",
        "[2021-06-29 15:02:56.578] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.0.1/RunJS-2.0.1-mac.zip)",
        "[2021-06-29 15:05:53.574] [info] Checking for update",
        "[2021-06-29 15:05:55.038] [info] Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).",
        "[2021-06-30 17:30:57.672] [info] Checking for update",
        "[2021-06-30 17:30:58.740] [info] Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).",
        "[2021-07-06 12:33:20.602] [info] Checking for update",
        "[2021-07-06 12:33:21.522] [info] Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).",
        "[2021-07-19 10:31:38.074] [info] Checking for update",
        "[2021-07-19 10:31:39.288] [info] Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).",
        "[2021-07-22 13:07:32.148] [info] Checking for update",
        "[2021-07-22 13:07:33.232] [info] Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).",
        "[2021-07-22 16:17:35.571] [info] Checking for update",
        "[2021-07-22 16:17:36.524] [info] Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).",
        "[2021-07-22 17:13:08.783] [info] Checking for update",
        "[2021-07-22 17:13:09.618] [info] Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).",
        "[2021-07-23 11:37:54.167] [info] Checking for update",
        "[2021-07-23 11:37:55.282] [info] Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).",
        "[2021-07-26 08:42:35.612] [info] Checking for update",
        "[2021-07-26 08:42:36.750] [info] Found version 2.1.0 (url: RunJS-2.1.0-arm64-mac.zip, RunJS-2.1.0-mac.zip, RunJS-2.1.0-arm64.dmg, RunJS-2.1.0.dmg)",
        "[2021-07-26 08:42:36.751] [info] Downloading update from RunJS-2.1.0-arm64-mac.zip, RunJS-2.1.0-mac.zip, RunJS-2.1.0-arm64.dmg, RunJS-2.1.0.dmg",
        "[2021-07-26 08:42:36.761] [info] Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: uO3wmY/SUcPnV1PriZzLEWF+F0Qk+R9HO2MDmr6gQQPcSDHe1nEZvwRSnvDA0UMSqJL+ktQMgRt3I0JynchXjQ==, expected: LVYMj0MGG846LiUDBaK7pjnmN/EyaTLdgexzKgcfJjA78UkFcv0vcE7rc03AXIc1DzfI8IltAslwPLO02c0USQ==. Directory for cached update will be cleaned",
        "[2021-07-26 08:42:42.621] [info] New version 2.1.0 has been downloaded to /Users/didac/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.1.0-arm64-mac.zip",
        "[2021-07-26 08:42:42.678] [info] / requested",
        "[2021-07-26 08:42:42.684] [info] /1627281762625-9244.zip requested",
        "[2021-07-26 08:42:42.685] [info] /1627281762625-9244.zip requested by Squirrel.Mac, pipe /Users/didac/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.1.0-arm64-mac.zip",
        "[2021-07-26 08:42:48.058] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.1.0/RunJS-2.1.0-arm64-mac.zip)",
        "[2021-07-26 21:13:43.284] [info]  Checking for update",
        "[2021-07-26 21:13:44.017] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
        "[2021-07-27 13:26:23.296] [info]  Checking for update",
        "[2021-07-27 13:26:24.657] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
        "[2021-07-27 15:43:39.201] [info]  Checking for update",
        "[2021-07-27 15:43:39.779] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
        "[2021-07-28 14:51:35.832] [info]  Checking for update",
        "[2021-07-28 14:51:37.287] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
        "[2021-07-29 10:02:13.358] [info]  Checking for update",
        "[2021-07-29 10:02:43.393] [error] Error: Error: net::ERR_TIMED_OUT",
        "    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)",
        "    at SimpleURLLoaderWrapper.emit (events.js:315:20)",
        "[2021-07-29 10:02:48.291] [error] Error: net::ERR_TIMED_OUT",
        "    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)",
        "    at SimpleURLLoaderWrapper.emit (events.js:315:20)",
        "[2021-07-29 15:28:50.980] [info]  Checking for update",
        "[2021-07-29 15:28:52.548] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
        "[2021-08-02 13:48:43.421] [info]  Checking for update",
        "[2021-08-02 13:48:44.769] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
        "[2021-08-02 16:55:09.247] [info]  Checking for update",
        "[2021-08-02 16:55:10.092] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
        "[2021-08-03 11:41:18.846] [info]  Checking for update",
        "[2021-08-03 11:41:19.810] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
        "[2021-08-03 16:21:29.809] [info]  Checking for update",
        "[2021-08-03 16:21:30.684] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
        "[2021-08-04 13:20:15.760] [info]  Checking for update",
        "[2021-08-04 13:20:16.891] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
        "[2021-08-05 20:14:07.191] [info]  Checking for update",
        "[2021-08-05 20:14:08.411] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
        "[2021-08-19 17:08:24.921] [info]  Checking for update",
        "[2021-08-19 17:08:26.047] [info]  Update for version 2.1.1 is not available (latest version: 2.1.1, downgrade is disallowed).",
        "[2021-08-31 16:57:05.451] [info]  Checking for update",
        "[2021-08-31 16:57:07.268] [info]  Found version 2.1.3 (url: RunJS-2.1.3-universal-mac.zip, RunJS-2.1.3-universal.dmg)",
        "[2021-08-31 16:57:07.269] [info]  Downloading update from RunJS-2.1.3-universal-mac.zip, RunJS-2.1.3-universal.dmg",
        "[2021-08-31 16:57:07.280] [info]  Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: LVYMj0MGG846LiUDBaK7pjnmN/EyaTLdgexzKgcfJjA78UkFcv0vcE7rc03AXIc1DzfI8IltAslwPLO02c0USQ==, expected: TfD0IKnb+Q5fbZZjX4+0eLjqJEnFbYfvF7gCdsP4fJcCanr84CLFOktGOgWzoXYBxqtthpGymGu6hw7DAllutg==. Directory for cached update will be cleaned",
        "[2021-08-31 16:57:17.693] [info]  New version 2.1.3 has been downloaded to /Users/didac/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.1.3-universal-mac.zip",
        "[2021-08-31 16:57:17.768] [info]  / requested",
        "[2021-08-31 16:57:17.772] [info]  /1630421837697-7881.zip requested",
        "[2021-08-31 16:57:17.772] [info]  /1630421837697-7881.zip requested by Squirrel.Mac, pipe /Users/didac/Library/Application Support/Caches/runjs-updater/pending/RunJS-2.1.3-universal-mac.zip",
        "[2021-08-31 16:57:23.238] [info]  Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/lukehaas/RunJS/releases/download/v2.1.3/RunJS-2.1.3-universal-mac.zip)",
        "[2022-01-26 18:29:07.770] [error] Error: Error: net::ERR_TIMED_OUT",
        "    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7068)",
        "    at SimpleURLLoaderWrapper.emit (node:events:394:28)",
        "[2022-01-26 18:29:07.774] [error] Error: net::ERR_TIMED_OUT",
        "    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7068)",
        "    at SimpleURLLoaderWrapper.emit (node:events:394:28)",
        "[2022-02-14 13:08:34.598] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        "[2022-03-04 18:07:17.666] [error] [renderer] TypeError: Object has been destroyed",
        "    at /Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:2:15464",
        "    at IpcMainImpl.<anonymous> (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:2:11567)",
        "    at IpcMainImpl.emit (node:events:394:28)",
        "    at Object.<anonymous> (node:electron/js2c/browser_init:161:10774)",
        "    at Object.emit (node:events:394:28)",
        "[2022-04-20 18:18:55.409] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        "[2022-04-25 17:01:47.171] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        "[2022-05-03 17:54:24.612] [error] [renderer] TypeError: Cannot read properties of null (reading 'classList')",
        "    at t._handleClickOutside (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1775129)",
        "[2022-05-25 10:54:50.851] [error] [renderer] TypeError: Cannot read properties of null (reading 'classList')",
        "    at t._handleClickOutside (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2109:1775129)",
        "[2022-05-31 17:34:43.779] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        "[2022-06-01 16:47:26.693] [error] [renderer] TypeError: Cannot set properties of null (setting 'loaded')",
        "    at file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2116:264118",
        "    at CallbacksRegistry.apply (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2110:389834)",
        "    at file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2110:396174",
        "    at EventEmitter.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2110:395777)",
        "    at EventEmitter.emit (node:events:390:28)",
        "    at Object.onMessage (node:electron/js2c/renderer_init:69:746)",
        "[2022-06-30 16:27:20.890] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        "[2022-06-30 16:45:40.588] [error] [renderer] TypeError: Cannot set properties of null (setting 'loaded')",
        "    at file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2116:264118",
        "    at CallbacksRegistry.apply (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2110:389834)",
        "    at file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2110:396174",
        "    at EventEmitter.<anonymous> (file:///Applications/RunJS.app/Contents/Resources/app.asar/index-bundle.js:2110:395777)",
        "    at EventEmitter.emit (node:events:390:28)",
        "    at Object.onMessage (node:electron/js2c/renderer_init:69:746)",
        "[2022-07-14 19:19:03.600] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        "[2022-07-19 16:37:15.029] [error]",
        "[2022-08-23 13:09:52.492] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        "[2022-08-23 13:11:15.076] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        "[2022-08-23 13:11:15.937] [warn]  Error: Could not get code signature for running application",
        "    at Server.<anonymous> (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:14:142782)",
        "    at Object.onceWrapper (node:events:509:28)",
        "    at Server.emit (node:events:390:28)",
        "    at emitListeningNT (node:net:1368:10)",
        "    at processTicksAndRejections (node:internal/process/task_queues:82:21)",
        "[2022-08-23 13:11:15.948] [error] Error: Error: Could not get code signature for running application",
        "    at Server.<anonymous> (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:14:142782)",
        "    at Object.onceWrapper (node:events:509:28)",
        "    at Server.emit (node:events:390:28)",
        "    at emitListeningNT (node:net:1368:10)",
        "    at processTicksAndRejections (node:internal/process/task_queues:82:21)",
        "[2022-08-23 13:11:34.194] [error] [renderer] Error: ERR_FAILED (-2) loading 'data:text/html;base64,CiAgICA8aHRtbD4KICAgICAgPGhlYWQ+CiAgICAgICAgPHRpdGxlPlByZXZpZXc8L3RpdGxlPgogICAgICA8L2hlYWQ+CiAgICA8L2h0bWw+CiAg'",
        "    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)",
        "    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)",
        "    at EventEmitter.emit (node:events:402:35)",
        "[2022-08-23 13:11:38.301] [error] [renderer] Error: ERR_FAILED (-2) loading 'data:text/html;base64,CiAgICA8aHRtbD4KICAgICAgPGhlYWQ+CiAgICAgICAgPHRpdGxlPlByZXZpZXc8L3RpdGxlPgogICAgICA8L2hlYWQ+CiAgICA8L2h0bWw+CiAg'",
        "    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)",
        "    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)",
        "    at EventEmitter.emit (node:events:402:35)",
        "[2022-08-30 15:22:03.736] [error]",
        "[2022-10-10 11:52:07.809] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        "[2023-02-20 10:08:01.918] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        "[2023-02-20 16:53:39.283] [error]",
        "[2023-03-03 01:10:51.914] [error]",
        "[2023-03-08 10:28:56.405] [error]",
        "[2023-03-16 10:55:38.737] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        "[2023-03-16 17:07:34.509] [error]",
        "[2023-03-17 13:50:33.116] [error]",
        "[2023-04-12 16:37:12.061] [error]",
        "[2023-04-13 11:47:38.141] [error]",
        "[2023-04-18 17:07:49.345] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        "[2023-04-19 10:17:36.914] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        "[2023-05-03 15:13:28.868] [error]",
        "[2023-05-31 11:55:03.454] [error]",
        "[2023-09-07 11:54:30.847] [error]",
        "[2023-10-17 13:42:23.276] [error]",
        "[2023-10-17 17:07:11.349] [error]",
        "[2023-10-18 10:18:41.315] [error]",
        "[2023-10-19 17:48:25.902] [error]",
        "[2023-10-19 17:57:41.102] [error]",
        "[2023-10-20 15:21:38.572] [error]",
        "[2023-10-26 14:00:59.478] [error]",
        "[2023-10-31 16:06:43.329] [error]",
        "[2023-11-03 13:58:12.349] [error]",
        "[2023-11-06 09:54:04.041] [error]",
        "[2023-11-10 15:49:59.033] [error]",
        "[2023-11-13 17:55:41.416] [error]",
        "[2023-11-24 10:34:11.096] [error]",
        "[2023-12-22 10:15:27.429] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        "[2023-12-22 10:22:28.071] [error]",
        "[2024-01-12 16:12:37.739] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated",
        "sysctl: unknown oid 'sysctl.proc_translated'",
        "",
        ""
      ]
    }
  ]
}`

**Comment by lukehaas** [comment]
If you login to the license manager, it will tell you your latest available version and give you a download link: https://runjs.app/license-manager
