### ISSUE TITLE
Command not registered at startup when codelist modal not active

### ISSUE THREAD

**Issue by jonnymauser76** [lukehaas/RunJS#656]
Hey, 

I am using this wonderful plugin (v.0.6.0 with Obsidian 1.7.4) to trigger a script that helps me to close additional tabs, when I switch between different levels of my vault (I hate tabs). I have registered my script as a command to be able to trigger it from anywhere. However, I found some strange behaviour:

As long as the codelist view is not visible (e.g. not active or behind another pane) my command is not registered at startup.
![grafik](https://github.com/user-attachments/assets/8c51a46a-dcaa-4a7d-84be-33379e1c0536)
 
This coincides with an error, I found in the logs:

plugin:runjs:2677 Uncaught (in promise) TypeError: _a.update is not a function
    at eval (plugin:runjs:2677:50)

The RunJS Infobubble does not appear.

Whereas in cases in which the codelist view is active, everything works fine and my command is shown in the command palette

![grafik](https://github.com/user-attachments/assets/55f581c4-cfa5-42d7-b31a-16f82e988b65)

I also get the info bubble in the top right corner.

![grafik](https://github.com/user-attachments/assets/b8f3cbaf-4ed9-495a-9137-8176ac20efe2)

I would be glad to know whether this is intended behaviour. Currently I need to have the code list view active at all times. However, since there is only one script in it, it seems like a waste of screen space to me and I would love to get it in the background.

best
Jonny

**Comment by lukehaas** [comment]
Sorry, @jonnymauser76 , I think this has been raised in the wrong repo. This project is not an Obsidian plugin.
