### ISSUE TITLE
Quitting from macOS doc causes error

### ISSUE THREAD

**Issue by p12y** [lukehaas/RunJS#66]
If you quit the application by right clicking the icon in the doc and select 'Quit', you get the following error:

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'removeAllListeners' of null
    at App.h.on (/Applications/RunJS.app/Contents/Resources/app.asar/entry-bundle.js:18:224552)
    at App.emit (events.js:187:15)

**Comment by lukehaas** [comment]
Thanks, I'll have this fixed in the next release.

**Comment by lukehaas** [comment]
This is now resolved in 1.5.0
