### ISSUE TITLE
Output is scrambled in lines.

### ISSUE THREAD

**Issue by einsub** [lukehaas/RunJS#67]
I guess that this is caused by the code folding function. anyway, the shorter key has no problem.

![스크린샷 2019-04-01 오후 4 52 17](https://user-images.githubusercontent.com/2919667/55319339-da90cf00-549e-11e9-9cdf-fe38a3b25efe.png)

**Comment by lukehaas** [comment]
That's a strange one. Thanks for raising it.

**Comment by lukehaas** [comment]
I've looked into this but I'm not actually able to recreate the issue.
Which version of RunJS are you using?

**Comment by einsub** [comment]
I'm using 1.4.0

**Comment by lukehaas** [comment]
I just took another look and this time I was able to see it.
Will try and get a solution in the next release.

**Comment by lukehaas** [comment]
@einsub This is now resolved in the latest release: 1.5.1
