### ISSUE TITLE
Bug: multiple declarations cause syntaxerror

### ISSUE THREAD

**Issue by getify** [lukehaas/RunJS#69]
Bit of a strange one here, but... if I have multiple declarations in the same `var` statement, **AND** that comes after a `function` declaration, it reports a syntax error:

<img width="918" alt="Screen Shot 2019-04-06 at 7 46 34 AM" src="https://user-images.githubusercontent.com/150330/55665003-74aa9b80-5840-11e9-8d0e-7cbea83e74d8.png">

If there's no `function` declaration before it, no error reported:

<img width="445" alt="Screen Shot 2019-04-06 at 7 50 38 AM" src="https://user-images.githubusercontent.com/150330/55665017-b20f2900-5840-11e9-84e6-fb7ffffb2012.png">

If the `var` declarations are separate statements, no error reported:

<img width="436" alt="Screen Shot 2019-04-06 at 7 47 12 AM" src="https://user-images.githubusercontent.com/150330/55665005-796f4f80-5840-11e9-8242-b9bbd9fcc293.png">

**Comment by lukehaas** [comment]
Thanks for raising this. It will be fixed in the next release.

**Comment by lukehaas** [comment]
This is now resolved in version 1.5.0
