### ISSUE TITLE
Feature Request: hide output on the right

### ISSUE THREAD

**Issue by JiiB** [lukehaas/runjs#7]
Hi there.

I really like your little tool, great work 🎉 
It would be very nice if there was an option to toggle the preview/output view on the right side of the window. I would like to make sceenshots like this:

![grafik](https://user-images.githubusercontent.com/25438442/50706026-e8c87e00-105c-11e9-8530-7151ab6c8aa7.png)

**Comment by erikshestopal** [comment]
@JiiB I would suggest taking a look at [Carbon](https://carbon.now.sh/?bg=rgba(171%2C%20184%2C%20195%2C%201)&t=seti&wt=none&l=auto&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false)

**Comment by JiiB** [comment]
@erikshestopal oh great. thank you 👍 

I'll close this issue
