### ISSUE TITLE
Install specific package version

### ISSUE THREAD

**Issue by mdtanrikulu** [lukehaas/RunJS#71]
Is there any way to install specific version of npm package? I tried `web3@1.0.0-beta.31` on search bar, didn't worked.

**Comment by lukehaas** [comment]
This isn't currently supported. I'll consider how this could be supported in the future.

**Comment by lukehaas** [comment]
@mdtanrikulu this is now supported in RunJS version 1.10.0

![Screenshot 2020-07-17 at 17 32 47](https://user-images.githubusercontent.com/741344/87809619-97a16900-c853-11ea-8a50-32f69beacd68.png)

**Comment by mdtanrikulu** [comment]
@lukehaas Amazing!! gonna update. Thanks for keeping up your great work!

**Comment by jcubic** [comment]
How to install beta version? I've tried `@jcubic/lips@beta` and `@jcubic/lips@1.0.0~beta.5` but got error `"Something went wrong"`.
