### ISSUE TITLE
function declarations shouldn't be scoped by a block

### ISSUE THREAD

**Issue by arawwad** [lukehaas/RunJS#72]
![image](https://user-images.githubusercontent.com/25812184/56754911-7526ba00-678e-11e9-8e91-0845309ff433.png)

_Originally posted by @arawwad in https://github.com/lukehaas/RunJS/issues/70#issuecomment-486760550_

**Comment by lukehaas** [comment]
As I understand it, this is the correct behaviour. As described here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block

@arawwad, Can you tell me why you expect the function to not be scoped to the block?

**Comment by arawwad** [comment]
in the article you provided; the third snippet in the with function section is the correct behaviour... when foo is called outside should work correctly

**Comment by arawwad** [comment]
let and const are scoped to blocks and function scope .. var and function declarations are scoped to function scope only

**Comment by lukehaas** [comment]
I see now. The block should only prevent the function declaration from being hoisted to the top of the scope. Calling foo() below the block should work. 
You're right, thanks for raising this.

**Comment by getify** [comment]
Actually, the spec does currently say that functions are scoped to blocks. However, browsers have not historically treated functions in blocks consistently... so [Appendix B of the spec](https://www.ecma-international.org/ecma-262/10.0/#sec-block-level-function-declarations-web-legacy-compatibility-semantics) clarifies this complex issue.

**Comment by lukehaas** [comment]
@arawwad this is now resolved in RunJS version 1.11.0
