### ISSUE TITLE
Searching with `-` returns no results

### ISSUE THREAD

**Issue by justrhysism** [lukehaas/RunJS#73]
Searching using a dash `-` returns no results.

e.g. `is-date-object` not returned

Searching `date` returns `is-date-object` in the list.

Expectation: be able to search using all characters allowed in package names.

**Comment by lukehaas** [comment]
This is, unfortunately, an upstream issue with NPM itself.
If you type into your terminal `npm search is-date-object` you'll see that no results are returned, even though `npm search date` does return that package in the list.

**Comment by lukehaas** [comment]
This seems to relate to the reserved words in the package name rather than the hyphens. For example, if you search for `simple-datetime-utils` matching results are returned.

**Comment by justrhysism** [comment]
Damn. The package I actually wanted was `date-fns`, but I couldn't get that result back at all :(

**Comment by lukehaas** [comment]
@justrhysism this seems to be working now in RunJS version 1.11.0. I'm seeing results for `date-fns` and `is-date-object`
