### ISSUE TITLE
Cannot run Mocha 

### ISSUE THREAD

**Issue by emrejen** [lukehaas/RunJS#74]
I have installed Mocha, jest, and chai, but getting ReferenceError: describe is not defined

**Comment by lukehaas** [comment]
Please provide the code you're running.

**Comment by emrejen** [comment]
Sure - not much code actually - just a start
<img width="1335" alt="Screen Shot 2019-05-16 at 10 39 15" src="https://user-images.githubusercontent.com/54910/57835334-ef16f580-77c6-11e9-8a38-2659b579cc63.png">

**Comment by lukehaas** [comment]
The `describe` function is not defined here because it's not being imported.

As far as I know, Mocha can't be imported as an ES module anyway so it may be best to just find a testing library that can be used in this way.

**Comment by pablolucero** [comment]
is there any testing library we can use in RunJS?
