### ISSUE TITLE
Let `fs` work in working directory

### ISSUE THREAD

**Issue by Jpunt** [lukehaas/RunJS#75]
It seems that I can't use `fs` methods like `readFile` when setting a working directory. Am I doing something wrong? 

<img width="1104" alt="Screenshot 2019-05-28 at 11 22 06" src="https://user-images.githubusercontent.com/190501/58466872-d7caf700-813a-11e9-81f2-f475fd1e2984.png">

**Comment by lukehaas** [comment]
This is a bug. Thanks for raising!
I'll aim to get this sorted in the next release.

**Comment by lukehaas** [comment]
@Jpunt This is now resolved in the latest release: 1.5.1
