### ISSUE TITLE
[Question] Where is the node_modules stored?

### ISSUE THREAD

**Issue by OwenMelbz** [lukehaas/RunJS#77]
Hi - Where is the internal `node_modules` stored? Trying to debug a package but can't find the  files to dig.

Thanks!!

P.S. Love the tool, thanks for building it!

**Comment by lukehaas** [comment]
Hi, if you're on a mac then they will be in `~/Library/Application\ Support/runjs`

**Comment by OwenMelbz** [comment]
Ah lovely thanks, I only looked in `/Library/Application Support` :D Forgot to check the local version!

Thanks!
