### ISSUE TITLE
Increase font size to more than 30px

### ISSUE THREAD

**Issue by stefanjudis** [lukehaas/RunJS#82]
Hey Luke,

thanks for this great tool. I'll plan to use it for several live coding sessions at conferences. 
Everything works great except that I'd like to be able to increase the editor font size to more than 30px to be safe for a presentation stage.

<img width="322" alt="Screenshot 2019-06-14 at 12 33 47" src="https://user-images.githubusercontent.com/962099/59503447-b2f7b300-8ea0-11e9-9f4b-1ff99b2c5a01.png">

What do you think of that?

Thanks a bunch.

**Comment by lukehaas** [comment]
Sure, that makes sense. Will include that in the next release.

Great to hear that you've been using this for live coding at conferences. If there are any other features or enhancements that would make things better or easier for you in that scenario, I'd be keen to hear them.

**Comment by stefanjudis** [comment]
In-app snippets are definitely something that could be useful. :) 

> Will include that in the next release.

Without any pressure – do you have a rough eta for the next release? Just so that I can plan for using it. :)

**Comment by lukehaas** [comment]
Next release will probably be on Sunday, but I'd be happy to release this feature sooner if you need it more urgently.

**Comment by stefanjudis** [comment]
i'll be speaking on thursday at ndc oslo. :D But as said – don't worry about it. Current font-size will do. :)

**Comment by lukehaas** [comment]
Not a problem. I've just pushed a release. Latest release is 1.5.3, with much larger font-size options.
Good luck at the conference.
