### ISSUE TITLE
Set Work directory not working

### ISSUE THREAD

**Issue by philschonholzer** [lukehaas/RunJS#85]
I'm on MacOS and using Version 1.5.3 and setting Working Directory doesn't seem to work for me. I can't import local packages or files from the working directory and `__dirname` shows to the App folder: `/Applications/RunJS.app/Contents/Resources/app.asar`.

**Comment by lukehaas** [comment]
Thanks for raising this. Will release a fix for this in the next few days.

**Comment by lukehaas** [comment]
This is now resolved in 1.5.4
