### ISSUE TITLE
Can RunJS remember the window position/size between usages?

### ISSUE THREAD

**Issue by getify** [lukehaas/RunJS#87]
Every time I close RunJS and re-open it, I get its size/position reset back to the middle of the screen and rather small. It doesn't remember what I had set previously. Is there any way to get it to remember? It's a small annoyance, but would be nice to fix.

I'm on latest OSX, btw.

**Comment by lukehaas** [comment]
👍 Will aim to get this resolved in the next release.

**Comment by lukehaas** [comment]
This is now working in the latest release - 1.6.0
