### ISSUE TITLE
Set Work directory not working on Windows10 

### ISSUE THREAD

**Issue by SmallPotatoCZ** [lukehaas/RunJS#88]
When I want to set the directory of the working, there will be an error. 

> Error: ENOENT: no such file or directory, chdir 'D:ProgramsRunjs'

I think, 'D:ProgramsRunjs' should be 'D:Programs\Runjs'. So, maybe it is a bug of the software.

**Comment by lukehaas** [comment]
Thanks, I'll look into this.

**Comment by rayno** [comment]
same here, the directory is `D:\Projects\functional-light-v3\transduction` here is a screenshot. 
RunJS 1.5.4:
![image](https://user-images.githubusercontent.com/1233467/62050576-2ae42780-b21a-11e9-97b2-6c1814346bc6.png)

**Comment by lukehaas** [comment]
This is now resolved in version 1.6.0

**Comment by rayno** [comment]
I can confirm it works in version 1.6.0 on Windows 10 with Nodejs 10.15.0. Thanks!

**Comment by lukehaas** [comment]
Thanks
