### ISSUE TITLE
Console.table is not supported

### ISSUE THREAD

**Issue by alexzerah** [lukehaas/RunJS#89]
# Problem with console table

## Details

👋 Hi everyone, 

This is an incredible app ❤️🚀

I play with it with my friend @redhotman and we want to test `console.table`.
But nothing is displayed 😭

## Screenshot

<img width="799" alt="app js" src="https://user-images.githubusercontent.com/19301356/61145530-feb96e80-a4d7-11e9-98e0-44d0dea17e92.png">

**Comment by lukehaas** [comment]
`console.table` is not currently supported, but I'm aiming to have support for it soon. 👍

**Comment by jonatanpietroski** [comment]
I would appreciate it as well. Any plan to have it soon?

**Comment by lukehaas** [comment]
console.table is now supported in RunJS version 1.10.0

![Screenshot 2020-07-17 at 17 30 57](https://user-images.githubusercontent.com/741344/87809449-5610be00-c853-11ea-8092-936f07536a7c.png)

**Comment by jonatanpietroski** [comment]
Wow!! Cool!! thx man!
