### ISSUE TITLE
Dynamically download modules

### ISSUE THREAD

**Issue by astoilkov** [lukehaas/runjs#9]
First I should note that the design and minimalism of this app are awesome. If I can use this app instead of RunKit this would be awesome.

**Comment by lukehaas** [comment]
Thanks! Currently working on this feature. Will be in the next release.

**Comment by astoilkov** [comment]
Awesome! Just want to add that caching will be very much appreciated so I don't have to wait for modules to download every time I launch the app.

**Comment by lukehaas** [comment]
Lol

**Comment by lukehaas** [comment]
You can now install Node packages:
![install-npm-packages](https://user-images.githubusercontent.com/741344/52523427-546bbf80-2c89-11e9-9c11-fe7bc5cbbf00.png)

This window can be accessed via the Action menu.
