### ISSUE TITLE
install NPM packages does not find any package

### ISSUE THREAD

**Issue by rayno** [lukehaas/RunJS#91]
OS: Windows 10
RunJS Version: 1.5.4

When try in install package, none is found. Loading indicator is shown, but then nothing is displayed. Tried with several different packages: ramda, lodash, rimraf.

![image](https://user-images.githubusercontent.com/1233467/62050264-9bd70f80-b219-11e9-86b0-37f3223251e9.png)
![image](https://user-images.githubusercontent.com/1233467/62050285-a42f4a80-b219-11e9-964b-80f1908880af.png)

**Comment by lukehaas** [comment]
RunJS uses your system's version of NPM for searching/installing packages. It could be that you just need to update NPM.

**Comment by rayno** [comment]
Yes, it works with newer version, thanks :)
