### ISSUE TITLE
Reference error: variable is not defined is not thrown

### ISSUE THREAD

**Issue by KarthikKadambi** [lukehaas/RunJS#93]
This should had thrown ReferenceError: name is not defined

<img width="827" alt="Screenshot 2019-08-19 at 3 35 26 PM" src="https://user-images.githubusercontent.com/1627832/63257270-05858f00-c297-11e9-8034-7c4315b3d8d2.png">

**Comment by lukehaas** [comment]
Thanks for raising this. Will investigate.

**Comment by lukehaas** [comment]
@KarthikKadambi having now looked into this, I have found that `name` is an attribute of the window object and so was rightly displaying here as a blank string.

https://developer.mozilla.org/en-US/docs/Web/API/Window/name
