### ISSUE TITLE
Editor occasionally gets stuck in 'typeover' mode

### ISSUE THREAD

**Issue by JordanAtBridgit** [lukehaas/RunJS#96]
Description: 
Sometimes after working in the RunJS editor panel for a while, I will find myself in a state where each new character replaces the one following the cursor instead of inserting the new value inline and making the overall line longer. This means that any edit to an existing line of code is very difficult, and requires entire lines to be retyped just to add single characters.

Repro: 
Unfortunately, I'm not sure what the exact repro steps are. This generally happens when I've been working in the editor for quite some time, with many edits and inputs. (Not particularly helpful, I know.) 

Issue in action:
![Screen Recording 2019-09-17 at 5 22 00 PM](https://user-images.githubusercontent.com/38668836/65080812-244b7400-d970-11e9-9b13-9a06b128f090.gif)

Expected: 
It should be possible to insert new text without overwriting subsequent characters. 

Actual: 
New characters replace existing ones.

Overall, this has been an extremely useful tool, and I really appreciate how simple it is to use. This has been a great asset for quickly trying out ideas, or having junior devs experiment without the need to think about setting anything up. If there's any more detail I can add to clarify what's going on, please do let me know.

**Comment by lukehaas** [comment]
Thanks for raising this.
Could you let me know which OS you're on and which version of RunJS you're using?

**Comment by lukehaas** [comment]
I still haven't yet seen this issue while using RunJS, @JordanAtBridgit  are you still seeing this issue?
It's possible that this was an upstream issue that has since been resolved.

**Comment by JordanAtBridgit** [comment]
@lukehaas I haven't actually seen the issue, and I've been updating every time you release a new version. I'm fine with this being closed, and I can always reopen or submit a new bug if I see it happen again.
