### ISSUE TITLE
console.time and console.timeEnd don't work

### ISSUE THREAD

**Issue by aleffsouza** [lukehaas/RunJS#97]
Hello @lukehaas 

A big Thank you for building RunJS, it's a fantastic tool and It helps me a lot 😄 

Now, I was trying to measure some execution time using [`console.time`](https://nodejs.org/api/console.html#console_console_time_label) and [`console.timeEnd`](https://nodejs.org/api/console.html#console_console_timeend_label) and it prints out nothing 🤔  

If I run the code below on node.js' REPL (v10.11.0)
```
console.time("hello");
console.log("Hello World");
console.timeEnd("hello");
```
 I get the output:
```
Hello World
hello: 1.493ms
``` 

While on RunJS:
<img width="604" alt="Screenshot 2019-09-23 at 22 42 47" src="https://user-images.githubusercontent.com/11286702/65461114-9c73d700-de53-11e9-8d04-c137ebb03039.png">

RunJS v1.6.0
MacOS Mojave v10.14.6

Thank you!

**Comment by lukehaas** [comment]
@aleffsouza this is now supported in RunJS version 1.11.0
