### ISSUE TITLE
reference error instead of undefined

### ISSUE THREAD

**Issue by amirmeimari** [lukehaas/RunJS#98]
Hi there.
I'm using RunJS version `1.6.0`. when I try to `log` a `var` before declaration I get a reference error at first then I get `undefined`, but I'm sure I should only get `undefined`.

for example:
```
console.log(foo)
var foo = 1;
```

output:
```
ReferenceError: foo is not defined
at eval (eval at <anonymous> (:7:47), <anonymous>:51:13)
    at <anonymous>:7:47
    at <anonymous>:57:25
    at resolve 
....
undefined
```

see? first error then `undefined`.

**Comment by lukehaas** [comment]
Thanks @AmirMeimari. This is a known issue with RunJS - more detail can be found in this ticket: https://github.com/lukehaas/RunJS/issues/70

Solving this is a long term goal.

**Comment by lukehaas** [comment]
@amirmeimari this is now resolved in the latest version of RunJS 👍
