### ISSUE TITLE
[Feature Request] Adding Tabs

### ISSUE THREAD

**Issue by cairocoder** [lukehaas/RunJS#99]
It would be better if you allow the user to open multiple tabs within same workspace.

**Comment by cairocoder** [comment]
Any updates?

**Comment by lukehaas** [comment]
Thanks @cairocoder, this has been noted for future possible updates.

**Comment by augustnmonteiro** [comment]
👍 any updates on this?

**Comment by cairocoder** [comment]
We really need this, @lukehaas

**Comment by hroland** [comment]
Bump 👍 Even the native functionality to create a new window, then merge them, would be huge

<img width="493" alt="Screen Shot 2020-07-28 at 12 22 16 PM" src="https://user-images.githubusercontent.com/12371411/88654128-38521d00-d0cd-11ea-9266-b162bc39537d.png">
<img width="274" alt="Screen Shot 2020-07-28 at 12 23 36 PM" src="https://user-images.githubusercontent.com/12371411/88654117-35572c80-d0cd-11ea-8397-f51c11eb4c79.png">

**Comment by cairocoder** [comment]
Any updates for this @lukehaas ?

**Comment by lukehaas** [comment]
@cairocoder aiming for the first half of next year.

**Comment by cairocoder** [comment]
Hope it's soon @lukehaas

**Comment by lukehaas** [comment]
@cairocoder The latest version of RunJS now supports multiple tabs:

![tabs](https://user-images.githubusercontent.com/741344/122990593-0d834e00-d39c-11eb-9e6d-9e7b5ab27c90.gif)

**Comment by rcreasi** [comment]
Is there a way to give each tab a label?

**Comment by lukehaas** [comment]
@rcreasi Yes, if you set a directory then the tab will be labeled with the name of the directory, also if you save a file, the tab will be labeled with the file name.
